middleware/fastcgi/fastcgi.go
middleware/gzip/gzip.go

This adds a cleaner way to prevent double encoding. Puts back io.Copy simplified version of writing body which I accidentally replaced earlier.

gzip middleware now strips encoding header

---

server/server.go

Fix for [Issue 13](https://github.com/mholt/caddy/issues/13):
Sites configured with ip `0.0.0.0` are now wildcards and no longer filter by request host.
e.g.
```
0.0.0.0:2015
root /html
```

Fix for Issue 13: Trouble running in Docker containers (or binding to 0.0.0.0)

---

config/config.go
config/parser_test.go
config/parsing.go
main.go

Default port used if none is specified in config
This could resolve #16. @j-mcnally Would this suffice you think?

-port flag to allow overriding default port

---

config/middleware.go
middleware/git/doc.go
middleware/git/git.go
middleware/git/gitclient.go

Caddyfile Syntax :
```
git repo path {
repo
path
branch
key
interval
}
```
`repo` 	- git repository
compulsory. Both ssh (e.g. git@github.com:user/project.git)
and https(e.g. https://github.com/user/project) are supported.
Can be specified in either config block or top level
`path` 	- directory to pull into
optional.  Defaults to site root.
`branch` 	- git branch or tag
optional. Defaults to master
`key` 	- path to private ssh key
optional. Required for private repositories. e.g. /home/user/.ssh/id_rsa
`interval`  - interval between git pulls in seconds
optional. Defaults to 3600 (1 Hour).
Examples :
public repo pulled into site root
```
git github.com/user/myproject
```
public repo pulled into mysite
```
git https://github.com/user/myproject mysite
```
private repo pulled into mysite …

Implementation of Git middleware

---

README.md

Go version 1.4 or greater is required to run caddy locally due to a need update in how the BasicAuth method was implemented. I believe that in previous Go versions, it was a private method thus throwing this error:
```
$GOPATH/src/github.com/mholt/caddy/middleware/basicauth/basicauth.go:36: r.BasicAuth undefined (type *http.Request has no field or method BasicAuth)
```

Specify Go Version in README

---

middleware/fastcgi/fastcgi.go

Environment variables can now be defined for **fastcgi** using **env** keyword.
Sample Caddyfile with fastcgi and user defined environment variables.
```
fastcgi / 127.0.0.1:9000 php {
env ENVIRONMENT production
env API_KEY 2391e0182b3bcc18425ec6ed37ec0f16
}
```

fastcgi: user defined environment variables

---

middleware/git/doc.go
middleware/git/git.go
middleware/git/gitclient.go

Post pull command can now be added using **then**.
Relative paths are now accepted.
Syntax:
```
then cmd [args]
```
Example usage with Hugo 
```
git github.com/user/site {
path  ../
then  /usr/local/bin/hugo --destination=/home/user/hugosite/public
}
root /home/user/hugosite/public
```

git: post pull command. retries after pull failure.

---

middleware/fastcgi/fastcgi.go
middleware/fastcgi/fcgiclient.go

FastCGI middleware currently allows only `GET` and `POST` requests and returns a `405 (Method not Allowed)` for others.
This will allow the following additional request types.
* HEAD
* PUT
* PATCH
* DELETE
`HEAD` is essential and the others are useful for REST endpoints.

fastcgi: allow more request types.

---

middleware/proxy/policy.go
middleware/proxy/policy_test.go
middleware/proxy/proxy.go
middleware/proxy/reverseproxy.go
middleware/proxy/upstream.go
middleware/proxy/upstream_test.go
middleware/replacer.go

First off - thanks for creating caddy. We were looking for a solution that would allow us to write custom service discovery backends for our mesos cluster in nginx (like creating a custom upstream) as DNS-based service discovery wasn't working too well for us (failover & dns caching didn't work too well). It looked like we would have to write our module in C. With this we can write something simpler with Go.
As I have done work creating the reverse proxy backend (for our service discovery), I thought it would have made the most sense to provide more general features to the upstream backend (as we would use those too), that had most of the base features included, but still retained the ability to be easily extensible (any developer can simply copy the `staticUpstream` implementation and …

Proxy Middleware: Add support for multiple backends, load balancing & healthchecks

---

config/setup/proxy.go
middleware/proxy/proxy.go
middleware/proxy/upstream.go

Sorry for fiddling around with this middleware so much - I had noticed that a recent refactor caused the way we were doing things to break and unable to write our own proxy backends in Caddy. 
This PR simply moves things around so that interfaces are properly exposed so its easier to write your own proxy backends. Our original intent with the proxy backend was to provide a standard one (@ `upstream.go`), and have that easily copyable to another package in case you wanted to extend that upstream backend. (For example are working on a `mesosupstream` proxy backend that allows you specify mesos tasks rather than domain names - we would still like to take advantage of the proxy middleware however).
This way if someone wants to write backend that uses a different method of service discovery …

proxy: Refactor so that other upstream backends can be implemented

---

config/directives.go
config/setup/bindaddr.go
config/setup/bindhost.go
server/config.go

**Problem**
When using virtual hosts behind docker or with a host that doesn't resolve that may not resolve - Caddy won't start. Alternatively there is no way to tell Caddy to bind on a different host rather than trying to resolve the host name.
Ex.
```
http://channelmeter.com {
proxy / http://node:3000
}
http://api.channelmeter.com {
proxy / http://api:3000
}
```
Inside a docker container, this will cause Caddy to try and bind on `67.207.200.30`. This isn't allowed (by Docker) and so you get permission denied. An option would be to include another directive that allows you to bind on another address such as `0.0.0.0`  - such as
```
http://channelmeter.com {
bindaddr 0.0.0.0
proxy / http://node:3000
}
http://api.channelmeter.com {
bindaddr 0.0.0.0
proxy / http://api:3000
}
```
This PR …

core: Add the option to specify what address to bind on in Caddyfile

---

config/setup/tls.go

This is more of a cosmetic thing, but when setting servers, we usually have times when we want to have a server listen on both on http and https without automatically upgrading to https. (Ex, our API service which if request over http, via XHR, doing a redirect to https would cause a CORS violation).
However, we also don't want to repeat options in our Caddy file. A configuration like this:
```
http://api.example.com, https://api.example.com {
tls example.crt example.key
bindaddr 0.0.0.0
gzip
log /dev/fd/1
}
```
Would cause a Caddy to error out with 
`Configuration error: Cannot multiplex 0.0.0.0:http (HTTP) and 0.0.0.0:http (HTTPS) on same address`
With the following change, tls won't be enabled for servers with port http (either `http://example.com` or `0.0.0.0:http`.
I think its a sane …

tls: suggestion - disable tls if port is http?

---

config/directives.go
config/setup/internal.go
middleware/internal/internal.go

I tried to implement a subset of the [X-accel](http://wiki.nginx.org/X-accel) Nginx feature for Caddy.
> X-accel allows for internal redirection to a location determined by a header returned from a backend. This allows you to handle authentication, logging or whatever else you please in your backend and then have Nginx handle serving the contents from redirected location to the end user, thus freeing up the backend to handle other requests. This feature is commonly known as X-Sendfile.
You can mark some locations as "internal" in the Caddy file.
```
localhost:8000
internal /internal
proxy /redirect http://localhost:9000
```
Now, you get a `404` for `http://localhost/internal/*`. The proxy running at port 9000 has the possibility to respond with an `X-Accel-Redirect` header. Example …

Adding "internal" middleware

---

middleware/redirect/redirect_test.go

A small test case for redirect based on the rewrite test.
Testing both that the Location header and response body is set to the expected values.
Should we skip verification of the body since it is generated in `http.Redirect`?

redirect: initial test for Redirect

---

middleware/basicauth/basicauth.go
middleware/basicauth/basicauth_test.go

Test + Patch
But if this is not the desired behaviour for middlewares, I can just change test case.

basicauth: Should write an unauthorized code to response. (Actually only returns it)

---

config/setup/headers.go
config/setup/headers_test.go
middleware/headers/headers.go
middleware/headers/headers_test.go

A small test case for headers based on the rewrite/redirect tests.
This PR contains a breaking change since `Rule.Url` was changed to `Rule.Path`

headers: Initial test for Headers and change of Rule.Url to Rule.Path

---

config/setup/rewrite.go
config/setup/rewrite_test.go
middleware/rewrite/rewrite.go
middleware/rewrite/rewrite_test.go

Regexp support for **rewrite** middleware. Not as robust as Apache and Nginx but a leap from current functionality.
Two types are now supported.
* Simple rewrite
* Regexp rewrite
This is the current functionality. Same syntax
```
rewrite from to
```
Syntax:
```
rewrite [basePath] {
r[egexp]    pattern
[ext]       ext
to          to
}
```
**basePath** - optional. Defaults to `/` e.g. /home/blog/ will only rewrite for subpaths of /home/blog/
**pattern** - regular expression pattern
**ext**     - optional. File extensions to include or ignore. Prefix with `!` to ignore. 
`.ext` for ext extension (e.g. /home.ext) or `/` for no extension (e.g. /home)
`.html` - only rewrite for .html
`!.html` - rewrite for everything else except .html
`!.txt .html` - rewrite for only .html, ignore everything …

Rewrite: Support for Regular Expressions.

---

app/app.go
config/config.go
config/parse/lexer.go
config/setup/git.go
config/setup/git_test.go
config/setup/log.go
middleware/basicauth/basicauth.go
middleware/basicauth/basicauth_test.go
middleware/browse/browse.go
middleware/extensions/ext.go
middleware/fastcgi/fcgiclient.go
middleware/git/git.go
middleware/git/git_test.go
middleware/gzip/gzip.go
middleware/internal/internal.go
middleware/log/log.go
middleware/markdown/markdown.go
middleware/markdown/metadata.go
middleware/path.go
middleware/proxy/policy.go
middleware/proxy/proxy.go
middleware/proxy/upstream.go
middleware/rewrite/rewrite.go
middleware/rewrite/rewrite_test.go
middleware/websockets/websockets.go
server/fileserver.go
server/server.go

This PR fixes a bunch of warnings generated when running golint on the source code.  For example, it contains updates to the godoc comments, removes else blocks when the if ends with a return, and makes method receiver names consistent for all methods on a particular type.  There are no functional changes.

Fix lint warnings

---

config/setup/tls.go
config/setup/tls_test.go
server/config.go
server/server.go

crypto/tls ClientSessionCache is used only for tls client.
reference: https://groups.google.com/forum/#!topic/golang-dev/ClGuwk-n_L4

removed tls cache option

---

config/setup/rewrite_test.go
middleware/proxy/reverseproxy.go
middleware/proxy/upstream.go

This should address #81. 
Some things worth noting:
1. I dug through the nginx source and it appears they make the change for a WebSocket connection by the status code, so I opted for the same thing.
2. For testing, I went ahead and ran the autobahn fuzzing server behind the proxy and used the testeeclient to exercise it. All the test passed successfully. I can share those results and commands used in slack if that would be helpful.
3. I also setup a regular http server behind the proxy to verify that still worked. It did.
4. Also as noted in the issue, you need to make sure your proxy directives include `Connection` and `Upgrade` like so:
```
proxy / localhost:8080 {
policy round_robin
proxy_header Connection {>Connection}
proxy_header Upgrade {>Upgrade}
} 
```
Let me know if I missed …

add supported for ws in reverse proxy

---

config/setup/tls.go
config/setup/tls_test.go
server/config.go
server/server.go

@okket Would you please take a look and see if this does what you need?
Usage:
```
tls cert.crt key.pem {
clients clientcert.crt
}
```
Cert files must be x509 encoded (not raw DER).

tls: Client authentication

---

config/setup/git.go
middleware/git/git.go
middleware/git/webhook/github_hook.go
middleware/git/webhook/github_hook_test.go
middleware/git/webhook/webhook.go

Greetings!
This is a middleware for responding to events on github using webhooks.
This PR adds handlers for the **push** and **release** events.
On receiving a handled event, the middleware executes the following steps:
* First, it first tries to validate the sha1 signature if one is present (if the secret was set in GH). 
* If a signature and a secret is present and it fails to validate the signature, the middleware will exit immediately! 
* Then it pulls the current release or the head of the tracking branch into a directory.
The middleware supports the same configuration arguments as the git middleware (it uses the middleware internally for pulling) as well as a few new ones.
A typical configuration would look like this:
ghdeploy {
repo			https://github.com/xenolf/Spoon-Knife
branch …

Webhook middleware for GitHub events

---

middleware/proxy/proxy.go
middleware/proxy/proxy_test.go
middleware/proxy/reverseproxy.go
middleware/proxy/upstream.go

For https://github.com/mholt/caddy/issues/95
Caddyfile:
```
proxy /api localhost:9999 {
without /api
}
```
Request ```/api/messages``` transformed to ```/messages``` and send to  localhost:9999.

Add "without" option to proxy middleware

---

config/setup/gzip.go
config/setup/gzip_test.go
middleware/gzip/filter.go
middleware/gzip/filter_test.go
middleware/gzip/gzip.go
middleware/gzip/gzip_test.go

New gzip syntax.
```
gzip {
ext extensions
not paths
level compression level
}
```
all configs are optional.
extensions - file extensions to compress for, separated by space. Supports wildcard `*` to accept all extensions and defaults to text types `.html .htm .css .json .php .js .txt .md .xml`.
paths - paths to **ignore** for compression separated by space. e.g. `/images /videos`
compression level - compression level from `1` (best speed) to `9` (best compression).

Gzip: Added compression level, extension and path filters.

---

app/app.go
config/config.go
config/setup/browse.go
config/setup/git.go
middleware/commands.go
middleware/git/git.go
middleware/git/git_test.go
middleware/git/webhook/github_hook.go
middleware/gzip/gzip_test.go
middleware/markdown/metadata.go
middleware/proxy/proxy.go
middleware/rewrite/rewrite.go
server/server.go

Error strings should not start with a capital letter because they are often prefixed with other strings.  See https://github.com/golang/go/wiki/Errors
This pull request updates all occurrences of `errors.New()` and `fmt.Errorf()` that started with uppercase letters.  The output is nicer.  For example, here's an error from a test failure before and after the change.
Before:
````
git_test.go:172: Test 5 should not error but found Private repository not yet supported on Windows
````
After:
````
git_test.go:172: Test 5 should not error but found private repository not yet supported on Windows
````

Update error strings (start with lowercase letters)

---

config/setup/redir.go
middleware/redirect/redirect.go
middleware/redirect/redirect_test.go

Proper Location redirects are disadvantageous in some situations.
For example, you may want a developer to know that a resource is available
via https, but you don't want an insecure call to the API to succeed.
See https://coolaj86.com/articles/secure-your-redirects/

add ability to do meta redirects

---

config/setup/internal.go
middleware/inner/internal.go
middleware/inner/internal_test.go

The internal package has the special meaning in go
(see https://golang.org/s/go14internal).
So rename it to `inner`.

rename middleware's name from `internal` to `inner`

---

config/setup/gzip.go
config/setup/gzip_test.go
middleware/gzip/filter.go
middleware/gzip/filter_test.go
middleware/gzip/gzip_test.go

Gzip now accepts MIME types.
```
gzip {
mimes mime_types
}
```
mime_types - space separated list of MIME types. e.g. `text/html text/css`. If specified overrides default.
Default: `text/plain text/html text/css application/json application/javascript text/x-markdown text/xml application/xml`
Other filters `not` and `ext` are still supported.
Only either of MIME types `mimes` or File extension `ext` should be specified. If both are specified, `mimes` is preferred to `ext`. The hierarchy is `mimes` > `ext` > `Default mimes`.

Gzip: Accept MIME types.

---

middleware/log/log.go
middleware/log/log_test.go

in the case of error (>=400) then no response may have been sent
As discussed a little while ago on Slack.

log: ensure the correct status is always logged

---

config/setup/errors.go

When checking if a file exist in errors config parse, print a warning instead of terminate

change from error to a warning in errors setup

---

config/config.go
config/config_test.go
server/config.go

Addresses which fail to resolve are handled more gracefully in the two most common cases: the hostname doesn't resolve or the port is unknown (like "http" or "https" on a system that doesn't support those port names). If the hostname doesn't resolve, the host is served on the listener at host 0.0.0.0. If the port is unknown, we attempt to rewrite it as a number manually and try again.
/cc @wmark and @coolaj86 - would you please take a look at this and see if this will do?

core: Handle address lookup and bind errors more gracefully (fixes #136 and #164)

---

middleware/fastcgi/fastcgi.go

This fixes https://github.com/mholt/caddy/issues/141.
It works both when `cgi.fix_pathinfo=0` and `cgi.fix_pathinfo=1` in `php.ini`

Fix for Issue 141: index not found, 502 Bad Gateway.

---

config/setup/gzip.go
config/setup/gzip_test.go
middleware/gzip/filter.go
middleware/gzip/filter_test.go
middleware/gzip/gzip.go
middleware/gzip/gzip_test.go

@abiosoft How's this look to you? It works on my machine. :smile: This change makes the MIME types no longer the default filter - instead, gzip is enabled by extensions and extensions override MIME filter, if any.
However, this doesn't fix the MIME types. We need to handle the MIMEFilter's ShouldCompress method differently. Relying on the Accept header from the client isn't ideal either - it could probably work for most things, but it seems that even nginx just uses file extensions (mime.types file). To truly filter mime types (which would be opt-in only), I think we'd have to buffer every response and detect the MIME type...
Or we drop MIME types entirely and just use file extensions. Thoughts?

gzip: Make it gzip again

---

config/setup/markdown.go
middleware/markdown/markdown.go
middleware/markdown/markdown_test.go
middleware/markdown/metadata.go
middleware/markdown/metadata_test.go
middleware/markdown/page.go
middleware/markdown/process.go
middleware/markdown/renderer.go
middleware/markdown/testdata/blog/test.md
middleware/markdown/testdata/log/test.md

This includes bug fixes and mainly an enhancement to Markdown to provide blogging capability.
* Metadata variables are now flattened. No need for the `variables` block/object.
* Links to all available markdown files are now available and can be used in templates ordered by newest to oldest. Accessible via `{{.Links}}`.
Example below. 
```html
{{ range .Links }}
<h3>
<a href="{{ .Url }}"> {{ .Title }} </a>
</h3>
<p>
{{ .Summary }}
<br />
{{ .Date.Format "Jan 02, 2006 15:04:05 UTC" }}
<p>
{{ end }}
```
a Link contains 
```go 
Title   string
Summary string
Date    time.Time
Url     string
```
* `date` can now be specified in metadata. This is used for ordering links and can be referenced in templates. Dates are only valid if specified in the format `YYYY-MM-DD HH:MM:SS`. Hopefully, this can …

Enhancements to Markdown

---

config/setup/markdown.go
middleware/markdown/markdown.go
middleware/markdown/markdown_test.go
middleware/markdown/page.go
middleware/markdown/testdata/og/first.md
middleware/markdown/testdata/og_static/og/first.md/index.html
middleware/markdown/watcher.go
middleware/markdown/watcher_test.go

* Markdown now watches for site changes for link generation. 
* `sitegen` config no longer required for links generation.
* `dev` config option added to change link generation to page loads rather than having to wait 60s for updated index (useful when actively editing Markdown files)

Markdown: Watch for file changes for links. Removed sitegen dependency for links.

---

middleware/middleware_test.go

It'll be m,ore meaningful for the IndexFile function to return an error value instead of bool with which users can understand whether the issue is because of filepath not ending with `/` or is it that the index file is not found

Initial test for middleware/middleware.go

---

middleware/browse/browse.go

we already have the option to sort the browse listing via queries, now we can pass `json=true` to get back a JSON representation of the files.
`127.0.0.1:2015/?json=true`
```JSON
[
{
"IsDir": true,
"Name": "server",
"Size": 204,
"URL": "server/",
"ModTime": "2015-08-17T21:28:46+03:00",
"Mode": 2147484141
},
{
"IsDir": false,
"Name": "README.md",
"Size": 4960,
"URL": "README.md",
"ModTime": "2015-08-17T21:28:46+03:00",
"Mode": 420
},
{
"IsDir": true,
"Name": "middleware",
"Size": 850,
"URL": "middleware/",
"ModTime": "2015-08-17T21:28:46+03:00",
"Mode": 2147484141
},......etc
```
it is possible also to pass an `items` query to get a specific number of files back, so the following will give you the biggest two files
`127.0.0.1:2015/?sort=size&order=desc&json=true&items=2`
```JSON
[
{ …
```

Add JSON option for the browse middleware

---

middleware/browse/browse.go

the old comment might throw the source-reader off, my bad.

Fixing my comment

---

config/setup/errors_test.go
config/setup/log_test.go
config/setup/roller.go

By default the time wasn't the time of the machine but UTC.

Use localtime for the log roller timestamp

---

config/setup/basicauth.go
config/setup/basicauth_test.go
middleware/basicauth/basicauth.go
middleware/basicauth/basicauth_test.go

If the password arg starts with htpasswd=, then the rest is treated as
the file name of the htpasswd file, and used for md5 and sha1 hashes.

Add htpasswd support for basic auth

---

config/setup/markdown.go
middleware/markdown/generator.go
middleware/markdown/markdown.go
middleware/markdown/markdown_test.go
middleware/markdown/page.go
middleware/markdown/process.go

* As value mutex was copied and therefore synchronization worked wrong
* It's pretty big structure with reference types, so copying create unnecessary
pressure on GC

Use markdown.Config as pointer everywhere

---

middleware/markdown/watcher_test.go

In latest go versions TestWatcher fails pretty often, because it is
"more concurrent" now. Reproducible with go master:
while go test github.com/mholt/caddy/middleware/markdown; do :; done

Use less strict condition to avoid problems with concurrency

---

middleware/replacer.go
middleware/rewrite/rewrite.go
middleware/rewrite/rewrite_test.go

* Rewrite now uses `middleware.Replacer`.
* Bug fix for regexps starting with `/`.
* `file` and `dir` variables added to `middleware.Replacer` to conform with existing `rewrite` vars.
I added `frag` (which is same as `fragment`) for compatibility with existing `rewrite` vars. (This may not be needed. Just for non breaking change).

Rewrite: Use middleware.Replacer.

---

server/server.go

The golang.org/x/net/http2 is now the official http2 repo.
It is advised to change the imports to it.

change to official http2 repo

---

config/directives.go
config/setup/mime.go
config/setup/mime_test.go
middleware/mime/mime.go
middleware/mime/mime_test.go

MIME, new middleware. Originated from https://github.com/mholt/caddy/issues/255.
It sets `Content-Type` in accordance to the requested file extension as specified in the Caddyfile.
simple/single
```
mime .swf application/x-shockwave-flash
```
multiple
```
mime {
.swf application/x-shockwave-flash
.pdf application/pdf 
}
```

New core middleware, MIME.

---

app/app.go
config/config.go
config/directives.go
config/parse/dispenser.go
config/parse/parsing.go
config/parse/parsing_test.go
config/setup/markdown.go
config/setup/proxy.go
config/setup/startupshutdown.go
main.go
middleware/basicauth/basicauth.go
middleware/browse/browse_test.go
middleware/errors/errors.go
middleware/fastcgi/fastcgi.go
middleware/fastcgi/fcgiclient.go
middleware/fastcgi/fcgiclient_test.go
middleware/gzip/filter.go
middleware/gzip/gzip_test.go
middleware/markdown/markdown_test.go
middleware/markdown/process.go
middleware/markdown/watcher.go
middleware/proxy/policy_test.go
middleware/proxy/upstream.go
middleware/replacer_test.go
middleware/rewrite/rewrite.go
middleware/rewrite/rewrite_test.go
middleware/roller.go
middleware/templates/templates_test.go
server/server.go

- Run `gofmt -s` on source code
- Fix various `golint` warnings
- Refactor some of the larger functions into smaller pieces
This obviously doesn't fix all warnings.  There's still some exported identifiers that I didn't know enough about to document, and I only looked at cyclomatic complexity for a few of the worst offenders.  I think it's certainly an improvement though.

Minor quality improvements (see #253)

---

config/setup/basicauth_test.go
config/setup/controller.go
config/setup/errors.go
config/setup/markdown.go
config/setup/markdown_test.go
middleware/basicauth/basicauth.go
middleware/basicauth/basicauth_test.go
middleware/markdown/generator.go
middleware/markdown/page.go
middleware/markdown/process.go
middleware/middleware.go
middleware/middleware_test.go

Most of the Windows test failures are due to the path separator not being "/".  The general approach I took here was to keep paths in "URL form" (ie using "/" separators) as much as possible, and only convert to native paths when we attempt to open a file.  This will allow the most consistency between different host OS.  For example, data structures that store paths still store them with "/" delimiters.  Functions that accepted paths as input and return them as outputs still use "/".
There are still a few test failures that need to be sorted out.
- config/setup/TestRoot (I hear this has already been fixed by someone else)
- middleware/basicauth/TestBrowseTemplate and middleware/templates/Test (a line endings issue that I'm still working through)

Fix test failures on Windows.

---

middleware/websocket/websocket.go

"A receive from a closed channel returns the zero value immediately"
Close the tickerChan in the calling function, this causes "case <-c" to
unblock immediately, ending the goroutine and stopping the ticker.

Simplify websocket ticker shutdown code

---

config/setup/websocket_test.go

Command arguments:
websocket /api5 "cmd arg1 arg2 arg3"
Optional block:
websocket /api6 cat {
respawn
}
Invalid option in optional block:
websocket /api7 cat {
invalid
}

Add tests for websocket configuration

---

config/config_test.go

Very simple test to make sure that NewDefault is populating the correct
fields with the correct values.

Add TestNewDefault to config tests

---

config/letsencrypt/letsencrypt.go
config/letsencrypt/renew.go
config/letsencrypt/storage.go

I don't see why we can't just use a time.Ticker to run the check every ~hour. Also, this makes it so the renewal check only runs once at startup instead of twice. What do you think @xenolf ?

Simplify timing mechanism for checking renewals

---

middleware/commands.go
middleware/commands_test.go

This implementation introduces the following changes:
* command can contain tokens with spaces. They must be surrounded by quotes
* command can contain backslashes as path separators
* quotes can be escaped by either backslash or doubling the quote ("") - the sequence backslash-quote (\") is the only time where backslash is not taken as path separator and is omitted from the token.
* commands can contain UNC paths
Tests were added to cover all the cases I could think of, but as googling suggested - CMD is not a shell and in many(/most/all?) cases the program is responsible for parsing its arguments. This means that choosing for example to support escaping by both backslash and double quotes is up to us.
This PR should be part of #286.

Fix windows command parsing

---

middleware/header.go
middleware/header_test.go
middleware/markdown/markdown.go
middleware/templates/templates.go

This PR addresses Issue #263 and adds Last-Modified headers to served markdown and template files.
The Issue mentions also Content-Length, but I did not see any problems with it. The cases, where Content-Length must not be sent are defined in [rfc2616#sec4.4](http://www.w3.org/Protocols/rfc2616/rfc2616-sec4.html#sec4.4). Most notably when Transfer-Encoding header is also present Content-Length header is to be omitted or ignored by clients.
Note: I do not like the name middleware/header.go, but I could not think of a better place/filename to place the function. The current file name might also be confusing because there's a middleware called headers, which has nothing to do with it. Suggestions are welcomed.

Add Last-Modified header when serving markdown and templates

---

config/setup/templates.go
config/setup/templates_test.go
middleware/templates/templates.go
middleware/templates/templates_test.go
middleware/templates/testdata/images/img.htm
middleware/templates/testdata/images/img2.htm

I created this to use in a project with Angular.js, that not work with default text/html delimiters.
Added delims argument in a new optional block in templates middleware.
How to use:
without block:
```
templates [path [extensions...]]
```
or 
```
templates {
path path
exten extens...
delims leftDelim rightDelim
}
```
example:
```
templates {
delims {% %}
path /frontend
}
```

Add option to change delims in templates

---

caddy/letsencrypt/letsencrypt.go
caddy/setup/tls.go

This pull request fixes a regression introduced by the LE changes.
When using a caddyfile without a TLS block, defaults were not set as the handler in tls.go was never executed.

Fix regression: Ensure TLS defaults are added by LE handlers.

---

caddy/caddy.go
caddy/setup/startupshutdown.go
caddy/setup/startupshutdown_test.go
server/config.go
server/server.go

We had to hack some special support into the server and caddy packages for this. There are some middlewares which should only execute commands when the original parent process first starts up. For example, someone using the startup directive to start a backend service would not expect the command to be executed every time the config was reloaded or changed - only once when they first started the original caddy process.
This commit adds FirstStartup to the virtualhost config.
@abiosoft Here's what I came up with... what do you think?

startup: Only run commands at first startup

---

middleware/gzip/gzip.go
middleware/gzip/gzip_test.go

When the downstream is cache server or CDN, it is important.
FYI, mod_deflate adds `Vary: Accept-Encoding` to the response headers by default also.

gzip: added Vary: Accept-Encoding to response header.

---

main_test.go

When CPU is 1 core, expected value (`int(0.5 * float32(maxCPU))`) is zero.
But `runtime.GOMAXPROCS(-1)` returns always 1.

fixed test failure on CPU 1 core machine.

---

caddy/parse/parsing.go
caddy/parse/parsing_test.go

This fixes #304 - environment variables can be used in the `Caddyfile` with the `{$VAR_NAME}` syntax.

Use environment variables for configuration

---

middleware/proxy/proxy.go
middleware/proxy/proxy_test.go
middleware/proxy/upstream.go
middleware/proxy/upstream_test.go

This will allow `proxy` to ignore subpath(s) if required.
**Syntax**
```
proxy {
...
[except] [subpaths...]
}
```
**Use Case**
Proxy all requests except static and download folder.
```
proxy / 127.0.01:8080 {
except /static /download
}
```

Proxy: Allow ignored subpaths.

---

middleware/proxy/policy_test.go

Instead of accessing the google website, we setup a local server
for test, then tests will work fine even we are offline.
Fix issue #346

proxy: make tests workable when offline

---

middleware/proxy/proxy_test.go
middleware/proxy/upstream.go

Each proxy block should could specify its own http header
instead of sharing a global one.
Fix issue #341

proxy: make http header block scoped

---

caddy/caddy.go
caddy/config.go

Other lint warnings left behind are ones due to external package and
due to maintainer's preferences.

Add a few super minor lint fixes

---

middleware/proxy/reverseproxy.go

The Host header one is a bug, the res.Body.Close() is one I just noticed in the code, not in traffic. I think the connection is already closed by then, so if you're not convinced or don't want the commit for any reason you may ignore this one and only pull the Host header fixing commit.

Two small proxy websocket fixes

---

middleware/markdown/metadata.go

We can't use json meta parser's remaining buffered data as the markdown body
because it may not contain the entire original content.
Now we adopt the way like toml and yaml parser's way to extract the meta content
at first.
Also when spilting the meta data and content body, additional io.Copy is
unnecessary.
Fix issue #355

markdown: fix json format parse issue

---

middleware/markdown/watcher_test.go

I could not think of many better ways to get rid of the intermittent Windows build failures. Would've loved to maintain the closeness of the intervals to sleep time.

Fix race condition in test for AppVeyor

---

middleware/fastcgi/fastcgi.go
middleware/fastcgi/fcgiclient.go

Fix for https://github.com/mholt/caddy/issues/426.

FastCGI: separate standard and error output responses.

---

middleware/fastcgi/fcgiclient.go

Fix for https://github.com/mholt/caddy/issues/455.
Fastcgi connections are still alive even processing response. This ensures connections are closed when reading is done.

FastCGI: Close client connections when done.

---

middleware/gzip/gzip.go

Other middlewares could potentially add to the Accept header. Cors does. This will make it so neither of them overwrite the other.

Gzip: Append to Vary header instead of replacing.

---

caddy/parse/import_glob0.txt
caddy/parse/import_glob1.txt
caddy/parse/import_glob2.txt
caddy/parse/parsing.go
caddy/parse/parsing_test.go

Import allows to use the star wildcard, question mark and square brackets as used by filepath.Glob - mimics the behavior in other servers.
Sample use
```
import /usr/local/etc/sites/*
```

Support magic characters in import pattern

---

middleware/rewrite/rewrite.go
middleware/rewrite/rewrite_test.go
middleware/rewrite/to.go
middleware/rewrite/to_test.go

Match groups can now be used as placeholder variables `{1}`, `{2}` ...
Something like this is now possible. (From https://github.com/mholt/caddy/issues/30#issuecomment-151588596)
```
rewrite {
r  ^/media/(.*?)/(.*?)/$
to /something/{2}/?media={1}
}
```

Support for rewrite match group.

---

caddy/directives.go
caddy/letsencrypt/letsencrypt.go
caddy/letsencrypt/letsencrypt_test.go

Reorder the bind and letsencrypt directives to ensure that BindHost is set in the configuration.
Then propagate that value in redirPlaintextHost to ensure use of user-specified bind address if user configured it thusly.

Make Let's Encrypt module honor the Bind settings

---

middleware/gzip/request_filter.go

SVG files are text based and can be compressed. Also Google PageSpeed Insights service warn if .svg files not compressed.

Add .svg to default ext list in gzip middleware

---

middleware/fastcgi/fastcgi.go
middleware/fastcgi/fastcgi_test.go

This allows scheme prefixes "tcp://" and "fastcgi://" in configuration.
Fixes #540

Parse address from fastcgi directive, pass results to Dial()

---

middleware/basicauth/basicauth_test.go

`go vet` on tip (Travis) yielded the following error:
```
$ go vet ./...
middleware/basicauth/basicauth_test.go:142: arg rule.Password in printf call is a function value, not a function call
```
This is newly introduced in Go 1.6, where it complains about using the value of a function instead of the call (`rule.Password` is a function, and not a field with some value). Which was exactly what was happening in the line I changed: it just printed the address of the function pointer:
```go
t.Logf("%d. username=%q password=%v", i, rule.Username, rule.Password)
```
```
basicauth_test.go:142: 1. username="md5" password=0x88330
```
I removed the output of that function value, since it's useless and doesn't gives any info. (Or I misunderstood this whole bit of code...)
P.S. I hope Travis accepts …

basicauth: fixed 'go vet' printing function value

---

middleware/fastcgi/fastcgi.go
middleware/fastcgi/fastcgi_test.go

When trying Caddy in production I noticed that `REMOTE_ADDR` didn't contain the full IP, in case of IPv6. This happens because you take the index of the first `:`, this works perfectly for IPv4 addresses, but for IPv6 addresses (which contain `:` :smile: ) it doesn't work.
Splitting it on the last `:` should split it correctly into port and ip.
I could only test this (very basically) on my local machine. So maybe you need to test it on your remote environment on some real IPs. (Can't do that right now.)

FastCGI: IPv6 when parsing r.RemoteAddr

---

caddy/letsencrypt/handler.go

This minor bug did not show in the tests, but in preparations for my "local hack" for #549.
On server side `net/http/Request.URL` is always the empty string. This is IMHO quite underdocumented. See comments at https://github.com/golang/go/blob/3092a63a649ee95865e8b1da4eb2ee4bfe634a7e/src/net/http/request.go#L79 .
Apparently `net/http/httputil.NewSingleHostReverseProxy` is quite happy with `"http://:5033"`(sic!) if the server is on localhost.
`net/http.Request.Host` is apparently the proper way. From the [godoc](https://godoc.org/net/http#Request):  
// For server requests Host specifies the host on which the
// URL is sought. Per RFC 2616, this is either the value of
// the "Host" header or the host name given in the URL itself.
// It may be of the form "host:port".

letsencrypt: properly retrieve hostname from request.

---

middleware/context.go
middleware/context_test.go

This allows any template to use:
{{.Markdown "filename"}} which will convert the markdown contents
of filename to HTML and then include the HTML in the template.

Add .Markdown directive

---

caddy/directives.go
caddy/directives_test.go

This will allow other packages using caddy as a library to register directives without modifying caddy's source. 
I can also make a custom fork of caddy and register plugins in an init function in a separate file to make a custom build of caddy.

Making directives externally registerable

---

middleware/fastcgi/fcgiclient.go

Sometimes we need to customize some Dialer parameters, e.g. set configurable Timeout. Function DialWithDialer allow to create FCGIClient and dial using custom Dialer, but not only the default net.Dialer. Changes are back compatible: function Dial is still there and use default "empty" net.Dialer.

New function DialWithDialer to create FCGIClient with custom Dialer.

---

middleware/proxy/proxy.go
middleware/proxy/proxy_test.go
middleware/proxy/reverseproxy.go
middleware/proxy/upstream.go

These are the changes so far as discussed in https://github.com/mholt/caddy/issues/406.
Open tasks:

Proxy to `unix:` socket

---

caddy/translate/pt-BR.go

So, here is the pt-BR translation for Caddy. I think that we have a lot of other strings to translate, so would be good to have a default en-US file with all strings on Caddy that need to be translated.

Create pt-BR translation file

---

caddy/setup/errors.go
middleware/errors/errors.go

The missing Content-Type for some errors that will be shown to the client will cause a Content-Type of `application/x-gzip` to be returned. This has undesirable results as it either causes a file download, or in the case for Google Chrome, I received an `ERR_INVALID_RESPONSE`.

Fix missing Content-Type for certain errors

---

caddy/https/setup.go
caddy/https/setup_test.go

This pull request adds :
- TLS_ECDHE_ECDSA_WITH_AES_256_GCM_SHA384
- TLS_ECDHE_RSA_WITH_AES_256_GCM_SHA384
**Should we remove SSL 3.0?**

Improving TLS Security

---

caddy/setup/rewrite.go
caddy/setup/rewrite_test.go

Matt, first thanks for the Caddy project...a true showcase of Golang's strengths!
I have a case where it would be useful to do the following:
```
rewrite /editor/spec {
if {method} is PUT
status 200
}
```
However, the current implementation prevents this use case, which I think is safe and reasonable. This PR allow status to be 2xx or 4xx. _Tests are included_. I hope you agree that this simple change is OK. Thanks again!

Allow rewrite status to be 2xx or 4xx.

---

middleware/markdown/markdown_test.go
middleware/markdown/metadata.go
middleware/markdown/metadata_test.go
middleware/markdown/process.go
middleware/markdown/testdata/docflags/template.txt
middleware/markdown/testdata/docflags/test.md

Hello, I've noticed that markdown middleware picks only those variables in JSON/TOML/YAML front matter that have type of string. There's a `map[string]string` that later gets into `{{.Doc.blah}}` directives.
However, it gets confusing when I try to use these variables as switch flags. e.g. `math: true` or `math: yes` both got skipped and set to `<no value>`. Which was very disturbing. So I've implemented `{{.DocFlags.blah}}` that maps to a `map[string]bool` where things like `math: yes` being stored.
Test looks like this:
**test.md**
```
---
var_string: hello
var_bool: true
---
```
**template.txt**
```
Doc.var_string {{.Doc.var_string}}
Doc.var_bool {{.Doc.var_bool}}
DocFlags.var_string {{.DocFlags.var_string}}
DocFlags.var_bool {{.DocFlags.var_bool}}
```
**RESULT**
```
Doc.var_string …
```

Implement .DocFlags directive and tests

---

dist/init/README.md
dist/init/freebsd/caddy

As providing a base framework for deploying Caddy in production becomes a larger interest to many people, I've created a directory called `dist/init/` to have a place to provide init scripts for various systems.
I've also added a FreeBSD service script I wrote myself to get Caddy running on FreeBSD.
If you're ok with it, I'd be glad to see more people adding init scripts for `sysvinit`, `systemd` and `upstart` as already discussed in various bug reports.

Proposal: Folder for init scripts within dist / FreeBSD service script

---

caddy/directives.go
main.go

This adds a `-directive` flag. This helps users confirm if custom build includes  a directive.
Example
```
caddy -directives | grep git
```

Add flag to list directives.

---

server/server.go

Minor change to server/server.go such that /.well-known/acme-challenge
can be passed through when TLS.Manual is true on the vhost the request
came in through.

Play nice when ACME used manually.

---

middleware/proxy/policy.go
middleware/proxy/policy_test.go
middleware/proxy/proxy.go
middleware/proxy/upstream.go
middleware/proxy/upstream_test.go

As per my comment https://github.com/mholt/caddy/issues/613#issuecomment-193796875, checking along with the other per-server checks makes for fewer code added, but with somewhat confusing method name.
The alternative is adding a `Full()` method on the host, with `CheckFull()` function on the upstream, and do do the `Full()` check in basically all the same places are where the `Down()` check is done.

Add check for per-host maximum connections

---

caddy/setup/mime.go
caddy/setup/mime_test.go
middleware/mime/mime.go
middleware/mime/mime_test.go

- The mime middleware used filepath where it should arguably use path.
- Changed the configuration to use a map instead of scanning an array
during every request.  The map is static (after configuration), so
should be fine for concurrent access.
- Catch duplicate extensions within a configuration and error out.
- Add tests for new error case.

Fixup mime middleware to use a map and error on duplicate extensions.

---

middleware/context.go
middleware/markdown/markdown_test.go
middleware/markdown/process.go
middleware/markdown/testdata/header.html

This should fix #660.
I'm not sure the solution is very elegant and would welcome suggestions for a cleaner way to fix it. I don't like having to create a NewContext() function and then having that unexported field in Context... it just feels hacky.
Edit: Refactored and squashed, so I think this'll do now.

Included files in Markdown templates have access to document vars

---

.gitattributes
dist/init/linux-systemd/caddy@.service

This iterates on the exemplary unit files for systemd. It does not add anything new to the Caddy binary itself.

Update unit files for systemd

---

caddy/directives.go
caddy/setup/pprof.go
caddy/setup/pprof_test.go
middleware/pprof/pprof.go

This is a really simple middleware for profiling caddy. It simply adds the pprof routes at the same paths the pprof package adds when you import it.
config is simply adding `pprof` to your caddyfile. Nothing else is supported.
I added it as a default middleware simply because I can't see any reason it would ever need serious changes or issues. 
Is this valuable enough to merge? Does it need documentation, or should it just be for caddy devs who know about it? It doesn't have a ton of use for general users, but I think it can be real useful in analyzing caddy's memory/cpu footprint if issues arise.
Fixes #610

Adding pprof middleware for profiling caddy.

---

middleware/fastcgi/fastcgi.go
middleware/path.go
middleware/path_test.go

This adds ability to check for file systems case sensitivity. Middlewares can now call `middleware.CaseSensitiveFS` to know if the file system is case sensitive or not and handle it as required.
This also caters for FastCGI middleware.

Handle file system case sensitivity.

---

caddy/directives.go
caddy/setup/expvar.go
caddy/setup/expvar_test.go
middleware/expvar/expvar.go
middleware/expvar/expvar_test.go

Right now it has a very simple configuration:
expvar /debug/vars
It will return a JSON object with memory statistics and the command line
used to start caddy, which are the two expvars that expvar registers by
default.
Since it's doing the same thing as expvar, any published variable will show up in the output.
What I'd like to do later is have per-vhost variables. Could be as simple as naming the published variables along the lines of host/varname.

Add expvar middleware

---

middleware/context.go
middleware/context_test.go

Adds the following methods available to templates:
- ToUpper: passthrough to strings.ToUpper
- ToLower: strings.ToLower
- Split: strings.Split
- Slice: builds a []interface{} from arguments
- Map: builds a map[string]interface{} from arguments.

Adding some useful utility functions for templates

---

dist/init/linux-upstart/README.md
dist/init/linux-upstart/caddy.conf

I've added the upstart configuration from my blog to the `dist/init` directory as you asked, @mholt. I also added a very quick overview about how it works.

dist/init: caddy.conf for upstart

---

caddy/https/https.go
caddy/https/setup.go
caddy/https/setup_test.go

Now it´s possible to do this:
```
domain.com {
tls me@domain.com {
key_type ec384 // ec256, rsa8192, rsa4096 or rsa2048
}
}
```

A new feature for the "tls" directive

---

middleware/proxy/reverseproxy.go

Caddy expects "websocket" to be completely lowercase.
Some applications send websocket Upgrade headers as shown below:
`Upgrade: WebSocket`
This change allows all variations of "websocket" and fixes https://github.com/rancher/rancher/issues/4278.

Allow mixed case Upgrade headers

---

caddy/parse/parsing.go
caddy/parse/parsing_test.go
server/server.go

RFC 3986 3.2.2: The host subcomponent is case-insensitive.

Handle host names case insensitively.

---

caddy/setup/browse.go

In order to have directly a link within the browse listing I have added
a link to the top of the table to get one level up in the tree. Added
that after a chat with @mholt.
Signed-off-by: Thomas Boerger <thomas@webhippie.de>

Added "go up" link to browse template

---

middleware/context_test.go

As Go tip has changed the error message I have made the tests less
restrictive to match older versions and tip version of the error.
Signed-off-by: Thomas Boerger <thomas@webhippie.de>

Make the TIP test happy again

---

middleware/browse/browse.go

In order to being able to really build a custom template for the browse
directive I have added another function to build even custom breadcrumb
paths. The other function `LinkedPath` is not that easy styleable as
this map function. That way we are able to build the breadcrumb path
matching different CSS frameworks like Bootstrap.
An example implementation should look like that, matching the Bootstrap structure:
```
<ol class="breadcrumb">
{{range $url, $name := .BreadcrumbMap}}
<li><a href="{{$url}}">{{$name}}</a></li>
{{end}}
</ol>
```
Signed-off-by: Thomas Boerger <thomas@webhippie.de>

Added breadcrumb map function to browse

---

caddy/setup/browse.go
middleware/browse/browse.go

As discussed with @mholt I have dropped the old LinkedPath function and
replaced it within the browse template with the new BreadcrumbMap
function. Visually it looks exactly the same as before, now the template
functionality is just more powerful.
Signed-off-by: Thomas Boerger <tboerger@suse.de>

Dropped LinkedPath and updated browse template

---

middleware/headers/headers.go
middleware/headers/headers_test.go
middleware/replacer.go
middleware/replacer_test.go

Issue #738
On matched header rules, replacer is used to replace any placeholders
defined in header rules iex. `X-Backend {hostname}` where `{hostname}` will
be replaced by the hostname key present in the replacer
hostname key added to replacer. The value is determined by the output of
`os.Hostname()`

Add hostname placeholder. Headers use replacer

---

caddy/setup/browse.go
middleware/browse/browse.go
middleware/browse/browse_test.go

Middleware browse has been refactored for better maintainability and extendability. As a result features that had been in one format are carried over to all other.
The outstanding cause for much grief—datetimes shown to visitors in the "wrong" format ('wrong' being a mismatch between expected format and what Caddy delivers)—has been addressed by delegating its formatting to the visitor's browser.
Standardizing the timezone of all returned datetime instances on UTC, and not depending on filesystem implementation details when sorting any directories, yields a well-defined user experience no matter where and on what system Caddy is actually deployed.

Make Browse Great Again ★★★

---

middleware/proxy/proxy.go
middleware/proxy/reverseproxy.go

While debugging #782, I noticed that using http2 and max_fails=0,
X-Forwarded-For grew infinitely when an upstream request failed after
refreshing the test page. This change ensures that headers are only
set once per request rather than appending in a time-terminated loop.
This change looks slightly bigger than it is since I inverted the big `if` statement at the top so we could just `continue` and avoid a level of indentation for a lot of the code. I also reordered a few things as it made sense to me; overall I feel like this is a change for the better, making things a little simpler, but I'm not sure I haven't broken something.
This change doesn't fix #782, #666, or #719, but it's one step closer I guess.
@nemothekid I'd really appreciate your review/critique on this when you have a …

proxy: Move handling of headers around to prevent memory usage spikes

---

middleware/proxy/proxy.go
middleware/proxy/proxy_test.go
middleware/proxy/reverseproxy.go
middleware/proxy/upstream.go

Issue #666 
Headers of the request sent by the proxy upstream can now be modified in
the following way:
Header prefixed with `+`: Header will be added if it doesn't exist
otherwise, the values will be merge
Header prefixed with `-': Header will be removed
Header with no prefix: Header will be replaced with given value
Based on the issue reported. This only modifies the headers sent upstream and not the headers of the response received from the upstream. 
I did, however investigate modifying the headers received from the upstream. Which required me changing `reverseproxy.go`. I removed it in the end since it felt like a hack. I feel it would be better to add `proxy_resp_header` to the proxy directive which makes the direction the headers should be applied clear.

Overwrite proxy headers based on directive #666

---

caddy/caddy.go
caddy/helpers.go
caddy/restart.go
caddy/restartinproc.go
main.go

This patch allows Caddy to restart in-process gracefully without the `-restart=inproc` flag, replacing the current default Restart on POSIX system.

Restart gracefully with in-process restart

---

dist/init/linux-systemd/README.md

Condenses the README file a bit, stresses that you need a up-to-date *systemd*, and highlights how to debug a failed start of *caddy* using system logs.

systemd, README: Edit to account for the recent spike in reports

---

caddy/setup/proxy_test.go
middleware/proxy/upstream.go

Hi! First PR here!
I added the upstream directive mentioned in #115 
This adds the ability to add an upstream directive to a proxy block, and is also compatible with the common format. Also support for port ranges is added, so the formats below will be supported:
```yaml
proxy / localhost:80 {
upstream example.com:8080-8090
....
}
```
```yaml
proxy / {
upstream example.com:8080-8090
....
}
```
```yaml
proxy / localhost:80 {
....
}
```
```yaml
proxy / {
upstream example.com:8080-8090
upstream localhost:2222-2225
....
}
```
...and so on.
I also added some tests for it.
Expecting your impressions about it!

Add upstream directive

---

caddyhttp/httpserver/server.go

Since the related changes in Go stdlib (https://github.com/golang/go/issues/9478, https://github.com/golang/go/issues/14204) is pushed back to Go 1.8 (ETA 2017 Feb), I think it is good time to make this change in Caddy as 0.9 is merged in master.
Closes  #809.

Close idle connections after graceful shutdown timeout

---

caddyhttp/proxy/upstream.go
caddyhttp/proxy/upstream_test.go

Hey! First time contributor and caddy user for that matter.
Based on #851 I've added the `reverse_proxy` preset for the proxy directive and a couple of tests to go with it.
**Example**
```
localhost {
proxy / localhost:8080 {
reverse_proxy
}
}
```
Instead of
```
localhost {
proxy / localhost:8080 {
proxy_header Host {host}
proxy_header X-Real-IP {remote}
proxy_header X-Forwarded-Proto {scheme}
}
}
```
Looking forward to a code review

Add reverse_proxy preset

---

caddyhttp/proxy/policy.go
caddyhttp/proxy/policy_test.go

Before, when load balancing across multiple hosts, if a host went down
then the next host in line would be sent a double share of requests.
This is because the round robin counter was only incremented once per
request, regardless of the health of the selection. If current
selection was unhealthy then the policy would advance to the next host,
but this would not be reflected in the policy counter. To fix this, the
counter is now incremented for every attempted host.
This commit adds a test case that identifies the issue, and a fix.

Balance round robin evenly when some hosts are down

---

caddyhttp/rewrite/to.go
caddyhttp/rewrite/to_test.go

Prevent `rewrite.To()` method to use `path.Clean()` on URL's query.
Closes #884.

Fix rewrite bug with URL query + test case (#884)

---

caddyhttp/proxy/upstream.go
caddyhttp/proxy/upstream_test.go

The `DefaultClient` in net/http doesn't specify a timeout and is 0 by default. Which means if a server is causing a connection to hang the request will hang.
This is to add a way to specify a "timeout" on health_check, as well as set a sensible 60 second default.
Example:
```
localhost {
proxy / localhost:8080 {
health_check /health interval=10s timeout=15s
}
}
```
Looking forward to everyones thoughts. 😄

Add timeout to health_check

---

caddyhttp/httpserver/server.go

This change will advertise QUIC availability using [Alt-Svc & Alternate-Protocol (deprecated) header](http://httpwg.org/http-extensions/alt-svc.html#alt-svc).
In the future, when the Chromium [host whitelist restriction](https://groups.google.com/a/chromium.org/forum/#!msg/proto-quic/1K79SVSLEiU/bvMLV0juEwAJ) will be removed clients will automatically switch to QUIC without special configuration described in [wiki](https://github.com/mholt/caddy/wiki/QUIC).
Furthermore instead of forcing QUIC, host can be whitelisted using command line flag:
```
/Applications/Google\ Chrome.app/Contents/MacOS/Google\ Chrome \
--user-data-dir=/tmp/chrome \
--no-proxy-server \
--enable-quic \
--quic-host-whitelist="YOUR_SITE" "YOUR_SITE"
```

Add support for Alt-Svc header

---

caddyhttp/markdown/markdown.go
caddyhttp/markdown/metadata/metadata.go
caddyhttp/markdown/metadata/metadata_json.go
caddyhttp/markdown/metadata/metadata_none.go
caddyhttp/markdown/metadata/metadata_test.go
caddyhttp/markdown/metadata/metadata_toml.go
caddyhttp/markdown/metadata/metadata_yaml.go
caddyhttp/markdown/process.go
caddyhttp/markdown/template.go

Hi Caddy community!
I took [Matt's advice](https://twitter.com/mholt6/status/744976277552062464) and wanted to get involved. 
I added comments to the `markdown` package to remove `golint` warnings. This commit removes all warnings that are possible to be removed. The interface required by `blackfriday`, the markdown library forces the remaining two warnings to remain.
I threw this together pretty quickly so if you'd like me to change something, feel free to comment with feedback.
Thanks!

Refactoring to remove lint

---

caddyhttp/proxy/policy_test.go
caddyhttp/proxy/proxy_test.go

This tests test two cases:
- When no host is specified, the address/host of the proxy should be used as host
- When the host is specified, it should appear in the request

Test that the host header forwarding on proxy

---

dist/init/linux-systemd/README.md
dist/init/linux-systemd/caddy.service
dist/init/linux-upstart/README.md
dist/init/linux-upstart/caddy.conf

`/usr/local/bin` is a more appropriate location for the Caddy binary to be installed. I believe `/usr/bin` is more geared towards distribution-managed programs and so there's a possibility that that directory may be changed during a distribution upgrade while `/usr/local/bin` wouldn't be.
As a side note, this change would help me in my efforts to automate the installation of Caddy on my servers.

Changing refs from /usr/bin to /usr/local/bin

---

caddy.go
caddy/caddymain/run.go
caddyhttp/httpserver/server.go
plugins.go

Extend the Server interface with ServePacket and ListenPacket - this is
in the same vein as the net package.
Plumb the packetconn through the start and restart phases.
Rename RestartPair to RestartTriple as it now also contains a Packet.
Not that these can now be nil, so we need to check for that when
restarting.

Allow for UDP servers

---

caddyhttp/httpserver/plugin.go

First, great job on the 0.9 release! It seems caddy's path lead into a bright future. Thanks also for including the locale plugin.
Trying it, I've figured out, that there might be a problem with the order of the directives. In the typical use case, the result of the locale detection might be used in the `rewrite` and `log` plugin. If I'm not mistaken, it makes sense to put the `locale` directive before those.

Change position of locale directive

---

dist/init/linux-sysvinit/README.md
dist/init/linux-sysvinit/caddy

In addition to `linux-upstart` and `linux-systemd`, I think this one might be very useful too.
The script is based on [this script](https://git.devuan.org/fredg/stuffs/blob/master/caddy/init.d/caddy) by @fredg, found via [Installation du serveur Caddy sous Devuan &middot;  Frédéric Galusik](http://galusik.xyz/installation-caddy-server-devuan/#démon:d7570338f345f168f3c50f22e7f8c47c). I have modified it into an extended version myself, since I had the need for this.

dist/init/linux-sysvinit: caddy for SysVinit

---

caddyhttp/httpserver/server.go

This re-enables HTTP/2 with Go 1.7. I am defensively setting the map to {"h2"}, if caddytls.MakeTLSConfig didn't set anything beforehand. Does that make sense?
It works on my public server.
fixes #975

Re-enable HTTP/2 for Go 1.7.

---

caddyhttp/proxy/policy.go
caddyhttp/proxy/policy_test.go
caddyhttp/proxy/proxy.go
caddyhttp/proxy/proxy_test.go
caddyhttp/proxy/upstream.go
caddyhttp/proxy/upstream_test.go

This would allow for "sticky sessions" based on client IP.  The basic algorithm is to hash the client IP address and then take `hash % len(pool)` which gives a fairly evenly distributed load but with the assurance that the request will be routed to the same host every time.

added ip_hash load balancing WIP

---

dist/init/linux-sysvinit/caddy

`$(which setcap)` might evaluate to nothing, and this way the error thrown will be more clear.
If setcap is not available on Debian/Ubuntu, you can install the package `libcap2-bin`

dist/init/linux-sysvinit: execute setcap directly

---

caddyhttp/proxy/proxy.go
caddyhttp/proxy/proxy_test.go
caddyhttp/proxy/reverseproxy.go
caddyhttp/proxy/upstream.go

More discussion in #938 - 
if the requests coming into Caddy are much greater than the maximum idle connections allowed in the transport backend, Caddy will continue to create more and more connections until the OS runs out of sockets.
This PR adds a [keepalive](http://nginx.org/en/docs/http/ngx_http_upstream_module.html#keepalive) option, like nginx that allows you set the number of idle connections for a proxy backend, allowing you to increase it from the default, defined in golang as 2 (or disable it).
To keep consistent with the internal `MaxIdleConnsPerHost` option on `http.Transport`, setting `keepalive` to 0, will actually keep the default value of 2. Setting it to a negative number (-1) will actually disable keepalives (new connection for every request).
I'm not sure what the …

Proxy: Add keepalive directive to proxy to set MaxIdleConnsPerHost on transport

---

caddyhttp/proxy/proxy_test.go
caddyhttp/proxy/reverseproxy.go

This PR depends on #984 because they would need to be merged and I didn't want to do that work.
The relevant commits to this PR are c4e65df and d534a21. 
How it essentially works is it created a new transport for Websockets connections (kind of wasteful), but then hijacks the connection on that transport and uses it to continue the websocket connection.
It passes the test created in #764, but I'm not sure if it actually fixes the problems outlined in #746.

Proxy: Single WebSocket connection

---

caddytls/setup.go
caddytls/setup_test.go

With this pull request, you can define just one TLS Protocol (Caddyfile)
> Caddyfile
```
example.com {
tls {
protocols tls1.2
}
}
```
**Why ?**
Caddy should be simple :heart:
> Caddyfile
```
example.com {
tls {
protocols tls1.2 tls.1.2
}
}
```
P.S.: I know you like tests @mholt, so I already included one!

Allow just one TLS Protocol (Caddyfile)

---

caddyhttp/basicauth/basicauth.go
caddyhttp/basicauth/basicauth_test.go

This is hopefully an acceptable workaround for #708, which is currently breaking HTTP Basic auth for many Android apps.

Add default "Restricted" realm to HTTP Basic auth

---

caddytls/user_test.go

We are using (see below) to generate a new user
```
func newUser(email string) (User, error) {
user := User{Email: email}
privateKey, err := ecdsa.GenerateKey(elliptic.P384(), rand.Reader)
if err != nil {
return user, errors.New("error generating private key: " + err.Error())
}
user.key = privateKey
return user, nil
}
```
We should do the same as a test (for the sake of integrity)!

Use P384 for TestUser (privateKey)

---

caddyhttp/errors/errors.go
caddyhttp/errors/errors_test.go
caddyhttp/errors/setup.go
caddyhttp/errors/setup_test.go

Add ability to specify default (fallback) error page in Caddyfile  via '*' as status code. This addresses #752

Add support for default (wildcard) error page

---

caddyhttp/errors/setup.go
caddyhttp/errors/setup_test.go

Check for duplicate status code entries in 'errors' directive as  was proposed by @vchimishuk in #1028

Check for duplicate status code entries in 'errors' directive

---

caddyhttp/errors/setup_test.go

Fix mistake in checking error conditions

Fix error which lead to skipping tests in 'errors.TestErrorsParse'

---

caddyhttp/httpserver/context.go
caddyhttp/httpserver/context_test.go
caddyhttp/httpserver/replacer_test.go

Feature request from [forum post](https://forum.caddyserver.com/t/environment-variables-in-templates/321)
* Environment variables in templates work as:
`{{.Env.NAME}}` ~~and for debugging you can do `{{.PrintEnv}}` to get them all with new-line breaks.~~
Includes test cases.

Added support for environment variables to 'templates' module.

---

caddy.go
plugins.go

Make ServerListeners public and add two helper methods to get access
to the address they listen on. This is useful for tests (among other
things)
Also make DefaultConfigFile a var so it can be overridden by server
types.

Implement missing bits for an external servertype

---

caddytls/client.go
caddytls/config.go
caddytls/config_test.go
caddytls/filestorage.go
caddytls/storage.go
caddytls/storagetest/memorystorage.go
caddytls/storagetest/storagetest.go
caddytls/tls_test.go

SiteExists lacked an error parameter, this can be used when there are OS or networking errors

Add error parameter to storage.SiteExists()

---

caddyhttp/proxy/reverseproxy.go

Instead of setting DisableKeepAlives, set MaxIdleConnsPerHost to -1 to prevent net/http from pooling the connections. DisableKeepAlives causes net/http to send a Connection: Closed header which is bad. Fixes #1056

Proxy: Set MaxIdleConnsPerHost to -1 to prevent Idle Conns

---

caddyhttp/caddyhttp_test.go
caddytls/config.go
caddytls/config_test.go
caddytls/filestorage.go
caddytls/setup.go
caddytls/tls.go

To use a plugged in storage, specify "storage storage_name" in the tls block of the Caddyfile, by default, file storage will be used

Add plugin capabilities for tls storage.

---

caddyhttp/proxy/reverseproxy.go

Removing quic protocol headers from being persisted during proxy requests.
Not removing them could lead to the client attempting to connect to the wrong port.
This makes the quic headers consistent with other protocol headers.

Keep quic protocol headers only between one hop

---

caddytls/config.go

It was set by default on the caddy-internal config object, and even
checked for conflicts, but it was never actually reflected on the
tls.Config.
This will have user-visible changes: a client that prefers, say, AES-CBC
but also supports AES-GCM would have used AES-CBC befor this, and will
use AES-GCM after.
This is desirable and important behavior, because if for example the
server wanted to support 3DES, but *only if it was strictly necessary*,
it would have had no way of doing so with PreferServerCipherSuites
false, as the client preference would have won.

Actually set tls.Config.PreferServerCipherSuites

---

caddy.go
caddy/caddymain/run.go

Caddyfiles read from STDIN now have server types associated with them.

---

caddyhttp/httpserver/plugin.go

This adds the multipass plugin to the Caddy's directives.
Relates to: https://github.com/caddyserver/caddyserver.com/pull/67

Add the multipass plugin to the directives

---

dist/init/linux-systemd/README.md
dist/init/linux-systemd/caddy.service

This PR makes a number of improvements to the Linux systemd service file and instructions.
* Make the caddy service file compatible with older versions of systemd so it works for more people. Accomplish this by commenting out optional directives that only work with newer versions of systemd.
* Simplify the structure of the instructions.
* Add much more complete step by step instructions for setting up the caddy service.
I tested this thoroughly on RedHat 7 on AWS, running systemd v219.

improvements for Linux systemd integration

---

caddyhttp/fastcgi/dialer.go
caddyhttp/fastcgi/fastcgi.go
caddyhttp/fastcgi/fastcgi_test.go
caddyhttp/fastcgi/fcgiclient.go
caddyhttp/fastcgi/setup.go

This builds on https://github.com/mholt/caddy/pull/1087 and fixes https://github.com/mholt/caddy/issues/1123. Reconnects if required and allows a configurable number of connection to reuse in the pool.
This instructs fastcgi to attempt to persist and reuse up to 5 connections. 
```
fastcgi / 127.0.0.1:900 php {
pool 5
}
```
It is disabled by default unless the configuration is added and `pool > 0`.
`pool 1` works fine from all my tests.
Caddyfile
```
0.0.0.0
root /src
fastcgi / fpm:9000 php {
pool 1
}
```
Result
```
❯ hey -n 1000 -c 20 http://localhost:2015
Summary:
Total:	8.8103 secs
Slowest:	0.3320 secs
Fastest:	0.0379 secs
Average:	0.1743 secs
Requests/sec:	113.5040
Status code distribution:
[200]	1000 responses
Response time histogram:
0.038 [1]	|
0.067 [4]	|∎
0.097 [20]	|∎∎∎
0.126 …
```

Fastcgi persistent fix

---

caddyhttp/proxy/proxy_test.go
caddyhttp/proxy/reverseproxy.go

This PR contains two parts:
1. Fix a subtle bug in `TestDownstreamHeadersUpdate` and `TestUpstreamHeadersUpdate`: wrong logic when checking `Merge-Me` header. Also do a minor refactor.
2. Don't append a predefined header: Some plugins may already set response headers(e.g. MIME plugin). I think the proxy shouldn't append them which may lead to misleading or duplication.

proxy: don't append predefined headers

---

caddyhttp/proxy/proxy.go
caddyhttp/proxy/proxy_test.go
caddyhttp/proxy/upstream.go

This PR should fix #1069 and resolve a few other outstanding irritants in proxy behavior for backends that are less-than-robust. In summary:
- Proxy no longer retries by default when a request fails, because `tryDuration` (now a configurable value on the Upstream itself) defaults to 0. This means that, by default, the downstream client must retry their request when a host initially goes down or no hosts are available.
- New configuration subdirectives: `try_duration` and `try_interval`. try_duration specifies how long to try selecting hosts (used to be 60s) until one succeeds. The introduction of try_interval (with a default of 1s) is there to prevent tight loops that spin the CPU in case all the requests fail gloriously fast; this also operates under the assumption that hosts won't …

proxy: Improve failover logic and retries

---

caddyhttp/proxy/policy.go
caddyhttp/proxy/policy_test.go

This should fix https://github.com/mholt/caddy/issues/1136.
Instead of modifying the pool directly I make a copy of it and remove hosts from the copy.  I'm not sure if this is the best way to do this or not.
It's necessary to keep track of the host pool because simply decreasing the `poolLen` could result in traffic still being sent to the down host.

1136 fix (IP hash policy no longer removes down host from pool)

---

caddyhttp/browse/setup.go
caddyhttp/browse/setup_test.go

Hello,
it is just the removing of the eager check in the browse middleware as stated in https://github.com/mholt/caddy/issues/1085
Caddy will start and throw a 404-error until the directory will be created.
Hopes that helps you ;)

Remove the eager check in the browse middleware

---

caddytls/config.go
caddytls/setup.go
caddytls/setup_test.go

This PR implements the feature request #1117 😄 
Caddyfile:
````
domain.com {
tls {
curves ab123, cd456, ef789
}
}
```
Supported Curves (https://golang.org/pkg/crypto/tls/#CurveID):
```
p256 
p384 
p521 
```

Feature Request: #1117

---

caddyhttp/httpserver/replacer.go
caddyhttp/httpserver/replacer_test.go

Fixes: https://github.com/mholt/caddy/issues/1066
This pull request changes the value of the default latency unit to use milliseconds.

Have milliseconds as the latency log time unit

---

caddyhttp/httpserver/plugin.go

All required pull request to enable full support of github.com/echocat/caddy-filter plugin:
* https://github.com/mholt/caddy/pull/1167
* https://github.com/caddyserver/buildsrv/pull/33
* https://github.com/caddyserver/caddyserver.com/pull/84

Added directive "filter" to whitelist for support of caddy-filter plugin

---

caddyhttp/fastcgi/fastcgi.go
caddyhttp/fastcgi/fastcgi_test.go
caddyhttp/fastcgi/setup_test.go
caddyhttp/markdown/summary/render.go

Preventing the deletion of  `Caddy-Rewrite-Original-URI` from header allows php fastcgi apps to correctly log the url requested.
With my basic testing seems to fix #1153 
I do not have enough knowledge to know if the other lines in the if statement are relevant or should also be removed.

Very simple fix for #1153

---

dist/init/linux-upstart/README.md
dist/init/linux-upstart/caddy.conf.centos-6
dist/init/linux-upstart/caddy.conf.ubuntu-12.04

The upstart versions of centos 6 and ubuntu 12.04 are missing features that are configured in the current upstart file. This PR adds separate files for these OSes.

add separate upstart scripts for centos 6 and ubuntu 12.04

---

.travis.yml
README.md
caddyhttp/log/log_test.go
caddyhttp/proxy/proxy_test.go

This PR is due to changes made in Golang's tip: https://github.com/golang/go/issues/17525
There's also one outstanding bug on golang's tip that I cannot track: reading from ping-pong WS proxy causes EOF
```
go test ./...
--- FAIL: TestWebSocketReverseProxyFromWSClient (0.00s)
proxy_test.go:205: EOF
FAIL
FAIL	github.com/mholt/caddy/caddyhttp/proxy	0.039s
```
**Please note:** this PR will PASS on golang 1.7.3 and fail on golang's tip.

Use proper Request

---

caddyhttp/httpserver/server.go

This is a 1 line fix for #1205. 
Details of each site started will be written to Log as well as stdout.
I dont think this needs a test case.

Log Site start to -log. Fix for #1205

---

caddyhttp/proxy/proxy.go
caddyhttp/proxy/proxy_test.go

Some web servers (e.g. Jetty 9.3) don’t like HTTP headers with empty values. This commit filters header replacements with zero length.
Should fixes #1225

Filter empty headers

---

dist/init/mac-launchd/README.md
dist/init/mac-launchd/com.caddyserver.web.plist

I added the *launchd* service file from my blogpost to the *init* folder.
It's not as good as the Linux ones because paths are not that fixed on Mac. So users can put Caddy wherever they want. But I figured out that adding a sample plist file would be useful.

launchd service file for Mac

---

caddyhttp/httpserver/context_test.go

This is a minor fix for an intermittent failure by TestFiles:
--- FAIL: TestFiles (0.00s)
context_test.go:771: Test [1]: Expected files [file1 file2], got: [file2 file1]
FAIL
FAIL	github.com/mholt/caddy/caddyhttp/httpserver	0.050s
Since Files() does not guarantee the order of the files returned, the test sorts the resulting slice before comparing to the expected one.

Sort the resulting slice before the comparison.

---

caddyhttp/fastcgi/dialer.go
caddyhttp/fastcgi/fastcgi.go
caddyhttp/fastcgi/fastcgi_test.go
caddyhttp/fastcgi/fcgiclient.go
caddyhttp/fastcgi/fcgiclient_test.go
caddyhttp/fastcgi/setup.go
caddyhttp/fastcgi/setup_test.go

Hi,
Here's a summary of the changes for #1094 , as well as some questions/concerns.
I added a new connect_timeout property to the fastcgi directive, e.g.:
fastcgi / 127.0.0.1:9000 {
connect_timeout 10s
}
I can test the new property using docker-compose: use iptables on the proxy 
and drop packets that are outbound to the FastCGI service.
I'm having a hard time writing a test for it. I combed through the net
package to find some way to generate a i/o timeout but found nothing. Some
[tests](https://golang.org/src/net/timeout_test.go) in the net package use
internal packages-those appear to be the ones with which the connection can be
impeded.
Any suggestions on how to test this while continuing to use net.Dialer?
Similarly, here's the new read_timeout property:
fastcgi / 127.0.0.1:9000 { …

Add connect_timeout and read_timeout to fastcgi.

---

dist/init/linux-systemd/caddy.service
dist/init/linux-upstart/caddy.conf
dist/init/linux-upstart/caddy.conf.centos-6
dist/init/linux-upstart/caddy.conf.ubuntu-12.04

Maybe make the path also equal, i found:
- `/etc/ssl/caddy`
- `/etc/caddy`
- `/etc/caddy/ssl`
And for MAC, i do not know :sweat_smile:

Init switch from HOME to Caddy

---

caddy.go
caddy_test.go
caddytls/client.go

Hello @mholt ,
this PR should fix issue #1258:
```
2016/11/24 16:10:41 [INFO] Obtaining new certificate for 1.caddy.domain.com
2016/11/24 16:10:42 [INFO] acme: Registering account for
2016/11/24 16:10:42 [INFO][1.caddy.domain.com] acme: Obtaining bundled SAN certificate
2016/11/24 16:10:43 [INFO][1.caddy.domain.com] acme: Trying to solve TLS-SNI-01
2016/11/24 16:10:45 [INFO][1.caddy.domain.com] The server validated our request
2016/11/24 16:10:45 [INFO][1.caddy.domain.com] acme: Validations succeeded; requesting certificates
2016/11/24 16:10:46 [INFO] acme: Requesting issuer cert from https://acme-staging.api.letsencrypt.org/acme/issuer-cert
2016/11/24 16:10:46 [INFO][1.caddy.domain.com] Server responded with a certificate.
2016/11/24 16:10:46 [WARNING] Stapling OCSP: no OCSP stapling for …
```

Fix issue #1258

---

caddy_test.go

This PR increases code coverage:
I cannot trigger (see below), as `ln, err := net.Listen("tcp", "[::]:0") == ln, err := net.Listen("tcp", "0.0.0.0:0")`!
```
if lnAddr == net.JoinHostPort("0.0.0.0", port) {  //covered
return true // not covered
} //covered
```
Soon,
Eldin 😄 
P.S.: Sorry for the separate PR, you pushed my PR a little bit too fast (I was 😴 ) -- I guess it´s not a big problem?

Increase code coverage (caddy.go)

---

caddyhttp/fastcgi/dialer.go
caddyhttp/fastcgi/fastcgi.go
caddyhttp/fastcgi/fastcgi_test.go
caddyhttp/fastcgi/fcgiclient.go
caddyhttp/fastcgi/fcgiclient_test.go
caddyhttp/fastcgi/setup.go
caddyhttp/fastcgi/setup_test.go

See #1094.
This update adds the send_timeout property to the fastcgi directive.
fastcgi / 127.0.0.1:9000 {
send_timeout 10s
}
Like the connect_timeout and read_timeout properties, send_timeout has a default value of 60 seconds.
I added/refactored some tests along the way.

Add send_timeout property to fastcgi directive

---

caddyhttp/proxy/proxy.go
caddyhttp/proxy/proxy_test.go
caddyhttp/proxy/reverseproxy.go

@mholt We already talked in length about the contents of this PR and here it is!
I tried to split up this PR in 4 commits to clearly separate the fixes. The commit messages probably say it all. 🙂

Fixed #1292 and resulting issues from #1300

---

caddyhttp/httpserver/pathcleaner.go
caddyhttp/httpserver/pathcleaner_test.go
caddyhttp/httpserver/server.go

* A generic function is implemented to allow masking of certain patterns before calling the built-in `path.Clean()` function.
* Added default mask to preserve double slashes of protocol separator (e.g., `http://`, `https://`, or `ftp://`).
* Unit tests for the new functionality.
Note: This PR implements the functionality discussed in #1298.

Implementing custom PathClean function to allow masking, closes #1298

---

caddyhttp/httpserver/plugin.go

...to fix [#2 Replacement doesn't happen - of caddy-fitler](https://github.com/echocat/caddy-filter/issues/2).

Fix position of "filter" in directives

---

caddyhttp/basicauth/basicauth.go
caddyhttp/basicauth/basicauth_test.go

If a site owner protects a path with basicauth, no need
to use the Authorization header elsewhere upstream, especially since it
contains credentials.
If this breaks anyone, it means they're double-dipping. It's usually
good practice to clear out credentials as soon as they're not needed
anymore. (Note that we only clear credentials after they're used,
they stay for any other reason.)

basicauth: Remove Authorization header on successful authz (issue #1324)

---

caddyhttp/proxy/proxy.go
caddyhttp/proxy/proxy_test.go
caddyhttp/proxy/upstream.go

> If only one upstream is defined we don't need to buffer the body.
> Instead we directly stream the body to the upstream host, which reduces memory usage as well as latency.
> Furthermore this enables different kinds of HTTP streaming applications like gRPC for instance.
This probably fixes #1310.
Again **NOTE:** This only works if your `proxy` directive specifies only a single upstream host.

proxy: Unbuffered request optimization

---

caddy/caddymain/run.go
plugins.go

StartupHook enables the developer to create plugins that are executed in the very beginning of the Caddy process, even before it has started running. It allows, among many other things, to use flags and take advantage of the fact that Caddy hasn't started running yet to configure and enable a variety of features. I think this hook will open a whole new range of plugins.
I've already talked with @mholt about this because I was having a problem while I wanted to develop a plugin and he suggested this.

Add StartupHooks to Plugins

---

caddyhttp/httpserver/replacer.go
caddyhttp/httpserver/replacer_test.go

ISO 8601 is the standard time format and is easy to parse.
This change assumes users desiring ISO 8016 generally prefer UTC for simplicity.
This results in {whenISO} to be significantly shorter than {when}:
{when}    = "02/Jan/2006:15:04:05 +0000"
{whenISO} = "2006-01-02T15:04:12Z"
Add unit test to verify both, as there was no unit test for {when}.

Add {whenISO} to record timestamp in ISO 8601 format in UTC.

---

caddyhttp/proxy/proxy_test.go

Because of [this commit](https://github.com/golang/go/commit/6e36811c37399d60cbce587b7c48e611009c5aec) on go tip,
it will probe the request's body to determine whether to use chunked transfer
encoding which trailers depend on it.
So we just offer a non empty body to make trailers work.
fix issue #1359

proxy: fix TestReverseProxy failure on go tip

---

caddytls/certificates.go
caddytls/maintain.go

The loop which performs renewals in the background obtains a read lock
on the certificate cache map, so that it can be safely iterated. Before
this fix, it would perform the renewals in the read lock. This has been
fine, except that the TLS-SNI challenge, when invoked after Caddy has
already started, requires adding a certificate to the cache. Doing this
requires an exclusive write lock. But it cannot obtain a write lock
because a read lock is obtained higher in the stack, while the loop
iterates. In other words, it's a deadlock.
I was able to reproduce this issue consistently locally, after jumping
through many hoops to force a renewal in a short time that bypasses
Let's Encrypt's authz caching. I was also able to verify that by queuing
renewals (like we do deletions and OCSP updates), …

tls: Fix background certificate renewals that use TLS-SNI challenge

---

caddyhttp/caddyhttp.go
caddyhttp/caddyhttp_test.go
caddyhttp/httpserver/plugin.go
caddyhttp/httpserver/server.go
caddyhttp/httpserver/server_test.go
caddyhttp/httpserver/siteconfig.go
caddyhttp/timeouts/timeouts.go
caddyhttp/timeouts/timeouts_test.go

This PR enables default timeout values and makes timeouts configurable with the Caddyfile. This is important for mitigating slowloris attacks (a type of DoS attack) which will now be mostly prevented right out of the box. I'd been meaning to do this, since it's not hard, but decided it was finally time to get around to it.
Closes #1311 and fixes this forum issue: https://forum.caddyserver.com/t/non-tls-vulnerable-to-slowloris-attack/1322?u=matt
I suspect some users who are doing long-polling or have other types of extenuating proxy/websocket scenarios would need to raise or disable these timeouts. However, I tested a simple websockets web page (just an echo server using the websocket directive) and even with the default timeouts, did not experience any interruption in service. Standard …

New 'timeouts' directive to configure timeouts; default timeouts enabled

---

caddyhttp/log/log.go

A very simple fix for #1398 by simply adding a second '-' into the format for common log file.
In the future it may be desirable to add a placeholder for {>User} or {user} to "represent userid of the person requesting the document as determined by HTTP authentication" , however my personal opinion may be that in 2016 HTTP authentication even with HTTPS is not sufficiently 'common'.
This simple fix makes the caddy common file format compatible with the generally accepted 'common' file format, even if it will never provide the 'user' in the log.

Added additional '-' to common log format #1398

---

caddyfile/dispenser.go
caddyhttp/errors/setup.go
caddyhttp/errors/setup_test.go
caddyhttp/httpserver/roller.go
caddyhttp/log/setup.go
caddyhttp/log/setup_test.go

Roll all logs by default

---

caddyhttp/httpserver/plugin.go

This PR fixes #1388. 
Exit from hideCaddyfile function if no Caddyfile exists

Fix for #1388 starting with no Caddyfile

---

caddyhttp/proxy/policy_test.go
caddyhttp/proxy/proxy.go
caddyhttp/proxy/proxy_test.go
caddyhttp/proxy/upstream.go
caddyhttp/proxy/upstream_test.go

The Conns and Unhealthy fields are updated concurrently across all active
requests.  Because of this, they must use atomic operations for reads and
writes.
Prior to this change, Conns was incremented atomically, but read unsafely.
Unhealthly was updated & read unsafely.  The new test
TestReverseProxyMaxConnLimit exposes this race when run with -race.
Switching to atomic operations makes the race detector happy.

Fix data race for max connection limiting in proxy directive.

---

caddyhttp/redirect/redirect.go
caddyhttp/redirect/redirect_test.go
caddyhttp/redirect/setup.go

`cfg.TLS.Enabled` may be changed after plugin setup ([here](https://github.com/mholt/caddy/blob/master/caddyhttp/httpserver/plugin.go#L132)), but redirect plugin doesn't catch it.

redirect: determine the FromScheme at runtime (#1297)

---

caddyhttp/staticfiles/fileserver.go
caddyhttp/staticfiles/fileserver_test.go

return 404 for "not a directory" errors

---

caddyhttp/httpserver/replacer.go
caddyhttp/httpserver/replacer_test.go

This adds the ability to query the request cookies for placeholders
using the syntax "@cookiename".
For example, this would allow rewriting based on a cookie:
```
rewrite {
if {:version} is 'dev'
to /dev/index.html
}
```

Add request placeholder support for querying request cookies.

---

caddytls/crypto.go

The reason this line was needed in the first place was due to https://github.com/golang/go/issues/15421.
This change should resolve the race in #1157 as well.

Set session ticket keys properly (fixed in Go 1.8)

---

caddyhttp/httpserver/server.go
caddyhttp/httpserver/server_test.go

Go 1.8 adds two timeout values that Caddy already supports, just have to enable them.

Set Go 1.8's ReadHeaderTimeout and IdleTimeout

---

caddytls/config.go
caddytls/setup_test.go

I promised to implement X25519 😄 (even though I have no time)

Implement curve X25519 (Golang 1.8)

---

caddyhttp/proxy/proxy.go
caddyhttp/proxy/proxy_test.go
caddyhttp/proxy/reverseproxy.go

proxy: handle encoded path in URL

---

caddyhttp/httpserver/replacer.go
caddyhttp/httpserver/replacer_test.go

Solve https://github.com/mholt/caddy/issues/1470
```
*:80 {
redir 403 {
if {?foo} is bar
}
}
```
```
$ curl localhost:80
404 Not Found
$ curl localhost:80?foo=bar
<a href="/403">Moved Permanently</a>.
```

Request placeholders: extract query argument

---

caddyhttp/httpserver/context.go
caddyhttp/httpserver/https.go
caddyhttp/httpserver/https_test.go
caddyhttp/httpserver/plugin.go
caddytls/client.go
caddytls/config.go

This commit removes _almost_ all instances of hard-coded ports 80 and
443 strings, and now allows the user to define what the HTTP and HTTPS
ports are by the `-http-port` and `-https-port` flags.
(One instance of "80" is still hard-coded in tls.go because it cannot
import httpserver to get access to the HTTP port variable. I don't
suspect this will be a problem in practice, but one workaround would be
to define an exported variable in the caddytls package and let the
httpserver package set it as well as its own HTTPPort variable.)
The port numbers required by the ACME challenges HTTP-01 and TLS-SNI-01
are hard-coded into the spec as ports 80 and 443 for good reasons,
but the big question is whether they necessarily need to be the HTTP
and HTTPS ports. Although the answer is probably no, …

httpserver: Flags to customize HTTP and HTTPS ports (including for ACME challenges)

---

caddyhttp/basicauth/basicauth.go
caddyhttp/basicauth/basicauth_test.go
caddyhttp/basicauth/setup.go
caddyhttp/basicauth/setup_test.go

Web browsers can be configured to save authenticated credentials for a combination of server and realm. Currently, the basicauth middleware always uses the default realm "Restricted". This PR supports the association of a custom realm with one or more protected resources. The benefit is that different credentials can be remembered by a browser for different groups of resources, something that applies to one of my use cases.
The changes are backward compatible. However, within a nested block, a resource to be protected can be placed after the `path` subdirective. This is in addition to simply naming a file or directory by itself as is supported currently. The new subdirective support seems to be more in line with most other middleware directives and looks a bit nicer when used with the …

Support realms with basic authentication

---

caddytls/filestorage.go

If of interest this implements issue #1394 by logging certificate location when first written to disk.
> 2017/03/06 21:53:10 [INFO][sitecert3.example.com] Certificate written to disk: C:\Users\admin\.caddy\acme\acme-v01.api.letsencrypt.org\sites\sitecert3.example.com\sitecert3.example.com.crt

Log certificate location

---

caddyhttp/proxy/reverseproxy.go

#1484. The fix is luckily very simple (it's literally only `tlsClientConfig != nil &&`). It can currently be tested by setting the default value of `httpserver.HTTP2` to `false` in `caddyhttp/httpserver/plugin.go` and then running `go test -run=TestWebSocketReverseProxyFromWSClient` (which I did).
@passcod If you know how and if you have the time it'd be really cool if you could test this PR by building caddy from source. 🙂
P.S.: This PR sadly does not contain a real testcase for 4e31a26. Reason being that we currently run all of our tests with `httpserver.HTTP2` set to `true`, which causes `TLSClientConfig` to be set and thus this error to never appear. Adding another testcase just for this very simple bug does not seem particularly helpful to me. Instead we should probably rather …

Fixed #1484

---

dist/init/linux-systemd/README.md

It makes no sense to set the executable bit on a systemd unit config file. Most likely a typo.

systemd README: set mode of caddy.service to 644 instead of 744

---

caddyhttp/gzip/gzip.go
caddyhttp/staticfiles/fileserver.go
caddyhttp/staticfiles/fileserver_test.go

This adds a Content-Length header when the file `myfile` is requested, gzip encoding is accepted and `myfile.gz` is present and served. I also added Content-Length checks to the fileserver tests.
For details see issue #1479

staticfiles: add Content-Length header (closes #1479)

---

caddyhttp/markdown/markdown.go

Ref: [caddyhttp/markdown/markdown.go](https://github.com/mholt/caddy/blob/master/caddyhttp/markdown/markdown.go#L168)
Func [strings.TrimRight](https://golang.org/pkg/strings/#TrimRight) (`TrimLeft` and `Trim`) removes *cutset* or a set of characters of type `string`, multiple times if possible:
```go
fmt.Println(strings.TrimRight("foo.md", ".md")) // ok: foo
fmt.Println(strings.TrimRight("md.md", ".md"))  // bad: <blank>
fmt.Println(strings.TrimSuffix("foo.md", ".md")) // good: foo
fmt.Println(strings.TrimSuffix("md.md", ".md"))  // good: md
```
Also see [the Go Playground](https://play.golang.org/p/TBKx3T4btT).
In order to generate the correct HTML page title from the filename, function `strings.TrimSuffix` should be used.
Searched the code base: …

markdown: backup title should use TrimSuffix not TrimRight

---

caddyhttp/proxy/policy.go
caddyhttp/proxy/policy_test.go

Hey,
as promised an implementation of the load-balancing algorithm first.
Should be help fixing:
- https://github.com/mholt/caddy/issues/1463
- https://github.com/mholt/caddy/issues/1103
Greetings

Add the first policy  which sends the request to the first available host

---

caddyhttp/browse/browse.go
caddyhttp/browse/browse_test.go
caddyhttp/staticfiles/fileserver.go

Previously the browse package invoked staticfiles.Redirect when
redirecting clients who requested a directory but with a Request-URI
that did not contain a trailing '/'. staticfiles.Redirect only used a
relative URI. This change defers the decision of how to format the
Location header value to the helper methods in the staticfiles package.

browse: Use helper functions in staticfiles to redirect

---

.gitignore
caddyhttp/browse/browse.go
caddyhttp/browse/browse_test.go
caddyhttp/browse/testdata/photos/test1/test.html

Following [this discussion on the caddy forum](https://forum.caddyserver.com/t/browse-function-display-folders-first/1613) this PR changes default ordering of a directory listing to show Directories first in alphabetical order then files in alphabetical order.  
This is the standard ordering that people expect to see in any gui (web or desktop based) display of files and folders.  The change simply modifies the main name sort.  When sorting on modified date, I have left it the same so it sorts files and folders together as a list.
I modified the test and added a folder to the test directory to show that the sorting works.

Sort Browse listing by dir first

---

.gitignore
caddyhttp/browse/browse.go
caddyhttp/browse/browse_test.go
caddyhttp/browse/setup.go
caddyhttp/browse/testdata/photos/test1/test.html

I have submitted this as a new PR for #1536 as @wmark  requested that the origional PR #1527 be reverted.
This PR has the revert and then the necessary changes applied.
- `name` sort has been reverted to previous behaviour
- Behaviour is now the same for urls where sort=name is included such as  `https://…/…/?sort=name ×{asc,desc}`
- New sort created `namedirfirst` that sorts dir then file in alpha order
- Default order when no sort defined is `namedirfirst`
- json tests updated to include sort=name in url
Sorry to create a new PR but this seemed the most straightforward way to make a clean PR.

Add new browse sort - namedirfirst

---

caddyhttp/proxy/proxy.go
caddyhttp/proxy/proxy_test.go
caddyhttp/proxy/setup.go
caddyhttp/proxy/upstream.go
caddyhttp/proxy/upstream_test.go

Closes #1503. 
This pull request adds a Stop method to the Upstream interface for safely shutting down the running goroutines.
The Stop function is registered with the Caddy controller's OnShutdown handler during setup so that the kill signal is propagated to all consumers.
I added some tests to check that healthchecks don't get sent after upstreams receive their kill signals.

Cleanly shutdown proxy healthchecks on restart

---

caddyhttp/browse/browse.go

While reading **browse** I noticed this one. We've given **directories** a special treatment due to differences in filesystem implementations, but actually forgot to sort them further by the next dimension.
As their order has been undefined until now (their apparent size is set to `-1` anyway), this does not change any expectations of legacy scripts.

browse: fix arbitrary ordering of directories with sort=size

---

caddy.go
caddy_test.go
caddytls/client.go

My first Caddy PR :)
Fix for #1592. It doesn't handle hostnames that resolves to private IPs.

Disable warning for insecure CA if located on private network.

---

dist/init/linux-systemd/README.md

Use `systemctl --version` instead of a distribution-specific command.

dist: better way to get systemd version

---

caddy.go
caddy_test.go
caddytls/client.go

Followup to #1599 after #1592 was re-opened
If `net.SplitHostPort` returns an error (i.e. no port in the address), then we need to manually strip the square brackets so that it's a valid address for `net.ParseIP`, otherwise it returns `nil`.
I also added a couple tests to cover those cases.

Fix 1592: Allow insecure CA URL on internal networks

---

caddy.go
caddyhttp/browse/browse.go
caddyhttp/httpserver/mitm.go
caddyhttp/httpserver/replacer.go
caddytls/config.go
plugins.go

Fixed most of the warning presented by running `golint ./...`
None.
None.
- ✅  I have written tests and verified that they fail without my change
- ✅ I have squashed any insignificant commits
- ✅ This change has comments for package types, values, functions, and non-obvious lines of code
- ✅ I am willing to help maintain this change if there are issues with it later
There is still some remaining warning, but I'm not sure I agree with them:
```
caddyhttp/httpserver/mitm.go:612:2: don't use ALL_CAPS in Go names; use CamelCase
caddyhttp/httpserver/mitm.go:613:2: don't use ALL_CAPS in Go names; use CamelCase
caddyhttp/httpserver/mitm.go:614:2: don't use ALL_CAPS in Go names; use CamelCase
caddyhttp/httpserver/mitm.go:615:2: don't use ALL_CAPS in Go names; use CamelCase …
```

lint fixes

---

caddyhttp/httpserver/context.go
caddyhttp/httpserver/context_test.go
caddyhttp/markdown/markdown.go
caddyhttp/templates/templates.go

During writing [my blog caddy plugin](https://github.com/tw4452852/caddy-totorow), I find that there is no way to add push links in template files. I think this is very useful to indicate server push in templates when combining with `push`.
For example, something in `index.html` looks like: 
```
...
<script src="/public/js/jquery.js" type="text/javascript" charset="utf-8"></script>
<link rel="stylesheet" type="text/css" href="/public/css/style.css" />
{{.AddLink /public/js/jquery.js}}
{{.AddLink /public/css/style.css}}
...
```
Client will receive server push for `/public/js/jquery.js` `/public/css/style.css`

Context: add Push action

---

caddyhttp/internalsrv/internal.go

make `internalResponseWriter` inherit original ResponseWriter's interfaces.
N/A.
No.

internal: inherit original ResponseWriter's interfaces

---

caddyhttp/httpserver/plugin.go

I would like to add my login plugin as an official 3rd party plugin.
It allows the login using multiple backends and plays nicely together with the existing caddy-jwt plugin. 
See the README's for more details: 
https://github.com/tarent/loginsrv
https://github.com/tarent/loginsrv/tree/master/caddy

caddy 'login' plugin

---

caddyhttp/httpserver/tplcontext.go
caddyhttp/httpserver/tplcontext_test.go

I have just read the `LinkHeader` [spec](https://www.w3.org/wiki/LinkHeader), found that we should support it more generally, like `Apache` and `Nginx` do.
rename context's `Push` action to `AddLink` for more general use case.
N/A.
Add a new template action for `AddLink`.

rename Push action for more general use

---

caddyhttp/markdown/template.go

Adds the second `args ...interface{}` parameter to the version of `Include` used with the Markdown plugin. This allows arguments to included templates when using that plugin.
I don't think this will require any changes. The documentation already implies that passing arguments to included templates should be possible.

Support template arguments for Markdown.

---

caddyhttp/log/setup.go
caddyhttp/log/setup_test.go

support additional prefix/suffix with predefined format
#1663 
Add document for this in log directive.

log: allow additional prefix/suffix with predefined format

---

caddyhttp/proxy/upstream.go
caddyhttp/proxy/upstream_test.go

Adds `health_check_port` to proxy. Similar to haproxy's `check port`.
```
proxy / {
upstream blue1:8080
upstream blue2:8080
upstream green1:8080
upstream green2:8080
health_check_path /
health_check_port 8081
}
```
This is useful when deploying in a blue/green fashion, where services expose a public and an internal(debug) port.
none
- Add `health_check_port` to upstream docs

proxy: added 'health_check_port' to upstream

---

caddyhttp/log/setup.go
caddyhttp/log/setup_test.go

This will add a check for maximum number of arguments to the log directive. If len(args) > 3 it will return an error. This can happen when having unmatched number of quotes.
#1668
None

Add check for maximum number of arguments to log directive

---

caddyhttp/httpserver/replacer.go
caddyhttp/httpserver/server.go
caddyhttp/limits/handler.go
caddyhttp/limits/handler_test.go
caddyhttp/proxy/proxy.go

Renames MaxBytesExceededErr to ErrMaxBytesExceeded and make golint happier :)
Ref: https://ci.appveyor.com/project/mholt/caddy/build/2811#L87
N/A
None

Fix lint warning by renaming MaxBytesExceededErr -> ErrMaxBytesExceeded

---

caddytls/config.go
caddytls/config_test.go
caddytls/setup_test.go

This PR allows Caddy to automatically detect the presence of absence of the AES-NI instruction set. If it is present, Caddy's normal cipher suites will be used. If AES-NI is not supported, ChaCha20 suites will be preferred over the slow, possibly not constant-time AES support that the Go runtime will use instead.
#1674
None required.

caddytls: Prefer ChaCha20 if AES-NI instruction set is unavailable

---

caddyhttp/proxy/policy.go
caddyhttp/proxy/policy_test.go

Add a new load balancer policy based on URI hashing. It reuses most code from the IP hash policy. Later this can be extended with a length and depth parameter ([ref](http://cbonte.github.io/haproxy-dconv/1.8/configuration.html#4.2-balance)).
https://github.com/mholt/caddy/issues/1463
Add new policy to https://caddyserver.com/docs/proxy

 Add new URI hash based load balancing policy

---

caddyhttp/httpserver/condition.go
caddyhttp/httpserver/condition_test.go

Adds a not_starts_with condition. The inverse of starts_with.
The rewrite "if" conditions list should be updated: https://caddyserver.com/docs/rewrite#if

Add not_starts_with condition.

---

caddyhttp/httpserver/plugin.go

New directive for the http server type called `grpc`
N/A
No document changes needed. Link to plugin's documentation --> [here](https://github.com/pieterlouw/caddy-grpc/blob/master/README.md)

Add grpc plugin directive

---

caddyhttp/gzip/setup.go

Cleans up some redundant code in the gzip initialization code.
Specifically, `gzip.NewWriter` calls `gzip.NewWriterLevel` with the compression level `gzip.DefaultCompression`.
This code otherwise functions similarly to the previous code.
n/a
None.

gzip: cleaned up writer pool initialization code

---

dist/init/linux-systemd/caddy.service

This updates the systemd unit to configure the use of SIGQUIT to trigger a graceful shutdown when the service is stopped.
I didn't create an issue for this, but I did look at open issues matching "systemd", and none of them appeared to be relevant.
The exact behavior of `systemctl start caddy`, `systemctl reload caddy`, and `systemctl stop caddy` are not currently discussed in the README. This modification does not, in my opinion, violate the principle of least surprise for the behavior of `systemctl stop caddy`.

Configure systemd to send SIGQUIT on stop

---

caddy_test.go

AppVeyor fails randomly, this PR fixes this issue (https://ci.appveyor.com/project/mholt/caddy/build/2930)
```
--- FAIL: TestListenerAddrEqual (0.00s)
caddy_test.go:156: Test 6 (127.0.0.1:1234 == 127.0.0.1:1234): expected false but was true
FAIL
FAIL	github.com/mholt/caddy	0.068s
Command exited with code 1
```
see #1711 
None

Fix TestListenerAddrEqual

---

caddyhttp/httpserver/plugin.go

The directive reauth has been added to allow configuration of the plugin [caddy-reauth](https://github.com/freman/caddy-reauth).
This pull request is not related with an existing issue.
Add documentation for new directive `reauth`

Add reauth directive

---

caddyhttp/httpserver/plugin.go

Adds the [gopkg plugin](https://github.com/zikes/gopkg) to Caddy.
NA
None necessary, however I can contribute to https://caddyserver.com/docs/http.gopkg if desired.

add gopkg plugin

---

caddyhttp/httpserver/plugin.go

Adds the `restic` directive to the list of HTTP directives. Plugin repo: https://github.com/restic/caddy
n/a
n/a

Add restic plugin directive

---

caddyhttp/markdown/markdown.go
caddyhttp/markdown/markdown_test.go
caddyhttp/markdown/setup.go
caddyhttp/markdown/setup_test.go
caddyhttp/markdown/template.go
caddyhttp/markdown/testdata/blog/test.md
caddyhttp/markdown/testdata/docflags/template.txt
caddyhttp/markdown/testdata/docflags/test.md
caddyhttp/markdown/testdata/header.html
caddyhttp/markdown/testdata/log/test.md
caddyhttp/markdown/testdata/markdown_tpl.html
caddyhttp/markdown/testdata/og/first.md
caddyhttp/markdown/testdata/tpl_with_include.html

This implements the control of markdown's template as said in [this comment](https://github.com/mholt/caddy/issues/1445#issuecomment-294700924).
While working with this issue, I found that markdown's tests won't failed even its template file is missing.
After tracking this down, this issue even exists dating back to ac4fa2c, it seems missed markdown's testdata when migrating.
add template control option and fix fake tests issue.
#1445 
we should inform the user about this option.

markdown: reload template on each request and fix fake tests

---

caddyhttp/errors/setup_test.go
caddyhttp/httpserver/roller.go
caddyhttp/log/setup_test.go
vendor/gopkg.in/natefinch/lumberjack.v2/lumberjack.go
vendor/manifest

This PR addresses https://github.com/mholt/caddy/issues/1728 and provides a new `rotate_compress` option for `log` and `errors` directive to the Caddyfile, which will enable gzip compression for rotated log files.
It also updates the Lumberjack package dependencies in the `vendor` directory, and adds go-syslog, which was not present in `vendor` and was breaking tests when this was not present.
https://github.com/mholt/caddy/issues/1728
https://github.com/caddyserver/website/pull/18

Introduce `rotate_compress` option for log and errors directives in Caddyfile

---

caddyhttp/markdown/markdown_test.go

remove unnecessary `returns` after `Fatal` and fix the real  ineffectual assignments.
The [last commit](https://github.com/mholt/caddy/pull/1682/commits/655e61ab32a72831e897a46cf8763577fa719612) in pr #1682 .
N/A.

markdown: fix the real ineffectual assignments in test

---

caddyhttp/proxy/upstream_test.go

`go vet` began failing after 078c991574647c27 and causing CI failures. 
This patch changes the Error call added in commit 078c991574647c27 to
an Errorf call to support the use of the %d and %s tokens that are needed.
https://travis-ci.org/mholt/caddy/jobs/248392875
https://ci.appveyor.com/project/mholt/caddy/build/2979
`caddyhttp/proxy/upstream_test.go:480::error: possible formatting directive in Error call (vet)`
None
This is a ~one~four-character fix, so I'm pretty sure I can safely check these. ;)

proxy: Fix CI fail from format token in Error call

---

caddyhttp/httpserver/replacer.go
caddyhttp/httpserver/replacer_test.go

Implements the 'when_unix' placholder and add a test. The timestamp for the test is taken from running  time.MOCKDATE.Unix() and putting the result in place.
https://github.com/mholt/caddy/issues/1745
https://caddyserver.com/docs/placeholders should be updated with the new placeholder

adds unix timestamp placeholder

---

caddyhttp/proxy/policy.go
caddyhttp/proxy/policy_test.go
caddyhttp/proxy/upstream.go
caddyhttp/proxy/upstream_test.go

Add a new proxy policy which routes to upstream based on the hash of a given request header's value.
Example:
```
proxy {
policy header My-Header
}
```
This also changes the `Policy` registration process to allow policies to receive a single optional `string` argument.
#1463
The new policy would need added at https://caddyserver.com/docs/proxy

add Header proxy policy

---

dist/init/freebsd/caddy

* uses more of the builtin functionality for starting and stopping of the process by using command and command_args along with procname
* removed -f from daemon as this was hiding error message that were sent to stdout on startup, now writing stdout to the logfile directly
for example, this was being hidden:
“Activating privacy features.. [www.domain.com] failed to get certificate: Error presenting token: Could not find the start of authority”
it now shows up in the log
* aded “caddy_env” to allow the setting of environment variables that caddy might need, for example when setting creds for “DNS Challenge”
* added a check to ensure caddy_config_path file exists
N/A
None! Documented in the init script

iteration on init script for freebsd

---

caddyhttp/httpserver/plugin.go

After a long time I finally think caddy-cache is ready to be published. It does not have every feature I want but I think it handles the basic thinks it needs to support:
- it handles Vary header
- it handles correct usage of cache headers with the help of https://github.com/pquerna/cachecontrol
- it handles locking and concurrency (if two request gets the server at the same time, there will be only one fetch to upstream and both original requests will get the response at the same time without having to wait until the upstream request ends)
What do you think?
Adds a middleware for http caching
https://github.com/mholt/caddy/issues/10
It needs a new section for the new cache directive

Publish caddy-cache

---

caddyhttp/gzip/gzip.go
caddyhttp/gzip/gzip_test.go

According to https://tools.ietf.org/html/rfc7232#section-2.1
> Likewise, a validator is weak if it is shared by two or more
representations of a given resource at the same time, unless those
representations have identical representation data.  For example, if
the origin server sends the same validator for a representation with
a gzip content coding applied as it does for a representation with no
content coding, then that validator is weak.
Although it seems to be harmless at most time, follow the RFC would be appreciate.
Not yet.
No documentation need to be changed.

gzip: change ETag to weak etag after gzip

---

caddyhttp/errors/setup.go
caddyhttp/errors/setup_test.go
caddyhttp/httpserver/roller.go
caddyhttp/log/setup.go
caddyhttp/log/setup_test.go

Revise log and error roller parser.
1) Each subdirective must be on its own line.
2) `rotate_compress` subdirective doesn't accept any parameter.
#1761 
N/A.

log,error: fix roller parser issue

---

caddyhttp/push/handler.go
caddyhttp/push/handler_test.go
caddyhttp/push/push.go
caddyhttp/push/setup.go

Send the push resources for `/index.html` when requesting the root/home page `/`
Fix #1744 
None

Pushes for /index.html work when surfing to /

---

caddyhttp/proxy/proxy_test.go
caddyhttp/proxy/reverseproxy.go

When proxying to a chunked websocket server, we will hang when closing the response's body because underlying connection isn't closed. Now we defer this action until the proxying is finished.
#1316 
N/A.

proxy: fix hang on chunked websocket server

---

caddyhttp/httpserver/mitm.go
caddyhttp/httpserver/mitm_test.go

Fixes a panic in some cases when checking version of software from User-Agent string
https://caddy.community/t/runtime-error-slice-bounds-out-of-range/2387?u=matt
None

mitm: Fix out of bounds error when checking software version in UA

---

caddyhttp/httpserver/server.go
caddyhttp/httpserver/siteconfig.go
caddyhttp/httpserver/vhosttrie.go

* Moves fallbackHosts to vhostTrie. Therefore, this list is no longer global, rather is per-trie(and, as a result, is per-listener).
* SiteConfig now has an option to make it a fallback site for all unmatched requests.
None
None

Move fallbackHosts to vhostTrie

---

caddyhttp/fastcgi/fastcgi.go

Closes https://github.com/mholt/caddy/issues/1788
https://github.com/mholt/caddy/issues/1788
None

fastcgi: Fix for #1788. Align atomic fields to 64-bit word (Go bug)

---

dist/init/freebsd/caddy

The freebsd init will fail in precmd because the path is wrong.
There is none, yet.
No

freebsd init: typo in filename.

---

caddyhttp/staticfiles/fileserver.go
caddyhttp/staticfiles/fileserver_test.go

static files such as notindex.html were redirected to /not.  
discovered in #1811 
none

static files ending with index filenames redirected incorrectly

---

caddy.go
caddyhttp/httpserver/https.go
sigtrap_posix.go
upgrade.go

Implements zero-downtime, graceful binary upgrades with SIGUSR2. This is the first step towards enabling automatic upgrades in production for the continued security and privacy of all sites and their connections served by Caddy. Next step in evil plan is to figure out a good, secure way to trigger rolling updates. (However, this PR is not the place to discuss those details -- try the [forum](https://caddy.community) or a new issue instead.)
I think this progress will interest @paragonie-scott as it's a step toward auto updates.
Closes #814
Update the CLI page to explain signal USR2.
Edit: D'oh, I forgot about Windows, as usual... Update: fixed.

SIGUSR2 triggers graceful binary upgrades (spawns new process)

---

caddyhttp/httpserver/condition.go
caddyhttp/httpserver/condition_test.go
caddyhttp/rewrite/rewrite.go
caddyhttp/rewrite/setup_test.go

* Fixes bug caused by Replacer running on the regular expressions in IfMatcher. We also now compile regular expressions up front to detect errors.
* Fixes rewrite bugs that come from formatting a rule as a string and failing with nil dereference caused by embedding Regexp pointer in a Rule. Re: Issue #1794
#1794 
It might be good to update the docs to let users know that they cannot use replacement vars in regular expressions.

Fix for #1794: Fixes issues with IfMatcher and regular expressions.

---

dist/init/linux-systemd/caddy.service

This is a follow up to #1719 
In short, we are now using systemd's restart limit default that is 5 allowed service restarts in 10 seconds and the restart directive was changed to `on-abnormal`, i.e. it won't restart on non-zero exit codes (e.g. on a bad Caddyfile).

Fix restart restart behaviour of the systemd service

---

dist/init/linux-systemd/caddy.service

`LimitNPROC` in `caddy.service` changed from `64` to `512`
This change solved #1723 for me. I arbitrarily doubled 64 to 128, not sure what is a better value. The error seems to be that caddy requests a 65th thread and then gets denied. Not sure if relevant to #1823 since perhaps that will affect restarting (no more "restart too quickly" errors?). Pinging @wmark
None.

Double systemd LimitNPROC to allow more threads

---

caddytls/certificates.go
caddytls/maintain.go

https://caddy.community/t/random-ocsp-response-errors-for-random-clients/2473?u=matt
Certificates are keyed by name in the cache, optimized for fast lookups
during TLS handshakes using SNI. A more "correct" way that is truly a
1:1 would be to cache certificates by a hash of the leaf's DER bytes,
but this involves an extra index to maintain. So instead of that, we
simply choose to prevent overlap when keying certificates by server
name. This avoids the ambiguity when updating OCSP staples, for instance.
(The fillCertFromLeaf changes are just cleanup, not actually related to the bug.)

tls: Fix OCSP stapling bug when certificate names overlap other certs

---

caddyhttp/browse/browse.go
caddyhttp/browse/browse_test.go

Fixes the build on Windows so I can get a release out. Will continue to investigate the issue and try to resolve it, but it's a pretty niche case and I think might be caused by how the tests are set up; I'm not sure. This PR definitely does fix one bug related to using filepath instead of path, but the tests had some permissions issues.
(none, but CI tests started failing for Windows with Go 1.9)
None

browse: Ignore one Test function on Windows (temporary)

---

caddyhttp/fastcgi/fastcgi.go
caddyhttp/fastcgi/fastcgi_test.go

As described in #1846, many PHP apps depend on the `SCRIPT_NAME` CGI environment variable. The Caddy FastCGI plugin sets `SCRIPT_NAME` to roughly what would be expected by NGINX (essentially, a path to the script relative to the URL.) Unfortunately, when using path-based routing with VHosts, the path prefix gets lost, leading to PHP software such as phpBB and anything else depending on Symphony's requestUri logic failing (and probably more stuff too.)
This patch does exactly one thing: it finds the path prefix via the request context and prepends it to the calculated `SCRIPT_NAME`. That's it. This simple change seems to be all you need to do in the circumstances I was able to think of.
This patch affects #1846.
I don't believe any changes need to be made, since this simply brings Caddy's …

Fix SCRIPT_NAME for FastCGI

---

caddyhttp/browse/browse_test.go
caddyhttp/httpserver/path.go
caddyhttp/httpserver/path_test.go

When checking if one path matches another using Path.Matches(), call path.Clean() on the paths to compress/merge multiple slashes. Note that it does NOT effectively match paths where `p == "/foo"` and `base == "//foo"` (this will be a match even though it looks like it shouldn't be) - however I think this is not a concern, as removing slashes is rare... also note that this change doesn't mutilate the request URI at all, it's only a side-effect-less change for path matching. It should fix an issue for all middlewares that use path.Matches. If they use their own path matcher, though, they're on their own...
#1859
Maybe a note somewhere that multiple slashes are merged for path matching, similar to nginx's location block, assuming `merge_slashes` is NOT `off`.
/cc @hstaugaard @magikstm

httpserver: Fix #1859 by cleaning paths when matching them

---

caddyhttp/header/header.go
caddyhttp/httpserver/server.go

Reverts the recent change to add sponsor headers to HTTP responses. I'm opening this PR here in the hope we can discuss undoing this recent addition. Ref https://github.com/WedgeServer/wedge/issues/2 and the [HN post](https://news.ycombinator.com/item?id=15237923).
You're of course free to simply close this PR immediately, but I really hope you'll consider feedback from the community (especially on HackerNews) regarding this change before doing so.
N/A
N/A
- **N/A** I have written tests and verified that they fail without my change
- **N/A** I have squashed any insignificant commits
- **N/A** This change has comments for package types, values, functions, and non-obvious lines of code

Revert "Implement Caddy-Sponsors HTTP response header"

---

dist/init/linux-sysvinit/caddy

Fixes two issues with the `dist/init/linux-sysvinit/caddy` init script, specifically it fixes an issue where the log isn't created and secondly it fixes a spurious error in the log file because the daemon user isn't responsible for writing the pid file.
None as far as I am aware.
None.
- [N/A] I have written tests and verified that they fail without my change
- [Yes] I have squashed any insignificant commits
- [N/A] This change has comments for package types, values, functions, and non-obvious lines of code
- [Yes] I am willing to help maintain this change if there are issues with it later

Fix pid error in linux sysvinit

---

caddy.go
caddy/caddymain/run.go
plugins.go

Provides a new hook that plugins can use to gain access to the `caddy.Instance`. This is particularly important to allow plugins the ability to dynamically generate a new Caddyfile and reload the server with the new configuration. 
With this change in place a plugin could access the instance as follows:
```go
func init() {
caddy.RegisterEventHook("sampleinithook", SampleInitHook)
}
func SampleInitHook(eventType caddy.EventName, eventInfo interface{}) error {
if eventType != caddy.InstanceStartupEvent {
return nil
}
instance, ok := eventInfo.(*caddy.Instance)
if !ok {
return errors.New("Invalid eventInfo provided for caddy.InstanceStartupEvent event")
}
// save the instance for later use and/or do something useful with it here
}
```
- Wiki documents this as a TODO: …

Add hook for instance startup

---

caddyhttp/fastcgi/fastcgi.go
caddyhttp/fastcgi/fastcgi_test.go
caddyhttp/fastcgi/setup.go
caddyhttp/fastcgi/setup_test.go

Adds support in fastcgi module to discover upstreams using SRV lookup
closes: https://github.com/mholt/caddy/issues/1803
The fastcgi module documentation (https://caddyserver.com/docs/fastcgi) requires an update:
``` diff
- endpoint is the address or Unix socket of the FastCGI server.
+ endpoint is the address or Unix socket of the FastCGI server. Service discovery using SRV lookup is supported. If the endpoint start with `srv://` it will be considered as a service locator and caddy will attempt to resolve available services via SRV DNS lookup.
```
``` diff
- upstream specifies an additional backend to use. Basic load balancing will be performed. This can be specified multiple times.
+ upstream specifies an additional backend to use. Basic load balancing will be performed. This can be …
```

Add support for SRV upstreams in fastcgi

---

onevent/hook/hook.go
onevent/hook/hook_test.go

Take this for example:
on startup /path/to/my/script.sh &
Currently it will run this script as blocking and passing "&" as if it were a parameter because it only checks for "&" if there is *more than one* argument. If the same is written this way, it works:
on startup /path/to/my/script.sh dummy &
Now this is run non-blocking.
The change itself is very minimal. I don't know how to write a test to check this new behavior.

Allow nonblocking onevent command with no other arguments

---

dist/init/linux-upstart/caddy.conf.centos-6

Fixes upstart script so it actually works on Centos 6 and Amazon Linux. The script had comments that Centos6 upstart doesn't support some features, but it still used them.
https://github.com/mholt/caddy/pull/1189
None I can think of.

Fix upstart script for Centos 6 (and Amazon Linux)

---

caddyhttp/staticfiles/fileserver.go

Reverts https://github.com/mholt/caddy/commit/bdb61f4a1d93c412fe08fbd6e4644ec3ac9378da but leaves the test case.
https://github.com/mholt/caddy/issues/1408
https://github.com/mholt/caddy/pull/1409
https://github.com/golang/go/issues/18984
None.

staticfiles: remove mapFSRootOpenErr because Go stdlib has fixed the relevant issue

---

caddytls/maintain.go

If an OCSP response's issuing OCSP responder certificate expires before the OCSP response itself does, consider the OCSP responder's expiration date to be the end of the OCSP response's vality period, so that we obtain a new OCSP response sooner.

Handle the case of an OCSP responder certificate expiring before an OCSP response it issued

---

.travis.yml
appveyor.yml

This change fixes the CI tests
n/a
n/a

CI: Fix CI Tests

---

onevent/hook/hook.go

Changes the log output of on startup from 
> 2017/10/22 10:43:18 [INFO] Nonblocking Command with ID 880159d2-fe8c-4457-982b-0a7154ebbed6: "d:\php7\php-cgi.exe -b 43249"
to 
> 2017/10/22 11:02:32 [INFO] Nonblocking Command "d:\php7\php-cgi.exe -b 43249" with ID 347a7d5c-e281-49df-a6b0-cf27d8d0dfc0
Personally I think this is easier to read when looking for commands that are being executed in the logs.

hook: Change log output

---

onevent/on.go
startupshutdown/startupshutdown.go

Execute onevent commands once per server block
#1933 
n/a

onevent/startupshutdown: run command once per server block

---

caddyhttp/browse/browse.go
caddyhttp/browse/setup.go
caddyhttp/httpserver/plugin.go
caddyhttp/httpserver/server.go
caddyhttp/httpserver/siteconfig.go
caddyhttp/index/index.go
caddyhttp/index/index_test.go
caddyhttp/push/handler.go
caddyhttp/push/handler_test.go
caddyhttp/push/push.go
caddyhttp/push/setup.go
caddyhttp/staticfiles/fileserver.go
caddyhttp/staticfiles/fileserver_test.go

Adds per-site index capability while maintaining the a list of possible index file names
Fixes #1801 
The index plugin docs. Currently it's not clear whether it's per-site or not, which is what the linked issue is about.

Implement per-site index (fixes #1801)

---

caddy.go
sigtrap_posix.go
upgrade.go

caddy.go:569: could be simplified
sigtrap_posix.go:87: value of inst is never used
upgrade.go:151: should omit nil check; len() for nil slices is defined as zero
Simplifies return, removes unused variable and reduces a variable check.
fixes #1935
none

all: few code improvements

---

dist/init/freebsd/caddy

Fixes #1923 by removing unnecessary `-u ${caddy_user}` option for the `daemon` command in the init script for FreeBSD.
#1923 
None

FreeBSD init: Remove unnecessary daemon -u option

---

caddytls/config.go
caddytls/handshake.go
caddytls/setup.go

This adds the ask sub-directive to tls that defines the URL of a backend HTTP service to be queried during the TLS handshake to determine if an on-demand TLS certificate should be acquired for incoming hostnames. When the ask sub-directive is defined, Caddy will query the URL for permission to acquire a cert by making a HTTP GET request to the URL including the requested domain in the query string. If the backend service returns a 2xx response Caddy will acquire a cert. Any other response code (including 3xx redirects) are be considered a rejection and the certificate will not be acquired.
#1847
The TLS docs will need a reference to the `ask` directive and some updated language around on-demand TLS in general.

Add option for a backend check to approve use of on-demand TLS

---

caddyhttp/proxy/proxy.go
caddyhttp/proxy/reverseproxy.go
caddyhttp/proxy/reverseproxy_test.go
caddyhttp/proxy/upstream.go
caddyhttp/proxy/upstream_test.go

Adds support in proxy package to discover upstream using SRV lookup
Closes #https://github.com/mholt/caddy/issues/1803
The proxy module documentation page https://caddyserver.com/docs/proxy required as update:
``` diff
- to is the destination endpoint to proxy to. At least one is required, but multiple may be specified. If a scheme (http/https/quic) is not specified, http is used. Unix sockets may also be used by prefixing "unix:". QUIC connections are experimental, but to try it, just use "quic://" for the scheme.
+ to is the destination endpoint to proxy to. At least one is required, but multiple may be specified. If a scheme (http/https/quic/srv) is not specified, http is used. Unix sockets may also be used by prefixing "unix:". QUIC connections are experimental, but to try it, just …
```

Add SRV support for proxy upstream

---

caddyhttp/httpserver/middleware.go
caddyhttp/httpserver/replacer.go
caddyhttp/httpserver/server.go

This PR sets up a `Replacer` and `ResponseRecorder` object per-request, so that the functions that "create" them preferentially retrieve them from the request itself before creating a new one. This allows directives throughout the middleware chain to leverage shared information collected over the course of the request.
I have tested this locally using a custom plugin that adds custom placeholders, in combination with the `headers` directive, which were previously in conflict, causing the placeholders to not be available in the `log ` directive, and that now works as expected!
Tests here still need to be added.
Follows on from a comment on a previous PR attacking a manifestation of this underlying issue: https://github.com/mholt/caddy/pull/1931#pullrequestreview-71723741
Previous PR: …

Setup a Replacer and ResponseRecorder per-request, making interactions with placeholders more coherent

---

caddyhttp/log/log.go

Make code in line with current documentation for CommonLogFormat for {user} placeholder.
I tested with latest version of the plugin https://github.com/tarent/loginsrv.
It works as noted in the documentation https://caddyserver.com/docs/log under the predefined format `{common} (default)`.
I've not added a new test yet.
#1951
None.

Add {user} placeholder to CommonLogFormat

---

caddyhttp/basicauth/basicauth.go

Following on from #1937 and #1931 this change adds {user} value in basicauth to be used by replacer
- #1937
- #1931
- #1953 
I don't think it requires any but I can add if necessary.

add basicauth {user} to replacer

---

caddy/caddymain/run.go
caddy/caddymain/run_test.go

caddy/run.go:238
the percent value is resolved in a GOMAXPROCS relative number by simple
division, thus rounding down the non-integer quotient. If zero, the call
to runtime.GOMAXPROCS is silently ignored.
We decide here to exceptionally round up the CPU cap in case of percent
values that are too small.
#1962

caddymain: fix setCPU silently ignoring small percent values

---

dist/init/linux-sysvinit/README.md
dist/init/linux-sysvinit/caddy

It allow to overwrite the variables used in the sysvinit script by providing the file caddy in either /etc/default/ (Debian based https://www.debian.org/doc/manuals/debian-reference/ch03.en.html#_the_default_parameter_for_each_init_script ) or in /etc/sysconfig/ (CentOS based https://www.centos.org/docs/5/html/5.2/Deployment_Guide/s1-sysconfig-files.html ).
That way the server administrators can easily increase the ulimit and change installation paths if necessary.
None
Already documented in README

implemented sourcing of default file for sysvinit

---

caddyhttp/proxy/reverseproxy.go

Add `KeepAlive: true` to QuicConfig of `h2quic.RoundTripper`. 
This follows convention of KeepAlive being turned on as a default in the rest of Caddy.
Issue #999
None.
- [ Y] I have written tests and verified that they fail without my change
- [ Y] I have squashed any insignificant commits
- [ Y] This change has comments for package types, values, functions, and non-obvious lines of code
- [ Y] I am willing to help maintain this change if there are issues with it later

Turn on KeepAlive in QuicConfig of RoundTripper

---

caddy/caddymain/run.go

Implements handling for glob values for the -conf flag.
https://github.com/mholt/caddy/issues/1910
https://caddyserver.com/docs/cli should be updated to mention the ability to use globs.
---
95% of the time spent preparing this pull request was figuring out how to fork, branch, then fix my branch, then rebase and start over, then squash two commits into one branch.
This proposed PR feels pretty hacky to me, but it works and I think the only alternative is to copy a whole lot of code out of `doImport` itself.

confLoader: use import to handle globbed values for -conf flag

---

sigtrap_posix.go

The signal is already trapped; make it do the same thing as SIGQUIT to
be more inline with Unix/Linux shutdown expectations.
Fixes #1993
SIGTERM is detailed on various pages/READMEs. I haven't followed up with those yet.

shutdown: allow graceful shutdown for SIGTERM on posix

---

dist/init/linux-systemd/caddy.service

Sets privatedevices in systemd to 'false' as it may not work for some devices.
I didn't create one yet. It was discussed in the forum recently here:
https://caddy.community/t/systemd-fails-to-load-caddy-on-a-raspberry-pi/3170
It is related to: 
https://github.com/mholt/caddy/issues/1853
https://serverfault.com/questions/871635/error-running-otherwise-working-caddy-under-systemd-v232
https://caddy.community/t/error-running-otherwise-working-caddy-under-systemd-v232/2638
More details on this feature here:
https://www.freedesktop.org/software/systemd/man/systemd.exec.html#PrivateDevices=
None.

Systemd - disable privatedevices as it may not work for some devices

---

caddyhttp/fastcgi/fastcgi.go
caddyhttp/fastcgi/fcgiclient.go
caddyhttp/fastcgi/fcgiclient_test.go

According to RFC 7231 and RFC 7230, there's
no reason a GET-Request can't have a body
(other than it possibly not being supported
by existing software). It's use is simply not
defined, and is left to the application.
It passes along any HTTP Body for GET requests to fastcgi endpoints. 
Fixes #1961 
None.

Updated GET requests to send along the body (fcgi)

---

README.md

Updates the minimum version of Go required to build from source. 1.8 fails since #2009 from the introduction of `sync.Map`
#2009
This *is* the doc change.

Update min version to build from source

---

caddytls/config.go
caddytls/setup_test.go

It ups the default minimum TLS version to 1.2 instead 1.2
#2045
[Caddy Documentation](https://caddyserver.com/docs/tls]) section `Protocols`

Change default tls minimum version to 1.2

---

caddytls/certificates.go
caddytls/certificates_test.go
caddytls/crypto.go
caddytls/handshake.go
caddytls/handshake_test.go

Serves a certificate keyed by an empty hostname for any SNI name if
there were no other matches.
This should only happen for sites defined with an empty hostname (like
":8080") and which are using self-signed certificates or some other
funky self-managed certificate. But that certificate should arguably
be used for all incoming SNI names.
Fixes #2035
Probably none
@benjamin-demarteau Please take a look, let me know how this works for you!

tls: Fall back to certificate keyed by empty name (fixes #2035)

---

caddyhttp/httpserver/server.go
caddyhttp/httpserver/server_test.go

Fixes a bug introduced by #2014
I did not origionally test with query string.  I have added tests and fixed code.  The url passed in to trimPathPrefix will never have scheme / host / port 
I may never have a fragement either but I have added test to ensure if it is it willwork.
Please review code and test if possible. 
#2014 
#2038 
NA

 Fix Issue #2038 - Querystring being lost from URI

---

caddyhttp/fastcgi/fastcgi.go
caddyhttp/httpserver/replacer.go
caddytls/config.go
caddytls/setup.go

It implements two new placeholders: ```tls_protocol``` and ```tls_cipher``` which will contain, when using a secure connection, the protocol and cipher respectively.
For fastcgi, it passes these two placeholders in a manner that is compatible with Apache's [mod_ssl](https://httpd.apache.org/docs/2.4/mod/mod_ssl.html), i.e. as environment variables ```SSL_PROTOCOL``` and ```SSL_CIPHER```.
#2055
The documentation for placeholders will need to incorporate details of these two placeholders. Essentially:
```{tls_protocol}``` The protocol used for a secure transport connection (e.g. "tls1.2").
```{tls_cipher}``` The cipher used for a secure transport connection (e.g. "ECDHE-ECDSA-WITH-CHACHA20-POLY1305").

Implement placeholders for tls_protocol and tls_cipher

---

plugins.go
sigtrap_posix.go

- Purge event hooks after USR1 reload
- ~Create a new func to delete event hooks~
#2044
/

caddy: Purge event hooks after USR1 reload

---

caddyhttp/httpserver/replacer.go
caddyhttp/httpserver/replacer_test.go

Makes placeholder braces escapable by backslash character (`\`) for strings fed to a httpserver.Replacer.
It achieves this by using loops to identify the first unescaped opening brace and closing brace, then cleaning up escaped braces as it works its way through the string.
This allows, for example, JSON to be set as a `header` or a `fastcgi` env var and even allows placeholders to continue working inside that JSON.
Fixes https://github.com/mholt/caddy/issues/2063
A quick search determined that the following areas call some form of `replacer.Replace`:
- Env vars in `fastcgi`
- Log formats for `log`
- Upstream and downstream headers in `proxy`
- The location targets of both `redirect` and `rewrite`
- `httpserver.IfMatcher` when evaluating `ifCond.True()`
There may be more I wasn't able to …

httpserver.Replacer: Rework loop to ignore escaped placeholder braces

---

README.md

Removes the reference to caddyserver/website which is no longer valid. Suggests to open an issue on this repo for now.
#1940
N/A

Change README to remove reference to old docs repo

---

caddyhttp/httpserver/plugin.go
caddyhttp/httpserver/server.go
caddyhttp/httpserver/siteconfig.go
caddytls/config.go

- Introduce StrictHostMatching mode for sites that require clientauth
- Error if QUIC is enabled whilst TLS clientauth is configured
(Our QUIC implementation does not yet support TLS clientauth, but
maybe it will in the future - fixes #2095)
- Error if one but not all TLS configs for the same hostname have a
different ClientAuth CA pool
#2095 
TLS client authentication is not permitted to be configured ambiguously; namely, sites defined with the same host but with ClientAuth enabled cannot be reliably protected by the right TLS configuration, since it is ambiguous which ClientAuth config will be used.
/cc @fholzer

httpserver: Prevent TLS client authentication bypass in 3 ways

---

caddyfile/parse.go
caddyfile/parse_test.go

Fix errors caught by fuzzing.
The fix for hanging involves limiting the number of wildcards in an
import pattern to just 1. Otherwise some patterns can expand to the
entire disk.
The other fix requires that the end string for an environment variable
expansion come after the start string.
Fix #2096 
- The `import` directive can have only one wildcard (`*` and `?`), instead of unlimited. And no `[ ]` globbing.
/cc @Mohammed90

Fix errors caught by fuzzing

---

caddyhttp/proxy/proxy_test.go
caddyhttp/proxy/upstream.go
caddyhttp/proxy/upstream_test.go

It fixes #1960 and adds some tests to verify.
#1960
We may need to mention the transparent preset already appends any **X-Forwarded-For** headers

Fixes #1960 Transparent proxy not appending existing X-Forwarded-For header

---

caddyhttp/rewrite/rewrite.go
caddyhttp/rewrite/rewrite_test.go
caddyhttp/rewrite/setup.go
caddyhttp/rewrite/setup_test.go

- Adds regexp support for simple rewrite rule. 
- Also includes an optional `not` syntax to negate the regex. Negating regex can be pain for an average user and Go's regex support makes it even more difficult. I think an optional `not` syntax should not hurt.
Reason:
- The simple rewrite rule is too basic and it is rarely used.
- Many rewrite config blocks are only used for regexp.
- Users that do not need `if` conditions do not need to open to config block, hence a cleaner Caddyfile.
Outcome:
Sample wordpress config can become a one liner.
```
rewrite not ^/wp-admin {path} {path}/ /index.php?{query}
```
No issues reported. Noticed the trend from users' Caddyfiles.
Rewrite:
Indication of regexp support and an additional option `not` field.
```
rewrite [not] from to... 
```

Regular expression support for simple rewrite rule

---

caddyhttp/proxy/reverseproxy.go

Fix a bug introduced in 98de336, #2070
https://github.com/mholt/caddy/commit/98de336a2130aa102e52af4d8150cb3c05101d15#diff-a71769529a289e215ba922059611256bL309
Before 98de336, `proxy` used `http.DefaultTransport` for every request.
After 98de336, `proxy` creates a new `http.Transport` for every request.
Then `caddy` will create a lot of TCP connections and won't reuse them.
I found this because `github.com/transmission/transmission` can only have 1024 file descriptors, And it encounters error `too many files open` frequently when I upgraded `caddy` to 0.10.13.
See 1.
None.

proxy: initialize ReverseProxy.Transport earlier and fix TCP connection leak

---

caddyhttp/fastcgi/fastcgi.go
caddyhttp/fastcgi/fastcgi_test.go

Fixes https://github.com/mholt/caddy/issues/2152
This changes provides REQUEST_SCHEME env variable for fastcgi
https://github.com/mholt/caddy/issues/2152
-

Add REQUEST_SCHEME to fastcgi envs

---

caddyhttp/gzip/requestfilter.go

Completes #2175.
#2175.
This page could possibly list all files that are considered by gzip. It doesn't at the moment:
https://caddyserver.com/docs/gzip

Add .m3u and .m3u8 (HLS playlist files) to gzip

---

plugins.go
sigtrap_posix.go

New event type called *restart* added which is emitted at server restart (at SIGUSR1)
We are using caddy as embedded server and we need to make preparations before restarts
Nothing

instance restart (reload) event

---

dist/init/linux-systemd/README.md

This fixes the permissions on /etc/caddy to match standard linux
permissions for /etc, and makes the Caddyfile read-only for the caddy
user.
n/a
This is a documentation change.

Fix configuration permissions in systemd integration.

---

caddyfile/parse.go
caddyfile/parse_test.go

Two problems are fixed by this code simplification:
1. Snippets defined in one import file are strangely not available in
another.
2. If an imported file had a directive with an argument "import", then
the rest of the tokens on the line would be converted to absolute
filepaths.
An example of 2 would be the following directive in an imported file:
```
server {
basicauth / import secret
}
```
In this case, the password would actually be an absolute path to the
file 'secret' (whether or not it exists) in the directory of the imported
Caddyfile.
The problem was the blind token processing to fix import paths in the
imported tokens without considering the context of the 'import' token.
My first inclination was to just add more context (detect 'import' tokens
at the beginning of lines and check …

Fix two import problems: snippets and import literals.

---

caddyhttp/browse/setup.go

Fixes #2214
Browser defaults vary and this way we prevent mix-ups from setting only some colors.
Thanks for your consideration.
Best, Sebastian

http.browse: Set page background color (fixes #2214)

---

caddyhttp/browse/setup.go

Fixes #2179
Current Caddy code uses a combination of CSS styles that some mainstream browsers (e.g. Firefox) do not support well: `td:first-child { width: 100%; }` together with `td:last-child { padding-right: 5%; }`.
The old approach was three columns with:
- `Name`: 100% width, 5% padding left
- `Size`: minimal width
- `Modified`: minimal width, 5% padding right
Now the new approach is five columns with:
- _Dummy_: 5% width
- `Name`: 80% width
- `Size`: minimal width
- `Modified`: minimal width
- _Dummy_: 5% width
Thanks for your consideration.
Best, Sebastian

Fix http.browse CSS/HTML (fixes #2179)

---

caddyhttp/httpserver/plugin.go

This adds a little [WKD](https://tools.ietf.org/html/draft-koch-openpgp-webkey-service-06) plugin. WKD is a simple PGP public key discovery system.
https://github.com/emersion/caddy-wkd

Register Web Key Directory directive

---

.gitignore

Unignores the `caddyfile/` package, which causes problems on systems with case-insensitive filesystems (such as macOS).
#2237 
None

Don't ignore the caddyfile/ package (#2237)

---

rlimit_posix.go

Minor fix to use backticks for something that should be executed on shell.
n/a
n/a

rlimit_posix.go: Use backticks for shell code

---

caddytls/config.go

The following two cipher suites are removed from the default cipher suites:
```
TLS_RSA_WITH_AES_256_CBC_SHA
TLS_RSA_WITH_AES_128_CBC_SHA
```
These cipher suites do not use ephemeral keys and so do not have forward secrecy.
They are not listed here anymore: https://wiki.mozilla.org/Security/Server_Side_TLS
https://github.com/mholt/caddy/issues/2226
None. The default cipher suites are not listed anywhere as far as I know.

Remove weak cipher suites from the defaults.

---

caddyhttp/httpserver/plugin.go

fix: correct import path for filemanager plugins

---

caddy/caddymain/run.go

This makes it easier to disable metrics for projects that embed package caddymain.

caddy/caddymain: make EnableTelemetry a variable

---

appveyor.yml

This PR is updating teh Go version to the latest stable version for the AppVeyor build.
This is related to PR #2217 where the AppVeyor build fails because of old Go version.
None

Go version bump for Windows builds

---

caddyhttp/proxy/policy.go
caddyhttp/proxy/policy_test.go

This change fixes 502 errors for multiple backends when header policy is used and there is no such header in request
https://github.com/mholt/caddy/issues/2126
-

Fix 502 errors for requests without headers

---

caddyhttp/httpserver/plugin.go

Filebrowser changed their github structure, this just updates the paths in plugins.go
None
- [ X] I have written tests and verified that they fail without my change
- [X ] I have squashed any insignificant commits

Update paths for filebrowser plugins

---

caddyhttp/httpserver/plugin.go

Update `minify` plugin position so it executes before `gzip`.
Ref.: https://github.com/hacdias/caddy-minify/issues/23

fix: update minify position

---

README.md

Adding TLS client cert placeholders #2217 uses features of go
v1.10.  Update README requirements accordingly.
README documentation update
Issue not raised.  Simply ran into problem getting sources per instructions with the version of go mentioned
Just the README file
n/a

Bump required version of golang to 1.10 in README.md

---

caddyhttp/fastcgi/setup.go
caddyhttp/fastcgi/setup_test.go

Add default timeouts for fastCGI
Timeouts still can be disabled if you explicitly set timeout to 0.
https://github.com/mholt/caddy/issues/2113
There should be documentation changes at this link https://caddyserver.com/docs/fastcgi, but i don't know how to update documentation.

Add fastcgi timeouts

---

caddyhttp/proxy/reverseproxy.go

This PR just sets the `DualStack` field in the `defaultDialer` instance in the `reverseproxy.go` file to `true`.
The reason for this change is because for new connections to Caddy response times can take over 1 second with it set to `false`.
This only became a problem since Caddy v0.10.13 when the new custom default dialer was put in place in the `reverseproxy.go` file. Before that the reverse proxy code used the default dialer in the Go standard library which always has `DualStack` set to `true`. So really this change is just bringing the code more into line with how it was behaving before.
When `DualStack` is set to `true` the response times for new connections come down from over 1 second to ~300ms, which relates to the `net.Dialer`'s `FallbackDelay` field. This is always 300ms because …

Set `DualStack` to `true` in the reverse proxy default dialer

---

.travis.yml
appveyor.yml

CI configuration changed: use `golang.org/x/lint/golint` instead of `github.com/golang/lint/golint`
#2319

[CI configurations]: get golint tool from `golang.org/x/lint/golint`

---

caddyfile/parse.go
caddyfile/parse_test.go

Handles variable replacement correctly when the substitution string starts after the an occurrence of its end token. e.g.:
```
template IN ANY {
match "^([a-zA-Z0-9]*\.){1,2}{$CLUSTER_DOMAIN}\.$"
answer "{{ .Name }} 60 IN CNAME loadbalancer.default.svc.{$CLUSTER_DOMAIN}"
upstream
fallthrough
}
```
https://github.com/coredns/coredns/issues/2153
None

fix environment variable substitution after Go template

---

caddytls/user_test.go

Sometimes I got flaky test error like below.
```
$ cd caddytls
$ go test -v . -run 'TestGetEmail'
=== RUN   TestGetEmail
--- FAIL: TestGetEmail (0.03s)
user_test.go:210: Did not get correct email from storage; expected 'test4-3@foo.com' but got 'test3@foo.com'
FAIL
FAIL	github.com/mholt/caddy/caddytls	0.045s
```
To make the cause cleary, I embed debug code to show what happened.
```
$ cd caddytls
$ go test -v . -run 'TestGetEmail'
=== RUN   TestGetEmail
Your sites will be served over HTTPS automatically using Let's Encrypt.
By continuing, you agree to the Let's Encrypt Subscriber Agreement at:
(none - testing)
Please enter your email address to signify agreement and to be notified
in case of issues. You can leave it blank, but we don't recommend it.
Email address: 
(test) 2018-10-12 …
```

Improve flaky test

---

caddyhttp/proxy/proxy.go
caddyhttp/proxy/proxy_test.go
caddyhttp/proxy/reverseproxy.go
caddyhttp/proxy/reverseproxy_test.go
caddyhttp/proxy/upstream.go

A previous PR I made (#2305) just enabled `DualStack` in the default dialer that was being used in reverse proxies to improve initial connection speed, or connection speed after the TLS handshake timeout had already passed.
In the Go standard library's `net` package, the `net.Dialer` uses a fallback delay as part of its implementation of "Happy Eyeballs" when `DualStack` is enabled. This fallback delay is just a measure of how much of a head start the first connection gets before allowing another "racer" to attempt a second connection.
By default when this duration is not set the `fallbackDelay` function in the `net` package defaults to returning `300 * time.Millisecond`.
It would be useful to configure this fallback delay duration from a caddyfile instead of having to edit the source and …

Add a new `fallback_delay` sub-directive to the `proxy` directive

---

caddyhttp/errors/errors.go

To pass `errors` unit test when source code `$GOPATH` is `/home/user/caddy`.
caddy repository is at `/home/user/caddy/src/github.com/mholt/caddy`
This issue happens on Linux and Windows too.

Prevent errors test fail if $GOPATH is something like /home/user/caddy

---

caddyhttp/templates/templates.go
caddyhttp/templates/templates_test.go

In tempates middleware, delete the two headers related to cache.
#1920
None.

templates: delete ETag and Last-Modified headers in ServeHTTP

---

caddyhttp/httpserver/plugin.go

Hello!
Major changes are coming to File Browser (https://github.com/filebrowser/filebrowser/pull/575) and Hugo and Jekyll plugins are being removed. Also, I'm renaming `filemanager` to `filebrowser` to keep up with the actual name of the software.
`hugo`, `jekyll` and `filemanager` were hidden from the Caddy web site already. I'm working on the new `filebrowser` directive.
No, there are many changes and, unfortunately, the user will be required as an intermediate to make a change. If kept the same directive probably most would ignore and start complaining about bugs.
This will force people to look for information. I'll also provide a guide on Caddy Community as soon as the new plugin is released, which will be soon.
---
That's it!
/cc @mholt

feat: remove jekyll, hugo. Replace by filebrowser

---

caddytls/config.go

It sets a fake `tls.Config.GetCertificate` callback in the `tls.Config`. According to the Go standard library, a `tls.Config` must have `Certificates` or `GetCertificate` set, otherwise it will be rejected by `tls.Listen`. quic-go recently implemented the same check, and rejects the `tls.Config` as currently constructed by Caddy.
I think it should be permissible to have a `tls.Config` that only sets the `GetConfigForClient` callback, and I opened https://github.com/golang/go/issues/29139, but it looks like this was postponed to Go 1.13.
#2346, especially https://github.com/mholt/caddy/issues/2346#issuecomment-445248107

set a GetCertificate callback in the tls.Config

---

caddyfile/parse.go
caddyfile/parse_test.go

Adds support for import statements to Caddyfile directives.
#2378 
The [import](https://caddyserver.com/docs/import) docs

add support for directive level imports

---

caddyhttp/proxy/reverseproxy.go

Avoid allocation during string comparison.
None.
None.

caddyhttp: use strings.EqualFold

---

caddyhttp/httpserver/replacer.go
caddyhttp/httpserver/replacer_test.go

Add placeholder server_port
[#2412](https://github.com/mholt/caddy/issues/2412)
https://caddyserver.com/docs/placeholders
Add placeholder "{server_port}" with value "The server port on the request" to request placeholders.

Implement placeholder server_port (#2412)

---

caddyhttp/httpserver/plugin.go

This pull request adds support for the [caddy-extauth plugin](https://github.com/BTBurke/caddy-extauth) that creates a forward/external authentication capability to caddy.  I'm the author of the JWT plugin and have found that many people need/want a more flexible authentication solution where they have full control over authorizing each request.  Instead of adding more complexity to plugins like JWT, forward or external authentication allows someone to create their own authorization service in any language and have it plug in easily to Caddy's auth flow.
This is similar to forward authentication services in [Traefik](https://docs.traefik.io/configuration/entrypoints/#forward-authentication) and [Ambassador](https://www.getambassador.io/reference/services/auth-service/#the-external-authenti …

add BTBurke/caddy-extauth plugin

---

onevent/hook/config.go
onevent/on_test.go

When fixing #2161 by moving the emitEvent call to ensure on startup was called at the right point, a new event was created instance_startup.  After discussion it has been decided we dont need this new event and it was a breaking change so it has been reverted.
- Anyone else who would like to test. 
#2161 
https://github.com/hacdias/caddy-service/issues/21
none

Rollback changes creating an additional instance_startup event in #2161

---

caddyhttp/proxy/reverseproxy.go
caddyhttp/proxy/reverseproxy_test.go
caddyhttp/proxy/upstream.go
caddyhttp/proxy/upstream_test.go

By using option ca_certificates in proxy block it is possible now to select a
CA for which backend certificates should be verified against.
Resolves #1550
Co-authored-by: Danny Navarro <navdgo@gmail.com>
It adds a `ca_certificates` option to proxy, which allows one to use their own PEM with CA certificates to validate a proxy backend against.
https://github.com/mholt/caddy/issues/1550
https://caddyserver.com/docs/proxy would need documentation updated.
A section along the lines of:
```
ca_certificates are a list of CA Certificate file paths to validate the connection to the backend server being proxied to.
ex. ca_certificates foo.pem bar.pem
```
This is a non issue. `SSL_CERT_FILES` and `SSL_CERT_DIR` are only taken into account when a NewCertPool is created through x509.SystemCertPool(). …

Implement own CA certificates of backends

---

caddy/caddymain/run.go
caddy/caddymain/run_test.go

run caddy:
```
$ ./caddy --disabled-metrics "os,,, arch, cpu, caddy_version,"
panic: runtime error: slice bounds out of range
goroutine 1 [running]:
github.com/mholt/caddy/caddy/caddymain.initTelemetry(0x0, 0x0)
/go/src/github.com/mholt/caddy/caddy/caddymain/run.go:407 +0x8d4
github.com/mholt/caddy/caddy/caddymain.Run()
/go/src/github.com/mholt/caddy/caddy/caddymain/run.go:102 +0xb99
main.main()
/go/src/github.com/mholt/caddy/caddy/main.go:27 +0x27
```
This patch fixed above problem.

optimized parse cli's disabledMetrics flag string to initTelemetry

---

caddy.go
caddyhttp/caddyhttp_test.go
caddytls/setup.go
caddytls/tls.go
plugins.go

Should resolve the failure in
https://github.com/coredns/coredns/pull/2541.
This change is breaking to clustering plugin developers (not Caddy
users), but logical, since only the caddytls package uses CertMagic
directly (the httpserver package also uses it, but only because it also
uses the caddytls plugin); and it is early enough that no clustering
plugins really exist yet.
This will also require a change of devportal
so that it looks for a different registration function, which has moved
to the caddytls package.
https://github.com/coredns/coredns/pull/2541
No user-facing changes, but update the wiki about how to write (and register) a clustering plugin. Devportal needs updating too, since the registration function moved.

caddytls: Change clustering to be a plugin to the caddytls package

---

caddytls/config.go
caddytls/setup.go
caddytls/setup_test.go

add TLS 1.3
#2080 
https://caddyserver.com/docs/tls
1. "tls1.3" is a new suppoted protocol if caddy is built by Go 1.12 or newer.
2. TLS 1.3 cipher suites are not configurable.
If caddy should be able to be built by Go 1.11 after the releasing of 1.12, I think this PR can be accepted now.
If not, the new file with build tag "go1.12" is useless and the change can be applied to config.go directly when Go 1.12 is released.

caddytls: add TLS 1.3 support

---

caddytls/selfsigned.go

While reviewing the code i found that "names" is not used and can be removed

caddytls selfsigned: removed useless code

---

caddyhttp/errors/setup.go
caddyhttp/errors/setup_test.go

I found I had written the following  in several places in my caddyfile
````
example.com {
root c:\web
log / c:\logs\mylogfilt.txt
errors /  c:\logs\myerrorlog.txt
}
````
However `error` does not require a path param so the `/` is unneeded
This silently fails and the only place the log is written to is stdout.
This PR raises a parsing error in this case.
I'm not sure how to write tests for this.

Raise parsing error if errors directive has more than one argument.

---

caddyhttp/basicauth/basicauth.go

This is an update to recent PR #2434 .
I realised I can set the user value before calling replace.
An additonal benefit of this change is that the access logs will show the username even when the user is not authenticated. eg.  
>127.0.0.1 - admin [16/Feb/2019:09:38:31 +0000] "GET /admin HTTP/1.1" 401 17
This seems to be how other webservers report authentication failures.

Simplify User Replacement on basicauth authentication failure

---

caddyhttp/proxy/proxy.go
caddyhttp/proxy/proxy_test.go
caddyhttp/proxy/upstream.go
caddyhttp/proxy/upstream_test.go

Adds an extra parameter to header_upstream and header_downstream that allows regex-based replacement of headers. They are in the format `header_upstream [header] [regex] [replacement]`
This allows unwanted values from the server and client (e.g. redirects, cookies) to be modified by Caddy. This therefore allows search (and mobile) to be fixed on [wikipedia.matt.life](https://wikipedia.matt.life), and [wikimirror](https://github.com/CristianCantoro/wikimirror).
#442 - An existing (but not merged) implementation of Location rewriting
#606 - Nginx proxy_redirect feature request
This change may be obsoleted by #1639, the proxy middleware rewrite.
Add the extra parameter to header_upstream and header_downstream, and describe it. Give examples of it being used to change the Location header, …

Regex rewriting of upstream/downstream headers in proxy

---

caddy.go

try to fix #2490: just run `s.Serve` after all `s.Listen` successfully.
caddy works fine after chaning the code.

server work after all listen success

---

caddy/caddymain/run.go

This PR implements #2479.
There are 2 commits in here:
1. Rename the original `env` flag to `envfile`.
2. Add the new `env` flag implementation which prints environment variables.
Let me know if you wish me to add a log message before printing environment variables and which text should it have.
I navigated [the docs](https://godoc.org/github.com/mholt/caddy) looking for places where it was necessary to update the meaning of each flag, but found nothing.
Kind regards

caddy: add a way to print the environment

---

caddy.go

1. `err2` looks strange
2. use `if err:=xxx; err !=nil {}` to instead.

caddy: improve error naming

---

README.md

Update the build instructions to reflect the transition to Go modules. This will not be necessary in Go 1.13, according to https://blog.golang.org/modules2019
#2560 
n/a
@mholt The PR template does not show up :/

readme: Update build instructions

---

README.md

The latest release is tagged as v1.0.0-beta2 instead of 1.0.0-beta2 so the `go get` command in the instructions needs to be adjusted accordingly.

Fix instructions for building Caddy from source

---

caddyhttp/httpserver/plugin.go

This PR adds publish/subscribe middleware to Caddy. The repository is https://github.com/jung-kurt/caddy-pubsub.

Add pubsub plugin

---

README.md

My first time using Go was in regards to building Caddy-- so I hit a bit of a dead-end when knowing what to call the file mentioned in **To build Caddy with plugins (and with version information)**.  As obvious as it is now-- it took me far too long to realize the file could be anything with the extension `.go`.  This small PR might save fellow newcomers a small headache.

Clarify docs about Go file to build Caddy

---

caddyhttp/rewrite/rewrite.go
caddyhttp/rewrite/rewrite_test.go

Enable substitution of numbered regex captures in the `to` part of a simple rewrite rule.
Example:
```Caddyfile
rewrite ^/foo/(bar)$ /{1}
```
This would previously rewrite to `/` while now it rewrites to `/bar`.
https://github.com/mholt/caddy/issues/2586
On https://caddyserver.com/docs/rewrite copy the description of "destinations..." after the second example code block to the description of "to" after the first example code block.

Simple rewrite regex captures

---

caddyhttp/httpserver/plugin.go

I'm finally looking to make my plugin for caddy officially available.
The code currently lives at https://github.com/dhaavi/caddy-authplugger, but will be moved to https://github.com/dhaavi/caddy-permission within the next days.
Like a couple other plugins, this plugin is about authentication, but, additionally also about authorization:
Instead of just relaying authenticating users to another piece of software, it aims to bring fine-grained permission management to otherwise unsupported web applications.
For example, I've been using this code for over a year now to enforce fine-grained permissions on the filebrowser plugin. It plays fairly nice for the basic feature set, I must say. (I have not yet bothered to integrate all features with the permission model)
Technically speaking, it …

Add permission plugin directive

---

caddyhttp/httpserver/plugin.go

Added a plugin directive named 'recaptcha' for the http server type. Source is here: https://github.com/defund/caddy-recaptcha
The plugin adds middleware which looks for certain requests and validates their reCAPTCHA response tokens. Invalid requests are dropped, so I placed the directive underneath the other request filter directives.
Both reCAPTCHA v2 and v3 are supported. Thanks!

Add recaptcha plugin directive

---

modules/caddyhttp/caddyhttp.go
modules/caddyhttp/encode/encode.go
modules/caddyhttp/fileserver/staticfiles.go
modules/caddyhttp/rewrite/rewrite.go
modules/caddyhttp/routes.go
modules/caddyhttp/server.go
modules/caddyhttp/staticresp.go
modules/caddyhttp/staticresp_test.go
modules/caddyhttp/templates/templates.go

Makes v2's handler config linear, as opposed to nested.
Differentiating middleware and responders has one benefit, namely that
it's clear which module provides the response, but even then it's not
a great advantage. Linear handler config makes a little more sense,
giving greater flexibility and simplifying the core a bit, even though
it's slightly awkward that handlers which are responders may not use
the 'next' handler that is passed in at all.
#2662
Update the wiki to show the flattened config structure for handlers.

Flatten HTTP handler config

---

modules/caddyhttp/replacer.go
replacer.go

Improves performance of placeholders in Caddy 2. Placeholders are the equivalent of variables in other web servers (but better). They allow you to refer to dynamic values in static configuration.
I was lazy with the initial implementation because I wanted to get it done quickly.
Note that this optimization affects ALL usage of placeholders, but the tests I performed were using them in a response body.
Using this sample config:
```
{
"apps": {
"http": {
"servers": {
"myserver": {
"listen": [":8080"],
"routes": [
{
"handle": [{
"handler": "rewrite",
"method": "FOO",
"uri": "/test/abc?foo=bar"
},
{
"handler": "static_response",
"body": "Method: {http.request.method} URI: '{http.request.uri}' Path: '{http.request.uri.path}' Query: '{http.request.uri.query}'"
}]
}
]
}
}
}
}
}
```
Here are some …

v2: Performance improvements to Replacer implementation (placeholders)

---

caddyhttp/staticfiles/fileserver.go
caddyhttp/staticfiles/fileserver_test.go

Allow precompressed zstandard file to be served from the file system.

Staticfiles zstd

---

dist/init/freebsd/README.md
dist/init/freebsd/caddy

There is no good way to rotate the logfile created by the previous FreeBSD rc.d script (logging uses redirection to send the output the file and the file is held open by the shell).
This solves the problem by sending caddy's std{out,err} stream to syslog.  
Because the script uses the `daemon` utility to run the `caddy` process, this change simply uses the `daemon` command's builtin syslog functionality.
The old `caddy_logfile` rc.conf variable is replaced by `caddy_syslog_facility` (which defaults to 'local7') and `caddy_syslog_level` (which defaults to 'notice').
By default, these messages will end up in `/var/log/messages`, but all of syslog's power can be used to manage them.  The README.md documents a simple way to send the output to `/var/log/caddy.log`.
None.
This PR adds a …

Use syslog to manage caddy std{out,err} on FreeBSD

---

dist/init/freebsd/README.md

Add  `dist/init/freebsd/README.md` that describes how to configure the system so that `caddy` can be run without root privileges.
Perhaps this could be added to the main Caddy documentation?
Note that #2652 also adds a `dist/init/freebsd/README.md`, but merging them should be straightforward (the order of the sections is un-important).

Document how to run without root priv's on FreeBSD

---

caddyhttp/websocket/sample/Caddyfile
caddyhttp/websocket/sample/index.html
caddyhttp/websocket/setup.go
caddyhttp/websocket/websocket.go
caddyhttp/websocket/websocket_test.go

Websocket enhancement
- `type lines` option: one line one websocket message, '\n' char required in stdin/stdout (Following v0.11 behavior, this is the default if `type` is not specified)
- `type text` option: '\n' is not checked, '\n' chars are in websocket message, handle UTF-8 chars at buffer end)
- `type binary` option
- `bufsize` option: for handling stdout
See `caddyhttp/websocket/sample/index.html`, `caddyhttp/websocket/sample/Caddyfile` for detailed aims of the test cases
Need to update https://caddyserver.com/docs/websocket

Websocket enhancement

---

cmd/commands.go
cmd/proc_posix.go
cmd/proc_windows.go

---
name: Implement taskkill /f to force quit on windows when caddy stop
about: Gracefull shutdown on windows
title: ''
labels: ''
assignees: ''
---
As discussed this is the first iteration of forced shutdown on windows.
The current code wont shutdown caddy on windows.  taskkill /f is required. 
Shutsdown a running instance of caddy by using `taskkill /f` to force shutdown of the process.  Also ensure process is found on windows systems
#2657 
Important to tell windows users that shutdown is not graceful on windows.  Ideally recommend they call stop on admin interface before calling `caddy stop`
I will make a change to

V2: Implement taskkill /f to force quit on windows when caddy stop

---

admin.go
sigtrap.go

Add a stop command to  admin  website.
This gracefully stops all servers and exits the go process.
This enables graceful shutdown on Windows.
Gives the following output on windows 
````
D:\godev\src\github.com\caddyserver\caddy\cmd\caddy>caddy start
2019/07/14 22:50:14 Caddy 2 admin endpoint listening on localhost:2019
Successfully started Caddy
D:\godev\src\github.com\caddyserver\caddy\cmd\caddy>2019/07/14 22:50:20 [INFO][cache:0xc0000a8780] Started certificate maintenance routine
2019/07/14 22:50:24 Shutting down...
2019/07/14 22:50:24 [INFO][cache:0xc0000a8780] Stopped certificate maintenance routine
2019/07/14 22:50:24 Shut down.
````
#2670 
#2657 
Add `stop` command to admin website

V2:Add stop command to admin.  

---

caddy.go
modules/caddyhttp/encode/encode.go
modules/caddyhttp/encode/encode_test.go
modules/caddyhttp/fileserver/browse.go
modules/caddyhttp/fileserver/browse_test.go
modules/caddyhttp/fileserver/staticfiles.go

Allocating a value and returning a reference to it in a single function causes the Go compiler to escape the value to the heap, since it has to outlive the function's lifetime. Optimizing the function calls (as shown in the first commit) can enable mid-stack inlining of the function and avoiding a heap allocation.
https://github.com/caddyserver/caddy/issues/2681
This is an internal change.

Part 1: Optimize using compiler's inliner

---

caddyconfig/httpcaddyfile/addresses.go
caddyconfig/httpcaddyfile/builtins.go
modules/caddyhttp/fileserver/caddyfile.go

The wrong import path slipped in during the last refactor for the Caddyfile adapter. This PR corrects the import path.
None.
None

fix the package import path by adhering to gomod semantic when major version is > 1

---

modules/caddyhttp/caddyhttp.go
modules/caddyhttp/server.go
modules/caddytls/connpolicy.go

---
name: Add support for client TLS authentication Caddy V2
about: Adding support for client TLS authentication for the next Caddy release
title: 'Add support for client TLS authentication :smile:'
labels: 'V2'
assignees: '@alexandrestein'
---
The thing is pretty obvious and it was available in **Caddy 1**.
[An issue](https://github.com/caddyserver/caddy/issues/2680) is open about this.
I'm really new to the project and I don't know if this is the best way to this.
To test this update I used a similar configuration:
```json
{
"apps": {
"http": {
"http_port": 80,
"https_port": 443,
"grace_period": "2s",
"servers": {
"mainServices": {
"listen": [
":443"
],
"tls_connection_policies": [
{
"match": {
"sni": [
"0.dom.com",
"dom.com"
]
},
"client_cas": [ …
```

Add support for client TLS authentication Caddy V2

---

modules/caddyhttp/matchers.go
modules/caddyhttp/reverseproxy/fastcgi/caddyfile.go

When using the `php_fastcgi` directive, should redirect requests from `/foo` to `/foo/` if there is a `/foo/index.php` file.
See #2752 and https://caddy.community/t/v2-redirect-path-to-path-index-php-with-assets/6196?u=matt
Update php_fastcgi docs.

fastcgi: Implement / redirect for index.php with php_fastcgi directive

---

.gitattributes

---
about: go.mod, go.sum always eol=lf
title: 'go.mod, go.sum always eol=lf'
labels: ''
assignees: ''
---
For Windows users, go.mod, go.sum should always use eol=lf

go.mod, go.sum always eol=lf

---

go.mod
go.sum
modules/caddytls/acmemanager.go

Adds the ability to customize trusted root CAs for ACME servers. Makes integrations with things like Smallstep CA a lot easier and more secure.
/cc @mmalone
Closes #2702
Add `trusted_roots_pem_files` to docs.

tls/acme: Ability to customize trusted roots for ACME servers

---

cmd/commandfuncs.go
cmd/commands.go
cmd/main.go

Changed command structure to generate cli guide in formatted way.
Provides usage message and help message for each command.
Copied documents from wiki. Maybe we can make it in more 'automated way'.
But I think It will be too complicated for now.
```
$ caddy (or 'caddy help')
Caddy, The HTTP/2 Web Server with Automatic HTTPS.
Usage: 
caddy <command> [<args>]
Available commands:
adapt-config  Adapts a configuration to Caddy's native JSON config structure
environ       Prints the environment as seen by caddy
list-modules  Prints the modules that are installed
reload        Gives the running Caddy instance a new configuration
run           Starts the Caddy process, blocks indefinitely
start         Starts the Caddy process, blocks until server initiated
stop          Gracefully stops the …
```

cli: Change command structure, add help subcommand (#328)

---

caddyhttp/staticfiles/fileserver.go
caddyhttp/staticfiles/fileserver_test.go

The Handler interface expects a first return value of 0 if headers have already been written. (cf. https://godoc.org/github.com/caddyserver/caddy/caddyhttp/httpserver#Handler)
When using http.Redirect, this is the case as http.Redirect does write headers. When using Caddy with templates, returning http.StatusMovedPermanently could cause a wrong (200) response on a non-slashy request on a directory name. This is probably due to another handler down the chain altering the response, but I didn't debug further.
Returning 0 ensures the redirection will always take place.
This appears to fix https://github.com/caddyserver/caddy/issues/2114 for me -- I have found the issue only after writing the fix, so based on @mholt's comments there I wonder if I have missed something obvious. If so, I'm …

Signal that redirection headers have been written

---

caddyhttp/httpserver/server.go

I played a bit with this issue https://github.com/caddyserver/caddy/issues/2694 and I was able to reproduce it. The logs don't show anything because the function calls in this function do not return errors https://github.com/caddyserver/caddy/blob/master/caddyhttp/httpserver/server.go#L557
After restoring the errors temporarily to debug I could see the error was:  
````set tcp 127.0.0.1:xxxx->127.0.0.1:yyyy : protocol not available````
After digging around a bit I found out that openbsd has not user-settable per-socket keepalive times http://golang.ir/src/net/tcpsockopt_openbsd.go
Adds a runtime check to skip the call to tc.SetKeepAlivePeriod for openbsd
https://github.com/caddyserver/caddy/issues/2694
None
(*Can't figure out which tests that would be in this case*)

no SetKeepAlivePeriod in openbsd

---

dist/init/linux-systemd/caddy.service

In systemd 231
(https://github.com/systemd/systemd/blob/4f10b80786e8baa1399b6de6111d5b3a16bf99ba/NEWS#L3558-L3565),
ReadWriteDirectories was renamed ReadWritePaths.
In https://github.com/caddyserver/caddy/pull/2620/files, @aspeteRakete
renamed the directive in Caddy's example systemd unit.
However, this means that if anyone runs this sytemd unit on a version of
systemd older than 231, Caddy will go into a crash loop that hammers
Let's Encrypt's servers. That's because the ProtectSystem=full directive
prevents writes to all paths that aren't explicitly permitted, and older
systemd doesn't see any paths being permitted.
To maximize compatibility, I re-add the original ReadWriteDirectories
directive. Older systemd will read that; newer systemd will read the
newer directive. Both should …

Re-add ReadWriteDirectories.

---

README.md
admin.go
caddyconfig/configadapters.go
cmd/caddy/main.go
dynamicconfig.go
dynamicconfig_test.go
modules/caddyhttp/httpcache/httpcache.go
modules/caddyhttp/reverseproxy/circuitbreaker.go
modules/caddyhttp/starlarkmw/example/caddy.json
modules/caddyhttp/starlarkmw/internal/lib/module.go
modules/caddyhttp/starlarkmw/starlarkmw.go
modules/caddyhttp/starlarkmw/tools/gen/example.star
modules/caddytls/certselection.go
modules/caddytls/distributedstek/distributedstek.go
modules/caddytls/pemloader.go

This pull request delivers on the proposal in #2786, which is that we permanently make all proprietary code open source.
Everything is here except the embedded scripting language (the Starlark integration), which I need a little more time to migrate.
Since this PR makes some changes to the core of the v2 code base, I want to clarify that the proprietary repo did _not_ maintain a separate version of the v2 core. There was never an "Enterprise version" in the sense of there being a different product; there was only "Enterprise modules" that plugged into the open source core. In the enterprise repo, these features existed only as separate modules which plugged into Caddy 2 just like any other modules do.
Now that they are all open source, I decided that some of these features would be better …

v2: Merge enterprise code into open source v2 branch

---

.gitignore
modules/caddyhttp/replacer.go
modules/caddyhttp/replacer_test.go

Add additional placeholders for RemoteAddr (the IP + port of the client)
- `http.request.remote`, e.g. "70.116.186.215:34231"
- `http.request.remote.host`, e.g. "70.116.186.215"
- `http.request.remote.port`, e.g. "34231"
No issue created as this PR is so small. It's fine to close it if it doesn't fit!
List of placeholders needs to be expanded!

Add RemoteAddr placeholders

---

modules/caddyhttp/reverseproxy/reverseproxy.go

---
title: ''
labels: ''
assignees: ''
---
Add param `MaxIdleConnsPerHost` in HTTPTransport to optimize reverse proxy latency.
I test some values like 32 as well as 16,100,200, 32 is enough indeed . 
But i think the suiteable value may depend on hardware, linux kernel params, qps... it's difficult for me to found out it, we may need more test or make it configable in the future.
[https://github.com/caddyserver/caddy/issues/2805](https://github.com/caddyserver/caddy/issues/2805)

optimization reverse proxy MaxIdleConnsPerHost

---

caddy/caddymain/run.go
sigtrap.go
sigtrap_posix.go

Moves the `certmagic` import out of the core `caddy` package. The only use of certmagic is calling a shutdown hook. The reason behind this change is reducing the import graph for projects that use Caddy's core packages but not certmagic, for example [nextdhcp](https://github.com/nextdhcp/nextdhcp).
Ideally the telemetry import would be eliminated too (perhaps using an interface variable that is populated by an init func in the telemetry package), but I thought I'd start here.

Move certmagic import out of caddy package

---

modules/caddyhttp/caddyhttp.go
modules/caddyhttp/matchers.go
modules/caddyhttp/matchers_test.go

Allow environment placeholders in the `match` part:
```json
"routes": [
{
"match": [
{
"host": ["{env.DOMAIN_NAME}"]
}
]
```
#2802
In the `routes.match` section, the `host` part supports the following placeholders:
- `system.hostname`
- `system.os`
- `system.arch`
In addition, environment placeholders are supported, in the form `env.ENV_NAME`.
This allows to use configurations like this:
```json
"routes": [
{
"match": [{ "host": ["{system.hostname}"] }]
}
]
```
(match the hostname that's assigned to the OS caddy is running on)
```json
"routes": [
{
"match": [{ "host": ["{env.ENVIRONMENT}.example.com"] }]
}
]
```
(given the environment variable `ENVIRONMENT` set to `staging`, this will match the hostname `staging.example.com`)

Replace placeholders in host matcher

---

.golangci.yml
azure-pipelines.yml
caddyconfig/caddyfile/lexer.go
cmd/main.go
modules/caddyhttp/server.go

The enabled preferred linters of `golangci-lint` were inlined as part of the invocation in `azure-pipelines.yml`. This prevents the code editors (e.g. VSCode) from enforcing the project's linting preferences due to the preferences being embedded in `azure-pipelines.yml`. Our linter of choice, `golangci-lint`, supports having a configuration file named `.golangci.yml` at the module root to enforce project-wide standard of linting.
N/A
None.

v2: Lint v2 Linter

---

dist/init/freebsd/caddy

Clear rc_flags in start precmd. If these flags are still present during
start command, they are passed to daemon(8) instead of caddy(8).
Extract all options into $caddy_options environment variable.
Without these changes, passing custom Caddy flags (ie. `-disable-tls-alpn-challenge`) is impossible.

Update FreeBSD Init script to support custom flags

---

azure-pipelines.yml

Downloading the latest Go and extracting the archive is slow on Windows. According to PowerShell/PowerShell#2138 this is due to PowerShell attempting to update the progress. Since this is running on CI, the progress isn't important.
PowerShell/PowerShell#2138
N/A

v2: speed up some of powershell's processes

---

azure-pipelines.yml

- Use the --api-key flag rather than the `auth` command
- Fix an issue with finding LLVM's fuzzer
- Enable fuzzers on non-fork PRs in addition to schedule
N/A
N/A

fuzz-ci: fix & enhance fuzzing process

---

admin.go
caddyconfig/httpcaddyfile/httptype.go
caddyconfig/httpcaddyfile/options.go
cmd/commandfuncs.go

After these changes, the admin endpoint is no longer enabled by default if a configuration file is specified. Instead, the admin listener needs to be configured explicitly.
For the `Caddyfile` this has been simplified with the "admin" option. Without parameters, it will use the (current) default listen address. If a parameter is given, it is treated as listener address.
Example:
```
{
admin
}
```
Example 2:
```
{
admin 0.0.0.0:1234
}
```
Closes #2833
* It needs to be stated that `run` only initializes the admin listener if no config file is given.
* The admin endpoint documentation needs to mention that if a config file is given, the listen address has to be specified for the admin endpoint to be available.
* The `Caddyfile` documentation needs to be enhanced to mention the new `admin …

admin listener as optin for initial config

---

caddy/caddymain/run.go
caddyhttp/errors/errors.go
caddyhttp/httpserver/logger.go
dist/init/linux-systemd/caddy.service

solves #2615
---
title: ''
labels: ''
assignees: ''
---
This change adds a flag to enable/disable timestamps for the process log. It also unifies the timestamp format for the log entries. Until this change there were two different formats:
```
Okt 01 00:37:30 example.com caddy[2548]: 01/Oct/2019:00:37:30 +0200 [ERROR 499 /api/update] context canceled
Okt 01 00:38:33 example.com caddy[2548]: 01/Oct/2019:00:38:33 +0200 [ERROR 499 /api/update] context canceled
Okt 01 00:38:48 example.com caddy[2548]: 2019/10/01 00:38:48 http: TLS handshake error from 109.192.194.xxx:22799: tls: unsupported SSLv2 handshake received
Okt 01 00:38:49 example.com caddy[2548]: 2019/10/01 00:38:49 http: TLS handshake error from 109.192.194.xxx:22837: tls: …
```

Add flag to disable timestamps for process log

---

cmd/main.go
logging.go
modules/logging/filewriter.go

Fixes #2870 
Adds support for placeholders in config file.
#2870 
The config file can have placeholders for any environment variables like `{env.LOG_LEVEL}`.

Add support for placeholders in some logging config

---

admin.go
listeners.go
listeners_fuzz.go
listeners_test.go
modules/caddyhttp/caddyhttp.go
modules/caddyhttp/reverseproxy/healthchecks.go
modules/caddyhttp/reverseproxy/hosts.go
modules/caddyhttp/server.go

Changes the return of `ParseNetworkAddress` to be an instance of new struct type `Listener` (hardest thing in CS is naming). This should be reducing memory consumption because it'll merely reference the port range instead of allocating into a slice all the possible addresses covered by the range.
Closes #2851 
None. I've already updated code comments.

fix OOM issue caught by fuzzing

---

caddyhttp/fastcgi/fastcgi.go

.PHP (or case variant) is served as plain text, so we have a security issue here on Windows.

Fixes security issue on Windows

---

dist/init/linux-systemd/caddy.service

Move the config field in this script to the right part.
i.e.
move `StartLimitIntervalSec` and `StartLimitBurst` from [Service] to [Unit]
ref: https://lists.freedesktop.org/archives/systemd-devel/2017-July/039255.html
systemd version: `systemd 237`
(You can check with `man systemd.directives`, mine is `systemd 237`)
I am not sure if it is valid with old ubuntu and others.
Maybe we can mention it in the document, and keep a new version script?
none
Maybe, need a further discuss.

fix(systemd): update caddy.service on Ubuntu 18

---

caddyconfig/httpcaddyfile/parser_test.go
modules/caddyhttp/matchers.go
modules/caddyhttp/matchers_test.go

---
about: This addresses a bug in the caddy file parser when parsing query matchers
title: ''
labels: ''
assignees: ''
---
As discussed in #2899 
I have had a go at what a set of parser tests could look like. Open to suggestions about getting the state of a particular parsed entity and verifying it contains the parsed data.
#2899
https://github.com/caddyserver/caddy/wiki/v2:-Documentation#matcher
> query <key=val...>
becomes
> query <key=[val...]>  | val can be the value to match or the wildcard '*' to match any value.

v2: fixes query matcher parsing

---

go.mod
go.sum

update quic-go to v0.14.0

---

caddyhttp/proxy/reverseproxy.go
caddyhttp/proxy/upstream.go

---
title: ''
labels: ''
assignees: ''
---
I need to proxy requests to a https backend which requires mTLS. In order to do this transparently to clients i added tls_client as a configuration parameter for proxy.
This parameter can be compared to "insecure_skip_verify" i.e. setting up the transport
Add "tls_client" to proxy documentation
tls_client /certificatefile /keyfile
is the correct documentation
- [x ] I have squashed any insignificant commits
- [ x] This change has comments explaining package types, values, functions, and non-obvious lines of code
- [ x] I am willing to help maintain this change if there are issues with it later

ability to use client certs in reverse proxy

---

go.mod
go.sum

v0.14.1 now actually removes the Ginkgo dependency from the non-test builds (hopefully).

update quic-go to v0.14.1

---

README.md

`caddyserver.com/pricing` is a broken link (looks like pricing for individual products is no longer *A Thing* since a shift to a sponsorship model), so it could be appropriate to replace it with a link to mholt's GitHub Sponsor page instead.
--

Repair broken README link: "become a sponsor"

---

caddyhttp/fastcgi/fastcgi.go

…ed after .php on Windows @mholt  check your email for more info

Trim those characters because they serve PHP as plain text if appended

---

dist/init/freebsd/caddy

`install` use 0755 mode by default.

FreeBSD init: PID file should not be executable

---

azure-pipelines.yml
context.go
listeners.go
logging.go
modules/caddyhttp/reverseproxy/streaming.go
modules/caddyhttp/starlarkmw/internal/lib/module.go
modules/caddyhttp/templates/templates.go
modules/caddytls/connpolicy.go
modules/logging/filewriter.go

This PR addresses:
- Updating `golangci-lint` addresses a false-negative in the `bodyclose` linter.
- Use US spelling of `canceled`
- Simplify some of the code (one of them addresses linter complaint of lack of error check)
Addressing errcheck lints requires more elaborate study of the code to know where it can be ignored. Catching and checking these `(*http.Server).Serve()` and `(*http3.Server).Serve()` requires some restructuring of the code. I imagine using the `Group` type from either `go4.org/syncutil` or `golang.org/x/sync/errgroup` is needed to capture those errors and react properly, but haven't looked deep enough into how the structure should look like and how they'll be employed:
- admin.go
https://github.com/caddyserver/caddy/blob/8c7c2e4af2e4e7ad842b959e2100855f6edadd68/admin.g …

v2: housekeeping: address minor lint complaints

---

modules/caddyhttp/reverseproxy/caddyfile.go
modules/caddyhttp/reverseproxy/httptransport.go

Allows specifying ca certs with by filename in
`reverse_proxy.transport`.
Example
```
:443
root * app
try_files {path}.html {path}
reverse_proxy /api api:443 {
tls
tls_trusted_ca_certs certs/rootCA.pem
}
}
file_server
tls certs/cert.pem certs/key.pem
```
These changes should be backwards compatible by simply opting to add a new way of specifying certs in `modules/reverseproxy/httptransport.go`

v2: Proposal: Support tls_trusted_ca_certs in reverse_proxy.transport

---

modules/caddyhttp/caddyhttp.go
modules/caddyhttp/errors.go
modules/caddyhttp/fileserver/caddyfile.go
modules/caddyhttp/reverseproxy/fastcgi/caddyfile.go
modules/caddyhttp/reverseproxy/fastcgi/fastcgi.go
modules/caddyhttp/reverseproxy/healthchecks.go
modules/caddyhttp/reverseproxy/hosts.go
modules/caddyhttp/reverseproxy/httptransport.go
modules/caddyhttp/reverseproxy/reverseproxy.go
modules/caddyhttp/rewrite/caddyfile.go
modules/caddyhttp/rewrite/rewrite.go
modules/caddyhttp/routes.go
modules/caddyhttp/server.go
modules/caddyhttp/starlarkmw/starlarkmw.go
modules/caddyhttp/subroute.go
modules/caddyhttp/vars.go

Previously, all matchers in a route would be evaluated before any
handlers were executed, and a composite route of the matching routes
would be created. This made rewrites especially tricky, since the only
way to defer later matchers' evaluation was to wrap them in a subroute,
or to invoke a "rehandle" which often caused bugs.
Instead, this new sequential design evaluates each route's matchers then
its handlers in lock-step; matcher-handlers-matcher-handlers...
If the first matching route consists of a rewrite, then the second route
will be evaluated against the rewritten request, rather than the original
one, and so on.
This should do away with any need for rehandling.
I've also taken this opportunity to avoid adding new values to the
request context in the handler chain, as this creates …

v2: Change routes to sequential matcher evaluation

---

caddyconfig/caddyfile/dispenser_test.go
caddyconfig/caddyfile/parse.go
caddyconfig/caddyfile/parse_test.go

Fixes small issue when importing files.
The parse time replacements are not happening.

fix replacing variables on imported files

---

caddyhttp/gzip/gzip.go

If using caddy as a reverse proxy, when the upstream returns HTTP header `Vary: Accept-Encoding`, caddy will add this header again.
```bash
curl localhost:8080/test -v
*   Trying ::1...
* TCP_NODELAY set
* Connected to localhost (::1) port 8080 (#0)
> GET /test HTTP/1.1
> User-Agent: curl/7.64.1
> Accept: */*
> Accept-Encoding: deflate, gzip
>
< HTTP/1.1 200 OK
< Cache-Control: private, no-cache
< Content-Encoding: gzip
< Content-Type: application/json; charset=utf-8
< Date: Wed, 18 Dec 2019 10:52:58 GMT
< Expires: Wed, 17 Sep 1975 21:32:10 GMT
< Vary: Accept-Encoding
< Vary: Accept-Encoding
```

Avoid duplicated Vary header

---

modules/caddyhttp/reverseproxy/circuitbreaker.go
modules/caddyhttp/reverseproxy/reverseproxy.go
modules/caddyhttp/reverseproxy/selectionpolicies.go

Adds docs for circuit breaker config and "random selection" load balancing policy.
The other config I know of that are missing docs is for NTLM transport here:
https://caddyserver.com/docs/json/apps/http/servers/errors/routes/handle/reverse_proxy/transport/http_ntlm/
Most of them are straightforward though.

v2: some documentation & rename of circuit breaker config parameter

---

modules/caddytls/connpolicy.go

The `max` argument for the `protocols` setting of the `tls` directive is optional. If not specified, the created `*tls.Config` has its MaxVersion set to TLS 1.3. That is, given such Caddyfile:
```
example.com {
root * /path/to/root
tls cert.pem cert.key {
protocols tls1.2
}
}
```
Caddy should have TLS config with minimum of tls1.2 and max tls1.3 (which is the default max). Because max is not specified, the `ConnectionPolicy` struct has an empty string as value of `ProtocolMax`. So the comparison `p.ProtocolMin > p.ProtocolMax` results in `true` because string with content is greater than an empty string.
We should check if both knobs have custom values in them before comparing them, and we should check first before actually changing values in `*tls.Config`.
Found via: …

v2: only compare custom TLS protocol relative to each other if both are set

---

modules/caddyhttp/caddyhttp.go

Fixes #3001
See https://github.com/caddyserver/caddy/blob/v2/modules/caddyhttp/replacer.go#L112-L128, this updated the documentation to match the replacers as implemented.

Update orig_uri placeholder docs

---

modules/caddyhttp/matchers_test.go
modules/caddyhttp/vars.go

This PR adds var matcher against regular expressions rather than just static values. It should help a lot with the nginx-adapter, and can serve as wildcard matcher too.

v2: Implement RegExp Var Matcher

---

modules/caddyhttp/fileserver/browsetpl.go

This allows creating links that display only a subset of files in a directory.
Fixes #3025 for Caddy v2.

browse: allow filter init via `filter` query param

---

go.mod

update  lego to v3.3.0 to fix dnspod json error
```
2020/02/09 12:33:46 [INFO] Deactivating auth: https://acme-v02.api.letsencrypt.org/acme/authz-v3/2718866049
2020/02/09 12:33:48 [INFO] [*.test-rooter.proginn.com] acme: Trying renewal with 587 hours remaining
2020/02/09 12:33:48 [INFO] [*.test-rooter.proginn.com] acme: Obtaining bundled SAN certificate
2020/02/09 12:33:49 [INFO] [*.test-rooter.proginn.com] AuthURL: https://acme-v02.api.letsencrypt.org/acme/authz-v3/2718866543
2020/02/09 12:33:49 [INFO] [*.test-rooter.proginn.com] acme: use dns-01 solver
2020/02/09 12:33:49 [INFO] [*.test-rooter.proginn.com] acme: Preparing to solve DNS-01
2020/02/09 12:33:49 [INFO] [*.test-rooter.proginn.com] acme: Cleaning DNS-01 challenge
2020/02/09 12:33:49 [WARN] [*.test-rooter.proginn.com] acme: …
```

update  lego to v3.3.0 to fix dnspod json error

---

modules/caddyhttp/caddyauth/basicauth.go

Came across this small inconsistency between docs and implementation. basicauth docs says algorithm defaults to bcrypt, but implementation will raise an error if no hash is specified.

Don't lie: default basicauth hash to bcrypt

---

modules/caddyhttp/matchers.go
modules/caddyhttp/matchers_test.go

- Fix crash when specifying just `*` to `header` directive. (Fixes #3060)
- Look for `Host` header in `header` and `header_regexp`. (Fixes #3059)
- Make `header_regexp` check for each header values (and not only the first) in a `or` fashion. This makes `header_regexp` behave more like `header` which I think is more consistent.
- Fix parsing of `header_regexp`'s `name` parameter in Caddyfile. (See #3059)
I didn't find any existing test for matchers parsing in Caddyfile, so I didn't write one. Please tell me if I missed something.
I'm not very fluent in Go, so please do point out all my silly mistakes :smirk: .

Multiple fixes for header and header_regexp directives

---

modules/caddyhttp/caddyhttp.go

Currently, when an error chain is defined, the default error handler is bypassed entirely - even if the error chain doesn't handle every error. This may result in pages returning a blank 200 OK page instead of the error status defined by the error.
For instance, it's possible for an error chain to match on the error status code and only handle a certain subtype of errors (like 403s). In this case, we'd want any other errors to still go through the default handler and return an empty page with the status code.
This PR changes the "suffix handler" passed to errorChain.Compile toset the status code of the response to the error status code.
Fixes #3053

Add handler for unhandled errors in errorChain

---

cmd/commandfuncs.go

Fix typo in cmdStart comment

---

modules.go

Make comment more readable about caddy ModuleID's Name() method.

---

caddyhttp/httpserver/plugin.go
caddyhttp/httpserver/server.go
caddyhttp/httpserver/siteconfig.go
caddytls/config.go
caddytls/setup.go

~~This basically disables `StrictHostMatching` for Caddy with single server configurations and TLS Client auth enabled.~~
~~Since its a single server configuration, the concerns about someone being able to bypass the TLS Client Auth by connecting to another server running without TLS Client auth and using the `Host` header is not applicable anymore.~~
This PR adds a new `insecure_disable_sni_matching` subdirective to the `tls` directive and it will disable the default behaviour of caddy denying a TLS client authenticated connection using a mismatched TLS SNI and `Host` request header

Add insecure_disable_sni_matching directive to tls

---

caddyconfig/httpcaddyfile/builtins.go
caddyconfig/httpcaddyfile/httptype.go
go.mod
go.sum
modules/logging/encoders.go
modules/logging/filewriter.go
modules/logging/netwriter.go
replacer.go
replacer_test.go

This change exposes more to the Caddyfile:
- A global option `debug` that enables debug mode, which for right now simply means to set all log levels to DEBUG
- A `log` directive for the HTTP Caddyfile, which enables customizable access logging
Syntax:
```
log {
output <writer_module> ...
format <encoder_module> ...
level  <level>
}
```
I still need to make the various log writer and encoder modules implement `UnmarshalCaddyfile`; for now, though, `FileWriter` at least lets you specify a filename in the Caddyfile:
```
log {
output file /var/log/access.log
}
```
The most basic way to enable an access log is:
```
log
```
And to enable debug mode, use a global option:
```
{
debug
}
```
Still lots of open questions, such as what the default format should be -- these and other details can be …

v2: debug mode, and 'log' directive for Caddyfile

---

caddyconfig/caddyfile/parse.go

Small expansion to the work done in https://github.com/caddyserver/caddy/pull/2963 which simply calls `os.ExpandEnv` so env vars like `{$URL}` where `$URL=$SCHEME://$HOST:$PORT` (contrived) get the expanded $SCHEME, $HOST, and $PORT variables included

v2: expand environment variables within caddy files

---

azure-pipelines.yml

The recent experience in #3047 shows a pain point in the CI flow where logs of build errors aren't easily accessible. This PR attempts to address it. It updates a few other things on the way.

ci: improve CI flow

---

caddyhttp/httpserver/server.go

This PR fixes an issue introduced by #3075 (sorry about that) where SNI matching was being applied globally even if ClientAuth was not being used and causing all websites listening in a TLS port to fail randomly with status `403 Forbidden`
We now enforce SNI Host matching will happen only if ClientAuth is enabled and only if `insecure_disable_sni_matching` is *NOT* set.

Only enforces SNI matching if ClientAuth is enabled

---

azure-pipelines.yml

@francislavoie suggeted we publish the pipeline build artifacts so we get access to per-commit binaries. Here'e the attempt to do just that.

ci: publish build artifacts

---

caddyconfig/caddyfile/formatter.go
caddyconfig/caddyfile/formatter_test.go
cmd/commandfuncs.go
cmd/commands.go

This takes the config file as input and formats it.
Code currently implements a `Formatter` interface
which can be implemented by various adapter to format
a file.
Currently only Caddyfile formatter is implemnented.
Fixes #3020 
I still have to write tests (`TODO`).
An example of formatting (I hope this covers everything):
**Before `caddy format`:**
```
localhost { # starts with a comment
{$SOME_ENV}
encode zstd gzip
templates
file_server browse\this\server
}
:8080, :8081 { respond "I am \"80\""
}
```
**After `caddy format`:**
```
localhost {
{$SOME_ENV}
encode zstd gzip
templates
file_server browse\this\server
}
:8080, :8081 {
respond "I am \"80\""
}
```

cmd: Add `caddy fmt` command.

---

caddyconfig/caddyfile/formatter.go
caddyconfig/caddyfile/formatter_test.go

Previously the formatter did not include support for
blocks inside other blocks. Hence the formatter could
not indent some files properly. This fixes it.
Fixes #3104

fmt: Add support for block nesting.

---

go.mod
go.sum

v0.15.0 shipped with a broken ChaCha header protection. Let's hope nobody deployed it yet.

update quic-go to v0.15.1

---

caddyconfig/httpcaddyfile/builtins.go
caddyconfig/httpcaddyfile/directives.go
caddyconfig/httpcaddyfile/httptype.go

Remove the tag tracking from global state. This better supports reloading configuration via the admin reload function.
@mholt thoughts about the `logCounter` it will mutate the log files unnecessarily I think https://github.com/caddyserver/caddy/pull/3111/files#diff-3235e86b75f6440c822f6d7d8f4beb61R540

remove the certificate tag tracking from global state

---

azure-pipelines.yml

Build the published executables with CGO disabled, stripped, and with `-trimpath` for more reproducible build.
Any thoughts on publishing checksum alongside the executables?

ci: better published executables

---

modules/caddyhttp/reverseproxy/ntlm.go

Initially reported in the forum: https://caddy.community/t/http-ntlm-option-resulting-in-runtime-error/7155/3
Fixes #3119

v2: http_ntlm: fix panic due to unintialized embedded field

---

modules/caddytls/connpolicy.go

---
title: ''
labels: ''
assignees: ''
---
Ability to specify in tls connection policy that a client SSL cert be present.
https://caddy.community/t/v2-client-auth/6581/2
https://github.com/caddyserver/caddy/wiki/v2:-Documentation#httpserverstls_connection_policies need to be updated to include
"require" boolean "requires a client certificate, but will not verify it"
- [x ] I have written tests and verified that they fail without my change
- [ x] I have squashed any insignificant commits
- [ x] This change has comments explaining package types, values, functions, and non-obvious lines of code
- [ x] I am willing to help maintain this change if there are issues with it later

ability to specify that client cert must be present in SSL

---

modules/caddyhttp/autohttps.go

It's still not perfect but I think it should be more correct for
slightly more complex configs. Might still fall apart for complex
configs that use on-demand TLS or at a large scale (workarounds are
to just implement your own redirects, very easy to do anyway).
Should fix #3127 but will need to be more verified first.
/cc @anoadragon453 - please try it soon and let me know!

caddyhttp: New algorithm for auto HTTP->HTTPS redirects

---

replacer.go
replacer_test.go

This fixes the specific issue flagged by the fuzzer.
It does beg the question what the expected output should be for this input, but I went with this:
```plain
{
input:  `{}{}{}{\\\\}\\\\`,
expect: `{\\\}\\\\`,
},
```
My reasoning is that the first three braces are valid, but match no keys so get removed. The second brace is opened by never closed and so it is not replaced. The closing brace is escaped and so we loose the escape character but retain the brace.
I've made an assumption that handling of escaped escape characters is an edge case and one that will need to be handled if requested.
I'll post benchmarks in a comment.

Fix #3130: Crash at fuzzing target replacer

---

caddyconfig/httpcaddyfile/addresses.go
caddyconfig/httpcaddyfile/addresses_test.go
caddyconfig/httpcaddyfile/builtins.go
caddyconfig/httpcaddyfile/httptype.go
go.mod
go.sum
modules/caddyhttp/autohttps.go
modules/caddyhttp/caddyhttp.go
modules/caddyhttp/fileserver/command.go
modules/caddyhttp/reverseproxy/command.go
modules/caddypki/ca.go
modules/caddypki/certificates.go
modules/caddypki/command.go
modules/caddypki/crypto.go
modules/caddypki/maintain.go
modules/caddypki/pki.go
modules/caddytls/acmeissuer.go
modules/caddytls/internalissuer.go
modules/caddytls/tls.go
modules/standard/import.go
replacer.go

This pull request adds support for localhost certificates. It creates a new App module called `pki` and a new Issuer module called `internal`.
In Caddy v1, users would write `tls self_signed` in the Caddyfile (#2502) to have Caddy generate a quick, self-signed certificate for use in local/dev environments. But the cert was only stored in memory, so its key had to continually be re-trusted every time you restarted Caddy. It was a quick and bad implementation.
In Caddy 2, we can do better than that. These days, internal/local certificates can be very useful when done properly, and there is now tooling in Go to make this possible.
This design implements a proper, fully-managed, self-contained PKI (Public Key Infrastructure) system. Caddy generates a root and intermediate certificate, stores …

v2: Implement 'pki' app powered by Smallstep for localhost certificates

---

caddyconfig/caddyfile/formatter.go
caddyconfig/caddyfile/formatter_test.go

This fixes indentation for blocks starting with
a brace as:
```Caddyfile
{
...
}
```
Fixes #3144

fmt: Fix brace opening block indentation.

---

caddyconfig/httpcaddyfile/directives.go
modules/caddyhttp/rewrite/caddyfile.go

This PR unifies the `strip_prefix`, `strip_suffix`, and `uri_replace` directives into a single `uri`directive which does all of those, without any confusion with regards to matchers.
Closes #3140.

Unify strip_prefix, strip_suffix, uri_replace into uri directive

---

go.mod
go.sum
modules/caddyhttp/celmatcher.go
modules/caddyhttp/matchers.go

CEL (Common Expression Language) is a very fast, flexible way to express
complex logic, useful for matching requests when the conditions are not
easy to express with JSON.
CEL Go repo: https://github.com/google/cel-go
Example JSON config:
```json
{
"apps": {
"http": {
"servers": {
"cel": {
"listen": [":2015"],
"routes": [
{
"match": [{
"expression": "{http.request.uri.path}.startsWith('/foo')"
}],
"handle": [{
"handler": "static_response",
"body": "You matched!"
}]
}
]
}
}
}
}
}
```
Example Caddyfile:
```
localhost
@foo {
expression {path}.startsWith('/foo')
}
respond @foo "You matched!"
```
Obviously this PoC is contrived, but you get the idea.
We support all placeholders by expanding them out to a proper CEL function call like `caddyPlaceholder(request, "http.request.uri.path")` before …

caddyhttp: Implement CEL matcher (see #3051)

---

modules/caddyhttp/reverseproxy/reverseproxy.go

Adds `Alt-Svc` to the list of headers that get removed when proxying to a backend.
This fixes the issue of having the contents of the Alt-Svc header duplicated when proxying to another Caddy server.
This was already blacklisted in Caddy v1
https://github.com/caddyserver/caddy/blob/891446d06340db2912c9a970bfe862bd54efbb70/caddyhttp/proxy/reverseproxy.go#L584-L600

reverseproxy: Add Alt-Svc to Hop-by-hop headers list

---

caddyconfig/caddyfile/parse_fuzz.go

The input type the `caddyfile.Parse` func accepts has changed from `io.Reader` to `[]byte`. The amendment of the fuzzer func was missed.
The failure was detected in #3152

v2: fuzz: accommodate the change of function signature

---

.github/workflows/ci.yml

I felt it was weird that I had to make separate jobs per environment, I just didn't find any info on how to do it initially. Did a bit more digging, found this thread which explained it pretty clearly.
https://github.community/t5/GitHub-Actions/Create-matrix-with-multiple-OS-and-env-for-each-one/m-p/38574#M3418
Trying this out. Let's see if it works.

Use matrix includes to set per-os variables, simplify cross-platform

---

.github/workflows/ci.yml

As requested by @mholt https://github.com/caddyserver/caddy/pull/3166#discussion_r396000650
As described in https://stackoverflow.com/a/59819441
Edit:
```
caddy_v2_Linux_38997b3
caddy_v2_macOS_38997b3
caddy_v2_Windows_38997b3
```

ci: Improve build artifact file names

---

modules/caddyhttp/matchers.go
modules/caddyhttp/reverseproxy/caddyfile.go
modules/caddyhttp/reverseproxy/hosts.go
modules/caddyhttp/reverseproxy/httptransport.go
modules/caddyhttp/reverseproxy/reverseproxy.go

This change allows you to specify the `"lookup_srv"` field on a proxy upstream to lookup a name's SRV records to get the upstream dial address. Resolves #3179.
In the Caddyfile, prefix proxy upstream addresses with `srv+`, for example:
```
reverse_proxy srv+example.com
```
or
```
reverse_proxy srv+https://example.com
```
(It's a little weird but that's how it goes I guess.)
@danlsgiga Can you please try this? Once the CI is finished, it should have a binary you can download and use, or you can just pull it yourself and build. Let me know!

reverse_proxy: Add support for SRV backends

---

.github/workflows/ci.yml
caddytest/caddytest.go

So here is an approach to not having the tests run in CI while we get to the bottom of Windows networking stack.

exclude integration tests in ci

---

modules/caddytls/automation.go
modules/caddytls/tls.go

Support the following configuration:
```json
{
"apps": {
"tls": {
"automation": {
"policies": [
{
"key_type": "{env.KEY_TYPE}"
}
]
}
}
}
}
```
Also adds a check to validate key_type is valid (rsa2048, rsa4096, etc.)

Support placeholders in key_type

---

modules/caddyhttp/caddyauth/caddyauth.go

Long overdue PR to allow Authentication modules to add arbitrary data to a User.

caddyauth: Add Metadata field to caddyauth.User

---

modules/caddyhttp/matchers.go
modules/caddyhttp/matchers_test.go
modules/caddyhttp/reverseproxy/fastcgi/caddyfile.go

A "not" matcher now accepts an array of matcher sets, rather than a single matcher set.
Matcher sets are OR'ed (i.e. if any matcher sets return true, this matcher returns false; if all matcher sets return false, this matcher returns true). This is analogous with how matcher sets work in routes.
Matchers within the same set are the same (i.e. they are AND'ed).
In the Caddyfile, if `not` appears multiple times in the same set, each occurrence creates a new matcher set within a single "not" matcher; in other words, multiple `not`s are effectively OR'ed because they create a single matcher (that is AND'ed with the others).
See https://caddy.community/t/v2-matcher-or-in-not/7355/
/cc @princemaple - please try this out and confirm that it works for you! Thanks!

Allow specifying multiple matcher sets in "not" matcher

---

caddyconfig/caddyfile/parse_fuzz.go

Thus far the fuzzers have found a few crashers in the Caddyfile parser. However, the fuzzer have been stuck at import glob expansion after import glob expansion, which aren't reproducible.

ci: fuzz: skip fuzz data that contains `import`

---

.github/workflows/release.yml
.goreleaser.yml

- The magical Github-y syntax was referencing the wrong step ID to get the tag
- Exclude commits prefixed with `ci:` from the changelog

chore: ci: fix release action script

---

.goreleaser.yml

Based on download stats, demand for 32-bit binaries these days is
extremely low. Also unify some of the filename conventions; just a
few bikeshedding changes :)

ci: goreleaser: Drop some platforms and replacements

---

caddytest/caddytest.go
caddytest/integration/caddyfile_adapt_test.go
go.mod
go.sum

Pulled test harness fix and base test cases from #3193 
Incorporated feedback from #3193 
None of the sorting code is needed yet as these tests deal with single hostnames.
Example diffing output, when changing the port number from the expected output.
```
{
"apps": {
"http": {
"servers": {
"srv0": {
"listen": [
- 						":80"
+ 						":81"
],
"routes": [
{
.. (truncation is mine)
```

add adaption tests. fix load failure not failing tests

---

caddyconfig/httpcaddyfile/httptype_test.go
modules/caddyhttp/matchers.go

Simple addition to make it possible to have `not` negate a matcher on the same line instead of requiring it to be contained in a block.
E.g. before:
```
@notStatic {
not {
path /static*
}
}
```
after:
```
@notStatic {
not path /static*
}
```

caddyhttp: Support single-line not matcher shortcut

---

modules/caddyhttp/matchers.go

This fixes some bugs that could occur when matchers were defined with blocks when it didn't make sense:
```
@badMatcher {
path /somepath* {
method POST
}
}
```
This would return a matcher like the following, which doesn't make sense:
```
"match": [
{
"path": [
"/somepath*",
"POST"
]
}
],
```
The above matcher will now instead error out with `Error during parsing: malformed path matcher: blocks are not supported`
The same is true for `host`, `path`, `method`, `query`, `header`, `header_regexp`, `remote_ip` and `path_regexp` matchers, where blocks don't make sense.
Maybe we could generalize this error/message, but I just did the simple fix for now.

caddyhttp: Be more strict about not having blocks on matchers

---

modules/caddyhttp/reverseproxy/selectionpolicies.go

As per https://caddy.community/t/lb-policy-ip-hash-fails/7449
The selection policies were missing their Caddyfile unmarshalers except for `random_choice` which did have it.

caddyhttp: Add missing LB policy Caddyfile unmarshalers

---

caddyconfig/httpcaddyfile/httptype.go
caddyconfig/httpcaddyfile/tlsapp.go

As per https://caddy.community/t/how-do-i-use-rsa-instead-of-ec-certificates/7448/3?u=francislavoie
```
{
key_type rsa4096
}
```

caddytls: Add Caddyfile support for key_type global option

---

.golangci.yml
admin.go
caddyconfig/httpcaddyfile/addresses.go
caddyconfig/httpcaddyfile/httptype.go
caddyconfig/httpcaddyfile/tlsapp.go
caddytest/caddytest.go
logging.go
modules.go
modules/caddyhttp/caddyauth/basicauth.go
modules/caddyhttp/caddyauth/command.go
modules/caddyhttp/fileserver/caddyfile.go
modules/caddyhttp/replacer.go
modules/caddyhttp/responsewriter.go
modules/caddyhttp/routes.go
modules/caddyhttp/templates/frontmatter.go
modules/caddytls/automation.go
modules/caddytls/fileloader.go
modules/caddytls/pemloader.go
modules/caddytls/tls.go

This PR enables 2 additional linters:
- [prealloc](https://github.com/alexkohler/prealloc), which finds slices that can be preallocated and subsequently [leads to better performance and fewer allocations](https://github.com/alexkohler/prealloc#purpose)
- [unconvert](https://github.com/mdempsky/unconvert), which removes unnecessary conversions
I've taken action on all of `unconvert` and most of `prealloc`.  [`maligned`](https://github.com/mdempsky/maligned) reports 4 structs whose size can be reduced:
- 64 B -> 56 B: AdminConfig, AutoHTTPSConfig, responseRecorder
- 152 B -> 144 B: AutomationPolicy

chore: make the linter happier

---

caddyconfig/httpcaddyfile/httptype.go
caddytest/integration/sni_test.go

Fixes #3223 and supercedes #3193.
Thanks for the test @sarge! It passes on my machine. We'll see what CI says.

Fix for TLS conn policy being applied to HTTP-only servers

---

caddyhttp/errors/errors.go
caddyhttp/errors/errors_test.go

At some point I need to support custom error pages for more file types, such as json, text, etc., but the existing code does not meet the requirements.
E.g:
```
localhost:8080 {
log / stderr "{combined}"
cors / {
origin            http://localhost:3000
methods           POST,PUT,GET,DELETE,OPTION
allow_credentials false
max_age           3600
allowed_headers   Authorization,Content-Type
}
errors {
404 examples/gateway/404.json
500 examples/gateway/500.json
}
......
}
```
When the error code is 404,500, even if the custom file is json ContentType is still "text / html; charset = utf-8" is not "application / json"
This pr is to solve this problem, the Content-Type is automatically determined according to the file extension, which is well compatible with the old configuration

Updated custom error page handlers to support more file types

---

modules/caddyhttp/reverseproxy/reverseproxy.go

This sets the X-Forwarded-Proto header to upstreams by default; seems like a good idea for wider compatibility by default; overrideable if necessary.
@brunojcm can you please give this a try? Either build from this branch or download the CI artifacts when it completes.
Closes #3275.

reverseproxy: Set X-Forwarded-Proto

---

.github/workflows/ci.yml

I'm thinking caching GOCACHE might speed up builds in CI... let's see.

ci: Cache the GOCACHE directory to speed up builds and tests

---

modules/caddyhttp/reverseproxy/reverseproxy.go

resubmit the PR of https://github.com/caddyserver/caddy/pull/3290
due to the CLA(I used a fake email address in my git config, sorry for the inconvenience for re-submit)

reverseproxy: always set the req.URL.Host with the upstream

---

modules/caddyhttp/server.go

I was digging around for the `http.auth.user.id` placeholder in the code and noticed that the common_log format was using the wrong placeholder.

caddyhttp: Fix common_log format's user ID placeholder

---

caddytest/caddytest.go
caddytest/integration/caddyfile_test.go
caddytest/integration/sni_test.go
caddytest/integration/testdata/cookie.html

Refactored the caddytests helpers. I am shooting for making the simple cases easy, and the complex ones possible.
I have exposed a low level function
```func AssertResponseCode(t *testing.T, req *http.Request, expectedStatusCode int) *http.Response {```
And have build a some of the higher level functions for some of the common cases. Building wrappers for all of the http verbs seems unnecessary.
@greenpau would you mind having a look and seeing if these are suitable?

refactored caddytest helpers

---

.github/workflows/ci.yml
.github/workflows/release.yml
.goreleaser.yml

Replaces #3280
I need to do this from a branch on this repo to be able to test using secrets, i.e. for gemfury.
~Work in progress.~
~TODO:~
- In postinstall:
- if `caddy` is enabled, restart that one
- if `caddy-api` is enabled, then restart that one
- else enable and start `caddy`
- In preremove:
- if `caddy` is enabled, then stop and disable that one
- if `caddy-api` is enabled, then stop and disable that one
- Turn off the PR trigger
- Remove `--skip-publish` in GoReleaser
- Remove publishing the `.deb` as Github artifacts

ci: Enable GoReleaser .deb support

---

caddyconfig/httpcaddyfile/httptype.go
modules/caddyhttp/server.go

Even though any logs can just be ignored, most users don't seem to like configuring an access log to go to a file only to have it doubly appear in the default log.
This also fixes a few little bugs related to access log controls in the Caddyfile. Users now have the ability for fine-grained customization over which requests to which hosts get access-logged.
Related to:
- #3294
- https://caddy.community/t/v2-logging-format/7642/4?u=matt
- https://caddy.community/t/caddyfile-questions/7651/3?u=matt
- #3310

caddyhttp: General improvements to access logging

---

caddyconfig/caddyfile/lexer.go
caddyconfig/caddyfile/lexer_test.go

Slated to land just after 2.0 release.
Closes #2591

caddyfile: Support backticks as quotes

---

caddyconfig/httpcaddyfile/httptype.go
caddyconfig/httpcaddyfile/httptype_test.go
caddytest/integration/caddyfile_adapt_test.go

I think this is a big win for readability. Almost identical implementation to #3228.
Caddyfile:
```
:80 {
@matcher {
method GET
}
respond @matcher "get"
@matcher2 method POST
respond @matcher2 "post"
@matcher3 not method PUT
respond @matcher3 "not put"
}
```
JSON:
```
{
"apps": {
"http": {
"servers": {
"srv0": {
"listen": [
":80"
],
"routes": [
{
"match": [
{
"method": [
"GET"
]
}
],
"handle": [
{
"body": "get",
"handler": "static_response"
}
]
},
{
"match": [
{
"method": [
"POST"
]
}
],
"handle": [
{
"body": "post",
"handler": "static_response"
}
]
},
{
"match": [
{
"not": [
{
"method": [
"PUT"
]
}
]
}
],
"handle": [
{
"body": "not put",
"handler": "static_response"
}
]
}
]
}
}
}
}
}
```

httpcaddyfile: Support single-line matchers

---

caddyconfig/caddyfile/formatter.go
caddyconfig/caddyfile/formatter_test.go
caddyconfig/caddyfile/lexer.go
caddyconfig/caddyfile/lexer_test.go

See discussion in https://caddy.community/t/example-for-redir/7475
Also updated `caddy fmt` to skip adding a space before `#` when it shouldn't

caddyconfig: Only parse `#` as the start of a comment if preceded by whitespace

---

modules/caddyhttp/fileserver/matcher.go

Previously, matching by trying files other than the actual path of the URI was:
file {
try_files <files...>
}
Now, the same can be done in one line:
file <files...>
As before, an empty file matcher:
file
still matches if the request URI exists as a file in the site root.
Inspired by: https://caddy.community/t/why-caddy-2-is-not-able-to-serve-static-brotli-files/7653/19?u=matt

file_server: Accept files args in one-liner of Caddyfile matcher

---

caddyconfig/httpcaddyfile/httptype.go
modules/caddytls/connpolicy.go

This can lead to nicer, smaller JSON output for Caddyfiles like this:
a {
tls internal
}
b {
tls foo@bar.com
}
i.e. where the tls directive only configures automation policies, and
is merely meant to enable TLS on a server block (if it wasn't implied).
This helps keeps implicit config implicit.
Needs a little more testing to ensure it doesn't break anything
important.
Diff: https://www.diffchecker.com/U9uyyjkT
JSON before:
```json
{
"apps": {
"http": {
"servers": {
"srv0": {
"listen": [
":443"
],
"routes": [
{
"match": [
{
"host": [
"a"
]
}
],
"terminal": true
},
{
"match": [
{
"host": [
"b"
]
}
],
"terminal": true
}
],
"tls_connection_policies": [
{
"match": {
"sni": [
"a"
]
}
},
{
"match": {
"sni": [
"b"
]
}
},
{}
]
}
}
},
"tls": {
"automation": {
"policies": [
{
"subjects": [
"a"
], …
```

httpcaddyfile: Only append TLS conn policy if it's non-empty

---

modules/caddyhttp/reverseproxy/caddyfile.go

See https://caddy.community/t/how-can-i-use-proxy-ssl-name-for-sni-in-caddy-2/7739
Caddyfile:
```
:8000
reverse_proxy https://mydomain.com {
tls_server_name mydomain.com
}
}
```
JSON:
```
{
"apps": {
"http": {
"servers": {
"srv0": {
"listen": [
":8000"
],
"routes": [
{
"handle": [
{
"handler": "reverse_proxy",
"transport": {
"protocol": "http",
"tls": {
"server_name": "mydomain.com"
}
},
"upstreams": [
{
"dial": "mydomain.com:443"
}
]
}
]
}
]
}
}
}
}
}
```

caddyhttp: Add tls_server_name http transport option to Caddyfile

---

.goreleaser.yml

dan@fstn4-p1:~/go/src/github.com/caddyserver/caddy/cmd/caddy$ file ./caddy 
./caddy: ELF 64-bit LSB executable, 64-bit PowerPC or cisco 7500, version 1 (SYSV), dynamically linked, interpreter /lib64/l, for GNU/Linux 3.10.0, BuildID[sha1]=1fc956e7b143268aec43dd6850e6af65562ed412, not stripped
dan@fstn4-p1:~/go/src/github.com/caddyserver/caddy/cmd/caddy$ ./caddy version
(devel)
dan@fstn4-p1:~/go/src/github.com/caddyserver/caddy/cmd/caddy$ ./caddy build-info
path: github.com/caddyserver/caddy/v2/cmd/caddy
main: github.com/caddyserver/caddy/v2 (devel) 
dependencies:
cloud.google.com/go v0.54.0 h1:3ithwDMr7/3vpAMXiH+ZQnYbuIsh+OPhUPMFC9enmn0=
...
Builds and runs seamlessly here (ppc64le, haven't tested s390x).

goreleaser: add s390x and ppc64le builds for linux

---

.github/workflows/ci.yml
.goreleaser.yml

Fixing syntax error introduced in #3325, and adding a `goreleaser check` command so we can avoid these in the future 😉

Fixing goreleaser syntax error

---

modules/caddytls/connpolicy.go

Hi,
I have problem with certificate-based authentication. In my env Caddy can't authorized connection despite  correct certificates and configuration. After some debugging I notice that Caddy check only last certificate in request but client certificate is fist and second is CA cert.
This patch change this behavior - all certs from request are verified.
--------
When client certificate is enabled Caddy check only last certificate from
request. When this cert is not in list of trusted leaf certificates,
connection is rejected. But in some cases client certificate is not
last certificate in list; sometimes is first, before certificates of CA.
This patch add checking all sent certificates - if any match with trusted
certificates connection is accepted.

tls/client auth: verify all certificates in client request

---

.github/workflows/ci.yml
.github/workflows/release.yml

@mholt We'll need two new secrets added:
- `CADDYSERVER_DIST_TOKEN`
- `CADDYSERVER_DOCKER_TOKEN`
Both of these should be personal access tokens for their respective repos with the `repo` permissions scope.
Once those are added, I can try to trigger these by putting it in `ci.yml` temporarily. We'll need to add a CI config to one of the other repos to accept the triggers to test that it works as expected.
See https://github.com/peter-evans/repository-dispatch for docs.
We'll likely also use https://github.com/peter-evans/create-pull-request on the sister repos to do the work.
/cc @hairyhenderson @Mohammed90

ci: Add release tagged event triggers to sister repos

---

modules/logging/filewriter.go

* For `roll_size` and `roll_keep_for` directives, round up instead of down.
For example, if a user wants to be able to look back on 36 hours of logs,
but you must round to a 24-hour multiple, then it's better to round up to
48 hours (which includes the desired 36 hours) instead of down to 24 hours.
* `roll_size` had an off-by-one error that caused the size to be as much as
1 MB larger than requested. For example, requests of `1MB` and `1.1MB`
both became 2 MB. Now `1MB` means 1 MB, and `1.1MB` is rounded up to 2 MB.

logging: fix/improve rounding logic for log rolling directives

---

README.md

Table of Contents says "Get Started"; Section Header says "Quick Start". Changed table of contents to align with section header.

docs: Fix TOC/section header mismatch

---

caddytest/caddytest.go

This has confused a couple of people. Closes #3383

caddytest: Dumps current config in test failures, if config was loaded

---

modules/caddyhttp/caddyauth/command.go

http: Add support in hash-password for reading from terminals/stdin (#3365)

---

caddytest/integration/caddyfile_adapt_test.go
modules/caddyhttp/matchers.go

Found while discussing here: https://caddy.community/t/multiple-named-matchers-for-basicauth/8025
Consider the following Caddyfile:
```
:80
@test {
not {
header Abc "123"
header Bcd "123"
}
}
respond @test 403
```
And the following adapted JSON:
```
{
"apps": {
"http": {
"servers": {
"srv0": {
"listen": [
":80"
],
"routes": [
{
"match": [
{
"not": [
{
"header": {
"Bcd": [
"123"
]
}
}
]
}
],
"handle": [
{
"handler": "static_response",
"status_code": 403
}
]
}
]
}
}
}
}
}
```
Notice that only the 2nd header matcher is found within the `not` matcher in the JSON. This is incorrect.
The `not` matcher UnmarshalCaddyfile was just setting the matchers in its internal map by name, which means they would override eachother and only the last one would be kept.
This PR essentially just copies the …

caddyhttp: Fix merging of matchers within a not block

---

caddyconfig/httpcaddyfile/directives.go
caddyconfig/httpcaddyfile/httptype.go
caddyconfig/httpcaddyfile/options.go
caddytest/integration/caddyfile_adapt_test.go

This is a refactor to make global options be registerable like Caddyfile directives.
It makes it possible for plugins/modules to add their own global options if their configuration doesn't make sense to be inside a server block.
The only functional change here should be the error messages.

httpcaddyfile: Make global options pluggable

---

caddy.go
caddy_test.go
caddyconfig/httpcaddyfile/options.go
caddytest/integration/caddyfile_adapt_test.go
cmd/main.go
modules/caddyhttp/reverseproxy/caddyfile.go
modules/logging/filewriter.go

This has come up a few times, most recently https://twitter.com/_francislavoie/status/1255374426612383745
Adds support for a `d` suffix for number of days (i.e. 24 hours) in duration strings wherever Caddy parses them.
Caddyfile:
```
:80
log {
output file /var/log/access.log {
roll_size 1gb
roll_keep 5
roll_keep_for 90d
}
}
```
JSON:
```json
{
"logging": {
"logs": {
"default": {
"exclude": [
"http.log.access.log0"
]
},
"log0": {
"writer": {
"filename": "/var/log/access.log",
"output": "file",
"roll_keep": 5,
"roll_keep_days": 90,
"roll_size_mb": 954
},
"include": [
"http.log.access.log0"
]
}
}
},
"apps": {
"http": {
"servers": {
"srv0": {
"listen": [
":80"
],
"logs": {
"default_logger_name": "log0"
}
}
}
}
}
}
```

caddy: Add support for `d` duration unit

---

caddyconfig/httpcaddyfile/httptype.go
caddytest/integration/caddyfile_adapt_test.go

Adds the following new placeholder shorthands to the Caddyfile (plus one non-`*` placeholder):
```
{port}      ->  {http.request.port}
{query.*}   ->  {http.request.uri.query.*}
{labels.*}  ->  {http.request.host.labels.*}
{header.*}  ->  {http.request.header.*}
{path.*}    ->  {http.request.uri.path.*}
{re.*.*}    ->  {http.regexp.*.*}
```
These are quite commonly used placeholders. Because they're relatively long, it's hard to remember the exact syntax on the fly, requiring frequent referencing of the docs to verify.
~Currently I implemented this via just a quick prefix replacement, it's unlikely users would use these string patterns on their own. Probably the most concerning would be `{r.` because it's such a short sequence.~
~I chose the very short `{r.*.*}` as the syntax for the …

httpcaddyfile: Add shorthands for parameterized placeholders

---

modules/caddyhttp/reverseproxy/command.go

caddyhttp: reverse-proxy command add --insecure flag

caddyhttp: reverse-proxy command add --insecure flag

---

modules/caddyhttp/reverseproxy/reverseproxy.go

I confirmed that this fixes #3382. Thanks for the report @MexHigh - please try this out. There are build artifacts available in the Actions / CI.

reverseproxy: Apply response header ops before copying it (fix #3382)

---

caddyconfig/httpcaddyfile/builtins.go
caddyconfig/httpcaddyfile/builtins_test.go

See #3418 
Adds an error if any arguments are specified for `log` instead of silently ignoring.

httpcaddyfile: Be stricter about `log` syntax

---

modules/caddyhttp/caddyauth/caddyfile.go

Closes #3252
Old syntax:
```
basicauth [<matcher>] [<hash_algorithm>]
```
New syntax:
```
basicauth [<matcher>] [<hash_algorithm> [<realm>]]
```
Caddyfile example:
```
:80
basicauth /protected* bcrypt restricted {
Bob JDJhJDEwJEVCNmdaNEg2Ti5iejRMYkF3MFZhZ3VtV3E1SzBWZEZ5Q3VWc0tzOEJwZE9TaFlZdEVkZDhX
}
```
Adapted JSON:
```
{
"apps": {
"http": {
"servers": {
"srv0": {
"listen": [
":80"
],
"routes": [
{
"match": [
{
"path": [
"/protected*"
]
}
],
"handle": [
{
"handler": "authentication",
"providers": {
"http_basic": {
"accounts": [
{
"password": "JDJhJDEwJEVCNmdaNEg2Ti5iejRMYkF3MFZhZ3VtV3E1SzBWZEZ5Q3VWc0tzOEJwZE9TaFlZdEVkZDhX",
"username": "Bob"
}
],
"hash": {
"algorithm": "bcrypt"
},
"realm": "restricted"
}
}
}
]
}
]
}
}
}
}
}
```

caddyauth: Add realm support to basicauth Caddyfile directive

---

modules/caddyhttp/templates/frontmatter.go
modules/caddyhttp/templates/tplcontext_test.go

Had an issue with templates and SplitFrontMatter that did not work when on Windows.
Created an test case and found that the issue was in the way fronmatter was detected.
Due to the extra control characters in Windows newline it did not match correctly.
Fixed by removing the extra "\r" 
Fix for https://github.com/caddyserver/caddy/issues/3386
And to some degree cloud also add value to #3191

windows newline issue withSplitFrontMatter, fix for #3386

---

caddyconfig/httpcaddyfile/httptype.go
caddyconfig/httpcaddyfile/options.go
caddytest/integration/caddyfile_adapt/auto_https_disable_redirects.txt
caddytest/integration/caddyfile_adapt/auto_https_off.txt

Fixes #3219 
Adds a new global option to the Caddyfile to configure Automatic HTTPS:
```
{
auto_https [off|disable_redirects]
}
```
---
Disabling redirects from Caddyfile:
```
{
auto_https disable_redirects
}
localhost
```
JSON:
```
{
"apps": {
"http": {
"servers": {
"srv0": {
"listen": [
":443"
],
"routes": [
{
"match": [
{
"host": [
"localhost"
]
}
],
"terminal": true
}
],
"automatic_https": {
"disable_redirects": true
}
}
}
}
}
}
```
---
Disabling Auto HTTPS completely from Caddyfile:
```
{
auto_https off
}
localhost
```
JSON:
```
{
"apps": {
"http": {
"servers": {
"srv0": {
"listen": [
":443"
],
"routes": [
{
"match": [
{
"host": [
"localhost"
]
}
],
"terminal": true
}
],
"tls_connection_policies": [
{}
],
"automatic_https": {
"disable": true
}
}
}
}
}
}
```

httpcaddyfile: Add `auto_https` global option

---

caddyconfig/httpcaddyfile/httptype.go
caddyconfig/httpcaddyfile/httptype_test.go

We don't support defining matchers outside of site blocks. Some users try it, but get confusing error messaging because it still gets read as a site address. Instead, we can improve the error message in those cases because a site address starting with `@` isn't valid anyways.
Consider this Caddyfile:
```
@foo {
path /bar/*
}
localhost {
respond "hello"
}
```
Before:
```
$ ./caddy adapt --config Caddyfile
adapt: Caddyfile:2: unrecognized directive: path
```
After:
```
$ ./caddy adapt --config Caddyfile
adapt: cannot define a matcher outside of a site block: '@foo'
```

httpcaddyfile: Improve error on matcher declared outside site block

---

cmd/commandfuncs.go
cmd/main.go
modules/caddyhttp/caddyauth/command.go
modules/caddyhttp/fileserver/command.go
modules/caddyhttp/reverseproxy/command.go

If you run `caddy hash-password` then hit `^C` to interrupt, the terminal would get stuck in a broken state. Not good.
This fixes that by storing the state before starting to read passwords (which modifies the terminal state) and restores it if `SIGINT` is caught.
This also has the side-effect of avoiding the default cleanup handling from Caddy which prints out some log lines that aren't helpful in this situation, e.g.:
```
2020/05/15 14:52:47.348	INFO	shutting down	{"signal": "SIGINT"}
2020/05/15 14:52:47.349	ERROR	stopping admin endpoint	{"signal": "SIGINT", "error": "no admin server"}
2020/05/15 14:52:47.349	INFO	shutdown done	{"signal": "SIGINT"}
```
And also, I changed the prompts to be printed to STDERR instead of STDOUT, so now you can do `caddy hash-password > hashed.txt` and it …

caddyauth: Fix hash-password broken terminal state on SIGINT

---

.goreleaser.yml

There's no need to create a whole new directory and copy `main.go` into it. It's already there, so just re-purpose it. Also, let's package bash-completions now that we have them.

chore: simplify goreleaser flow, add bash completions to .deb

---

modules/caddyhttp/celmatcher.go

Nothing but a tiny change. `NewIdent` is now deprecated.

chore: forego the use of deprecated cel func NewIdent in favor of NewVar

---

modules/caddyhttp/reverseproxy/healthchecks.go

Fixes #3450 - tested http+https

reverseproxy: Fix HTTPS detection for active health checks #3450

---

caddyconfig/caddyfile/dispenser.go
caddyconfig/caddyfile/dispenser_test.go

See discussion in #3402, we've had a couple suggestions to move this out of the `_test` file to make it usable for plugin authors in their own tests.

caddyfile: Make NewTestDispenser accessible for plugin authors

---

modules/caddyhttp/reverseproxy/caddyfile.go

See the discussion here: https://caddy.community/t/proxy-upstream-placeholders/8085
So as it turns out, if you try to use a placeholder as a proxy address, it works fine, unless you also specify a scheme (i.e. the address containing `://`), which uses a different code path.
For example with this Caddyfile:
```
:8080
reverse_proxy http://{host}:8081
```
The error message when adapting looks like this:
> `adapt: parsing caddyfile tokens for 'reverse_proxy': Caddyfile:2 - Error during parsing: parsing upstream URL: parse "http://{http.request.host}:8081": invalid character "{" in host name`
This doesn't really explain why it doesn't work. This PR adds a condition ahead of the call to `url.Parse` (which triggers that error) which gives a more useful message:
> `adapt: parsing caddyfile tokens …

reverseproxy: Improve error message when using scheme+placeholder

---

modules/caddyhttp/fileserver/command.go

This closes #3452.
Using `--access-log` as-in:
```bash
./caddy file-server --access-log
```
Will enable the default access log and caddy will start showing the http access log in the console:
```json
2020/05/26 20:44:49.126	INFO	http.log.access	handled request	{"request": {"method": "GET", "uri": "/", "proto": "HTTP/1.1", "remote_addr": "[::1]:38556", "host": "localhost:8000", "headers": {"Accept": ["text/html,application/xhtml+xml,application/xml;q=0.9,image/webp,image/apng,*/*;q=0.8,application/signed-exchange;v=b3;q=0.9"], "Sec-Fetch-Mode": ["navigate"], "Sec-Fetch-Dest": ["document"], "Accept-Encoding": ["gzip, deflate, br"], "Accept-Language": ["en-US,en;q=0.9,pt-PT;q=0.8,pt;q=0.7"], "Connection": ["keep-alive"], "Upgrade-Insecure-Requests": ["1"], "User-Agent": ["Mozilla/5.0 (X11; …
```

file-server: add flag to enable the access log

---

modules/logging/netwriter.go

Simply reconnect after failed writes.
See https://caddy.community/t/v2-log-output-net-does-not-reconnect-after-lost-connection/8386?u=matt

logging: Net writer redials if write fails

---

cmd/commandfuncs.go

This is to make it easier to use unix sockets with the admin endpoint in combination with the command line interface.
Update: finished and ready. Man, HTTP requests over unix sockets are a pain in Go.

cmd: Support unix socket admin endpoints

---

caddyconfig/httpcaddyfile/httptype.go

This changes grants modules the ability to customize the listener wrapppers by introducing a new server block pile called listener_wrappers.
For example directives can now return `ConfigValue`s like so:
```go
package custom
type CustomModule struct {}
func init() {
caddy.RegisterModule(CustomModule{})
httpcaddyfile.RegisterDirective("custom_listener", parseCaddyfile)
}
var (
_ caddy.Module          = (*CustomModule)(nil)
_ caddy.ListenerWrapper = (*CustomModule)(nil)
)
func (c *CustomModule) WrapListener(listener net.Listener) net.Listener {
// omitted to keep the example short but you probably want to wrap this
// incoming listener with your own customised one
return listener
}
func parseCaddyfile(h httpcaddyfile.Helper) ([]httpcaddyfile.ConfigValue, error) {
var mod CustomModule
// …
```

httpcaddyfile: allow modules to customize listener wrappers

---

modules/caddyhttp/caddyauth/basicauth.go
modules/caddyhttp/caddyauth/caddyfile.go

Cache capacity is currently hard-coded at 1000 with random eviction.
It is not enabled by default, but the Caddyfile _will_ enable it by default because I assume this is the most common preference.
I used this Caddyfile to test, but you can use anything, really:
```
:5555
basicauth {
test JDJhJDEwJEdSbzFmZWcxOGZXc3k2Tm5vdE9OamVZWTFGTmQ2SUE2aGJaWDZIWFVGczVRMVpoUi56RjNL
}
respond "Yahaha! You found me!"
```
Please give it a try @mikelococo ! Thank you for the report.
Fixes #3462

caddyauth: Cache basicauth results

---

.github/workflows/release.yml

I'm not certain if the condition will work, but the semver parsing is verified to work, it's copy-pasted from the caddy-docker repo when I was testing the event trigger.
Worst-case though, if it still publishes, we can remove the release from the Gemfury interface after it's pushed.

ci: Disable publishing .deb on beta tags

---

modules/caddyhttp/reverseproxy/fastcgi/fastcgi.go

In commit f2ce81c, support for multiple path splitters was added. The
type of SplitPath changed from string to []string, and splitPos was
changed to loop through all values in SplitPath.
Before that commit, if SplitPath was empty, strings.Index returned 0 and
PATH_INFO was set correctly in buildEnv.
Currently, however, splitPos returns -1 for empty values of SplitPath,
behaving as if a split position could not be found at all. PATH_INFO is
then never set in buildEnv and remains empty.
Restore the old behaviour by explicitly checking whether SplitPath is
empty and returning 0 in splitPos.
Closes #3490

fastcgi: Make sure splitPos handles empty SplitPath correctly

---

.github/workflows/ci.yml

I tried to make it as simple as possible and as minimal as possible. The flow is:
- Read the current short-sha of git HEAD
- rsync the repo to the remote server into a directory whose name is the short-sha
- Store the exit code
- Delete the remote directory
- Exit with the exit code of the test run

ci: add CI on s390x

---

.github/workflows/ci.yml

Forks don't have access to secrets, which are needed to access the ssh key.

ci: skip s390x tests on forks

---

modules/caddyhttp/templates/frontmatter.go
modules/caddyhttp/templates/tplcontext_test.go

Fixes #3497
Small refactor to the template frontmatter extraction code: 
- Now generalizes a frontmatter type into a struct which defines the fence delimiters and the parse function.
- Now loops over the supported types list instead of using a switch to detect the frontmatter type.
- Each type can now have more than one fence closing string, each are searched for in order they appear (currently only yaml supports more than one).

templates: Add support for dots to close yaml frontmatter

---

modules/caddyhttp/reverseproxy/command.go

Currently:
```
% caddy reverse-proxy --broken
flag provided but not defined: -broken
Usage of file-server:
...
```
Should be:
```
% caddy reverse-proxy --broken                    
flag provided but not defined: -broken
Usage of reverse-proxy:
```

chore: Fix typo in reverse-proxy subcommand help message

---

caddytest/integration/caddyfile_adapt/php_fastcgi_matcher.txt
modules/caddyhttp/reverseproxy/fastcgi/caddyfile.go

Fixes #3511
The order of operations for parsing `php_fastcgi` was wrong when I did the refactor to allow for subdirectives.
When we call `h.NewFromNextSegment()`, it will consume the matcher token (because it does `d.NextSegment()` which calls `d.NextArg()`). We need to grab the matcher token earlier before it gets dropped.

fastcgi: Fix php_fastcgi matcher regression

---

.github/workflows/release.yml

https://help.github.com/en/actions/reference/context-and-expression-syntax-for-github-actions#literals
https://github.com/caddyserver/caddy/actions/runs/147953515

ci: Apparently only single-quote strings are supported

---

modules/caddyhttp/server.go

First try an exact lookup like before, but if it fails, strip the port
and try again. example.com:1234 should still use a logger keyed for
example.com if there is no key example.com:1234.
Fix #3488

caddyhttp: Better host matching for logger names

---

.github/workflows/release_published.yml

Didn't trigger correctly, the tag was empty: https://github.com/caddyserver/caddy/runs/812332740?check_suite_focus=true
Looks like event payloads need to be prefixed with `github.event` to get the actual payload contents. Didn't dig deep enough.
https://help.github.com/en/actions/reference/context-and-expression-syntax-for-github-actions#github-context

ci: Fix release publish trigger

---

caddyconfig/httpcaddyfile/directives.go
caddytest/integration/map_test.go
modules/caddyhttp/map/caddyfile.go
modules/caddyhttp/map/map.go
modules/caddyhttp/standard/imports.go
replacer.go

Simple map implementation. #2824 
Open to suggestions around hybrid implementations or other data types.
Maps are resolved during request pipeline at the point in the pipeline, I did consider deferring evaluation to the point of substitution.
[edit]
A recurring idea I have for this feature is to make it more caddy-like, somehow taking the idea of matchers. It does make it more verbose specifying a matcher for each case.
```
map [dest_var] {
[matcher] [value]
...
}
map $is_an_image {
path /img/* true
path /images/* true
path_regexp *.[jpg|bmp] true
default false
}
```

caddyhttp: Add `map` handler

---

modules/caddyhttp/matchers.go
modules/caddyhttp/matchers_test.go

Adds the ability to use placeholders in query matchers (both key and value) as described/requested in #3520

feat: add support for placeholders in query matcher keys & values

---

modules/caddyhttp/fileserver/browse.go
modules/caddyhttp/fileserver/browselisting.go
modules/caddyhttp/fileserver/browsetpl.go

A simple update to the **browse** functionality within the **file-server** 
- Added an optional **from** URL parameter complementary to the existing **limit** parameter.
Use case -> To efficiently browse folders with many... many... files
caddy file-server --listen 8000 --browse
http://localhost:8000/browse
Shows all files
http://localhost:8000/browse?limit=10
Shows only files 10 files starting from 0
http://localhost:8000/browse?limit=10&from=5
Shows only files 10 files starting from 5

[file-server] Add "from" parameter to browse complementary to "limit"

---

modules/caddyhttp/reverseproxy/fastcgi/fastcgi.go

Closes #3568
Closes #3569 
See https://tools.ietf.org/html/rfc3875#section-4.1.13 for SCRIPT_NAME requiring leading slash
See https://tools.ietf.org/html/rfc3875#section-4.1.15 for SERVER_PORT requiring omission if empty

fastcgi: Comply with RFC3875, ensure a leading slash on index rewrite

---

modules/caddyhttp/reverseproxy/fastcgi/caddyfile.go
modules/caddyhttp/reverseproxy/fastcgi/fastcgi.go

This PR will enable resolving real path on symlinked releases.
When using a symlink based directory schema PHP, through Caddy, will serve old symlinked directory instead of resolving the actual real path of new released code: due to the nature of PHP opcache the new release path is not read by PHP because it’s cached and symlink path doesn’t change form PHP prospective.
Adding the new `resolverootsymlink` subdirective on php_fastcgi will enable resolution of real path, thus permitting Caddy to server the actual codebase instead of the old one.
See [this forum post](https://caddy.community/t/resolve-real-path-on-symlinked-releases/8963) to further details.
Example Caddyfile:
```
http://example.test {
root * /var/www/deploy/current
php_fastcgi 127.0.0.1:9000 {
resolverootsymlink
}
}
``` …

fastcgi: Implement resolve symlinks feature

---

caddyconfig/httpcaddyfile/directives.go
modules/caddyhttp/headers/headers.go
modules/caddyhttp/push/caddyfile.go
modules/caddyhttp/push/handler.go
modules/caddyhttp/push/link.go
modules/caddyhttp/push/link_test.go
modules/caddyhttp/standard/imports.go

Implement HTTP/2 server push. Borrowed much of the code from v1, but the standard lib does most of the hard work. All I had to do was expose the config surface.
Push is a new handler in the standard HTTP chain. Caddy 1 supported server push but it wasn't a very common feature so it wasn't a dev priority for the initial release of v2. Well, here it is now.
Supports the Caddyfile, too:
```
push
push /index.html /style.css
push /index.html {
/resource1.css
/resource2.jpg
}
push /example.html {
GET /foo.css
HEAD /bar.jpg
headers {
Authorization {header.Authorization}
}
}
```
For now, see the code comments for more info about syntax and capabilities.
We copy some essential headers such as Accept and Cache-Control by default, but that's all (for now). We want to be conservative until server …

push: Implement HTTP/2 server push

---

caddyconfig/caddyfile/lexer.go
caddyconfig/caddyfile/lexer_test.go
caddyconfig/caddyfile/parse.go

As requested by @lucaslorentz in this comment https://github.com/lucaslorentz/caddy-docker-proxy/pull/160/files#r449789804
This exposes a `Tokenize` function which was only in the lexer test previously to do the work of lexing bytes as input to get the list of tokens.
One quirk that I'm not sure how best to handle is the `filename` param. In other languages I'd make that an optional param, but Go doesn't have that, so I'm just using `""` as the empty value to keep `File` nil.

caddyfile: Expose Tokenize function for modules to use the lexer

---

caddytest/integration/caddyfile_adapt/reverse_proxy_h2c.txt
modules/caddyhttp/reverseproxy/caddyfile.go

I have successfully established h2c connection between caddy and my local service with the commits in https://github.com/caddyserver/caddy/pull/3561. 
But the json config in https://github.com/caddyserver/caddy/issues/3556#issuecomment-655274156 cannot be simply ported to caddyfile because of the absence of `compression` field in `reverse_proxy -> transport http` config. This PR is just a minor modification to make this field available to caddyfile's http transport config.
Config example:
```
versions h2c 2
compression off
}
```

httpcaddyfile: Support `compression` in http transport config

---

admin.go
caddy.go
modules/caddyhttp/reverseproxy/selectionpolicies.go
modules/caddyhttp/templates/tplcontext_test.go

- Added additional checks to make sure the code will not panic.
- Removed redundant parentheses
- Log the error whenever an unexpected error occurs when running the admin server (improved feedback for end user)

Small improvements to avoid possible panics and inform users about the actual error

---

modules/caddyhttp/fileserver/matcher_test.go

I think I updated the wrong test case before. I don't have Linux handy so it's going to be trial-and-error until we can figure this out.
This is a new test case. If I recall correctly, we had problems with `.PHP` (non-lowercased path splits) that led to unfavorable handling of those requests in the past.

fileserver: First attempt to fix failing test on Linux

---

caddyconfig/httpcaddyfile/httptype.go
caddyconfig/httpcaddyfile/httptype_test.go
caddyconfig/httpcaddyfile/options.go
caddytest/integration/caddyfile_adapt/global_options_admin.txt

Currently, `admin` field in caddyfile's global option could only affects two fields in `caddy.AdminConfig`: `Disabled` and `Listen`. This PR makes modification of `EnsureOrigin` and `Origins` field available to caddyfile config.

httpcaddyfile: Bring `enforce_origin` and `origins` to admin config

---

caddytest/integration/stream_test.go
modules/caddyhttp/reverseproxy/reverseproxy.go
modules/caddyhttp/reverseproxy/streaming.go

Sorry for breaking the encode handle.  This PR fixes #3606 . Add an integration test.

reverse_proxy: fix bi-h2stream breaking gzip encode handle(#3606).

---

caddyconfig/httpcaddyfile/builtins.go
caddyconfig/httpcaddyfile/directives.go
caddytest/integration/caddyfile_adapt/php_fastcgi_expanded_form.txt

While updating https://github.com/caddyserver/website/pull/71 I figured I'd take a look at what it would take to fix `route` to allow named matchers within it, turned out to be pretty simple.
There's was plenty of duplicate code in the logic of `parseRoute` compared to `parseSegmentAsSubroute`, but we didn't want the logic from `buildSubroute` for `route` because it does things we don't need.
It was pretty simple to extract out everything except the call to `buildSubroute` into an internal function so that `route` and `handle` can share almost entirely the same code paths.
(I recommend reviewing with "hide whitespace changes" turned on, makes the diff clearer)

httpcaddyfile: Refactor to allow named matchers in `route` blocks

---

.github/workflows/ci.yml

As of early August 2020 the VM has been down for several days due to
lack of power due related to bad weather at the data center... sigh.

ci: Ignore s390x failures

---

modules/caddyhttp/marshalers.go

If present, adds the subject CommonName and cert serial number of the client leaf certificate.
Also fix typo in an existing field name.

caddyhttp: Add TLS client cert info to logs

---

caddyconfig/httpcaddyfile/builtins.go
caddyconfig/httpcaddyfile/options.go
caddyconfig/httpcaddyfile/tlsapp.go
caddytest/integration/caddyfile_adapt/global_options.txt
caddytest/integration/caddyfile_adapt/global_options_admin.txt
go.mod
go.sum
modules/caddyhttp/autohttps.go
modules/caddytls/acmeissuer.go
modules/caddytls/internalissuer.go
modules/caddytls/tls.go
modules/caddytls/zerosslissuer.go

Configuring issuers explicitly in a Caddyfile is not easily compatible
with existing ACME-specific parameters such as email or acme_ca which
infer the kind of issuer it creates (this is complicated now because
the ZeroSSL issuer wraps the ACME issuer)... oh well, we can revisit
that later if we need to.
New Caddyfile global option:
{
cert_issuer <name> ...
}
Or, alternatively, as a tls subdirective:
tls {
issuer <name> ...
}
For example, to use ZeroSSL with an API key:
{
cert_issuser zerossl API_KEY
}
For now, that still uses ZeroSSL's ACME endpoint; it fetches EAB
credentials for you. You can also provide the EAB credentials directly
just like any other ACME endpoint:
{
cert_issuer acme {
eab KEY_ID MAC_KEY
}
}
All these examples use the new global option (or tls subdirective). You
can …

caddytls: Add support for ZeroSSL; add Caddyfile support for issuers

---

modules/caddyhttp/reverseproxy/selectionpolicies.go

Super simple fix to allow `lb_policy header Host` to work.
See https://caddy.community/t/v2-lb-policy-testing/9441

reverseproxy: Add support for `Host` header selection policy

---

caddytest/integration/caddyfile_adapt/reverse_proxy_h2c.txt
modules/caddyhttp/reverseproxy/caddyfile.go

https://caddy.community/t/adding-buffer-requests-to-caddyfile-for-reverse-proxy/9675/2

reverseproxy: Add `buffer_requests` option to `reverse_proxy` directive

---

modules/caddyhttp/app.go

Well this was way simpler than I expected... went way down the rabbithole in the wrong direction then realized all we needed was this one liner.
See https://pkg.go.dev/go.uber.org/zap?tab=doc#NewStdLog
Right now, this will log all errors from `http.Server` as INFO level, but we can easily change that by using `NewStdLogAt` instead to specify the level. Not sure what level you think we should use. Warn? Error?
This is how it looks before:
```
...
2020/08/20 04:10:27.647 INFO    serving initial configuration
2020/08/20 00:10:33 http: TLS handshake error from [::1]:65239: EOF
2020/08/20 04:11:32.551 INFO    shutting down   {"signal": "SIGINT"}
...
```
And after this change:
```
...
2020/08/20 04:32:52.059 INFO    serving initial configuration
2020/08/20 04:32:55.226 INFO    http    http: TLS …
```

caddyhttp: Wrap http.Server logging with zap

---

modules/caddytls/acmeissuer.go

The `dns` option was missing, so this would fail with an error:
```
tls {
dns cloudflare XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
issuer acme {
dir https://acme-staging-v02.api.letsencrypt.org/directory
resolvers 1.0.0.1
}
}
```
```
Error during parsing: when defining an issuer, all its config must be in its block, rather than from separate tls subdirectives
```
The fix is to add `dns` to acmeissuer as well, so this is possible:
```
tls {
issuer acme {
dir https://acme-staging-v02.api.letsencrypt.org/directory
dns cloudflare XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
resolvers 1.0.0.1
}
}
```

caddytls: Add `dns` config to acmeissuer

---

caddytest/integration/caddyfile_adapt/log_filters.txt
modules/logging/filterencoder.go
modules/logging/filters.go

Closes #3694
~~This is essentially done but lacks tests and proper support for the `ip_mask` filter.~~
Caddyfile:
```
:80
log {
output stdout
format filter {
wrap console
fields {
request>headers>Authorization delete
request>headers>Server delete
request>remote_addr ip_mask {
ipv4 24
ipv6 32
}
}
}
}
```
Adapted JSON:
```json
{
"logging": {
"logs": {
"default": {
"exclude": [
"http.log.access.log0"
]
},
"log0": {
"writer": {
"output": "stdout"
},
"encoder": {
"fields": {
"request\u003eheaders\u003eAuthorization": {
"filter": "delete"
},
"request\u003eheaders\u003eServer": {
"filter": "delete"
},
"request\u003eremote_addr": {
"filter": "ip_mask",
"ipv4_cidr": 24,
"ipv6_cidr": 32
}
},
"format": "filter",
"wrap": {
"format": "console"
}
},
"include": [
"http.log.access.log0"
]
}
}
},
"apps": …
```

logging: Implement Caddyfile support for filter encoder

---

modules/caddyhttp/reverseproxy/reverseproxy.go

Currently the Provision-er of the reverse proxy handler accepts upstream network address with range size more than 1. This means the following Caddyfile is accepted and validates successfully:
```
localhost
reverse_proxy localhost:2000-2020
```
This is despite the comment on the `Dial` field of the `Upstream` struct saying only a single socket is accepted:
https://github.com/caddyserver/caddy/blob/e2f913bb7f813ac2f79cd3644066eff3815accd4/modules/caddyhttp/reverseproxy/hosts.go#L68-L78
The code doesn't validate that until request time, when the method `fillDialInfo` is called:
https://github.com/caddyserver/caddy/blob/e2f913bb7f813ac2f79cd3644066eff3815accd4/modules/caddyhttp/reverseproxy/hosts.go#L161-L164
This PR adds validation of the port range size of an upstream address to the …

reverseproxy: return validation error if upstream address has port range size of more than 1

---

caddyconfig/httpcaddyfile/httptype.go
caddytest/integration/caddyfile_adapt/handle_path_sorting.txt

Fixes an issue found in #3675
I don't love this fix frankly, any hard-coded logic is 😬 but I'm not sure of a better way to do this. We want `handle` and `handle_path` to have different `dirFunc` logic, but we need them to sort equivalently because they are both just handles, where one is just a shortcut to the other.
Having done this, I think we could probably remove `handle_path` from the directive order since it'll never actually be seen by the sort function.

httpcaddyfile: Ensure handle_path is sorted as equal to handle

---

caddytest/integration/autohttps_test.go
modules/caddyhttp/app.go
modules/caddyhttp/metrics.go
modules/caddyhttp/metrics_test.go
modules/caddyhttp/routes.go
modules/caddyhttp/server.go

This fixes a bug that I introduced in #3709, that @mholt patched in c82c231ba7ec7c400e4d48ab943f57a6b29a2a2a.
The behaviour was that with this `Caddyfile`:
```
localhost
respond "Hello, world!"
```
This happened:
```console
$ curl -v http://localhost
*   Trying ::1...
* TCP_NODELAY set
* Connected to localhost (::1) port 80 (#0)
> GET / HTTP/1.1
> Host: localhost
> User-Agent: curl/7.64.1
> Accept: */*
> 
* Empty reply from server
* Connection #0 to host localhost left intact
curl: (52) Empty reply from server
* Closing connection 0
```
Effectively, the headers were sent, but then the connection was closed. Based on the metrics now exposed, I discovered that in the `metricsInstrumentedHandler.ServeHTTP` function, the call to `h.mh.ServeHTTP` was not returning at all, since neither the …

metrics: Fixing panic while observing with bad exemplars

---

modules/caddyhttp/metrics.go
modules/caddyhttp/metrics_test.go

Fixes #3734 
I hadn't accounted for the `emptyHandler`!

metrics: Fix panic when headers aren't written

---

caddyconfig/httpcaddyfile/directives.go

Brought up here: https://caddy.community/t/v2-how-do-i-selectively-rewrite-multiple-times/9854
Basically, this disallows extra args on the line after the matcher for `route`, `handle`, `handle_errors` and `handle_path`. For example, these are now errors:
```
route @foo bar {
respond "Foo"
}
```
```
handle bar {
respond "Foo"
}
```
This is purely an adapter change to be stricter so that users don't have args in their config that do nothing useful (like thinking some args act like a matcher).

caddyconfig: Error on extra args for route and handle directive family

---

caddyconfig/httpcaddyfile/directives.go
caddytest/integration/caddyfile_adapt/matchers_in_route.txt

Fixes https://github.com/caddyserver/caddy/issues/3745
Basically I was doing `range segments` then modifying `segments` so we had a couple of bugs going on. Panic if a matcher segment was ever the last thing in a route, and bad parsing (skipped segments) in other situations.
Fixed by using a regular step loop and rewinding one step every time we splice a segment out.

httpcaddyfile: Fix panic when parsing route with matchers

---

admin.go
metrics.go
modules/caddyhttp/metrics.go

This is for consistency. The admin request counter always [sanitizes](https://github.com/prometheus/client_golang/blob/master/prometheus/promhttp/instrument_server.go#L292) the `method` label by lower-casing it, but the admin error counter and all of the HTTP metrics used the HTTP metric as-is.
This will not do:
```console
$ curl https://localhost/
$ curl -Xget https://localhost/
$ curl -s http://localhost:2019/metrics | grep ^caddy_http_request_duration_seconds_count | grep 'handler="file_server"'
caddy_http_request_duration_seconds_count{code="200",handler="file_server",method="GET",server="srv0"} 1
caddy_http_request_duration_seconds_count{code="200",handler="file_server",method="get",server="srv0"} 1
```
🤦‍♂️
This PR normalizes the method name. In `promhttp.InstrumentHandlerCounter`, …

metrics: Always track method label in uppercase

---

caddytest/integration/caddyfile_adapt/matcher_syntax.txt
modules/caddyhttp/matchers.go
modules/caddyhttp/vars.go

I noticed those were missing from the [Request Matcher docs of the Caddyfile](https://caddyserver.com/docs/caddyfile/matchers#path-regexp). I dug into the code and found they don't implement the necessary interface. Now they do.

caddyfile: Add support for `vars` and `vars_regexp` matchers

---

admin.go

When monitoring Caddy with Prometheus pointed at the default endpoint (http://localhost:2019/metrics), things can get a little verbose:
```
2020/09/24 00:17:00.484 INFO    admin.api       received request        {"method": "GET", "host": "localhost:2019", "uri": "/metrics", "remote_addr": "127.0.0.1:52404", "headers": {"Accept":["application/openmetrics-text; version=0.0.1,text/plain;version=0.0.4;q=0.5,*/*;q=0.1"],"Accept-Encoding":["gzip"],"User-Agent":["Prometheus/2.21.0"],"X-Prometheus-Scrape-Timeout-Seconds":["10.000000"]}}
2020/09/24 00:17:15.485 INFO    admin.api       received request        {"method": "GET", "host": "localhost:2019", "uri": "/metrics", "remote_addr": "127.0.0.1:52404", "headers": {"Accept":["application/openmetrics-text; …
```

admin: lower log level to Debug for /metrics requests

---

modules/caddyhttp/reverseproxy/streaming.go

Without this change, a Content-Type header like "text/event-stream;charset=utf-8"
would not trigger the immediate flushing.
Fixes #3765

reverseproxy: ignore RFC 1521 parameters in mime type when checking the Content-Type header

---

caddytest/integration/caddyfile_adapt/portless_upstream.txt
caddytest/integration/reverseproxy_test.go
modules/caddyhttp/reverseproxy/caddyfile.go

reverseproxy: default to port 80 for port-less upstream dial addresses

---

modules/caddyhttp/reverseproxy/reverseproxy.go

This should be checked with fix-srv-3753 branch due to #3753 bug.

reverseproxy: Change 500 error to 502 for lookup_srv config (#3763)

---

caddytest/integration/reverseproxy_test.go
modules/caddyhttp/reverseproxy/reverseproxy.go

This is the naive fix. I still need to test it some more and figure whether this fix is the best.
@waiyip-aquabyte and @danlsgiga, is it possible to test using the CI artifacts? You can find them [here](https://github.com/caddyserver/caddy/actions/runs/273408022).
Fixes #3753

reverseproxy: fix breakage in handling SRV lookup introduced by d55d50b

---

caddytest/integration/reverseproxy_test.go
modules/caddyhttp/reverseproxy/healthchecks.go
modules/caddyhttp/reverseproxy/hosts.go
modules/caddyhttp/reverseproxy/httptransport.go
modules/caddyhttp/reverseproxy/reverseproxy.go

Supersedes #3776
Partially reverts or updates #3756, #3693, and #3695
Please take a look @Mohammed90 @francislavoie and users we know to have been affected previously: @waiyip-aquabyte,  @danlsgiga, @markuswustenberg, and @yflau. Build artifacts are available in the CI / actions area.
My understanding is that fixing #3753 introduced regressions fixed by #3693 and #3695, which broke dynamic upstreams (using placeholders in dial addresses) as reported in #3768. Instead of piling more code on top to patch the regressions, this change causes the recently-added integration tests to pass without adding more complexity. I think the key is to just not parse the network address at provision-time, which we can't reliably do because we don't know whether it is a usable address (because it supports …

reverseproxy: Fix dial placeholders, SRV, active health checks

---

caddyconfig/httpcaddyfile/tlsapp.go
caddyconfig/httpcaddyfile/tlsapp_test.go
caddytest/integration/caddyfile_adapt/tls_automation_policies.txt

This should fix a frustrating edge case where wildcard subjects are
used, which potentially get shadowed by more specific versions of
themselves; see the new tests for an example. This change is motivated
by an actual customer requirement.
Although all the tests pass, this logic is incredibly complex and
nuanced, and I'm worried it is not correct. But it took me about 4 days
to get this far on a solution. I did my best.
This is actually a better solution to https://github.com/caddyserver/caddy/commit/b6686a54d8b21bedbf042caa4a6c09d78d345fc7 I think.

httpcaddyfile: Revise automation policy generation

---

modules/caddyhttp/reverseproxy/caddyfile.go

This removes the hard coded port 80 when the `reverse_proxy` upstream is using a placeholder.
Here is an example Caddyfile to reproduces the issue:
```
my.domain.com {
encode zstd gzip
some_module_that_sets_the_http_var
respond /test 200 { # works as expected
body {http.vars.some_custom_var}
close
}
tls internal
reverse_proxy / {
to {http.vars.some_custom_var}
}
file_server
}
```
More detailed explanations are documented in this conversation: https://caddy.community/t/dynamically-set-reverse-proxy-upstreams-from-custom-module/10142/15

check if the upstream is a placeholder

---

caddytest/integration/caddyfile_adapt/reverse_proxy_options.txt
modules/caddyhttp/reverseproxy/caddyfile.go
modules/caddyhttp/reverseproxy/httptransport.go

- Makes `max_conns_per_host` configurable in Caddyfile
- Adds new `max_idle_conns_per_host` option which is passed through to `http.Transport`, plus Caddyfile support
- Fix godoc for `buffer_requests` (was in the wrong place) and add other missing options from http transport
This stuff came up after I read https://caddy.community/t/caddy-container-500-mb-ram-within-10h-1-gb-at-some-point/10070/13 which made me dig into this
I'll make a website PR as well after merged (unless you want me to do it asap?)

reverseproxy: Make conns per host configurable, fix godocs

---

caddytest/integration/caddyfile_adapt/matcher_syntax.txt
modules/caddyhttp/matchers.go

Adds support for adding multiple headers values to match to the same field, from the Caddyfile.
This was something that was already possible in JSON, but in the Caddyfile, it was only keeping the last defined field-value pair, and not merging it into the list.
Example:
```
@matcher7 {
header Foo bar
header Foo foobar
header Bar foo
}
respond @matcher7 "header matcher merging values of the same field"
```
Now gives this JSON matcher (would only have `"Foo": ["foobar"]` before):
```json
"header": {
"Bar": [
"foo"
],
"Foo": [
"bar",
"foobar"
]
}
```

caddyhttp: Add Caddyfile support for merging header matchers

---

caddytest/integration/caddyfile_adapt/sort_directives_with_any_matcher_first.txt
modules/caddyhttp/fileserver/caddyfile.go
modules/caddyhttp/fileserver/matcher.go
modules/caddyhttp/fileserver/staticfiles.go
modules/caddyhttp/fileserver/staticfiles_test.go

Improvements to file hiding logic, but mostly to documentation to make it clear that hide paths are _file system paths_, NOT request paths, and that any relative paths are relative to the current working directory, NOT the site root (because site roots can be dynamic).
Hopefully these tests pass on Windows :man_shrugging:

fileserver: Improve and clarify file hiding logic

---

caddytest/integration/caddyfile_adapt/reverse_proxy_options.txt
modules/caddyhttp/reverseproxy/caddyfile.go

Inspired by https://github.com/caddyserver/caddy/issues/3841#issuecomment-720269139

reverseproxy: Wire up a few missing http transport options in Caddyfile

---

modules/logging/filters.go

Addresses: #3820 
Related: https://caddy.community/t/use-ip-mask-in-caddyfile-v2/10173/11
IPv4 filter was not working correctly because `to16()` does always return a `true` value if it's an valid ip address. Independently if it's v4 or v6.
On the otherhand `to4()` does return nil when it's not an v4. So in this case it would correctly identify an IPv6 address and use the proper mask.
Logging before:
```
{
"msg": "handled request",
"request": {
"remote_addr": "[::]:61671",
},
}
```
Logging after
```
{
"msg": "handled request",
"request": {
"remote_addr": "127.0.0.0:63058",
},
}
```

Fixes logging filter for ip_mask with ipv4 adresses

---

caddytest/integration/caddyfile_adapt/matcher_syntax.txt
modules/caddyhttp/matchers.go

I noticed this while revising the matcher docs, `query` wasn't adapting as advertised. It was only letting you have one value per key, and if you specified more tokens, it would fail because `d.Args(&query)` would end up hitting every 2nd token because it's in a `d.Next()` loop. Switches to `Add` from `Set` which will append the value (even if it's empty) instead of overwriting every time.
Also, turns out that `Add` on headers will work even if there's nothing there yet (because it's initialized already as an empty array), so we can remove the condition I introduced in #3832 (effectively we just switched from `Set` to `Add`)

caddyhttp: Merge query matchers in Caddyfile

---

modules/caddyhttp/caddyauth/basicauth.go

contains 3 small improvements
* roll two `if` statements into one, since `err` is guaranteed be `nil` in the second case
* unlock cache mutex after reading from the map, as this happens by-value and reduces code complexity with double unlocks
* switch cache `sync.Mutex` to `sync.RWMutex` for better concurrency on cache fast track

basicauth: Nitpicks and small improvements

---

modules/caddyhttp/reverseproxy/selectionpolicies.go
modules/caddyhttp/reverseproxy/selectionpolicies_test.go

reverse_proxy: Fix random_choose lb_policy

---

go.mod
go.sum

see https://github.com/golang/go/issues/42534

reverseproxy: fix random hangs on http/2-requests with Server Pushes

---

modules/caddyhttp/reverseproxy/streaming.go

https://caddy.community/t/caddy-reverse-proxy-to-another-domain/9589/6
Looks like we forgot to set up logging here. I'm not sure if using the sugared logger is ideal, but it's the easiest way to get this working as similarly to the stdlib implementation I think.

reverseproxy: Logging for streaming and upgrades

---

caddytest/integration/caddyfile_adapt/reverse_proxy_h2c_shorthand.txt
modules/caddyhttp/reverseproxy/caddyfile.go

reverseproxy: Add Caddyfile scheme shorthand for h2c

---

caddyconfig/caddyfile/parse.go
caddyconfig/caddyfile/parse_test.go

Closes #2313
This adds support for an optional default in Caddyfile environment variable placeholders with a `:` separator. This is specifically for the ones like `{$FOO}`, not the ones like `{env.FOO}` which are replaced at runtime.
For example:
```
{$DOMAIN:localhost} {
respond "Hello world!"
}
```
If the `DOMAIN` environment variable exists, the site label will be set to the value of that environment variable, but if not set, will be set to `localhost`.
FYI @mholt I also noticed while working on this that we were doing `os.GetEnv` and feeding that into `os.ExpandEnv`, which actually means that the env var will be replaced twice in chain. I retained this behaviour for now and added a test for it, but it feels like that wasn't intentional. It would technically be a minor breaking change …

caddyfile: Add support for env var defaults, tests

---

modules/caddypki/acmeserver/acmeserver.go

There have been some issues with the badger storage engine being used by the embedded acme_server. This will replace the storage engine with bbolt.
Fixes #3847
Closes #3849
Closes #3867

acme_server: switch to bbolt storage

---

modules/caddypki/acmeserver/acmeserver.go
modules/caddypki/ca.go

Now using a UsagePool to manage database instances.
Verified with the following `Caddyfile`.
Verifying graceful change by toggling debug on and off and graceful destruction by toggling `acme_server` and `respond` directives.
```
{
local_certs
debug
}
acme.localhost {
acme_server
}
```
One thing to note, now that the database paths are not wholly predictable, this branch no longer deletes old db directories.
Fixes #3865

acme_server: fix reload of acme database

---

modules/caddyhttp/reverseproxy/hosts.go
modules/caddyhttp/reverseproxy/reverseproxy.go

Related to #3748
Do not pass the request context to the LookupSRV call (no context is used for the dial call anyways). This avoids caddy from logging the "operation was cancelled" coming from the [net package](https://golang.org/src/net/net.go#L411) constantly when the client closes the connection and the request context is canceled, which also was misleading caddy to log these as `502` in the access logs
I've also added and additional error handling for when the upstream connection timesout and we return the `http.StatusGatewayTimeout` code (504) appropriately, instead of 502.

reverseproxy: Avoid "operation was canceled" errors

---

modules/caddyhttp/caddyauth/basicauth.go
modules/caddyhttp/caddyauth/caddyauth.go

https://caddy.community/t/placeholder-for-username-of-basicauth-user/10606
See also https://github.com/caddyserver/website/pull/117

docs: Mention {http.auth.user.id} placeholder in basicauth JSON docs

---

caddytest/integration/caddyfile_adapt/header.txt
modules/caddyhttp/headers/caddyfile.go

Closes #3891
Fixes regression from b0d5c2c8ae076393e7a3ad59ce875027f4c29304
The problem is that `RegisterHandlerDirective` also calls `h.Next()` to consume the directive name from the dispenser before calling `h.MatcherToken()`. When this was changed to use `RegisterDirective` instead and use `h.ExtractMatcherSet()`, this was forgotten, so it broke request matchers because it would first see `headers` instead of `@foo` when trying to extract the matcher.
I confirmed it still rejects the config if non-matcher args are given at the same time as block ones.

headers: Fix Caddyfile parsing with request matcher

---

modules/caddyhttp/caddyauth/command.go

The docs at os/signal.Notify warn about this signal delivery loss bug at
https://golang.org/pkg/os/signal/#Notify, which says:
Package signal will not block sending to c: the caller must ensure
that c has sufficient buffer space to keep up with the expected signal
rate. For a channel used for notification of just one signal value,
a buffer of size 1 is sufficient.
Caught by a static analysis tool from Orijtech, Inc. called "sigchanyzer"

caddyauth: fix unbuffered channel passed to signal.Notify

---

modules/caddyhttp/fileserver/matcher.go
modules/caddyhttp/fileserver/matcher_test.go
modules/caddyhttp/reverseproxy/fastcgi/fastcgi.go

Fixes #3718
This isn't perfect, because if the `SplitPath` value is different between the `fastcgi` transport and a `file` matcher, then unexpected behaviour could happen... but this should work correctly for the `php_fastcgi` shortcut we provide.

fastcgi: Set PATH_INFO to file matcher remainder as fallback

---

caddytest/integration/caddyfile_adapt/matcher_syntax.txt
modules/caddyhttp/matchers.go

httpcaddyfile: support matching headers that do not exist

---

.github/workflows/release.yml

This is an attempt at mitigating recurrence of this:
https://twitter.com/caddyserver/status/1338324878441603073
Since this touches our release workflow, I'd really love to test this on a test repo elsewhere before it's actually merged.

ci: reject tags if not signed by Matthew Holt's key

---

.goreleaser.yml

See https://goreleaser.com/deprecations#nfpmsfiles and https://goreleaser.com/deprecations#nfpmsconfig_files
Cherrypicked from #3941 because my PR might not be the first one to be merged next.

ci: Update goreleaser to fix deprecation notices

---

.github/workflows/release.yml
README.md

See https://github.com/caddyserver/dist/issues/49
Still needs `CLOUDSMITH_API_KEY` to be added to the repo/org @mholt, I don't remember if you've done it already? Please let me know 😄 leaving as draft until that's confirmed and my TODO is fixed.
Also adds a condition to skip the `caddy_<version>_linux_armv7.deb` because Cloudsmith would complain and Gemfury would have it override the `armv6` one, because apparently they're both `armhf`. But maybe we should skip the `armv6` one instead of `armv7`? I don't know. I assume the `armv6` one would be more compatible 🤷‍♂️ but I don't know anything about ARM arch differences.

ci: Add pushing to cloudsmith

---

caddyconfig/caddyfile/adapter.go
caddyconfig/configadapters.go
caddyconfig/httpcaddyfile/builtins_test.go
caddyconfig/httpcaddyfile/httptype_test.go
caddytest/caddytest.go
cmd/commandfuncs.go
modules/caddyhttp/reverseproxy/caddyfile.go

This will help encourage people to keep their Caddyfiles tidy.
Doesn't work on imported Caddyfiles, since we don't pass the warnings into the parser (since, in theory, the Caddyfile adapter could never produce warnings because it was designed for Caddy in the first place)... could be refactored sooner or later, or we can just give up and use `log.Print` directly.
I noticed that this editor plugin auto-fmts the Caddyfile on save, which is awesome: https://github.com/matthewpi/vscode-caddyfile-support (but also made testing this inconvenient, haha)

caddyfile: Introduce basic linting and fmt check

---

cmd/commandfuncs.go
cmd/commands.go

One thing that I always found kinda difficult was inspecting the output of `caddy list-modules` manually/visually.
I often want to know at a glance which non-standard modules a binary contains so that I can upgrade that Caddy instance without forgetting any of the modules it uses when I create its build.
This output is much easier to scan. It lists the standard modules first, then non-standard ones separately. It even counts them. I also added a `--packages` flag so you can see what Go package the module comes from.
(In the future, there should be a way to easily download the same build configuration but at the latest version, or a specified version.)

cmd: Organize list-modules output; add --packages flag

---

caddytest/integration/caddyfile_adapt/reverse_proxy_health_headers.txt
modules/caddyhttp/reverseproxy/caddyfile.go
modules/caddyhttp/reverseproxy/healthchecks.go

reverse_proxy:
health check headers can be set through Caddyfile using health_headers directive
health check header host can be set properly

reverseproxy: Caddyfile health check headers, host header support

---

caddyconfig/httpcaddyfile/builtins.go
caddyconfig/httpcaddyfile/tlsapp.go
caddytest/integration/caddyfile_adapt/tls_automation_policies_2.txt

It seems that `key_type` subdirective it's not implemented in v2. I don't know if this is intentional but I needed this ASAP and I implemented it myself. Here is the code if you are interested

caddytls: add 'key_type' subdirective

---

modules/caddyhttp/rewrite/rewrite.go
modules/caddyhttp/rewrite/rewrite_test.go

Prevent information loss, i.e. the encoded form that was sent by the
client, when using URL strip/replace.
Fixes #3596

rewrite: Use r.URL.RawPath (#3596)

---

caddytest/caddytest.go

very minor change I noticed while working on caddy-auth-portal

use the configurable adminport value, not a hardcoded default

---

cmd/commandfuncs.go
cmd/commands.go
cmd/notify.go

I was getting stuck/frustrated on another feature I have planned for Caddy 2.4, so I took a quick break and threw this together, from my own personal wishlist which I expressed in a tweet recently: https://twitter.com/mholt6/status/1349186705002151937
The `caddy upgrade` command replaces the current Caddy executable with a new one from the build server. It honors custom builds, as long as all the plugins are registered on the Caddy website. Of course, this requires permissions to replace current executable. You might have to run `sudo caddy upgrade`.
This is very experimental but I figure we can merge this in sooner or later and have people try it out and offer feedback.
There's more we could do here, like allowing the user to customize versions and/or just download the binary without …

caddycmd: Add upgrade command

---

admin.go
caddy.go
caddyconfig/configadapters.go
caddyconfig/httploader.go
caddyconfig/load.go
go.mod
go.sum
modules/caddytls/acmeissuer.go
modules/caddytls/tls.go
sigtrap.go
sigtrap_posix.go

This PR adds 3 separate, but very related features:
1. Automated server identity management
2. Remote administration over secure connection
3. Dyanmic config loading at startup
How do you know you're connecting to the server you think you are? How do you know the server connecting to you is the server instance you think it is? Mutually-authenticated TLS (mTLS) answers both of these questions. Using TLS to authenticate requires a public/private key pair (and the peer must trust the certificate you present to it).
Fortunately, Caddy is really good at managing certificates by now. We tap into that power to make it possible for Caddy to obtain and renew its own identity credentials, or in other words, a certificate that can be used for both server verification when clients connect to it, and …

admin: Secure socket for remote management

---

caddyconfig/httpcaddyfile/builtins.go
caddyconfig/httpcaddyfile/builtins_test.go

Fixes #3979
Changes confirmed working with `html` redir code.
```
user@pc ~ $ curl -i -G https://hostname.com/
HTTP/2 302
location: https://www.hostname.com/
server: Caddy
content-length: 334
date: Sat, 23 Jan 2021 04:28:18 GMT
<!DOCTYPE html>
<html>
<head>
<title>Redirecting...</title>
<script>window.location.replace("https://www.hostname.com/");</script>
<meta http-equiv="refresh" content="0; URL='https://www.hostname.com/'">
</head>
<body>Redirecting to <a href="https://www.hostname.com/">https://www.hostname.com/</a>...</body>
</html>
```

Fix html redir code, improve flow

---

.github/workflows/ci.yml

I've updated Go installation on the machine from go1.14.3 to go1.15.6. Actually, I've replaced the unpacked tarball with the Snap package, which enables automatic updates.

ci: update the command to run tests on the s390x machine

---

caddyconfig/httpcaddyfile/httptype.go

This is an attempt at solving #3634 in the simplest way I can think of.
/cc @abiosoft and @vrongmeal since you both have Caddy apps (`exec` and `git` respectively) which could make use of this.
So the idea here is that to make a third-party Caddy app configurable via the Caddyfile, it would be in global options. For example, take this Caddyfile config (taking inspiration from the https://github.com/abiosoft/caddy-exec README):
```
{
exec {
command hugo {
args "generate" "--destination=/home/user/site/public"
at startup
foreground
timeout 10s
}
command echo {
args "foobar"
at startup
}
}
}
```
A package would invoke `App("exec", parseExec)`, where `parseExec` has the signature `func parseExec(d *caddyfile.Dispenser, _ interface{}) (interface{}, error)`, but actually returns a …

httpcaddyfile: Make third-party app modules configurable via globals

---

.github/workflows/ci.yml
.github/workflows/cross-build.yml
.github/workflows/release.yml
README.md
go.mod

ci: Build and test on Go 1.16, bump minimum to 1.15

---

modules/caddyhttp/app.go
modules/caddyhttp/replacer.go
modules/caddyhttp/reverseproxy/reverseproxy.go

Adds 4 placeholders, one is actually outside reverse proxy though:
`{http.request.duration}` is how long since the server decoded the HTTP request (headers).
`{http.reverse_proxy.upstream.latency}` is how long it took a proxy upstream to write the response header.
`{http.reverse_proxy.upstream.duration}` is total time proxying to the upstream, including writing response body to client.
`{http.reverse_proxy.duration}` is total time spent proxying, including selecting an upstream and retries.
Obviously, most of these are only useful at the end of a request, like when writing response headers or logs.
See also: https://caddy.community/t/any-equivalent-of-request-time-and-upstream-header-time-from-nginx/11418
Closes #4012

reverseproxy: Add duration/latency placeholders (close #4012)

---

caddytest/integration/caddyfile_adapt/reverse_proxy_upstream_placeholder.txt
modules/caddyhttp/reverseproxy/caddyfile.go

See https://caddy.community/t/migrate-to-using-a-wildcard-certificate/11679/21
Fixes a bug where an upstream with a placeholder would append a `:` in the JSON.
Before:
```json
{
"handler":"reverse_proxy",
"upstreams":[
{
"dial": "{upstream}:"
}
]
}
```
After:
```json
{
"handler":"reverse_proxy",
"upstreams":[
{
"dial": "{upstream}"
}
]
}
```

reverseproxy: Fix upstreams with placeholders with no port

---

caddytest/integration/map_test.go
modules/caddyhttp/map/map.go

map: Replace placeholders with regex groups

---

caddyconfig/httpcaddyfile/builtins.go
caddyconfig/httpcaddyfile/builtins_test.go
caddyconfig/httpcaddyfile/httptype.go
caddyconfig/httpcaddyfile/options.go
caddyconfig/httpcaddyfile/options_test.go
caddytest/integration/caddyfile_adapt/global_options_log_and_site.txt
caddytest/integration/caddyfile_adapt/global_options_log_basic.txt
caddytest/integration/caddyfile_adapt/global_options_log_custom.txt
caddytest/integration/caddyfile_adapt/global_options_log_multi.txt

This PR is a follow up on the previous attempt in https://github.com/caddyserver/caddy/pull/3968 but instead implemented as a global logging option.
It follows up on discussion in https://github.com/caddyserver/caddy/issues/3958 about adding more functionality to the Caddyfile. I also added in another commit for a small new "replace" filter aimed at the same goal as I wrote up in the original ticket, providing more tools to remove sensitive data from logs.
Closes https://github.com/caddyserver/caddy/issues/3958

Allow configuration of loggers through Caddyfile global options

---

caddytest/integration/caddyfile_adapt/log_filters.txt
modules/logging/filters.go

This filter is intended to be useful in scenarios where you may want to
redact a value with a static string, giving you information that the
field did previously exist and was present, but not revealing the value
itself in the logs.
This was inspired by work on adding more complete support for removing
sensitive values from logs [1]. An example use case would be the
Authorization header in request log output, for which the value should
usually not be logged, but it may be quite useful for debugging to
confirm that the header was present in the request.
This PR was split out from https://github.com/caddyserver/caddy/pull/4028
[1] https://github.com/caddyserver/caddy/issues/3958

logging: add replace filter for static value replacement

---

caddyconfig/httpcaddyfile/builtins.go
caddyconfig/httpcaddyfile/directives.go
modules/caddyhttp/staticerror.go

Closes https://github.com/caddyserver/caddy/issues/3782
Just adds Caddyfile support for the static `error` handler that already exists: https://caddyserver.com/docs/json/apps/http/servers/routes/handle/error/
Syntax:
```
error [<matcher>] <status>|<message> [<status>] {
message <text>
}
```

httpcaddyfile: Add `error` directive for the existing handler

---

.gitignore

These tend to clutter up repositories.

.gitignore: add IDE files
