caddytest/integration/caddyfile_adapt/request_header.txt
modules/caddyhttp/headers/caddyfile.go

Fixes #4084
The first token needs to be skipped with `h.Next()`, otherwise the matcher token is read as the header field.

headers: Fix Caddyfile parsing for `request_header` with matchers

---

cmd/main.go

Lines in the logs like this:
```
2021/03/22 06:11:28.733 INFO    using adjacent Caddyfile
[WARNING][caddyfile] Caddyfile:2: input is not formatted with 'caddy fmt'
```
Now become:
```
2021/03/22 06:16:08.734 INFO    using adjacent Caddyfile
2021/03/22 06:16:08.735 WARN    input is not formatted with 'caddy fmt' {"adapter": "caddyfile", "file": "Caddyfile", "line": 2}
```
Just a bit nicer.

cmd: Use `caddy.Log()` instead of `fmt.Printf` for config adapter warnings

---

sigtrap_posix.go

Was missing a comma, so added it

sigtrap_posix: add missing comma to SIGTERM info

---

modules/caddyhttp/server.go

Just a minor improvement on grammar that I found could be made looking through this file.

caddyhttp: improve grammar of comment for AllowH2C

---

go.mod
go.sum
logging.go
modules/caddyhttp/caddyauth/command.go

golang.org/x/crypto/ssh/terminal is deprecated in favor of golang.org/x/term
See https://github.com/caddyserver/caddy/pull/4073/checks?check_run_id=2152150495
Error: SA1019: package golang.org/x/crypto/ssh/terminal is deprecated: this package moved to golang.org/x/term.  (staticcheck)
See https://github.com/caddyserver/caddy/pull/4073/checks?check_run_id=2152228516
Error: SA1019: package golang.org/x/crypto/ssh/terminal is deprecated: this package moved to golang.org/x/term.  (staticcheck)
Test: `go test -count=1 './...'`

go.mod: Migrate golang.org/x/term

---

caddytest/integration/caddyfile_adapt/reverse_proxy_health_path_query.txt
modules/caddyhttp/reverseproxy/caddyfile.go
modules/caddyhttp/reverseproxy/healthchecks.go
modules/caddyhttp/reverseproxy/reverseproxy.go

Closes #4049
```
reverse_proxy localhost:54321 {
health_uri /health?ready=1
health_status 2xx
}
```
Also fixes a bug with `health_status` Caddyfile parsing, it would always only take the first character of the status code even if it didn't end with "xx". I fixed the same bug in #4021 but it's relevant here too because it affects the adapt test I wrote (will rebase #4021 after and remove the redundant fix)

reverseproxy: Implement health_uri, replaces health_path, supports query

---

modules/caddyhttp/reverseproxy/selectionpolicies.go

When using cookie lb_policy, the cookie sent doesn't contain a path. So the path of the cookie stored by the browser is the url path
For exemple with this Caddyfile:
```
{
debug
admin localhost:2010
auto_https disable_redirects
}
http://localhost:8443 {
respond "B"
}
http://localhost:8444 {
respond "C"
}
http://localhost:8442 {
reverse_proxy /* {
to http://localhost:8443 http://localhost:8444
lb_policy cookie 
}
}
```  
1) When using url http://localhost:8442/A/B/C, caddy send a cookie without path and this cookie is stored in the browser with the path `/A/B`
2) When the same brower try to reach url http://localhost:8442/A/E/D, the browser doesn't send the first cookie (as the path doesn't match), so the server is sending a new cookie without path, the stickyness is no more guarantee and …

reverseproxy: Set cookie path to `/` when using cookie lb_policy

---

.goreleaser.yml

As of go1.16, the `go` commands will no longer make automatic changes to go.{mod,sum} files (see: https://blog.golang.org/go116-module-changes). This broke the release script which relied on `go mod download` and/or `go build` to automatically generate the go.sum file. This commit explicitly invokes `go mod tidy` to have the go.sum file generated.

ci: accommodate `go mod` changes of go1.16

---

caddyconfig/caddyfile/adapter.go

This is a minor bug I noticed when working on Windows; `caddy fmt` always outputs unix line endings (LF), so if a Caddyfile crafted on Windows with CRLF line endings, the `input is not formatted with 'caddy fmt'` warning would always appear.
This change normalizes the input Caddyfile to LF line endings to avoid this problem when comparing.

caddyfile: Normalize line endings before comparing fmt result

---

caddyconfig/httpcaddyfile/tlsapp.go
caddytest/integration/caddyfile_adapt/tls_automation_policies_4.txt

Fixes #4101
The panic:
```
panic: runtime error: index out of range [-1]
goroutine 1 [running]:
github.com/caddyserver/caddy/v2/caddyconfig/httpcaddyfile.consolidateAutomationPolicies(0xc00052e800, 0x3, 0x40, 0x0, 0x0, 0xc0006e0de0)
caddyconfig/httpcaddyfile/tlsapp.go:498 +0xc4a
github.com/caddyserver/caddy/v2/caddyconfig/httpcaddyfile.ServerType.buildTLSApp(0xc0001f25a0, 0x5, 0x5, 0xc0006bb800, 0x0, 0x0, 0x0, 0xc000b7af60, 0x0, 0x0, ...)
caddyconfig/httpcaddyfile/tlsapp.go:356 +0xed8
github.com/caddyserver/caddy/v2/caddyconfig/httpcaddyfile.ServerType.Setup(0xc0007a1000, 0x43, 0x80, 0xc0006bb800, 0xc0001e5080, 0x5, 0x8, 0x0, 0xc0006bb9b0, 0x0)
caddyconfig/httpcaddyfile/httptype.go:218 +0x1095
github.com/caddyserver/caddy/v2/caddyconfig/caddyfile.Adapter.Adapt(0x1a26a40, 0x2414708, …
```

httpcaddyfile: Fix panic in automation policy consolidation

---

go.mod
go.sum

v0.20.0 contains a ton of performance improvements, as well as a few changes for HTTP/3. Most notably perhaps the support for Early Hints (see https://github.com/lucas-clemente/quic-go/pull/3047).

update quic-go to v0.20.0

---

admin.go
caddy.go
cmd/commandfuncs.go
notify/notify.go
notify/notify_linux.go
notify/notify_other.go

Initial sd_notify support was added in #3963, but that sent signals from both cmdRun and cmdReload.  This approach has two drawbacks:
- Reloads initiated via the API do not send signals.
- The signals are sent from different processes, which requires the `NotifyAccess=exec` directive in the unit file.
This change moves the NotifyReloading and NotifyReadiness invocations to Load, which address both of those drawbacks.  It also adds a complimentary NotifyStopping method which is invoked from handleStop.  All the notify methods are defined in a notify package to avoid an import loop.

notify: Send all sd_notify signals from main caddy process

---

caddytest/integration/caddyfile_adapt/file_server_status.txt
modules/caddyhttp/fileserver/caddyfile.go
modules/caddyhttp/fileserver/staticfiles.go

After reading a question about the `handle_response` feature of `reverse_proxy`, I realized that we didn't have a way of serving an arbitrary file with a status code other than 200. This is an issue in situations where you want to serve a custom error page in routes that are not errors, like the aforementioned `handle_response`, where you may want to retain the status code returned by the proxy but write a response with content from a file.
This feature is super simple, basically if a status code is configured (can be a status code number, or a placeholder string) then that status will be written out before serving the file - if we write the status code first, then the stdlib won't write its own (only the first HTTP status header wins).

fileserver: Add status code override

---

caddyconfig/caddyfile/formatter_fuzz.go
caddyconfig/caddyfile/lexer_fuzz.go
duration_fuzz.go
modules/caddyhttp/templates/frontmatter_fuzz.go

I'm prepping to bring back the continuous fuzzing of Caddy on another platform after the departure of FuzzIt. In the process, I found more possible targets that can be included based on the criteria of:
- accept string|[]byte as input
- function body is more than mere `json.Unmarshal`
One dilemma for now is where to store the seed corpus to be retrieved by the new platform. Any thoughts? I think some projects store them in a branch, but not sure how much of a hassle will it be to keep that branch updated. I've considered hiding them behind a `refs/<something>/corpus`, but it feels too magical and needs insider knowledge.

ci: fuzz: add more fuzz targets

---

caddyconfig/caddyfile/importgraph.go
caddyconfig/caddyfile/lexer.go
caddyconfig/caddyfile/parse.go
caddyconfig/caddyfile/parse_test.go
caddyconfig/caddyfile/testdata/import_recursive0.txt
caddyconfig/caddyfile/testdata/import_recursive1.txt
caddyconfig/caddyfile/testdata/import_recursive2.txt
caddyconfig/caddyfile/testdata/import_recursive3.txt
cmd/commandfuncs.go

Fix an edge case of Caddyfile import itself. I don't imagine anyone deliberately self-importing a Caddyfile but could happen if glob expansion wasn't vetted by the user.

caddyfile: reject cyclic imports

---

caddytest/integration/autohttps_test.go
modules/caddyhttp/autohttps.go
modules/caddyhttp/server.go

Taking a crack at implementing what I suggested in https://github.com/caddyserver/caddy/issues/3212
This is WIP, I haven't tested it yet, but wouldn't mind your 2c about this idea @mholt before I dive any deeper on the idea.
Basically, this should insert the redirect routes after any existing route with a host matcher but before any possibly existing user-defined catch-all route, then append our own catch-all at the end just in case as we already did before. I think this would better align with what users expect when they write a Caddyfile that has a `http://` route. This behaviour can be opted out of by setting `auto_https disable_redirects`.

caddyhttp: Implement better logic for inserting the HTTP->HTTPS redirs

---

modules/caddyhttp/reverseproxy/admin.go

As discussed in https://caddy.community/t/cli-to-query-for-upstream-server-status/12210
```
$ curl localhost:2019/reverse_proxy/upstreams
[
{"address": "localhost:10002", "healthy": true, "num_requests": 0, "fails": 0},
{"address": "localhost:10000", "healthy": true, "num_requests": 0, "fails": 0},
{"address": "localhost:10001", "healthy": true, "num_requests": 0, "fails": 0}
]
```
Tested with a Caddyfile like this:
```
{
auto_https off
}
:10000 {
respond "10000"
}
:10001 {
respond "10001"
}
:10002 {
respond "10002"
}
:9999 {
reverse_proxy localhost:10000 localhost:10001 localhost:10002
}
```

reverseproxy: Implement admin API for reporting upstream statuses

---

modules/caddytls/storageloader.go

An idea that came up in https://caddy.community/t/save-internally-issued-wildcard-certificate-in-consul/11740, this a simple module that might be useful for anyone who uses storage modules that aren't filesystem, to let them load certs/keys externally issued for use by Caddy.
Bit goofy, since we need to fetch the certmagic.Storage during provisioning, it needs a wrapping struct instead of just being an array like `load_files`.
Future work might involve adding Caddyfile support via a subdirective of the `tls` directive maybe?
Wouldn't surprise me if this is rejected but I figured I'd write it up real quick as an idea.

caddytls: Add `load_storage` module

---

caddyconfig/caddyfile/parse.go
caddytest/integration/caddyfile_adapt/import_args_snippet_env_placeholder.txt
replacer.go

See https://caddy.community/t/snippet-issue-works-outside-snippet/12231
So it turns out that `NewReplacer()` gives a replacer with some global defaults (like `{env.*}` and some system and time placeholders), which is not ideal when running `import` because we just want to replace `{args.*}` only, and nothing else.

caddyfile: Fix `import` replacing unrelated placeholders

---

modules/caddyhttp/fileserver/staticfiles.go

Just something I noticed when reading through the code; I think the `io.Copy` was a remnant of an older version of that code. I don't see a reason why we don't just let it fall through and serve the file with `http.ServeContent` normally. More consistent that way.
~~Also, I hoisted the `status_code` override logic above the error handler detection bit, because then it allows for overriding the status code during error routes. Not necessarily that likely to be useful, but it's more correct. (Reminder that the first `w.WriteHeader()` wins, subsequent ones have no effect). Marking this as a bug just for this reason, but it's barely worth discussing as a bug 😅.~~
Edit: So calling `w.WriteHeader()` ourselves makes the `w.Header().Set()` operations in `http.ServeContent` not actually work …

fileserver: Better handling of HTTP status override

---

modules/caddyhttp/reverseproxy/selectionpolicies.go
modules/caddyhttp/reverseproxy/selectionpolicies_test.go

The tests ran without an issue, so this should be the fix.
Fixes: #4135
Test: go test './...' -count=1

caddyhttp: reverseproxy: fix hash selection policy

---

caddyconfig/httpcaddyfile/tlsapp.go
caddytest/integration/caddyfile_adapt/tls_automation_policies_5.txt

When user set on_demand tls option in a catch-all (:443) policy,
we expect other policies to not have the on_demand enabled
See ex in tls_automation_policies_5.txt
Btw, we can remove policies if they are **all** empty.

httpcaddyfile: Fix unexpectedly removed policy

---

context.go
modules/caddytls/matchers.go
modules/caddytls/matchers_test.go

I'm not sure this is a good idea as a replacement for auth, but I think this could still be useful. See https://caddy.community/t/best-solution-for-mixing-lan-and-cloudflare-authenticated-origin-pulls/12139/8

caddytls: Implement remote IP connection matcher

---

modules/caddyhttp/fileserver/browse.go
modules/caddyhttp/fileserver/browse_test.go
modules/caddyhttp/fileserver/browsetplcontext.go
modules/caddyhttp/fileserver/browsetplcontext_test.go
modules/caddyhttp/fileserver/staticfiles.go
modules/caddyhttp/templates/templates.go
modules/caddyhttp/templates/tplcontext.go
modules/caddyhttp/templates/tplcontext_test.go

fileserver: Share template logic for both `templates` and `file_server browse`

---

modules/caddyhttp/matchers.go
modules/caddyhttp/matchers_test.go

Below is the report using `benchstat` and cmd:
`go test -run=BenchmarkHeaderREMatcher -bench=BenchmarkHeaderREMatcher -benchmem -count=10`
```
name                old time/op    new time/op    delta
HeaderREMatcher-16     869ns ± 1%     658ns ± 0%  -24.29%  (p=0.000 n=10+10)
name                old alloc/op   new alloc/op   delta
HeaderREMatcher-16      144B ± 0%      112B ± 0%  -22.22%  (p=0.000 n=10+10)
name                old allocs/op  new allocs/op  delta
HeaderREMatcher-16      7.00 ± 0%      5.00 ± 0%  -28.57%  (p=0.000 n=10+10)
```

caddyhttp: performance improvement in Regex Match

---

caddyconfig/httpcaddyfile/builtins.go
caddyconfig/httpcaddyfile/httptype.go
caddyconfig/httpcaddyfile/options.go
caddytest/integration/caddyfile_adapt/auto_https_ignore_loaded_certs.txt

Closes #4048
Adds `ignore_loaded_certs` as an option for the `auto_https` global option, which turns on `ignore_loaded_certificates`, i.e. making the automation policy still run for domains in the server even if they're covered by otherwise loaded certificates (such as a wildcard cert that covers that specific domain).
~~I went with the name `always` as suggested by a user in #4048 because I think it somewhat better describes what happens in a more user-friendly way, even if it's somewhat ambiguous.~~
And obviously it's not possible to set `ignore_loaded_certs` and `disable_redirects` at the same time, but I think the likelyhood of that being a valid usecase is quite low.
Example:
```
{
auto_https ignore_loaded_certs
}
*.example.com {
tls {
dns <provider>
}
respond "Wildcard"
} …
```

httpcaddyfile: Add `auto_https ignore_loaded_certs`

---

cmd/commandfuncs.go
cmd/commands.go

cmd: Add `envfile` flag to `start` command

---

modules/caddyhttp/fileserver/matcher.go

Fixes https://github.com/caddyserver/caddy/issues/4146
If `TryFiles` is empty, we fill it with `r.URL.Path`. In this case, this is `/`. Then later, in `prepareFilePath()`, we run the replacer (which turns `{path}` into `/` at that point) but `file` remains the original value (and the placeholder is still the placeholder there).
So then `strings.HasSuffix(file, "/")` will be `false` for the placeholder, but `true` for the empty `TryFiles` codepath, because `file` was `/` due to being set to the actual request value beforehand.
This means that `suffix` becomes `//` in that case, so after `sanitizedPathJoin`, it becomes `./`, so `strictFileExists`'s `strings.HasSuffix(file, separator)` codepath will return true.
I think we should change the `m.TryFiles == nil` codepath to `m.TryFiles = …

fileserver: Fix `file` matcher with empty `try_files`

---

caddytest/integration/caddyfile_adapt/encode_options.txt
modules/caddyhttp/encode/caddyfile.go

Followup to #4150, #4151 /cc @ueffel @polarathene
After a bit of discussion with @mholt, we decided to remove `prefer` as a subdirective and just go with using the order implicitly always. Simpler config, simpler docs, etc.

encode: Drop `prefer` from Caddyfile

---

.github/workflows/ci.yml
.github/workflows/cross-build.yml
.github/workflows/lint.yml

We decided that we'll use branches like `2.4` as the target for any changes that we might want to release in a `2.4.x` version like `2.4.1`, so that we can continue to merge changes targeting the next minor release (e.g. `2.5.0`) on master.
Our CI config wasn't set up for this to work properly though, since it was only running checks on PRs targeting master. See https://github.com/caddyserver/caddy/pull/4163 for example. This should fix it (then I'll rebase that PR so CI runs).
I couldn't find a way to do a pattern to only match digits for the branch names from Github's docs, it just looks like a pretty generic glob syntax. But this should do until we get to 3.0

ci: Run CI on PRs targeting minor version branches

---

modules/caddyhttp/reverseproxy/reverseproxy.go

Turns out this was an oversight, we assumed we could use `{http.response.header.*}` but that doesn't work because those are grabbed from the response writer, and we haven't copied any headers into the response writer yet.
So the fix is to set all the response headers into the replacer at a new namespace before running the handlers.
This adds the `{http.reverse_proxy.header.*}` replacer.
See https://caddy.community/t/empty-http-response-header-x-accel-redirect/12447

reverseproxy: Set the headers in the replacer before `handle_response`

---

caddyconfig/caddyfile/parse.go
caddyconfig/caddyfile/parse_test.go

Honestly, we should've done this a long time ago, but better late than never.
This is an incredibly common mistake made by users, so we should catch it earlier in the parser and give a more friendly message. Often it ends up adapting but with mistakes, or erroring out later due to other site addresses being read as directives.
There's not really ever a situation where a lone `{` is valid at the end of a site address, so this should be fine. But I suppose there are edgecases where the user wants to use a path matcher where it ends specifically in `{`, but... why?

caddyfile: Add parse error on site address with trailing `{`

---

modules/logging/netwriter.go

Replaces #4111, fixes #4083
My hypothesis is that if a dial timeout is configured, the server will still be able to respond to requests even if the log server is down, although there will probably still be a delay for up to the dial timeout.
I haven't had a chance to test this, if someone else could that would be great.
I did add simple redial memory, so it will only attempt to redial at most once every 10 seconds so that it doesn't block every single log emission for up to DialTimeout while the socket is offline. It just dumps the logs to stderr while the socket is down.

logging: Implement dial timeout for net writer (fix #4083)

---

metrics.go

This oughtta shut the linter up:
```console
$ golangci-lint run .        
metrics.go:14:26: SA1019: prometheus.NewBuildInfoCollector is deprecated: Use collectors.NewBuildInfoCollector instead. (staticcheck)
prometheus.MustRegister(prometheus.NewBuildInfoCollector())
^
```

metrics: use buildinfo collector from new collectors pkg

---

modules/logging/encoders.go

Whoops! 😅 
https://caddy.community/t/google-cloud-structured-logging-format/12678

logging: Actually use `level_key`

---

caddyconfig/httpcaddyfile/options.go
caddyconfig/httpcaddyfile/pkiapp.go
caddytest/integration/caddyfile_adapt/global_options_skip_install_trust.txt

Fixes https://github.com/caddyserver/caddy/issues/4002

httpcaddyfile: Add `skip_install_trust` global option

---

modules/caddyhttp/fileserver/browse.go
modules/caddyhttp/fileserver/staticfiles.go

This commit changes the file_server directive to redirect using the original request's URL instead of the possibly trimmed URL. This should make file_server work with handle_path.
This fix is taken from mholt's comment in https://caddy.community/t/file-servers-on-different-paths-not-working/11698/11.
---
For testing purposes, below Caddyfile should reproduce the before and afters:
```
{
debug
admin off
}
http://127.0.0.1:28475 {
root * /home/diamond
handle_path /browse* {
file_server browse
}
respond "Hi"
}
```
When accessing `http://127.0.0.1:28475/browse`, the redirection would lead to `/`; after the changes, it would lead to `/browse/`.

fileserver: Redirect within the original URL

---

caddytest/integration/caddyfile_adapt/tls_propagation_timeout.txt
modules/caddytls/acmeissuer.go

caddytls: Add Caddyfile support for `propagation_timeout`

---

modules/caddyhttp/fileserver/browse.go

This commit is a follow up to PR #4179 that introduced a bug where browse redirections to the right URL would not preserve query parameters.
Below is the copy-pasted comment that describes the issue:
---
I think you're right after all. With the path redirection, I'm not getting the query parameters back.
```
―❤―▶ cat main.go
...
http.Redirect(w, r, r.URL.Path+"/", 200)
...
―❤―▶ curl -v localhost:8080/path?a=b
...
< HTTP/1.1 200 OK
< Location: /path/
< 
<a href="/path/">OK</a>.
```
With the `String()` redirection, I'm getting the query parameters as expected in the `Location` header.
```
―❤―▶ cat main.go
...
r.URL.Path += "/"
http.Redirect(w, r, r.URL.String(), 200)
...
―❤―▶ curl -v localhost:8080/path?a=b
< HTTP/1.1 200 OK
< Location: /path/?a=b
< 
<a href="/path/?a=b">OK</a>.
```

fileserver: Fix browse not redirecting query parameters

---

go.mod
go.sum

Updates CertMagic to v0.14.0 which patches cert replacement upon OCSP revocation.
If the cert was revoked due to key compromise, the key is replaced too.
Obtain now reuses existing private key if already in storage.

Force auto-renew for OCSP revoked status (maybe) (fix #4191)

---

modules/caddyhttp/caddyhttp.go
modules/caddyhttp/caddyhttp_test.go
modules/caddyhttp/fileserver/browse.go
modules/caddyhttp/fileserver/matcher.go
modules/caddyhttp/fileserver/matcher_test.go
modules/caddyhttp/fileserver/staticfiles.go
modules/caddyhttp/fileserver/staticfiles_test.go
modules/caddyhttp/reverseproxy/fastcgi/fastcgi.go

Help prevent directory traversal within PHP apps. Basically we pulled `sanitizedPathJoin()` out of the file server and put it into `caddyhttp` and exported it so any middleware can use it for safe path joins.
Still needs some testing on Windows CI and in actual PHP environments.

caddyhttp: Refactor and export SanitizedPathJoin for use in fastcgi

---

modules/caddyhttp/encode/gzip/gzip.go
modules/caddyhttp/encode/zstd/zstd.go

zstd: Limit window sizes to 128K to keep memory in control both server and client size.
zstd: Write 0 length frames. This may be needed for compatibility.
zstd: Create fewer encoders. Small memory improvement.
gzip: Allow -2 (Huffman only) and -3 (stateless) compression modes.

encode: Tweak compression settings

---

caddytest/integration/caddyfile_adapt/file_server_disable_canonical_uris.txt
modules/caddyhttp/fileserver/caddyfile.go

add 'canonical_uris' parameter to caddyfile
reference #2741
Signed-off-by: mritd <mritd@linux.com>

fileserver: Add `disable_canonical_uris` Caddyfile subdirective

---

modules/caddyhttp/matchers.go

Use `strings.HasPrefix` to identify gRPC protocol. Fix https://github.com/caddyserver/caddy/issues/4234.

caddyhttp: Fix incorrect determination of gRPC protocol

---

caddytest/integration/reverseproxy_test.go
modules/caddyhttp/reverseproxy/healthchecks.go

Hello, 
This is a fix for https://github.com/caddyserver/caddy/issues/4231. I tried changing the Path variable in different ways but it did not help. 
It seems http transport relies on the address in the dial info context var which caused the issue (https://github.com/caddyserver/caddy/blob/master/modules/caddyhttp/reverseproxy/httptransport.go#L181). 
I have also added a test for healthchecks to reproduce the bug described in the issue.

reverseproxy: Keep path to unix socket as dial address

---

modules/caddyhttp/fileserver/browsetplcontext.go

This pull request fixes browse's default template to make `name_dir_first` sorting work.
The fix is basically a minor typo fix, changing `namedirfirst` in the template to `name_dir_first` to reflect `sortByNameDirFirst = "name_dir_first"`.

fileserver: Fix browse name_dir_first sorting

---

modules/logging/filters.go

While looking at the code base I noticed that probably interface guards for `ReplaceFilter` were missing.

logging: Add missing interface guards for replace filter

---

caddytest/integration/autohttps_test.go
modules/caddyhttp/server.go

Followup to https://github.com/caddyserver/caddy/pull/4033, see https://caddy.community/t/how-to-set-priority-in-caddyfile/13002/8 for context
As it turns out, my earlier change for HTTP->HTTPS redirect was not enough, because it left one edgecase.
If none of the routes in the HTTP server had host matchers, then it would return the index of the last route, even if the only route was a catch-all (which is defined as having no host matcher).
This means that a config like this would not work correctly, and `Foo` would be returned on requests to `http://bar.localhost/`
```
http:// {
respond "Foo"
}
bar.localhost {
respond "Bar"
}
```
What we want is for `http://bar.localhost/` to return a redirect to `https://bar.localhost/` instead (and this can be overridden by using `auto_https …

caddyhttp: Fix edgecase with HTTP->HTTPS logic

---

modules/caddyhttp/server.go
modules/logging/encoders.go

See https://github.com/caddyserver/caddy/issues/4148#issuecomment-833207811
With the upcoming removal of `common_log` from access logs, there's a few things we should do to smooth things out to offer a path for backwards compatibility.
- Add a `common_log` time format, which matches the format from the `{time.now.common_log}` placeholder which is currently used for the `common_log` field. This will make it easier for users of https://github.com/caddyserver/format-encoder to get the same time format by doing something like this:
log {
format formatted <insert common log template here> {
time_format common_log
}
}
- Add the `http.auth.user.id` placeholder's value to the logs. This currently isn't in the access logs, so if we drop `common_log`, that wouldn't be visible anywhere in the access …

logging: Prep for `common_log` removal

---

caddyconfig/caddyfile/dispenser.go
caddyconfig/caddyfile/dispenser_test.go

Use `fmt.Errorf` instead of `fmt.Sprintf` in `Dispenser.Errf` method to reserve the error chain information. Make the underlying error unwrapable by using `errors.Is` or `errors.As` helpers.

caddyfile: keep error chain info in Dispenser.Errf

---

admin.go
caddy.go

Implemented mostly referenced to the #4106
- add a `PullInterval` filed in config
- setup a timer in a goroutine
- `select` with context and timer
A trick point is that
https://github.com/colinaaa/caddy/blob/169bb265104d0ade5f8bab05d82e53eef30c0129/caddy.go#L485-L494
here I did not use if-else to check whether `PullInterval` is non-zero, but I directly use `time.After(PullInterval)` so that with 0 intervals. 
This will return immediately which is the same as executing without `time.After`
re #4106

admin: Implement a simple timer to pull config

---

caddyconfig/httpcaddyfile/httptype.go
caddytest/integration/caddyfile_adapt/log_skip_hosts.txt

Previously, some hosts that should be skipped in logging would
be missed as the current logic would only collect them after
encountering the first server that would log. This change makes sure
the ServerLogConfig is initialized before iterating over the server
blocks.
---
This connects: https://github.com/caddyserver/caddy/issues/4256#issuecomment-889676939
The condition this is fixing looks like:
- When parsing the Caddyfile, the server blocks get sorted in a different order than the one they are using in the Caddyfile
- The first server block that gets processed when calling `Setup` does not have a `log` directive
- `srv.Logs` therefore is `nil` on this iteration
- This condition does not pass https://github.com/caddyserver/caddy/blob/c131339c5cda3a541223fde4a714aab55de13b9a/caddyconfig/ …

httpcaddyfile: Ensure hosts to skip for logs can always be collected

---

modules/caddyhttp/reverseproxy/reverseproxy.go
modules/caddyhttp/reverseproxy/streaming.go

I went through the commits that touched stdlib's `reverseproxy.go` file in the past couple of years (only a dozen or so), and copied over all the changes that are to code that was copied into Caddy.
The commits I pulled changes from (hopefully apparent from looking at those commits what the changes in this PR are doing):
- https://github.com/golang/go/commit/2cc347382f4df3fb40d8d81ec9331f0748b1c394
- https://github.com/golang/go/commit/a5cea062b305c8502bdc959c0eec279dbcd4391f
- https://github.com/golang/go/commit/ecdbffd4ec68b509998792f120868fec319de59b
- https://github.com/golang/go/commit/21898524f66c075d7cfb64a38f17684140e57675
- https://github.com/golang/go/commit/ca3c0df1f8e07337ba4048b191bf905118ebe251
- https://github.com/golang/go/commit/9c017ff30dd21bbdcdb11f39458d3944db530d7e …

reverseproxy: Pull latest proxy changes from stdlib

---

caddyconfig/httpcaddyfile/httptype.go

I've noticed that it's a pretty common pattern to write a proxy like this, when needing to proxy over HTTPS:
```
reverse_proxy https://example.com {
header_up Host {http.reverse_proxy.upstream.hostport}
}
```
I find it pretty hard to remember the exact placeholder to use for this, and I continually need to refer to the docs when I need it. I think a simple fix for this is to add another Caddyfile shortcut for this one to shorten it:
```
reverse_proxy https://example.com {
header_up Host {upstream_hostport}
}
```

httpcaddyfile: Add shortcut for proxy hostport placeholder

---

admin.go
admin_test.go

Resolves #4260.
While stepping through the stack traces in the above issue, I initially thought the existing [config mutex](https://github.com/caddyserver/caddy/blob/master/caddy.go#L133-L134) should cover this situation, however, since we reference [`localAdminServer` (and `remoteAdminServer`)](https://github.com/caddyserver/caddy/blob/master/admin.go#L349) in a goroutine later on, it's still possible that the reads on those variables are concurrent with writes.
I added a test that when paired with the `-race` flag consistently fails against tag 2.4.3 (9d4ed3a3236df06e54c80c4f6633b66d68ad3673). With these changes, the test consistently passes with the `-race` flag (at least on my machine 😄).
The addition of a mutex here doesn't seem to appreciably impact performance and motivated my …

admin: Synchronize server assignment/references to avoid data race

---

replacer.go

This PR is necessary to support a header called `X-Request-Start` that is a UNIX timestamp of when the request was first received. Monitoring tools like AppSignal and NewRelic uses this header to track request queue time. If you need more information, you can read more about it:
- [Is it normal for requests to spend a long time in "Request Queuing" as reported by NewRelic?](https://help.heroku.com/QB0BKTNJ/is-it-normal-for-requests-to-spend-a-long-time-in-request-queuing-as-reported-by-newrelic)
- [Track request queue time](https://docs.appsignal.com/ruby/instrumentation/request-queue-time.html)

feat(time): bring back time.now unix formats

---

.github/workflows/ci.yml
.github/workflows/cross-build.yml
.github/workflows/release.yml
README.md
go.mod

Used https://github.com/caddyserver/caddy/pull/4024 as a template. Pretty much the same change, different versions.

ci: Build and test on Go 1.17, bump minimum to 1.16

---

cmd/main.go
storage.go

Fix the behaviour of the environment variables `XDG_DATA_HOME` and `XDG_CONFIG_HOME` when supplied through an env file to match the expected one.
For further information, check #4273 
Resolves #4273 
- Caddy should create its data and config directories and files at the common location as always when no env file is specified using `--envfile`.
- For example: `/home/user/.local/share/caddy/<files and/or folders>`
- When an env file is specified using `--envfile`, Caddy should use the environment variables `XDG_DATA_HOME` and `XDG_CONFIG_HOME` from the env file instead (instead) of the system ones. This should cause Caddy to create its files/directories at the location specified in the env file. 
- Example: Instead of `/home/user/.local/share/caddy/autosave.json` Caddy now uses …

cmd: Fix paths when using an env file

---

caddyconfig/caddyfile/parse.go

Some users forget to use a comma between their site addresses. This is invalid (commas aren't a valid character in domains) and later parts of the code like certificate automation will try to use this otherwise, which doesn't make sense. Best to error as early as possible.
Example thread on the forums where this happened: https://caddy.community/t/simplify-caddyfile/13281/9
```
foo.example.com,bar.example.com
respond "foo"
```
👇 
```
$ caddy adapt
2021/08/22 19:29:44.950 INFO    using adjacent Caddyfile
adapt: Caddyfile:1 - Error during parsing: Site addresses cannot contain a comma ',': 'foo.example.com,bar.example.com' - put a space after the comma to separate site addresses
```

caddyfile: Prevent invalid site addresses with comma

---

caddyconfig/caddyfile/parse.go
caddyconfig/httpcaddyfile/httptype.go

Some new users mistakenly try to define two sites without braces around each. Doing this can yield a confusing error message saying that their site address is an "unknown directive".
We can do better by keeping track of whether the current site block was parsed with or without a brace, then changing the error message later based on that.
For example, now this invalid config:
```
foo.example.com
respond "foo"
bar.example.com
respond "bar"
```
Will yield this error message:
```
$ caddy adapt
2021/08/22 19:21:31.028 INFO    using adjacent Caddyfile
adapt: Caddyfile:4: unrecognized directive: bar.example.com
Did you mean to define a second site? If so, you must use curly braces around each site to separate their configurations.
```
We could consider also linking to our docs where this is …

caddyfile: Better error message for missing site block braces

---

modules/caddyhttp/reverseproxy/reverseproxy.go

From reading through the code, I think this code path is now obsoleted by the changes made in https://github.com/caddyserver/caddy/pull/4266.
Basically, `h.flushInterval()` will set the flush interval to `-1` if we're in a bi-directional stream, and the recent PR ensured that `h.copyResponse()` properly flushes headers immediately when the flush interval is non-zero. So now there should be no need to call Flush before calling `h.copyResponse()`.
---
Since this was your code from https://github.com/caddyserver/caddy/issues/3556 and https://github.com/caddyserver/caddy/pull/3561 @masknu, would you mind confirming that your usecase still works correctly with this change, just as a sanity check? Thanks!

reverseproxy: Remove redundant flushing

---

modules/caddyhttp/encode/encode.go

The first write will determine if encoding has to be done and will add an Content-Encoding. Until then Flushing has to be delayed so the Content-Encoding header can be added before headers and status code is written. (A passthrough flush would write header and status code)
Fixes https://github.com/caddyserver/caddy/issues/4314
As of now, no integration test included

encode: ignore flushing until after first write

---

.github/workflows/cross-build.yml

This generated way too many test jobs, which weren't really that useful. Cross-build is just to keep us posted on which architectures are building okay, so it's not necessary to do it twice. Only plan9 is not working at this point (see https://github.com/caddyserver/caddy/issues/3615)

ci: Only test cross-build on latest Go version

---

cmd/commandfuncs.go
cmd/commands.go
cmd/main.go

Initial draft adressing caddyserver/dist#29
Because it's not yet clear where to put this package, I have put all code in one single file. 
As considered by @mholt, I could probably rewrite this as a Caddy module. However I think this would require exporting the "commands" variable from caddycmd, I am not sure if that could be a problem. Please let me know what you think

cmd: export CaddyVersion(), Commands()

---

.github/workflows/ci.yml
.github/workflows/release.yml

GoReleaser v0.177.0 fixes the issue, so the workaround is no longer needed.

ci: revert workaround implemented in #4306

---

caddytest/integration/caddyfile_adapt/php_fastcgi_handle_response.txt
modules/caddyhttp/reverseproxy/fastcgi/caddyfile.go

Fixes #4322
Super simple, actually. The problem was that if `handle_response` contained a `root` directive, then it would actually get consumed ahead of time as a subdirective for `php_fastcgi`, breaking the tokens, triggering an error when parsing when passed down to `reverse_proxy`.
The fix is to only read `php_fastcgi` subdirectives if the nesting is `1`, so we skip any that might appear within any sub-blocks.
The test fails before the change, passes after.

fastcgi: Fix Caddyfile parsing when `handle_response` is used

---

modules/caddyhttp/fileserver/matcher.go
modules/caddyhttp/matchers.go
modules/caddyhttp/routes.go

See #4344, this is a first step towards completing that issue.
Nginx supports a couple pieces of functionality in its implementation of `try_files` that allow handling the request either as an HTTP error, or by routing to a named location block. http://nginx.org/en/docs/http/ngx_http_core_module.html#try_files
For Caddy, I think it would be quite beneficial to add support to `try_files` for triggering an error as a fallback case, to short-circuit the request handling early. In many cases, it's not simply the case of "try_files matches, or doesn't".
The one potentially contentious bit here, implementation-wise, is the usage of a placeholder `http.matchers.error` as a way to carry the error from the matcher logic up to the HTTP handler chain logic. I'm hoping that this would have a minimal …

caddyhttp: Add support for triggering errors from `try_files`

---

caddytest/integration/caddyfile_adapt/php_fastcgi_try_files_override.txt
modules/caddyhttp/reverseproxy/fastcgi/caddyfile.go

See #4344, this is part 2 of completing that issue. This should be merged _after_ #4346.
This makes it possible to override the `try_files` logic in the `php_fastcgi` directive, without having to implement a `try_files` to run _before_ `php_fastcgi` (plenty of examples of users doing this on the forums, where their PHP apps didn't quite conform to what they needed).
It makes the following config possible:
```
:8080 {
root * /srv
php_fastcgi localhost:9000 {
try_files {path} {path}/index.php =404
}
file_server
handle_errors {
respond "Error!"
}
}
```

fastcgi: Implement `try_files` override in Caddyfile directive

---

modules/caddyhttp/fileserver/browse.go
modules/caddyhttp/fileserver/browsetplcontext.go

Fix: [#4353](https://github.com/caddyserver/caddy/issues/4353)

fileserver: Fix displayed file size if it is symlink

---

modules/caddyhttp/fileserver/browsetpl.go

Currently file browser template have all A link (visited and unvisited) in the same color (blue).
This PR make visited A links to be displayed in purpled color. 
Convenient to keep track of visited folders & opened files.

fileserver: purple color for visited links in browse

---

.golangci.yml
admin.go
caddy.go
caddyconfig/caddyfile/parse.go
caddyconfig/caddyfile/parse_test.go
caddyconfig/httpcaddyfile/builtins.go
caddyconfig/httploader.go
caddytest/caddytest.go
caddytest/integration/caddyfile_adapt_test.go
caddytest/integration/reverseproxy_test.go
caddytest/integration/stream_test.go
cmd/commandfuncs.go
cmd/main.go
logging.go
modules/caddyhttp/replacer.go
modules/caddyhttp/reverseproxy/fastcgi/client.go
modules/caddyhttp/reverseproxy/fastcgi/client_test.go
modules/caddyhttp/reverseproxy/healthchecks.go
modules/caddyhttp/reverseproxy/httptransport.go
modules/caddyhttp/staticresp_test.go
modules/caddyhttp/templates/tplcontext_test.go
modules/caddypki/crypto.go
modules/caddytls/acmeissuer.go
modules/caddytls/connpolicy.go
modules/caddytls/fileloader.go
modules/caddytls/folderloader.go

Since Caddy is currently using Go 1.16 and CI using Go 1.17, so it is safe to remove deprecated `ioutil` package, ref https://golang.org/doc/go1.16#ioutil. The relevant parameters within `.golangci.yml` have also been removed and it is no longer needed.

style: move from deprecated ioutil to os and io packages

---

caddyconfig/httpcaddyfile/httptype.go
modules/caddyhttp/app.go
modules/caddyhttp/replacer.go

Fixes https://github.com/caddyserver/caddy/issues/3767

caddyhttp: Placeholder for client cert in DER + base64 format

---

modules/caddytls/tls.go

See discussion on 42b7134ffa3bf3e9e86514c82407979c2627a5ab
/cc @Gr33nbl00d

caddytls: Mark storage clean timestamp at end of routine

---

modules/caddyhttp/matchers.go
modules/caddyhttp/matchers_test.go

I found an issue where it's possible to bypass path matchers by crafting a request with a path that doubles up slashes, or uses URL-encoded characters to smuggle the request past the path matcher.
This becomes a security issue, because auth gates using [`basicauth`](https://caddyserver.com/docs/caddyfile/directives/basicauth) can be bypassed 😬
The solution is to unescape (convert URL-encoded characters) then clean the path, before matching.
This could be a breaking change if exact behaviour of the matcher is required (without cleaning the path). In that case, then it's possible to use the [`expression`](https://caddyserver.com/docs/caddyfile/matchers#expression) matcher to do a direct string comparison or regexp on the `{http.request.uri.path}` placeholder (or simply `{path}` [in the …

caddyhttp: Sanitize the path before evaluating path matchers

---

modules/caddyhttp/server.go

Fixes #4428
It's best to still log handler errors at debug level so that they're hidden by default, but still accessible if additional details are necessary.

caddyhttp: Log non-500 handler errors at debug level

---

modules/caddyhttp/fileserver/browse.go
modules/caddyhttp/fileserver/browsetplcontext.go

fileserver: Fix handling of symlink sizes in directory listings

---

modules/caddyhttp/fileserver/browsetplcontext.go
modules/caddyhttp/fileserver/browsetplcontext_test.go

Breadcrumbs use the `.Name` field as the visual item while `.Path` is the data-oriented item. Earlier implementation used the URL path as-is, which could have been in escaped format. This PR un-escapes the URL path to use as for the `.Name`.
Fixes #4409

fileserver: browse: do not encode the paths in breadcrumbs and page title

---

caddytest/integration/caddyfile_adapt/log_filters.txt
modules/logging/filters.go
modules/logging/filters_test.go

Even if it's considered a bad security practice, it's common that query parameters contain sensitive information. Some examples:
* [OAuth access token](https://datatracker.ietf.org/doc/html/rfc6750#section-2.3)
* "magic links" and other temporary URLs
* [PHP session IDs](https://www.php.net/manual/en/session.idpassing.php)
* [Mercure JWT](https://github.com/dunglas/mercure/pull/562) (the reason why I started working on this patch in the first time)
This PR adds the possibility to redact such sensitive information from the logs.

logging: add a filter for query parameters

---

caddytest/integration/caddyfile_adapt/log_filters.txt
modules/logging/filters.go
modules/logging/filters_test.go

Similar to https://github.com/caddyserver/caddy/pull/4424 but for cookies, we often (and legitimately) contain sensitive data that must not be logged.

logging: add a filter for cookies

---

caddytest/integration/caddyfile_adapt/reverse_proxy_options.txt
modules/caddyhttp/reverseproxy/caddyfile.go
modules/caddyhttp/reverseproxy/fastcgi/fastcgi.go
modules/caddyhttp/reverseproxy/httptransport.go
modules/caddyhttp/reverseproxy/reverseproxy.go

Related to some of the issues in https://github.com/caddyserver/caddy/issues/4245, a complaint about the proxy transport defaults not being properly documented in https://caddy.community/t/default-values-for-directives/14254/6.
- Dug into the stdlib to find the actual defaults for some of the timeouts and buffer limits, documenting them in godoc so the JSON docs get them next release.
- Moved the keep-alive and dial-timeout defaults from `reverseproxy.go` to `httptransport.go`. It doesn't make sense to set defaults in the proxy, because then any time the transport is configured with non-defaults, the keep-alive and dial-timeout defaults are lost!
- Sped up the dial timeout from 10s to 3s, in practice it rarely makes sense to wait a whole 10s for dialing. A shorter timeout helps a lot with …

reverseproxy: Adjust defaults, document defaults

---

caddyconfig/httpcaddyfile/options.go
caddyconfig/httpcaddyfile/tlsapp.go
caddytest/integration/caddyfile_adapt/global_options_acme.txt

This option is pretty useful for setups with more than 30k+ certificates. To understand more about the motivation, please see:
- [Caddy + dynamodb: background maintenance taking too long and creating read spikes on dynamodb](https://caddy.community/t/caddy-dynamodb-background-maintenance-taking-too-long-and-creating-read-spikes-on-dynamodb/14153)
- [Caddy server huge drop of requests](https://caddy.community/t/caddy-server-huge-drop-of-requests/14180)

caddyfile: make renew_interval option configurable

---

admin.go
caddyconfig/httpcaddyfile/builtins_test.go
caddytest/integration/caddyfile_adapt/global_options_log_custom.txt
caddytest/integration/caddyfile_adapt/log_filters.txt
modules/caddyhttp/marshalers.go

Closes #4396, related to #4148
This is a breaking change, but we're already planning on removing  the`common_log` field as well at the same time, so might as well all do it together.
In general, the remote IP is the useful part of the remote address. The port is rarely useful, because it only identifies ephemeral information about the connection from the client. But we were logging both in one field, so certain tooling that would want to only get the remote IP would need to split it up. Splitting is non-trivial, because of IPv4, IPv6, shenanigans. So it's best if we split it up-front before logging. If the log consumer actually cares about the remote port, it can re-assemble it.

caddyhttp: Split up logged remote address into IP and port

---

modules/caddyhttp/reverseproxy/fastcgi/fastcgi.go

Fixes a TODO in code, should be reasonably self-explanatory. Using `zap.Any()` would fallback to using reflection, which is slower and can allocate. I doubt this would have any kind of real-world performance impact, but 🤷‍♂️ easy fix.

fastcgi: Fix a TODO, prevent zap using reflection for logging env

---

caddyconfig/httpcaddyfile/serveroptions.go
caddytest/integration/caddyfile_adapt/global_server_options_single.txt
modules/caddyhttp/marshalers.go
modules/caddyhttp/push/handler.go
modules/caddyhttp/reverseproxy/reverseproxy.go
modules/caddyhttp/server.go

Followup to https://github.com/caddyserver/caddy/commit/7d5047c1f190421528695e1cc3a4ad71c97eb022, as discussed off-Github.
Adds an opt-in flag to `http.servers.logs` which informs the Loggables about whether they should log sensitive headers (default omitted).
Also puts the flag in the request context so that it can bubble down into request handlers which may also log headers (`reverseproxy` and `push` both log their headers).
I'm finding the name of the option kiiinda verbose, but it's a balancing act. 
/cc @dunglas

caddyhttp: Make logging of sensitive headers opt-in

---

caddytest/integration/caddyfile_adapt/log_filters.txt
modules/logging/filters.go
modules/logging/filters_test.go

Follows #4424, #4425 and #4426. Implements a hash filter and hash actions for the query and cookie filters ask suggested by @wiese in https://github.com/caddyserver/caddy/pull/4424#issuecomment-972650688.

logging: add support for hashing data

---

modules/caddyhttp/fileserver/staticfiles.go

https://caddyserver.com/docs/json/apps/http/servers/errors/routes/handle/file_server/#hide interprets the markdown and it's a tad hard to read
I did a quick grep and I couldn't see any other places where this happens (in this repo at least).

docs: use backticks to not italicise glob path

---

caddyconfig/caddyfile/adapter.go

Closes #4416 
This PR only modifies "caddy fmt" warning message. The former one may cause confusion, and this mod might save several hours for someone else.

improve fmt warning message

---

caddyconfig/httpcaddyfile/directives.go
caddyconfig/httpcaddyfile/httptype.go
caddytest/integration/caddyfile_adapt/sort_directives_within_handle.txt

Fixes a bug reported in https://caddy.community/t/handle-path-being-ignored-when-paired-with-handle-in-same-block/14393
We had some code in `ServerType.Setup()` that would ensure `handle_path` has the same sort level as `handle`, but we were missing the same check in `parseSegmentAsConfig` to make sure that works properly inside of any nested subroute (`handle`, `route`, `handle_errors`, `handle_response`).
To be clear, the fix is copy-paste from another spot where we do the same thing:
https://github.com/caddyserver/caddy/blob/78b5356f2b1945a90de1ef7f2c7669d82098edbd/caddyconfig/httpcaddyfile/httptype.go#L196-L202
The new test fails before the change (the `handle_path` ends up after the `handle` in the same level, and they're missing a `group` name because the group is omitted if there's …

httpcaddyfile: Fix sorting edgecase for nested `handle_path`

---

modules/caddypki/acmeserver/acmeserver.go
modules/caddypki/pki.go
modules/caddytls/internalissuer.go

Fixes #4461
Previously, we would provision the `local` CA no matter what, if the PKI app has a config. That doesn't really make sense in all cases.
Instead, we should provision it only if there's no other CA, and if either `tls internal` is configured (implicitly or otherwise), or the `acme_server` is configured with the default CA.
I think this should have slightly less surprising behaviour for users who want to configure their own CA with an ID that isn't `local`.

pki: Avoid provisioning the `local` CA when not necessary

---

caddytest/integration/caddyfile_adapt/matcher_syntax.txt
modules/caddyhttp/vars.go

Enable "or" logic for multiple values. Fall back to checking placeholders if not a var name.
Seemed useful, idk. :man_shrugging: 
This matcher is actually undocumented so far, since I wasn't sure if it'd have any purpose. But I think there might be value in matching on placeholders and variables for more advanced configurations.

caddyhttp: Enhance vars matcher

---

modules/caddyhttp/app.go
modules/caddyhttp/replacer.go

`http.request.uuid` placeholder enables you to trace and troubleshoot requests end‑to‑end. 
```caddyfile
reverse_proxy web:3000 {
header_up X-Request-Id {http.request.uuid}
}
```

caddyhttp: Implement `http.request.uuid` placeholder

---

caddytest/integration/caddyfile_adapt/reverse_proxy_health_headers.txt
modules/caddyhttp/reverseproxy/caddyfile.go

Fixes #4481
Basically `health_headers` would eat any config items that came after it because the nesting wasn't properly set up.
I just did a bare-minimum change to the tests (fails before).

reverseproxy: Fix incorrect `health_headers` Caddyfile parsing

---

modules/caddyhttp/matchers.go

This is a followup to #4407, in response to a report on the forums: https://caddy.community/t/php-fastcgi-phishing-redirection/14542
Turns out that doing `TrimRight` to remove trailing dots, _before_ cleaning the path, will cause double-dots at the end of the path to not be cleaned away as they should. We should instead remove the dots _after_ cleaning.

caddyhttp: Fix `MatchPath` sanitizing

---

caddytest/integration/caddyfile_adapt/header.txt
modules/caddyhttp/headers/caddyfile.go

See https://caddy.community/t/only-one-header-link-applied/14571
In a single `header` handler, using `+` with the same field name multiple times would only use the last value, instead of adding each value.
Super simple fix, just need to use `.Add()` instead of `.Set()` if we're using the `+` operator.

headers: Fix `+` in Caddyfile to properly append rather than set

---

caddytest/integration/caddyfile_adapt/log_roll_days.txt
modules/logging/filewriter.go

As requested in https://caddy.community/t/caddyfile-vs-json-config-roll-gzip/14564

logging: Support turning off roll compression via Caddyfile

---

caddy.go
modules/caddyhttp/reverseproxy/reverseproxy.go

See good explanation: https://www.arangodb.com/2020/09/a-story-of-a-memory-leak-in-go-how-to-properly-use-time-after/

reverseproxy, admin: memory leak fix

---

modules/caddyhttp/app.go
modules/caddyhttp/httpredirectlistener.go

This is very much not done yet, but I just wanted to show the proof of concept.
---
Background: in certain cases, users would like HTTP->HTTPS redirects in situations where they only actually serve HTTPS on one port; if an HTTP request is made to that port, Caddy currently responds with `Client sent an HTTP request to an HTTPS server.` This response comes directly from Go's stdlib (added in https://go-review.googlesource.com/c/go/+/143177/, see https://github.com/golang/go/issues/23689#issuecomment-362936254 for context):
https://github.com/golang/go/blob/56c3856d529d72e280ad6b185f7927657de86c37/src/net/http/server.go#L1817-1825
While it could be argued that HTTP responses should never be sent on the HTTPS port... Go already does it.
This is alright, but Caddy _could_ go a step further …

caddyhttp: Redirect HTTP requests on the HTTPS port to https://

---

caddyconfig/httpcaddyfile/pkiapp.go
caddytest/integration/caddyfile_adapt/global_options_skip_install_trust.txt

Fixes #4435
Pretty self explanatory, allows configuring the PKI app name and root/intermediate common names. Works alongside the existing `acme_server` directive and `skip_install_trust` options. We could deprecate the top-level `skip_install_trust` in favor of configuring it via the default `pki` app, but 🤷‍♂️ I need no reason to do that right now. This works fine.

httpcaddyfile: Support configuring `pki` app names via global options

---

modules/caddyhttp/server.go

Made change to return status code 421 instead of 403 when StrictSNIHost matching is on.
This is related to:
https://github.com/caddyserver/caddy/issues/4017
I'm not suggesting this is the complete fix.  I just know it fixes a critical issue with Chrome (and presumable Firefox).

Fix to HTTP/2.- and Chrome coalescing issue

---

modules/caddyhttp/rewrite/rewrite.go
modules/caddyhttp/rewrite/rewrite_test.go

Fix https://github.com/caddyserver/caddy/issues/4515

rewrite: Fix a double-encode issue when using the `{uri}` placeholder

---

caddyconfig/httpcaddyfile/addresses.go
caddytest/integration/caddyfile_adapt/bind_ipv6.txt

The `net.JoinHostPort()` function has some naive logic for handling IPv6, it just checks if the host part has a `:` and if so it wraps the host part with `[ ]` but this causes our network type prefix to get wrapped as well, which is invalid for `caddy.NetworkAddress`. Instead, we can just concatenate the host and port manually here to avoid this side-effect.

httpcaddyfile: Fix incorrect handling of IPv6 bind addresses

---

caddyconfig/httpcaddyfile/addresses.go
caddyconfig/httpcaddyfile/options.go
caddytest/integration/caddyfile_adapt/global_options_default_bind.txt

Address some feedback in #4508, /cc @phrazer
This is pretty self explanatory, simple addition.

httpcaddyfile: Add `default_bind` global option

---

modules/caddyhttp/autohttps.go

Fix #4529 
I think it doesn't make sense to append to this slice if we actually want to prefer one port over the other. We don't need to keep a redirect for more than one port at all, I think, because we have no way to distinguish which port is the right target otherwise, when requests come in on the HTTP port.
I think the comment here was correct, but the behaviour was wrong.
This should fix it, by always preferring the HTTPS port -- if `443` is seen first then it will set it (because no value is set), then it will ignore any subsequent cause they aren't the HTTPS port. If something else comes first, and `443` follows, then it will overwrite it.

caddyhttp: Fix HTTP->HTTPS redir not preferring HTTPS port if ambiguous

---

caddyconfig/httpcaddyfile/directives.go
caddytest/integration/caddyfile_adapt/method_directive.txt
modules/caddyhttp/rewrite/caddyfile.go

Fixes #4523
Pretty simple. The order of this directive is up for debate though. Just went with what feels intuitive to me, but it's hard to say for sure how this will be used in combination with other directives.

rewrite: Add `method` Caddyfile directive

---

caddyconfig/httpcaddyfile/pkiapp.go
caddytest/integration/caddyfile_adapt/global_options_skip_install_trust.txt

Followup to #4450, I was being lazy. Adds the cert/key config.

httpcaddyfile: Add pki app `root` and `intermediate` cert/key config

---

caddytest/integration/caddyfile_adapt/tls_internal_options.txt
modules/caddytls/internalissuer.go

Options missing from Caddyfile which are configurable in JSON.
While these options are strongly recommended to not change, better to have the Caddyfile have them then not.

caddytls: Add internal Caddyfile `lifetime`, `sign_with_root` opts

---

listeners.go

previous PR: https://github.com/caddyserver/caddy/pull/4533
here is a simple demo of the error being caught and the error message being displayed: https://go.dev/play/p/ehz0pTPjMwZ

explain cryptic unix socket listener error related to process kill

---

modules/caddyhttp/templates/tplcontext_test.go

The TestFileListing test in tplcontext_test has one test that verifies
if directory traversal is not happening. The context root is set to
'/tmp' and then it tries to open '../../../../../etc', which gets
normalized to '/tmp/etc'.
The test then expects an error to be returned, assuming that '/tmp/etc'
does not exist on the system. When it does exist, it results in a test
failure:
```
--- FAIL: TestFileListing (0.00s)
tplcontext_test.go:422: Test 4: Expected error but had none
FAIL
FAIL
github.com/caddyserver/caddy/v2/modules/caddyhttp/templates	0.042s
```
Instead of using '/tmp' as root, use a dedicated directory created with
`os.MkdirTemp()` instead. That way, we know that the directory is empty.

caddyhttp: Fix test when /tmp/etc already exists

---

internal/metrics/metrics.go
internal/metrics/metrics_test.go
metrics.go
modules/caddyhttp/metrics.go
modules/caddyhttp/metrics_test.go

Protects against unbounded cardinality on the method label.
Note: I'm finding myself copying code again between the two metrics endpoints - how do we feel about `internal/`? I ask because there's no use of it yet... Otherwise I think I'd rather throw the common code in an `internal/metrics` package or something like that...

metrics: Enforce smaller set of method labels

---

modules/caddyhttp/reverseproxy/httptransport.go

Fix https://github.com/caddyserver/caddy/issues/4509

reverseproxy: Avoid returning a `nil` error during GetClientCertificate

---

admin.go

admin: Stop writing 500 status on invalid requests

---

caddyconfig/httpcaddyfile/tlsapp.go
caddytest/integration/caddyfile_adapt/global_options.txt

Fix #4588 
The global option was only turning off OCSP stapling for managed certs, but not unmanaged certs, since that was controlled by an option on the TLS app itself instead of inside of an automation policy.

httpcaddyfile: Disabling OCSP stapling for both managed and unmanaged

---

go.mod
go.sum

Workaround for #4331, for now
Unfortunately, bumping CEL will cause _all_ Caddy plugins to no longer build with the latest version of Caddy, if they have an earlier version of Caddy in their `go.mod`.
I don't know what our long-term solution will be, so this will require more research before we can safely bump CEL to a newer version.

go.mod: Revert version bump of CEL

---

modules/caddyhttp/server.go

Context: https://caddy.community/t/optional-reverse-proxy-with-file-system-fallback/15105
There are some situations where error handling is used to intercept 5xx errors emitted by Caddy, like from `reverse_proxy`, and those errors would still be logged at the ERROR level.
This could get noisy when this is being done "on-purpose". For example, a proxy being turned off half the time and only used as an optimization during development (for hot-module reload or something).
So instead, it probably makes more sense to always log _handled_ errors at DEBUG level, since it was actually handled. If the error falls through unhandled, or a new error is triggered, then it'll still log at ERROR level.

caddyhttp: Always log handled errors at debug level

---

caddytest/integration/caddyfile_adapt/log_roll_days.txt
modules/logging/filewriter.go

Tiny fix, something that was forgotten

logging: Add `roll_local_time` Caddyfile option

---

.goreleaser.yml

The earlier build script copied the `go.mod` of caddy, which caused quite few issues because `go mod` gets confused. Removing this step and opting to only `init`-ing the go module then requiring caddy with the appropriate version should avoid any complications.
While editing the file, it seems goreleaser have added a reference scheme for the `.goreleaser.yml` file. I've fixed the warnings along the way.

ci: update goreleaser

---

caddytest/integration/caddyfile_adapt/global_server_options_single.txt
modules/caddyhttp/app.go
modules/caddyhttp/httpredirectlistener.go

Followup to https://github.com/caddyserver/caddy/pull/4313
Turns out we have some issues with this being turned on by default, so we'll have to provide it as an optional module for now.
To turn it on, this needs to be added in global options:
```
{
servers {
listener_wrappers {
http_redirect
tls
}
}
}
```

caddyhttp: Move HTTP redirect listener to an optional module

---

caddytest/integration/caddyfile_adapt/reverse_proxy_handle_response.txt
modules/caddyhttp/reverseproxy/caddyfile.go

I was doing some thinking in https://github.com/caddyserver/caddy/issues/4298#issuecomment-903219435 and I think the UX of `handle_response` is super awkward in that it was doing two different things in one subdirective.
Semantically, it's expected that the `handle` family of options imply that subroutes will be defined (as per `handle` and `handle_path` directives).
Separating the status code replacement usecase into its own Caddyfile subdirective (even if it doesn't match the JSON 1:1) is easier to understand.
This is a breaking change, so we could defer this to v2.5.0, but I don't think many people use this yet so the impact should be very low. I haven't seen anyone on the forums asking questions using this feature yet since we released it in v2.4.0.

reverseproxy: Move status replacement intercept to `replace_status`

---

modules/caddyhttp/fileserver/browse.go

Fix https://github.com/caddyserver/caddy/issues/4466
See the issue for repro details.
Of note, `path.Base(r.URL.Path)` when the path is `""` returns `.`, so the base comparison check which will never be true when the path has been stripped fully.

fileserver: Fix canonicalization redir when within `handle_path`

---

caddyconfig/httpcaddyfile/serveroptions.go
caddytest/integration/caddyfile_adapt/global_server_options_multi.txt

In the Caddyfile, we were only allowing turning on `strict_sni_host` explicitly, but provided no way to explicitly turn it off, which may be necessary for situations where it gets turned on implicitly like when TLS client_auth is turned on.
This adds support for a first arg to be `on` (for symmetry, least surprise) or `insecure_off` (what's actually new in terms of behaviour). If the arg is omitted, then it's the same behaviour as before, i.e. turning it on.
```
{
servers {
protocol {
strict_sni_host [on|insecure_off]
}
}
}
```

httpcaddyfile: Support explicitly turning off `strict_sni_host`

---

admin.go
caddy.go
cmd/commandfuncs.go
cmd/commands.go
cmd/main.go
context.go
modules/caddypki/adminpki.go
modules/caddypki/command.go
modules/caddypki/pki.go

Fixes https://github.com/caddyserver/caddy/issues/4058, once this is completed. This is basically half-way to solving the linked issue.
This implements a new admin API, `GET /pki/certificates/<id>`, which returns information about the given PKI app's CA, by ID. 
For example, this is what a response might look like, for requesting info about the `local` CA (the default CA ID):
```bash
$ curl localhost:2019/pki/certificates/local
```
```json
{
"id": "local",
"name": "Caddy Local Authority",
"root": "-----BEGIN CERTIFICATE-----\nMIIBpDCCAUmgAwIBAgIQTS5a+3LUKNxC6qN3ZDR8bDAKBggqhkjOPQQDAjAwMS4w\nLAYDVQQDEyVDYWRkeSBMb2NhbCBBdXRob3JpdHkgLSAyMDIxIEVDQyBSb290MB4X\nDTIxMTEyNTA1NDIxMloXDTMxMTAwNDA1NDIxMlowMDEuMCwGA1UEAxMlQ2FkZHkg\nTG9jYWwgQXV0aG9yaXR5IC0gMjAyMSBFQ0MgUm9vdDBZMBMGByqGSM49AgEGCCqG\nSM49 …
```

pki: Implement `GET /pki/certificates/<id>` API, rework `caddy trust`

---

modules/caddyhttp/reverseproxy/fastcgi/fastcgi.go

as [tools.ietf.org/html/rfc3875#section-4.1.15](https://tools.ietf.org/html/rfc3875#section-4.1.15)
```
4.1.15.  SERVER_PORT
The SERVER_PORT variable MUST be set to the TCP/IP port number on
which this request is received from the client.  This value is used
in the port part of the Script-URI.
SERVER_PORT = server-port
server-port = 1*digit
Note that this variable MUST be set, even if the port is the default
port for the scheme and could otherwise be omitted from a URI.
```
related problem caused by this:  when works with xdebug , "Cannot accept external Xdebug connection: Cannot evaluate expression '$_SERVER['SERVER_PORT']'"

fastcgi: ensure `SERVER_PORT` is always set

---

modules/caddyhttp/reverseproxy/reverseproxy.go

Alternate fix for #4457, to potentially be merged instead of #4468.
As suggested in #4468, this could potentially kill two birds with one stone, fixing messy header handling (holding onto the original headers from the request and having to reset it before the response response is being written) and removing a potential data race from manipulating the incoming request.
Basically I copied the code from `http.Request.Clone()` except for the bits that touch `r.ctx` (we want to keep the same context for our shallow clone), the `r.Form` stuff (multiple fields), and `r.TransferEncoding` (I don't think this one matters?) since those are won't be modified during proxying, and we don't need the copy overhead.
I haven't tested this out any further than to confirm it does fix the bug reported in …

reverseproxy: Make shallow-ish clone of the request

---

caddytest/integration/caddyfile_adapt/file_server_pass_thru.txt
modules/caddyhttp/fileserver/caddyfile.go

https://caddy.community/t/serve-available-static-content-and-proxy-otherwise/15289/4
I guess it was just forgotten 🤷‍♂️

fileserver: Add `pass_thru` Caddyfile option

---

caddyconfig/caddyfile/dispenser.go
modules/caddyhttp/reverseproxy/addresses.go
modules/caddyhttp/reverseproxy/caddyfile.go
modules/caddyhttp/reverseproxy/command.go

Fix #4611
Quick refactor to split out the dial address parsing from the Caddyfile code to make it usable for the `reverse-proxy` command as well.
Also added a new helper method in the Dispenser because it's slightly cleaner when you already have an error from lower level parsing code that you want to throw as a parsing error.

reverseproxy: Refactor dial address parsing, augment command parsing

---

caddytest/integration/caddyfile_adapt/reverse_proxy_dynamic_upstreams.txt
caddytest/integration/caddyfile_adapt/reverse_proxy_options.txt
modules/caddyhttp/reverseproxy/admin.go
modules/caddyhttp/reverseproxy/caddyfile.go
modules/caddyhttp/reverseproxy/healthchecks.go
modules/caddyhttp/reverseproxy/hosts.go
modules/caddyhttp/reverseproxy/httptransport.go
modules/caddyhttp/reverseproxy/reverseproxy.go
modules/caddyhttp/reverseproxy/selectionpolicies_test.go
modules/caddyhttp/reverseproxy/upstreams.go

Right now, proxy upstreams have to be hard-coded into the config (with the only dyanamism coming from placeholders, which all act as a single upstream anyway). This change adds supports for truly dynamic upstreams, with the potential for every request to have different upstreams -- not only every request, but every _retry_ within a single request, too.
Instead of (or in addition to) specifying `upstreams` in your config, you could specify `dynamic_upstreams` and then define your upstream source module. Currently I'm implementing SRV and A/AAAA lookups as sources.
Fixes or related to:
- #1545 (currently the oldest open issue)
- #4174
- A currently-private sponsor's request. Hope to reveal this later!
When we're done, it will hopefully close or supercede #4350, #3801, #4446, and #4245. …

reverseproxy: Dynamic upstreams (with support for SRV and A/AAAA lookups)

---

modules/caddyhttp/reverseproxy/fastcgi/fastcgi.go

Followup to #4574, credit to @MisterDuval for reporting the issue and finding a reproduce case.

fastcgi: Protect against requests with null bytes in the path

---

caddyconfig/httpcaddyfile/builtins.go
go.mod
go.sum
modules/caddytls/acmeissuer.go
modules/caddytls/automation.go

CNAME can be used to delegate answering the chanllenge to another DNS
zone. One usage is to reduce the exposure of the DNS credential [1].
Based on the discussion in caddy/certmagic#160, we are adding an option
to allow the user explicitly specify the domain to delegate, instead of
following the CNAME chain.
This needs caddy/certmagic#160.

Add a override_domain option to allow DNS challenge delegation

---

modules/caddyhttp/vars.go

caddyhttp: retain all values of vars matcher when specified multiple times

---

caddyconfig/caddyfile/dispenser.go
caddyconfig/caddyfile/lexer.go
caddytest/integration/caddyfile_adapt/expression_quotes.txt
caddytest/integration/caddyfile_adapt/map_with_raw_types.txt
modules/caddyhttp/celmatcher.go
modules/caddyhttp/map/caddyfile.go

Followup to https://github.com/caddyserver/caddy/commit/93c99f67342504efe9f6b58a734aaec3929fe785 as pointed out in https://github.com/caddyserver/website/issues/221, and fixing the issue mentioned in https://github.com/caddyserver/website/issues/220
See the adapt tests, which cover how it behaves.
Note: This _is_ a breaking change, because people using `map` with numbers used to get strings, and will now get numbers.

caddyfile: Support for raw token values, improve `map`, `expression`

---

caddyconfig/caddyfile/dispenser.go
caddyconfig/caddyfile/parse.go
caddyconfig/caddyfile/parse_test.go

Fix #4501
Basically, we want to prevent two cases where bad block openings can happen.
```
localhost
reverse_proxy { to abc:123 }
```
☝️ this one used to result in the upstreams list containing `}` (the last token on the line) because since no newline happens, `to` reads all the remaining tokens on the same line, consuming both `abc:123` and `}`, but never closing the block.
This bug is being fixed by checking if after we see a `{` token, whether the next token is on a new line; if not, err. This could break "legitimate" situations where some hypothetical `expression`-like directive wants to consume all the tokens on the line where `{` is some syntactical token of that "language", but I think this is unlikely, and can be worked around by quoting the tokens like `"{"` and `"}"` (or with …

caddyfile: Prevent bad block opening tokens

---

caddyconfig/httpcaddyfile/directives.go
caddyconfig/httpcaddyfile/httptype.go
caddyconfig/httpcaddyfile/tlsapp.go
caddytest/integration/caddyfile_adapt/tls_automation_policies_9.txt

Guh, this is complicated.
Fixes #4640
This also follows up on #4398 (reverting it) which made a change that technically worked, but was incorrect. It changed the condition in `hostsFromKeysNotHTTP` from `&&` to `||`, but then the function no longer did what its name said it would do, and it would return hosts even if they were marked with `http://`, if they used a non-HTTP port. That wasn't the intent of it. The test added in there was kept though, because it is a valid usecase.
The actual fix is to check _earlier_ whether all the addresses explicitly have `http://`, and if so we can short circuit and skip considering the rest.

httpcaddyfile: Fix Auto-HTTPS edgecase

---

cmd/commandfuncs.go

Just a silly oops. Followup to #4443
I broke `caddy reload` when the admin address is not explicitly set in the config 😬 it would take the empty admin address if a `--config` is specified at all, and never fall through to use the default.
https://caddy.community/t/caddy-reload-failing/15556

cmd: Fix defaulting admin address if empty in config, fixes `reload`

---

modules/logging/encoders.go

Somehow, this was missed. Oops!

logging: Caddyfile support for `duration_format`

---

caddytest/integration/caddyfile_test.go
modules/caddyhttp/fileserver/staticfiles.go

Fix #4671 
Basically I added replaceAll for indexPage.

Replace placeholder for file_server index

---

modules/caddyhttp/reverseproxy/ascii.go
modules/caddyhttp/reverseproxy/ascii_test.go
modules/caddyhttp/reverseproxy/streaming.go

I had left this as a TODO for when we bump to minimum 1.17, but I should've realized it was under `internal` so it couldn't be used directly.
Copied the functions we needed for parity. Hopefully this is ok!

reverseproxy: Sync up `handleUpgradeResponse` with stdlib

---

modules/caddyhttp/app.go
modules/caddyhttp/replacer.go
modules/caddyhttp/reverseproxy/reverseproxy.go
modules/caddyhttp/server.go

Requested in https://caddy.community/t/http-timing-placeholders-are-strings-float-desired/15515

reverseproxy: Add `_ms` placeholders for proxy durations

---

cmd/commandfuncs.go
cmd/commands.go

Just thought this might be fun to have.
When using no options or using `--overwrite`, it can be difficult to find out what was _actually_ "wrong" according to the formatter.
Example output where a couple of the lines had spaces instead of tabs:
```
:80 {
root * /srv
file_server
handle_errors {
-       @404 {
-           expression {http.error.status_code} == 404
+ 		@404 {
+ 			expression {http.error.status_code} == 404
}
rewrite @404 /not-found.txt
}
}
```

cmd: Add `--diff` option for `caddy fmt`

---

go.mod
go.sum
modules/caddypki/ca.go

Fixes #4517
Big thanks to @maraino for adding an API in `smallstep/certificates` so that we can fix this

caddypki: Load intermediate for signing on-the-fly

---

.github/workflows/ci.yml
.github/workflows/cross-build.yml
.github/workflows/lint.yml
.github/workflows/release.yml

- Go `1.18.1` isn't being pulled by https://github.com/actions/setup-go right now because the versions are pulled from https://github.com/actions/go-versions and it hasn't been updated with it yet
- We were incidentally using `1.17` and `1.18` as our semver strings previously; if we change the matrix to use an actual semver like `~1.18.1` then it actually renames the job itself, which breaks the "required job" thing in github
- Mac 1.18.1 isn't out yet because of "an issue" https://github.com/golang/go/issues/52317 so I need to implement a hack for that too
- So to keep the same labels, but customize the semver string, I'm using an `include` to write to a `GO_SEMVER` variable for it, and using that as the `setup-go` version; the rest uses the short version name from the matrix.

ci: Ensure we always check for latest version of Go

---

.github/workflows/ci.yml

An upstream issue prevented #4703 from using go1.18.1 on macOS. The issue was resolved.

ci: use latest Go version on macOS

---

caddytest/integration/caddyfile_adapt/tls_propagation_timeout.txt
go.mod
go.sum
modules/caddytls/acmeissuer.go
modules/caddytls/automation.go

This has been a thorn for plenty of users in situations where their configured DNS resolvers can't actually see the TXT records Caddy ends up writing, so DNS challenges fail for them.
This makes it possible to turn off propagation, but also adds a new initial delay which can be used as a replacement for for "giving the the DNS provider some time to get their things sorted".
For example, to turn of propagation checks, but still wait 30 seconds before continuing:
```
tls {
issuer acme {
propagation_delay 30s
propagation_timeout -1
}
}
```

caddytls: Add `propagation_delay`, support `propagation_timeout -1`

---

caddyconfig/caddyfile/parse.go
caddyconfig/httpcaddyfile/httptype.go
cmd/commandfuncs.go
modules/caddyhttp/fileserver/command.go
modules/caddyhttp/reverseproxy/caddyfile.go

In the Caddyfile, [site addresses](https://caddyserver.com/docs/caddyfile/concepts#addresses) have historically supported paths. This was essentially a carry-over from Caddy v1. The idea is that you could write your sites with a path which would get turned into a subroute with that path as a matcher, and sites with the same domain would get grouped up together:
```
example.com/first* {
respond "first"
}
example.com/second* {
respond "second"
}
example.com {
respond "anything else"
}
```
This is kinda fun, it can read nicely if your config is relatively simple. But, keeping this feature has many problems, both from a config UX standpoint and from a code complexity standpoint:
- Since the site address _looks_ like a proper URL, users may be tempted to write their site address like …

httpcaddyfile: Deprecate paths in site addresses; use zap everywhere

---

caddyconfig/httpcaddyfile/directives.go
caddyconfig/httpcaddyfile/httptype.go
caddytest/integration/caddyfile_adapt/sort_vars_in_reverse.txt

I'm yoinking the placeholder from my https://github.com/caddyserver/caddy/pull/4657 PR because I think we should get this in ASAP for v2.5.0 along with the new `vars` directive.
Also, during testing while writing the docs, I realized we should reverse the `vars` directive sort order based on matchers; since this is a directive which overwrites existing values set by other previously run directives, we actually want the least-specific matcher to run first, and most-specific last, so that the most-specific is the last one to overwrites the value.
For example, with this config:
```
vars foo bar
vars /path* foo baz
respond {vars.foo}
```
Before this change, all requests would return `bar`, because the least specific matcher would run last, overwriting any more specific matcher. After the …

httpcaddyfile: Add `{vars.*}` placeholder shortcut, reverse `vars` sort order

---

modules/caddypki/command.go

caddypki: Fix `caddy trust` command to use the correct API endpoint

---

modules/caddyhttp/reverseproxy/selectionpolicies.go
modules/caddyhttp/reverseproxy/selectionpolicies_test.go

Previously, if a list of upstreams changed, hash-based LB policies
would be greatly affected because the hash relied on the position of
upstreams in the pool. Highest Random Weight or "rendezvous" hashing
is apparently robust to pool changes. It runs in O(n) instead of
O(log n), but n is very small usually.
- https://en.wikipedia.org/wiki/Rendezvous_hashing
- https://randorithms.com/2020/12/26/rendezvous-hashing.html
- https://medium.com/i0exception/rendezvous-hashing-8c00e2fb58b0 (:arrow_backward: what I used as a starting point)
This algorithm is very simple and makes sense to me. Hopefully I implemented this correctly! :)
/cc @jjiang-stripe and @cds2-stripe

reverseproxy: Improve hashing LB policies with HRW

---

modules/caddyhttp/templates/templates.go

As stated in #4736, the documentation is missing backticks that causes it to render incorrectly.

Add missing backticks

---

modules/caddyhttp/autohttps.go

Fixes an unclear message as per https://github.com/caddyserver/caddy/issues/4738
Old message:
```
validate: loading http app module: provision http: srv0: invalid listener address: :0
```
New message:
```
validate: loading http app module: provision http: srv0: invalid listener address: ::1:443, there are too many colons, so the port is ambiguous. Did you mean to wrap the IPv6 address with [] brackets?
```
Part of the issue is we were reusing the same variable before/after parsing, so `addr` would get clobbered with the empty `NetworkAddress` value, rendering it as `:0`. Not useful. I split up the variable name to fix that, and added a condition for when there's too many colons (kinda naive cause it doesn't look at whether `[]` was already there but whatever) to suggest a fix.

caddyhttp: Improve listen addr error message for IPv6

---

cmd/commandfuncs.go

Fixes a regression in https://github.com/caddyserver/caddy/commit/c2327161f725c820826587381f37d651a2b9736d
Reported in https://caddy.community/t/using-ip-mask-filter-with-2-5-actually-an-init-script-issue/15786

cmd: Fix unix socket addresses for admin API requests

---

.gitignore
logging.go

Fixes #4688
Before:
```
$ caddy trust --address localhost:2021 --ca local
2022/04/27 02:21:33.454 WARN    installing root certificate (you might be prompted for password)        {"path": "localhost:2021/pki/ca/local"}
2022/04/26 22:21:33 Note: NSS support is not available on your platform
2022/04/26 22:21:33 define JAVA_HOME environment variable to use the Java trust
2022/04/26 22:21:34 certificate installed properly in windows trusts
```
After:
```
$ caddy trust --address localhost:2021 --ca local
2022/04/27 02:39:49.365 WARN    installing root certificate (you might be prompted for password)        {"path": "localhost:2021/pki/ca/local"}
2022/04/27 02:39:49.367 INFO    Note: NSS support is not available on your platform
2022/04/27 02:39:49.367 INFO    define JAVA_HOME environment …
```

logging: Use `RedirectStdLog`

---

caddyconfig/httpcaddyfile/httptype.go
caddytest/integration/caddyfile_adapt/global_options_debug_with_access_log.txt

When access logging is turned on with the `log` directive, and the `debug` global option is used, the `default` logger would not correctly get the `"exclude": ["http.log.access.log0"]` attached to it; so you end up with the access log written twice, unintentionally.
The added adapt test fails before this change, i.e. `exclude` is missing from `default`.

httpcaddyfile: Fix duplicate access log when debug is on

---

caddytest/integration/caddyfile_adapt/reverse_proxy_handle_response.txt
modules/caddyhttp/reverseproxy/caddyfile.go

As per https://caddy.community/t/small-problem-with-basicauth-and-handle-error/15708, apparently I made the Caddyfile parsing a bit too strict, which prevented legitimate uses of `replace_status`.
Notably, it wasn't allowing no matcher (I thought there was no usecase, but turns out there is 😅) and it was parsing the `int` up-front instead of allowing strings for placeholders.

reverseproxy: Fix Caddyfile support for `replace_status`

---

modules/caddyhttp/templates/templates.go
modules/caddyhttp/templates/tplcontext.go

Fixes #4568
This allows plugins to add functions to the template execution engine. Such plugin modules must be placed under `http.handlers.templates.functions.*`, e.g. `http.handlers.templates.functions.foo`. The interface `templates.CustomFunctions` must be implemented by the plugin module in order to provide those functions.

templates: Add custom template function registration

---

modules/caddyhttp/reverseproxy/upstreams.go

Context: https://caddy.community/t/caddy-2-5-dynamic-upstreams-and-consul-srv-dns/15839
I realized it probably makes sense to allow `:53` to be omitted, since it's the default port for DNS.

reverseproxy: Permit resolver addresses to not specify a port

---

caddytest/integration/caddyfile_adapt/matcher_syntax.txt
modules/caddyhttp/matchers.go

When I implemented trust for proxy headers in https://github.com/caddyserver/caddy/pull/4507, I added this shortcut, since it's a really common usecase to want to list out all private IP ranges. I figured I should port this to the `remote_ip` matcher for the Caddyfile as well.  
This adds a new `private_ranges` option. I'm not doing anything fancy to remove duplicates or whatever, this is just a simple value which expands out to multiple range entries.
It's a nice win, makes config a lot shorter and less arcane to read. Compare:
```
@deny-public not remote_ip 192.168.0.0/16 172.16.0.0/12 10.0.0.0/8 127.0.0.1/8 fd00::/8 ::1
abort @deny-public
```
With the shortcut:
```
@deny-public not remote_ip private_ranges
abort @deny-public
```
Much nicer!

caddyfile: Shortcut for `remote_ip` for private IP ranges

---

caddyconfig/httpcaddyfile/builtins.go
caddyconfig/httpcaddyfile/builtins_test.go
caddyconfig/httpcaddyfile/directives.go
caddyconfig/httpcaddyfile/httptype.go
caddytest/integration/caddyfile_adapt/forward_auth_authelia.txt
caddytest/integration/caddyfile_adapt/reverse_proxy_options.txt
modules/caddyhttp/reverseproxy/caddyfile.go
modules/caddyhttp/reverseproxy/fastcgi/caddyfile.go
modules/caddyhttp/reverseproxy/forwardauth/caddyfile.go
modules/caddyhttp/reverseproxy/reverseproxy.go
modules/caddyhttp/rewrite/rewrite.go
modules/caddyhttp/rewrite/rewrite_test.go
modules/caddyhttp/standard/imports.go

So, this is _super cool_. We were just missing two small pieces plus a bug fix to make this pattern possible.
Recently, we found out that there's demand for integrating Caddy with Authelia https://github.com/authelia/authelia/issues/1241, so that Authelia can be used for acting as an auth gateway for apps served by Caddy. The way it's typically done with other proxies is with a built-in feature called [ForwardAuth in Traefik](https://doc.traefik.io/traefik/middlewares/http/forwardauth/) and [auth_request in Nginx](https://nginx.org/en/docs/http/ngx_http_auth_request_module.html). TL;DR, an HTTP request is made to Authelia, and Authelia either responds with a `200` if the request authorized :+1: or with a `401` or redirect if auth is required :-1:
So that got me thinking, `reverse_proxy` …

reverseproxy: Support performing pre-check requests

---

caddyconfig/httpcaddyfile/httptype.go
modules/caddyhttp/map/caddyfile.go

Essentially, this tries to prevent configs like this:
```
example.com {
map {host} {path} {
example.com /example
}
}
```
Where the output `{path}` is no good, because it's one of the [placeholder shorthands](https://caddyserver.com/docs/caddyfile/concepts#placeholders). This means that the map destination would actually clobber an existing replacer output, and produce unexpected behaviour.
The implementation is kiiinda tricky though.
Since shorthand replacement happens _before_ directive parsing (this surprised me when I was working on this, but "duh" I should've realized sooner), the `map`'s Caddyfile parser _actually_ sees `{http.request.uri.path}` instead of `{path}`; this means that we need to actually look for the _replacements_ and map them back to the shorthand (for the error …

map: Prevent output destinations overlap with Caddyfile shorthands

---

caddyconfig/httpcaddyfile/addresses.go
caddyconfig/httpcaddyfile/options.go
caddytest/integration/caddyfile_adapt/global_options_default_bind.txt

httpcaddyfile: Support multiple values for `default_bind`

---

modules/caddyhttp/reverseproxy/httptransport.go

Not sure if this is right, but exploring the solution for #4777. Maybe this is good, I dunno yet.
Should close #4777

reverseproxy: Support http1.1>h2c

---

caddyconfig/httpcaddyfile/httptype.go

Before:
```
handle_errors {
respond "{http.error.status_code} {http.error.status_text}"
}
```
After:
```
handle_errors {
respond "{err.status_code} {err.status_text}"
}
```
Nice little win for the common pattern of [error handling](https://caddyserver.com/docs/caddyfile/directives/handle_errors) :blush:

httpcaddyfile: Add `{err.*}` placeholder shortcut

---

.github/workflows/ci.yml
.github/workflows/cross-build.yml
.github/workflows/release.yml

I was getting tired of Windows being slow as molasses in our CI jobs, so I went to look at our trusty source of github actions + golang information, and found a somewhat recent commit that actually fixed it. See https://github.com/mvdan/github-actions-golang/commit/4b754729baa709da219a5889c459010d4eda1888
I'll do a 2nd empty commit to re-trigger CI shortly to confirm that it actually fixes it.

ci: Fix build caching on Windows

---

modules/caddyhttp/reverseproxy/command.go

added flag `--internal-certs`
when set, for non-local domains the internal CA will be used for cert generation
Closes https://github.com/caddyserver/caddy/issues/3589

reverseproxy: Add `--internal-certs` CLI flag

---

caddytest/integration/caddyfile_adapt/forward_auth_rename_headers.txt
modules/caddyhttp/reverseproxy/forwardauth/caddyfile.go

This twitter thread https://twitter.com/coldmacchiato_/status/1524683154237407232 made me realize there were some shortcomings to `copy_headers`; it wasn't possible to rename response headers when copied to the request, and if the header names are long, it can get unwieldy to have it all on one line.
So to fix this, I'm adding a `>` syntax where if a token has a `>`, the left side is the response header name, and the right side is the "destination" request header name.
```
copy_headers {
Tailscale-User>X-Webauth-User
Tailscale-Name>X-Webauth-Name
Tailscale-Login>X-Webauth-Login
Tailscale-Tailnet>X-Webauth-Tailnet
Tailscale-Profile-Picture>X-Webauth-Profile-Picture
}
```

forwardauth: Support renaming copied headers, block support

---

caddyconfig/load.go

Implements the feature requested by @adamburgess in #4465, an `/adapt` API endpoint for retrieving JSON config programmatically, without having to shell out to `caddy adapt` or POST an actual config to `/load` and then use a GET to retrieve it.
```bash
$ curl -v "http://localhost:2019/adapt" -H "Content-Type: text/caddyfile" --data-binary ':80 {
respond "Hello world!"
}' | jq
*   Trying 127.0.0.1:2019...
* Connected to localhost (127.0.0.1) port 2019 (#0)
> POST /adapt HTTP/1.1
> Host: localhost:2019
> User-Agent: curl/7.81.0
> Accept: */*
> Content-Type: text/caddyfile
> Content-Length: 30
> 
* Mark bundle as not supporting multiuse
< HTTP/1.1 200 OK
< Content-Type: application/json
< Date: Mon, 20 Jun 2022 16:47:44 GMT
< Content-Length: 285
< 
{
"warnings": [
{
"file": "Caddyfile", …
```

admin: Implement /adapt endpoint (close #4465)

---

modules/caddytls/acmeissuer.go
modules/caddytls/tls.go
modules/caddytls/zerosslissuer.go

This enables EAB reuse for ZeroSSLIssuer (which is now supported by ZeroSSL).
Calling `NewACMEIssuer()` destroys any state mutations in `PreCheck()` (or any of the other Issuer methods), which would also lose the email found by PreCheck's `getEmail()` call (in CertMagic; now called `setEmail`).
I ran this with the race detector, and it passed, so :man_shrugging:
I still wish the Config-Issuer dependency wasn't cyclical; not sure a better way to handle that right now. I tried adding the Config to the `ctx` which almost worked, except the `HandleHTTPChallenge` part doesn't have access to that context (darn). Back to the drawing board, I guess, if I want to make this more elegant than the whole `SetConfig()` dance...

caddytls: Reuse issuer between PreCheck and Issue

---

caddytest/integration/caddyfile_adapt/reverse_proxy_options.txt
modules/caddyhttp/reverseproxy/caddyfile.go

We recently merged PRs https://github.com/caddyserver/caddy/pull/4784 and https://github.com/caddyserver/caddy/pull/4843 to add `renegotiation` and `except_ports`. Both of these are actually options inside of the `TLS` struct, so they should be prefixed with `tls_` for the Caddyfile config.
I also just moved around the cases in the switch to better align with the documentation and order of the options.

reverseproxy: Adjust new TLS Caddyfile directive names

---

caddyconfig/httpcaddyfile/serveroptions.go
listen.go
listen_linux.go
modules/caddyhttp/app.go
modules/caddyhttp/server.go

See #4863  for more info
This is implemented at the `fakeCloseListener` layer, because during configuration reload it's unique. However,  reloading the keepalive interval does not update it for existing connections that are being proxied. It's only set when new connections are `Accept`ed.
Why not use the obvious approach with ListenConfig? Because when reloading, it would have to stop the existing listener and start a new one with the new ListenConfig. There wouldn't be a seamless switch between the old and new listeners, since only one can bind at one time. There's no way of updating the keepalive period after creating a `net.TCPListener` afaict.
I created a new function `ListenTimeout` to avoid breaking the API to `Listen` for modules.
Does this approach work? If so, I will proceed to …

TCP Keepalive configuration

---

admin.go
admin_test.go
caddy.go

Follow up from https://github.com/caddyserver/caddy/pull/4579#issuecomment-1179329165
Expects the `If-Match` HTTP header to be quoted, and will return the `ETag` HTTP header in quotes.

admin api: expect quoted ETags

---

caddytest/integration/caddyfile_adapt/reverse_proxy_load_balance.txt
modules/caddyhttp/matchers.go
modules/caddyhttp/reverseproxy/caddyfile.go
modules/caddyhttp/reverseproxy/reverseproxy.go

Partially addresses some of the remaining points in https://github.com/caddyserver/caddy/issues/4245
This makes it possible to configure an amount of retries without having a particular time limit.
If both are configured, then the first of the two limits to be reached will cause retries to stop. For example if duration is 10s and retries is 5, then if 5 fast retries happen before 10s, it will stop. If 3 slow retries happen and 10s is reached, it will stop.
I was mulling over whether we should default `try_interval` to 250ms as well if a retries count is configured, I think it's okay if we don't; it's unlikely "CPU will spin" if we use a retry count because the count should almost always be low enough that it won't last very long. The user can always configure the interval if they want it. …

reverseproxy: Implement retry count, alternative to try_duration

---

cmd/commandfuncs.go
modules/caddypki/command.go

Fix #4899
The problem was that `LoadConfig` would be called twice, but when using `stdin` that isn't possible.
The fix is to pass in the already-loaded config if available to `DetermineAdminAPIAddress` (which only happens for `reload`) and `nil` otherwise, which makes it skip doing its own loading in that case.

cmd: Fix reload with stdin

---

.github/workflows/lint.yml

#4875 
https://github.com/golangci/golangci-lint-action#multiple-os-support

ci: Run golangci-lint on multiple os(#4875)

---

modules/caddyhttp/routes.go
modules/caddyhttp/vars.go

Fixes a bug reported in https://caddy.community/t/error-handling-handler-error-with-multiple-handle-in-handle-errors/16692

caddyhttp: Clear out matcher error immediately after grabbing it

---

admin.go
caddy.go
cmd/main.go
modules/caddyhttp/app.go
modules/caddyhttp/fileserver/command.go
modules/caddyhttp/reverseproxy/command.go
modules/caddyhttp/server.go
modules/caddyhttp/staticresp.go

The `caddy respond` command is for simple HTTP servers that write hard-coded responses to the client. This is useful for testing, development, and maintenance.
This requires storing the current context instead of just the current config. The context gives access to the config and the loaded modules. This was needed so we can get the listener addresses if :0 is used.
Also disables config persistence on the file-server and reverse-proxy subcommands, since you'd probably never want `--resume` to use the last command you ran (you'd only want to use that to resume actual configs like from API requests).
This command supports port ranges to spin up multiple servers and pipes for input as well.
This enables some neat functionality, like:
```bash
$ caddy respond  # empty 200
```
```bash
$ caddy …
```

caddyhttp: Implement `caddy respond` command

---

caddy.go
cmd/commandfuncs.go
cmd/main.go
modules/caddyhttp/reverseproxy/fastcgi/fastcgi.go
modules/caddyhttp/tracing/tracer.go

Closes #4926
New Version() function returns simple and full version strings.
Go module information is still preferred. Then vcs info.
It's kind of weird, in that different ways of building Caddy give different outputs:
```
$ go run main.go version
unknown
$ go build && ./caddy version
496c88864c6b029b7d2c1017ec47ae86fe73045a (04 Aug 22 06:06 UTC)
$ xcaddy build --with github.com/caddyserver/caddy/v2=. && ./caddy version
v2.5.2 => /home/matt/Dev/caddyserver/caddy@(devel)
```
`go run` doesn't embed vcs in it, presumably because it runs from outside the git repo?
`go build` at least embeds commit info, so that's nice. That will still add a lot of helpful version info where we are currently lacking it in bug reports, etc.
`xcaddy build` of course builds Caddy as a dependency rather than as …

cmd: Use newly-available version information

---

caddyconfig/load.go
cmd/main.go
listeners.go
modules.go
modules/caddyhttp/matchers.go
modules/caddyhttp/push/link.go
modules/caddyhttp/reverseproxy/addresses.go
modules/caddyhttp/reverseproxy/fastcgi/client.go

fixed https://github.com/caddyserver/caddy/issues/4928

Replace strings.Index usages with strings.Cut

---

modules/logging/filters.go
modules/logging/filters_test.go

Fix #4941
The implementation wasn't correct. Headers in logs are actually of type `caddyhttp.LoggableStringArray`, but the implementation was trying to read it from `in.String` which only works if the logged field is actually a string; it's not, so we need to use `in.Interface` and type assert it.
The test was also incorrect for the same reason. I think the tests were written with the assumption that the logs actually work a certain way, but they don't in reality.
Tested with the following Caddyfile, with this command `curl -v -H'Cookie: myvalue=1; sessionid=ST1LLh3r3' http://localhost:8883`
```
{
debug
admin off
servers {
log_credentials
}
}
:8883 {
log {
format filter {
wrap json
fields {
request>headers>Cookie cookie {
replace sessionid REDACTED
}
}
}
}
}
```

logging: Fix `cookie` filter

---

modules/caddyhttp/reverseproxy/reverseproxy.go

Fixes https://github.com/caddyserver/caddy/issues/4860.
Backport of https://github.com/golang/go/pull/53164

reverseproxy: Support 1xx status codes (HTTP early hints)

---

modules/caddyhttp/reverseproxy/reverseproxy.go

If FlushInterval is explicitly configured to -1, we assume the user is intending for low-latency streaming, and apparently in those cases clients sometimes disconnect before the request has finished its round-trip with the backend.
This patch ignores the client disconnect in those cases so the request will still be completed without error.
Even though `flushInterval()` is dynamically computed, for now I'm requiring an explicit configuration of -1 because I don't fully know the implications of this yet. It might be fine, but if there's problems I want them to be opt-in.
We do know this solution at least works though.
Resolves #4922

reverseproxy: Ignore context cancel in stream mode

---

caddytest/integration/caddyfile_adapt/reverse_proxy_h2c_shorthand.txt
modules/caddyhttp/reverseproxy/addresses.go

As requested in https://github.com/caddyserver/caddy/issues/4498, just adding a little shorthand to make this work:
```
reverse_proxy unix+h2c//dev/shm/grpc
```
/cc @PaTTeeL

reverseproxy: Add `unix+h2c` Caddyfile network shortcut

---

modules/caddyhttp/fileserver/browse.go

Resets buffer acquired from the pool before using it.
Fixes https://github.com/caddyserver/caddy/issues/4962

fileserver: reset buffer before using it (#4962)

---

modules/caddyhttp/caddyhttp.go
modules/caddyhttp/caddyhttp_test.go
modules/caddyhttp/fileserver/staticfiles.go
modules/caddyhttp/matchers.go
modules/caddyhttp/matchers_test.go
modules/caddyhttp/rewrite/rewrite.go
modules/caddyhttp/rewrite/rewrite_test.go

This branch resolves several inconsistencies across Caddy's HTTP facilities regarding URI encodings in paths.
I am not entirely sure, but I suppose breaking changes might be possible if users relied on buggy behavior that has only just been determined and is being remedied here.
This PR mainly affects the `path` matcher and the `rewrite` middleware (including both the `rewrite` and `uri` Caddyfile directives). These are extremely commonly-used Caddy features.
URIs (essentially the part of the URL after the scheme and authority/host, e.g. `/foo/bar?a=b#frag` -- though servers don't really deal with `#fragment` components) are famous for being inconsistently encoded and parsed. Differences in parsing/handling between servers, proxies, and applications often lead to bugs and security …

caddyhttp: Smarter path matching and rewriting

---

modules/caddyhttp/server.go

caddyhttp: Set `http.error.message` to the HandlerError message

---

modules/caddyhttp/server.go

Followup to #4971, need to check that there actually is a wrapped error before trying to grab its message.

caddyhttp: Fix for nil `handlerErr.Err`

---

caddyconfig/httpcaddyfile/options.go
caddyconfig/httpcaddyfile/tlsapp.go
caddytest/integration/caddyfile_adapt/global_options_acme.txt

Allow the OCSP check interval in CertMagic to be configured in the
Caddyfile. Useful for testing certificate revocation with an ACME server
that provides short lived certificates.

httpcaddyfile: Add ocsp_interval global option

---

modules/caddyhttp/reverseproxy/reverseproxy.go
modules/caddyhttp/reverseproxy/upstreams.go

Signed-off-by: Abirdcfly <fp544037857@gmail.com>

Remove duplicate words in comments

---

cmd/commands.go

Instructions found at: https://github.com/spf13/cobra/blob/0580724b5fe33fbbff193befb787b1a1a0fe36a0/shell_completions.md

cmd: add completion command

---

modules/caddyhttp/staticresp.go

Since the `Body` field is a `string`, and it is generally configured via command-line or text config file, it follows that a reasonable default Content-Type is `text/plain`. This allows `templates` to render templates included in the response, and makes it clear to clients that they do not need to download a binary file, without extra configuration of this header.
We also detect valid JSON (JSON can be a number or quoted string which is easily ambiguous as to Content-Type, but the most common form of JSON is an object or array, so we only do it for those structures) and set `application/json`. But those are the only 2 special cases where we set the header automatically. I think those are probably the most common use cases for `respond`: plain text and hard-coded JSON.
This should make …

caddyhttp: Set Content-Type for static response

---

listeners.go
modules/caddyhttp/server.go

This can be useful for custom listeners. Plugins should simply register their network type during `init()`:
```go
func init() {
caddy.RegisterNetwork("foo", newFooListener)
}
func newFooListener(network, addr string) (net.Listener, error) {
// ...
}
```
Then in the Caddy config, users can listen on that network:
```json
{
"listen": ["foo/:80"]
}
```
(It's a little unclear how this would work in the Caddyfile. Maybe something like `foo://` or `foo+http://` in the site address, I dunno.)
Multiple registrations are allowed if multiple network types need to be supported.
This feature/API is experimental and may change!
/cc @Xe @willnorris

core: Plugins can register listener networks

---

caddyconfig/caddyfile/lexer.go
caddyconfig/httpcaddyfile/httptype.go
caddytest/integration/caddyfile_adapt/matcher_syntax.txt

This is admittedly a bit of a wacky idea... but it's super cool!!
Since https://github.com/caddyserver/caddy/pull/4715 we have support for calling most matchers from within a CEL expression, I think we should also have a nicer syntax for defining a matcher with an expression. Typing out the word `expression` to get at this functionality is not as nice as it could be.
My first thought was maybe we make an alias like `expr`? That is better (6 less chars to type) but it still doesn't feel great.
Then I thought of the change we semi-recently made to the parser in https://github.com/caddyserver/caddy/pull/4643 which allows us to detect if a token was explicitly quoted in the config. Matcher names (i.e. the module name) should never be quoted (because... why?) so I think we can make the …

httpcaddyfile: Add shortcut for expression matchers

---

modules/caddyhttp/autohttps.go
modules/caddyhttp/server.go

Fix #4982
I set up a clone function, because although it did work to assign the HTTP server to the same pointer for the logger as the HTTPS server, it worries me in case we later need to change it at runtime.

caddyhttp: Copy logger config to HTTP server during AutoHTTPS

---

.goreleaser.yml

I've tested that on upgrade, the newer man pages overwrite the older ones.

dist: deb package manpages and bash completion scripts

---

modules/caddyhttp/reverseproxy/fastcgi/caddyfile.go
modules/caddyhttp/reverseproxy/fastcgi/client.go
modules/caddyhttp/reverseproxy/fastcgi/fastcgi.go

Following the discussion in #4967 I've added support for logging any stderr messages sent by the upstream.
It is off by default and can be enabled with:
```
transport fastcgi {
capture_stderr
}
```
Naming it `capture` gives us room to *not* buffer stderr records if it's off but it also isn't super clear that the main purpose is logging (at least right now). On the other hand, I don't know what else could be done with this *besides* logging. We should think whether this name makes sense.
Logging is done through the FastCGI transport logger.
Messages received on stderr are logged at WARN level by default, or ERROR level if the response status is >= 400.
The field name `body` was chosen instead of `message` because there's not really a clear definition of what a message is, there is no way …

fastcgi: allow users to log stderr output (#4967)

---

modules/caddyhttp/reverseproxy/fastcgi/client.go
modules/caddyhttp/reverseproxy/fastcgi/client_test.go
modules/caddyhttp/reverseproxy/fastcgi/fastcgi.go
modules/caddyhttp/reverseproxy/fastcgi/header.go
modules/caddyhttp/reverseproxy/fastcgi/pool.go
modules/caddyhttp/reverseproxy/fastcgi/reader.go
modules/caddyhttp/reverseproxy/fastcgi/record.go
modules/caddyhttp/reverseproxy/fastcgi/writer.go

Trying to fix [3803](https://github.com/caddyserver/caddy/issues/3803).
I tried it on a small php site, no problem so far. Extensive testing is required.

fastcgi: Optimize FastCGI transport

---

modules/caddyhttp/caddyauth/basicauth.go
modules/caddyhttp/caddyauth/command.go
modules/caddyhttp/caddyauth/hashes.go

When provisioning `basicauth`, there's a big performance hit on loading/reloading configs because it calculates a fake password; we don't need to do this on-the-fly, it's totally fine to hash the password once offline and just hardcode it.
I did change the `Hasher` interface unfortunately because it's really the cleanest way to implement this, but I'm not aware of any plugins that implement another hashing algorithm anyways, so the breaking change should probably be fine.
---
FWIW I still think we should drop `scrypt` altogether, and stop using base64-encoded strings.
I don't see any compelling reason to keep `scrypt`, it has way too many knobs, and having the salt not being built-in makes it very error prone to use correctly. See …

caddyauth: Speed up basicauth provision, deprecate `scrypt`

---

modules/caddyhttp/matchers.go
modules/caddyhttp/push/handler.go
modules/caddyhttp/responsewriter.go
modules/caddyhttp/staticresp.go

This adds support for early hints in the static_response handler.
It implements my initial proposal. If accepted, it closes #5005.
A practical Caddyfile example, assuming that the endpoints behind `/heavy-pages/` take a while to load on the backend:
```
@hint {
protocol http2+
path     /heavy-pages/*
}
route @hint {
header  Link "</style.css>; rel=preload; as=style"
header  Link "</script.js>; rel=preload; as=script"
respond 103
}
reverse_proxy ...
```
(The HTTP/2 requirement is to try to protect old, incompatible clients. It is optional if your clients are modern or you don't care.)
Early hints are best used when the final response may not be ready for a while (a "while" being, perhaps, 2-3 RTTs, so still on the order of ms).
I had considered an implementation that automatically …

caddyhttp: Support `respond` with HTTP 103 Early Hints

---

.github/workflows/release.yml
.goreleaser.yml

The release workflow was missing the `id-token` permission for GitHub Actions to allow `cosign` to fetch an OIDC token.

ci: add `id-token` permission and update the signing command

---

modules/caddyhttp/fileserver/browse.go
modules/caddyhttp/fileserver/browsetplcontext.go
modules/caddyhttp/fileserver/caddyfile.go
modules/caddyhttp/fileserver/matcher.go
modules/caddyhttp/fileserver/staticfiles.go

According to a brief conversation in [Slack](https://caddyserver.slack.com/archives/C4DLAAP36/p1662419130255019?thread_ts=1662418198.184659&cid=C4DLAAP36), the `fs.StatFS` requirement was chosen for performance reasons.
A filesystem that implements `fs.StatFS` doesn't necessarily perform any faster than a `fs.FS` that requires calling `Open` first. For example, some of the filesystems in [`hairyhenderson/go-fsimpl`](https://github.com/hairyhenderson/go-fsimpl) have a lazy `Open`, and so there's no effective performance hit for [`fs.Stat`](https://pkg.go.dev/io/fs#Stat)'s fallback (`Open` followed by `Read` on the resulting `fs.File`).
I've changed references to `fs.StatFS`, and replaced calls to `Stat` with calls to `fs.Stat` instead.
I think this will make adoption much easier! …

Drop requirement for filesystems to implement fs.StatFS

---

caddyconfig/httpcaddyfile/httptype.go

This adds:
- `{file.*}` -> `{http.request.uri.path.file.*}`
- `{file_match.*}` -> `{http.matchers.file.*}`
This is a follow-up to #4993 which introduces the new URI file placeholders, and a shortcut for using `file` matcher output.
For example, where the `try_files` directive is a shortcut for this:
```
@try_files file <files...>
rewrite @try_files {http.matchers.file.relative}
```
It could instead be:
```
@try_files file <files...>
rewrite @try_files {file_match.relative}
```

httpcaddyfile: Add a couple more placeholder shortcuts

---

modules/caddyhttp/responsewriter.go
modules/caddyhttp/responsewriter_test.go

Doing so allows for splice/sendfile optimizations when available. Since splice can now be leveraged as well, reverse proxy might also benefit tho I haven't confirmed it.
Fixes #4731
To check whether sendfile is really being called or not we can construct two files, any file over 512 bytes should use sendfile in http 1. 
```
$ wc -c *.html
512 nosendfile.html
513 sendfile.html
```
logs trimmed for brevity
```
$ sudo strace -f -e sendfile ./caddy file-server --root . --listen 127.0.0.1:8080 --access-log
strace: Process 137302 attached
[...]
2022/09/06 21:56:45.335 INFO    Caddy serving static files on 127.0.0.1:8080
2022/09/06 21:56:50.505 INFO    http.log.access handled request {"request": {"proto": "HTTP/1.1", "method": "GET", "uri": "/nosendfile.html", "size": 512, "status": 200}}
[pid …
```

caddyhttp: ensure ResponseWriterWrapper and ResponseRecorder use ReadFrom if the underlying response writer implements it.

---

modules/caddyhttp/matchers.go

Fix #5028
Since the matchers would overwrite eachother, we should error out to tell the user their config doesn't make sense.

caddyhttp: Explicitly disallow multiple regexp matchers

---

modules/caddyhttp/encode/encode.go

Fix [5031](https://github.com/caddyserver/caddy/issues/5031), and head request header is consistent except for dynamically generated content.

fix encode handler header manipulation

---

caddyconfig/httpcaddyfile/serveroptions.go
modules/caddyhttp/app.go
modules/caddyhttp/metrics.go
modules/caddyhttp/routes.go
modules/caddyhttp/server.go

Related to #4644
Metrics have accumulated an unfortunate performance regression and have some functionality limitations. Since we don't have the time or expertise on hand currently to address these issues in the more ideal way, I think we need to make metrics opt-in for now.
In the JSON, metrics are enabled by setting `"metrics": {}` in your server config, or in the Caddyfile, use global options:
```
{
servers {
metrics
}
}
```
**This is EXPERIMENTAL and subject to change.**
Note that metrics for `handle_response` handlers (etc) will not be able to have metrics enabled, at least for now.
I think going forward a better long-term fix might be to have the `metrics` directive enable metrics, rather than a server-wide config. I'd also like to make certain aspects about metrics actually …

caddyhttp: Make metrics opt-in

---

.goreleaser.yml

The earlier template of SBOM document names was `"{{ .Binary }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}.sbom"`, which does not account for the varying versions of arm architecture. In other words, binaries of `armv5` and `armv6` end up having document ending with `[...]arm.sbom`, which causes an error on upload for both having the same name. We should further namespace the document names with the arm version.
Another issue with template naming is for signing certificate on Windows. The earlier template trims `.tar.gz`, but our Windows archives are suffixed with `.zip`. We should trim `.zip` as wll.
This PR does both.
Test results: https://github.com/gactions-playground/merry-go-round/releases/tag/v0.0.11

ci: fix the name template of singing certificate and sboms

---

caddy.go
caddytest/caddytest.go
caddytest/integration/caddyfile_test.go
caddytest/integration/handler_test.go
caddytest/integration/map_test.go
caddytest/integration/reverseproxy_test.go
caddytest/integration/sni_test.go
caddytest/integration/stream_test.go
modules/caddyhttp/app.go

This should make config reloads much faster. It avoids blocking from grace periods during config reloads by doing server shutdown in a goroutine. (We never returned any shutdown errors to the caller anyway.)
However, frequent config reloads with long grace periods can build up goroutines. This might be problematic if most/all of these are true:
- configs are being reloaded faster than the servers can shut down, for a sustained period of time,
- clients are slow to finish their requests, or requests are hijacked (WebSockets), and
- server resources are limited,
because obviously this will allow the next config to come in before the old one is out.
That might be OK, and it's probably just a matter of tuning to your actual requirements. If you meet the criteria above, shorten your grace …

caddyhttp: Honor grace period in background

---

admin_test.go
caddyconfig/httpcaddyfile/serveroptions.go
caddytest/integration/caddyfile_adapt/global_server_options_single.txt

Fix #5053
When checking for a block, the current nesting must be used, otherwise it returns the wrong thing.

httpcaddyfile: Fix `protocols` global option parsing

---

caddytest/caddytest.go
caddytest/integration/autohttps_test.go
caddytest/integration/caddyfile_test.go
caddytest/integration/handler_test.go
caddytest/integration/map_test.go
caddytest/integration/reverseproxy_test.go
caddytest/integration/sni_test.go
caddytest/integration/stream_test.go
caddytest/integration/test.init.config

The change in #5045 did as the message says, _hide_ the issue. The integration tests were not successful; they were skipped because the code did not receive confirmation the server was running, so it skipped it. There were 2 issues with it:
- The `grace_period` option in the caddyfile always expects a unit suffix, while the JSON is more graceful. I merely added the `ns` suffix to the caddyfile instead of fighting the unmarshaler.
- The admin listener endpoint got changed in the Go code, but it was never fed to the initial server. The code was not receiving a response. I included an initial config setting only the admin endpoint, and included the same endpoint in all the test config data.
I also added `skip_install_trust` and its corresponding adapted JSON format in all tests to avoid the …

ci: fix integration tests

---

modules/caddyhttp/reverseproxy/command.go

e338648fed3263200dfd6abc9f8100c6f1c0eb67 introduced multiple upstream addresses. A comment notes that mixing schemes isn't supported and therefore the first valid scheme is supposed to be used.
Fixes setting the first scheme.
fixes #5087

reverseproxy: fix upstream scheme handling

---

admin.go
listen.go
listen_unix.go
listeners.go
modules/caddyhttp/app.go
modules/caddyhttp/matchers.go
modules/caddyhttp/server.go

Deprecate:
- caddy.Listen
- caddy.ListenTimeout
- caddy.ListenPacket
Prefer caddy.NetworkAddress.Listen() instead.
Change:
- caddy.ListenQUIC (hopefully to remove later)
- caddy.ListenerFunc signature (add context and ListenConfig)
- Don't emit Alt-Svc header advertising h3 over HTTP/3
- Use quic.ListenEarly instead of quic.ListenEarlyAddr; this gives us more flexibility (e.g. possibility of HTTP/3 over UDS) but also introduces a new issue:
https://github.com/lucas-clemente/quic-go/issues/3560#issuecomment-1258959608
- Unlink unix socket before and after use
I'm not sure that `ListenAll()` will be useful. You'd think it would be, except the HTTP app, at least, sets up each listener one-by-one. That could probably be refactored and simplified with `ListenAll()`, but I haven't gotten there …

core: Refactor, improve listener logic

---

modules/caddyhttp/map/map.go
modules/caddyhttp/map/map_test.go

This updates the map directive to replace placeholders in default values in the same way as matched values.
I'm trying to use the map directive to override the username for some users in the [Tailscale Caddy plugin](https://github.com/tailscale/caddy-tailscale).  For example, I want to set `webauth.user` to "willnorris" if `http.auth.user.tailscale_user` equals "will@tailscale.com", but to default to the value of `http.auth.user.tailscale_login` in all other cases.  Prior to this patch, the default value would be the literal string "{http.auth.user.tailscale_login}" instead of expanding the placeholder.
```
map {http.auth.user.tailscale_user} {webauth.user} {
will@tailscale.com willnorris
default {http.auth.user.tailscale_login}
}
```

caddyhttp: replace placeholders in map defaults

---

caddytest/integration/caddyfile_adapt/php_fastcgi_expanded_form.txt
caddytest/integration/caddyfile_adapt/php_fastcgi_handle_response.txt
caddytest/integration/caddyfile_adapt/php_fastcgi_matcher.txt
caddytest/integration/caddyfile_adapt/php_fastcgi_subdirectives.txt
caddytest/integration/caddyfile_adapt/php_fastcgi_try_files_override.txt
modules/caddyhttp/reverseproxy/fastcgi/caddyfile.go
modules/caddyhttp/rewrite/rewrite.go
modules/caddyhttp/rewrite/rewrite_test.go

This seems to make more sense: if the path is rewritten internally before getting to `php_fastcgi`, then the external-facing HTTP redirect should use the original URI path, right?
In issue #5073, this is as follows:
- Request is for `/app`
- `handle_path` strips the `/app` prefix, leaving the URI path as empty string
- `php_fastcgi` sees that the path being requested (the site root) is a folder, and it has `index.php` in it, so it issues redirect to `{http.request.uri.path}/` which is now just `/` because `{http.request.uri.path}` is empty string
- I think it should use `{http.request.orig_uri.path}/` for the redirect instead. This makes it redirect to `/app/`.
Is this sound logic? @ArabCoders can you test this please?

fastcgi: Redirect using original URI path (fix #5073)

---

modules/caddyhttp/map/map.go

It was not accurate and would block valid configurations. Placeholders could be used in outputs that are defined in the same mapping as long as that placeholder does not do the same.
Example of a valid config that was blocked:
```
respond "Hello world: {bar}"
map {host} {foo} {bar} {
localhost A {foo}
}
```
It would give the error: `mapping 0 requires value of {foo} to define value of {foo}: infinite recursion` - which isn't really true nor does it make sense (it should probably say "mapping 0 requires value of {foo} to define value of {bar}" -- which isn't infinitely recursive).
For a request to `localhost`, the response is "Hello world: A" as expected, because although `{foo}` does get mapped to `{bar}`, the value of `{bar}` is simply "A". The recursion stops after 1 call (2 total).
--- …

map: Remove infinite recursion check

---

modules/caddyhttp/fileserver/browse.html

PR #4066 added a dark color scheme to the file_server browse template. PR #4356 later set the links for the `:visited` pseudo-class, but did not set anything for the dark mode, resulting in poor contrast. I selected some new colors by feel.
This commit also adds an `a:visited:hover` for both, to go along with the normal blue hover colors.

fileserver: better dark mode visited link contrast

---

service_windows.go

Wanted to test the Windows service manager integration, promptly failed,
because the check is inverted :D
With this fixed, Caddy starts as a Windows service, but doesn't find an
"adjacent" Caddyfile, because all Windows services have their working directory
set to `C:\WINDOWS\SYSTEM32`... Should we chdir in this case? (And if that
sounds like a good idea, is the init method in `service_windows.go` early
enough to do this safely?)

Fix inverted logic in Windows service detection

---

service_windows.go

As noted in #5106, when installing Caddy as a native Windows service (For reference, the PowerShell command for that is `New-Service -Name caddy -BinaryPathName "C:\caddy\caddy.exe run"`), caddy starts up in `C:\WINDOWS\SYSTEM32` - I think this is a bad idea for multiple reasons:
- You obviously cannot put an "adjacent" `Caddyfile` into `system32` (well, you technically can, but that sound like a bad idea all around) and as an alternative, you have to run caddy with a much longer command line (Like `New-Service -Name caddy -BinaryPathName "C:\caddy\caddy.exe run --config C:\caddy\Caddyfile"`
- If somebody tries to use relative paths in the `Caddyfile`, those will be relative to the `system32` directory, which will lead to hard-to-debug problems...
This is a "prototype" of a simple fix: …

Switch to program directory when running as Windows service

---

modules/logging/encoders.go

This is something that has bothered me for a while, so I figured I'd do something about it now since I'm playing in the logging code lately.
The `console` encoder doesn't actually match the defaults that zap's default logger uses. This makes it match better with the rest of the logs when using the `console` encoder alongside somekind of filter, which requires you to configure an encoder to wrap.
Before:
After:
As you can see, this colorizes + uppercases the level, and makes the timestamp not useless.
Worth saying, that technically zap's default logger sniffs the TTY to figure out whether it's interactive or not, and uses JSON if non-interactive, and a "modified" console encoder if interactive. I think it might turn off color if the terminal doesn't support it. But I don't think that's …

logging: Better `console` encoder defaults

---

modules/caddyhttp/fileserver/staticfiles.go

treat invalid file path as notFound so that PassThru can work
some  invalid file path can be valid URL path

treat invalid file path as notFound

---

modules/logging/encoders.go

Closes #5019
Adds a new `time_local` flag for encoders which logs in local time.
Example config:
```
:8881 {
log {
format console {
time_format wall_milli
time_local
}
}
}
```
Before:
```
2022/10/02 20:23:38.548	INFO	tls	finished cleaning storage units
2022/10/02 20:23:39.603	info	http.log.access.log0	handled request	{"request": {"remote_ip": "127.0.0.1", "remote_port": "45332", "proto": "HTTP/1.1", "method": "GET", "host": "localhost:8881", "uri": "/", "headers": {"Accept": ["*/*"], "User-Agent": ["curl/7.74.0"]}}, "user_id": "", "duration": 0.000001415, "size": 0, "status": 0, "resp_headers": {"Server": ["Caddy"]}}
```
After:
```
2022/10/02 20:23:27.753	INFO	tls	finished cleaning storage units
2022/10/02 16:23:29.178	info	http.log.access.log0	handled request	{"request": {"remote_ip": …
```

logging: Add `time_local` option to use local time instead of UTC

---

modules/logging/filters.go
modules/logging/filters_test.go

Thanks to @IndeedNotJames for reporting this problem.
When trying to filter HTTP headers in the logs, many filters don't work at all because they didn't handle fields that are array values, which all headers are because they can have multiple values.
These changes are mainly for HTTP headers, but it'll work in general for any `LoggableStringArray` type being logged.
Now, the `regexp`, `hash` and `ip_mask` filters will correctly iterate over each string in the `LoggableStringArray` and apply their filtering on those. 
Additionally, for `ip_mask`, we now split on commas and mask each segment that parses as an IP address. This should be useful for `X-Forwarded-For` type headers which may be a list of comma separated IPs.
And finally, I fixed a bug with `rename` where it would set the zap …

logging: Perform filtering on arrays of strings (where possible)

---

modules/caddyhttp/reverseproxy/forwardauth/caddyfile.go

Seems simple enough to canonicalize the header field names.

forwardauth: Canonicalize header fields (fix #5038)

---

caddyconfig/httploader.go
go.mod

Resolves https://github.com/caddyserver/caddy/issues/5070

httploader: Implement retries

---

replacer.go
replacer_test.go

Sometimes it can be useful to have access to the current working directory in the config file.
This patch adds a placeholder, `system.wd`, containing it.

replacer: working directory global placeholder

---

modules/caddyhttp/fileserver/browse.go
modules/caddyhttp/fileserver/browsetplcontext.go

Prevents caddy from performing disk IO needlessly when the request is cancelled before the listing is finished.
Closes #5129

fileserver: stop listing dir when request context is cancelled

---

modules/caddyhttp/templates/templates.go

Oops. Docs aren't appearing here anymore because of the newline 🙈  https://caddyserver.com/docs/modules/http.handlers.templates
It got broken all the way back in May 😬 https://github.com/caddyserver/caddy/commit/6891f7f421eac71dac8f8687255ede5189e7eb3a

docs: Fix templates documentation, stray newline breaks godoc

---

modules/caddyhttp/map/map.go

This is a really basic PR that clarifies that destination values (as used with Map) should be wrapped in braces.

Clarified how destination values should be formatted.

---

modules/caddyhttp/caddyhttp.go
modules/caddyhttp/caddyhttp_test.go
modules/caddyhttp/fileserver/staticfiles.go

I didn't even know about these Windows "features" (actually, I knew about short names as I grew up with them, but didn't know they were _still_ a thing... ugh) that, along with suffixing filenames with spaces and dots, allow an arbitrary number of variants to transparently refer to the same file on Windows NTFS.
Thanks to Adrian Denkiewicz of Doyensec for reporting this.

fileserver: Reject ADS and short name paths; trim trailing dots and spaces on Windows

---

caddyconfig/httploader.go

fixes #5158
Signed-off-by: Chris Lahaye <mail@chrislahaye.com>

caddyconfig: fix httploader leak from unused responses due to loop not breaking on success

---

modules/caddyhttp/staticresp.go

This fixes #5175 by canonicalizing the header field names.

caddyhttp: Canonicalize header field names

---

modules/caddypki/ca.go

instead of generating a new root certificate at the default location load the certificate from the configuration.
fixes: #5181

caddypki: use configured certificate instead of generating a new one

---

.github/workflows/lint.yml
.golangci.yml
caddyconfig/httpcaddyfile/pkiapp.go
cmd/caddy/main.go
modules/caddyhttp/caddyauth/caddyfile.go
modules/caddyhttp/encode/caddyfile.go
modules/caddyhttp/push/caddyfile.go
modules/caddyhttp/push/link.go
modules/caddyhttp/push/link_test.go
modules/caddyhttp/responsematchers.go
modules/caddyhttp/reverseproxy/selectionpolicies.go
modules/caddyhttp/reverseproxy/streaming.go
modules/caddyhttp/rewrite/caddyfile.go
modules/caddyhttp/staticerror.go
modules/caddyhttp/templates/caddyfile.go
modules/caddyhttp/templates/templates.go
modules/caddypki/acmeserver/caddyfile.go
modules/logging/filewriter.go
modules/logging/filterencoder.go
modules/logging/netwriter.go

While testing a NodeJS app of mine, I noticed that since our changes to the proxy to send a WebSocket close frame, when Caddy would close first, we would see `RangeError: Invalid WebSocket frame: MASK must be set` in our logs from https://github.com/websockets/ws.
After some investigation, it looks like when we're the "client" (i.e. the upstream half of the proxy, whereas for the downstream half we act as the "server"), we need to mask the message according to https://www.rfc-editor.org/rfc/rfc6455#section-5.3.
I copied the `maskKey` and `maskBytes` code from https://github.com/websockets/ws as noted in code comments.
Needs some testing to make sure this still works correctly.

reverseproxy: Mask the WS close message when we're the client

---

admin.go

certmagic.New takes a template and returns pointer to the new config. GetConfigForCert later must return a pointer to the new config not the template.
fixes #5162

admin: fix certificate renewal

---

admin.go

same way it is set in modules/caddytls/tls.go

admin: set certmagic cache logger

---

modules/caddyhttp/reverseproxy/selectionpolicies.go
modules/caddyhttp/reverseproxy/selectionpolicies_test.go

Small change, but long story. It's not easy to explain, sorry if it's not clear, feel free to ask questions.
I recently upgraded caddy from 2.4.x to 2.6.2, unfortunately the load balancing becomes quite unbalanced as
you can see on this graph:
I made some test code to expose this behaviour:
```go
policy := new(HeaderHashSelection)
policy.Field = "CF-Connecting-IP"
pool := UpstreamPool{
{Host: new(Host), Dial: "foobar:4001"},
{Host: new(Host), Dial: "foobar:4002"},
{Host: new(Host), Dial: "foobar:4003"},
{Host: new(Host), Dial: "foobar:4004"},
{Host: new(Host), Dial: "foobar:4005"},
{Host: new(Host), Dial: "foobar:4006"},
{Host: new(Host), Dial: "foobar:4007"},
{Host: new(Host), Dial: "foobar:4008"},
}
var distribution []int = make([]int, len(pool))
req, _ := http.NewRequest("GET", "/", …
```

reverseproxy: Improve hostByHashing distribution

---

caddytest/caddytest.go
caddytest/integration/test.init.config

Go module distribution excludes files that are not of a specific list of types. In other words,`.go` files are retained in the downloaded modules, but others are not for sure[^1]. This causes pain, e.g. #5187. The workaround in this PR is to write the init config to a temp file, and set the cleanup func to delete the file at the end of the test run.
For the record, I tried passing the init config t o`os.Stdin` by creating a `os.Pipe`, writing to the writer end, and setting `os.Stdin = reader`. However, this seems to slow down the run to the extent of test timeouts. It did work sometimes when the timeout value is set for very long period. It's probably a race condition. I don't believe forcefully going down that route is worth it. Writing the init config to a temp file is much simpler and …

caddytest: internalize init config into '.go' file

---

README.md

Closes #4040
Quote from me https://github.com/caddyserver/caddy/issues/5245#issuecomment-1345608813:
> GitHub supports the `prefers-color-scheme` CSS media feature in `<picture>` HTML elements since a few months.
>
> https://docs.github.com/en/get-started/writing-on-github/getting-started-with-writing-and-formatting-on-github/basic-writing-and-formatting-syntax#specifying-the-theme-an-image-is-shown-to
@francislavoie provided me with the caddy logo and I edited the certmagic one and made the "certificate paper" solid white instead of a white-transparent gradient.
I did not modify the ZeroSSL logo yet, because that one is coming from https://caddyserver.com/resources/images/zerossl-logo.svg (https://github.com/caddyserver/website/blob/master/src/resources/images/zerossl-logo.svg)
So I will …

readme: darker variants of logos in dark mode

---

caddy.go

If `debug.ReadBuildInfo()` doesn't return the build information we should not try to access it. Especially if users only want to build with the `CustomVersion` we should not assume access to `debug.ReadBuildInfo()`.
The build environment where this isn't available for me is when building with bazel.

version: don't panic if read build info doesn't work

---

modules/caddyhttp/encode/encode.go
modules/caddyhttp/encode/encode_test.go

Respect the request and response Cache-Control header with `no-transform` directive.
The request should not be altered if the `Cache-Control` contains the `no-transform` directive.
https://www.rfc-editor.org/rfc/rfc7234#section-5.2.1.6
https://www.rfc-editor.org/rfc/rfc7234#section-5.2.2.4
Closes https://github.com/darkweak/souin/issues/289

encode: respect Cache-Control HTTP header no-transform

---

.github/workflows/ci.yml

The dependbot PRs don't have access to secrets, which is necessary to connect to the S390x machine.

ci: exclude dependbot from running tests on s390x machine

---

.github/workflows/ci.yml
.github/workflows/release.yml

Starting 1st June 2023 (planned) workflows, `::set-output name...::` syntax cannot be used. You can see the example warnings here: https://github.com/caddyserver/caddy/actions/runs/3760367163
ref. [GitHub Actions: Deprecating save-state and set-output commands | GitHub Changelog](https://github.blog/changelog/2022-10-11-github-actions-deprecating-save-state-and-set-output-commands/)
This PR fixes the issue by using the `GITHUB_OUTPUT` environment variable as instructed in the above article.

ci: Update GitHub Actions to avoid `set-output` deprecation

---

.goreleaser.yml

See https://goreleaser.com/deprecations/#archivesreplacements
I took the default for `name_template` documented at https://goreleaser.com/customization/archive/?h=archive#archives, turned it into a multi-line string using the "After" tab from https://goreleaser.com/deprecations/#archivesreplacements, then changed `{{ .Os }}` to be wrapped by an `if darwin` outputting `mac` instead.
Technically untested, the goreleaser_check seems to pass now but I didn't run it to see if the template has the expected result. I don't have it installed locally etc so would appreciate if you could test it out @mohammed90 😊

ci: Fix goreleaser deprecation

---

caddyconfig/httpcaddyfile/builtins.go
caddytest/integration/caddyfile_adapt/tls_dns_ttl.txt
modules/caddytls/acmeissuer.go

My DNS provider (INWX) requires the TTL of a TXT record to be at least 300 seconds. Currently there is no way to configure this in a Caddyfile, if I see it correctly.
In addition, the `propagation_delay` and `propagation_timeout` options have also been added to the `tls` directive.

caddytls: Add `dns_ttl` config, improve Caddyfile `tls` options

---

modules/caddyhttp/reverseproxy/command.go

While playing around with `caddy reverse-proxy` (for https://caddy.community/t/unexpected-bind-address-already-in-use-for-unrelated-port/18238) I noticed that `http://localhost:8080` in `caddy reverse-proxy --from http://localhost:8080 [--to <upstream>]` enabled auto-https features.
Essentially ignoring the `http://` and turning `:8080` into a `https://` server with the usual redirects from `:80`.
Using `--from localhost:80` worked as expected, though.
This PR disables auto-https for `fromAddr.Scheme == "http"`, which also includes `:80` due to
https://github.com/caddyserver/caddy/blob/b166b9008344786e7cfe5715b7e8a4cd3ec1bd76/modules/caddyhttp/reverseproxy/command.go#L96-L98

reverseproxy: Don't enable auto-https when `--from` flag is http

---

modules/caddyhttp/reverseproxy/reverseproxy.go

* Fixes #5236
* enable request body buffering in reverse proxy
when the request header has Transfer-Encoding: chunked

Fix hanging caused by Transfer-Encoding: chunked

---

caddyconfig/httpcaddyfile/serveroptions.go
caddytest/integration/caddyfile_adapt/global_server_options_single.txt
modules/caddyhttp/app.go
modules/caddyhttp/matchers.go
modules/caddyhttp/replacer.go
modules/caddyhttp/reverseproxy/caddyfile.go
modules/caddyhttp/reverseproxy/reverseproxy.go
modules/caddyhttp/server.go

Partial work for #4924 as per my plan in https://github.com/caddyserver/caddy/issues/4924#issuecomment-1206477962
We've had requests for defining `trusted_proxies` globally, so it doesn't need to be configured for each `reverse_proxy`. This does that.
But also, this opens the door for more places we can use trusted proxies, such as in #4924 which asks for getting the real client IP. We can do that by looking at the XFF header _if the proxy is trusted_. That part isn't done in this PR, _edit:_ this is in #5104!
Also we might want to change how `remote_ip forwarded` works, possibly making it not trust forwarded by default (which would be a breaking change... but eh, it's known to be insecure right now). ~~And maybe we should add `client_ip` to the logs.~~ See #5104 for the logs part.

caddyhttp: Add server-level `trusted_proxies` config

---

caddyconfig/caddyfile/parse.go
caddyconfig/caddyfile/parse_test.go

* The function doesn't return an error anywhere.

chore: Fix caddyfile.replaceEnvVars return

---

caddyconfig/httpcaddyfile/builtins.go
caddyconfig/httpcaddyfile/directives.go
caddyconfig/httpcaddyfile/httptype.go
caddytest/integration/caddyfile_adapt/handle_nested_in_route.txt
caddytest/integration/caddyfile_adapt/php_fastcgi_expanded_form.txt

Fix #5308
The original parseRoute just appends result's routes to its routes, which is not enough when subroutes contain handle routes which must be exclusive.
A simple modification to a private function buildSubroute proved to be just enough, obviously routes don't need to be sorted.

httpcaddyfile: Fix `handle` grouping inside `route`

---

caddyconfig/caddyfile/adapter.go
cmd/commandfuncs.go

* Fixes #5294
* return exit 1 with an error message

cmd: `caddy fmt` return code is 1 if not formatted

---

go.mod
go.sum

As of Tailscale 1.34.0 on Windows, Tailscale now uses a named pipe to connect to the local tailscale service.
This pulls in tailscale/tscert#5 as reported in tailscale/tscert#4.
(Sorry, we should've noticed this earlier!)

go.mod: bump tscert package to fix Tailscale 1.34+ on Windows

---

modules/caddyhttp/tracing/module_test.go
modules/caddyhttp/tracing/tracer.go

Fixes #5171
- I'm a noob in Go - this was my first tackle at using the language. 
- I fixed the tests that started breaking, but did not add any new tests. I have no idea how to check the output span after it has been formatted in the tests.
- I built caddy and used it in my Server and checked that the output spans are correct - as in the placeholders are replaced.

tracing: Support placeholders in span name

---

modules/caddyhttp/reverseproxy/command.go

* Fixes #5290
Add new flag --disable-redirects for reverseproxy.
https://github.com/caddyserver/caddy/issues/5290#issuecomment-1383449714
`Using a command is more convenient in my case.`

reverseproxy: Add flag to short command to disable redirects

---

caddyconfig/httpcaddyfile/httptype.go
caddyconfig/httpcaddyfile/serveroptions.go
caddytest/integration/caddyfile_adapt/server_names.txt

caddyfile: Allow overriding server names

---

caddyconfig/httpcaddyfile/httptype.go
caddyconfig/httpcaddyfile/options.go
caddytest/integration/caddyfile_adapt/global_options_admin_with_persist_config_off.txt
caddytest/integration/caddyfile_adapt/global_options_persist_config.txt

* Fixes #5209
* `persist_config off` disables configuration persist explictly in Caddyfile
* if it sets, Admin.Config.Persist becomes false

httpcaddyfile: Add persist_config global option

---

cmd/commandfuncs.go

cmd: `fmt` exit successfully after overwriting config file

---

caddyconfig/httpcaddyfile/serveroptions.go
caddytest/integration/caddyfile_adapt/global_server_options_single.txt
caddytest/integration/caddyfile_adapt/reverse_proxy_options.txt
modules/caddyhttp/app.go
modules/caddyhttp/ip_range.go
modules/caddyhttp/server.go

Followup to #5103, I realized that the work there was somewhat incomplete.
We've already had requests for making it easy to configure trusted proxy ranges for e.g. CloudFlare, which publish their IP ranges at https://www.cloudflare.com/ips/. This PR makes it possible for a plugin to implement a module that can fetch those IP ranges and feed it to the global trusted proxies in the server.
This should be merged ASAP, before the next release, because otherwise this would be a breaking change. But since we haven't released this yet, it's the best time to make this pluggable.
Regarding the interface, I decided that it should just return a slice of `netip.Prefix` and not an error, because returning any error would mess with the HTTP server being able to function properly. See the godoc comment …

caddyhttp: Pluggable trusted proxy IP range sources

---

modules/caddyhttp/responsewriter.go
modules/caddyhttp/reverseproxy/streaming.go

Fix http access log will not record size and status for hijacked response writer.

log response size for websocket request

---

modules/caddyhttp/reverseproxy/caddyfile.go
modules/caddyhttp/reverseproxy/reverseproxy.go

Mostly reverts 845bc4d50b437995d574819850206e4b3db4040d (#5289) -- that was my bad, totally an oversight on my part of the code review.
Adds warning for unsafe config. The `buffer_requests` and `buffer_responses` config params, together with a separate `max_buffer_size` parameter, were not safely designed: very prone to configuring unbounded buffers. I'm not sure why I ever thought that was fine.
Deprecates unsafe properties in favor of simpler, safer designed ones.
We'll need a better fix for #5236 -- even if it's the same kind of fix (buffering, and resetting the Content-Length) as long as it's opt-in this time.
/cc @u5surf What do you think?
I think this patch merits a quick release of v2.6.4.

reverseproxy: Don't buffer chunked requests (fix #5366)

---

caddyconfig/caddyfile/adapter.go
cmd/commandfuncs.go

An impressive amount of users misunderstand `caddy fmt`. 
This (tiny) PR slightly rephrases the hints to mention `--overwrite` (which a lot of users are unaware of) in an attempt to make it more clear what this command actually does (for users that don't check help pages that is)

cmd: make `caddy fmt` hints more clear

---

caddyconfig/caddyfile/dispenser.go
caddyconfig/caddyfile/importargs.go
caddyconfig/caddyfile/lexer.go
caddyconfig/caddyfile/parse.go
caddyconfig/caddyfile/parse_test.go
caddyconfig/httpcaddyfile/builtins_test.go

imported snippets reflect actual lines in file
fix [5202](https://github.com/caddyserver/caddy/issues/5202)

caddyfile: Implement variadics for import args placeholders

---

modules/caddytls/tls.go

Closes #5383 
This warns about on-demand being vulnerable only if the automation policy is the default fallback (no subjects) or has any wildcard certs, because those are infinite cardinality.
If there's only single (non-wildcard) subjects, then the cardinality is limited to only the length of the subject list, so there's no risk of abuse.

caddytls: Loosen the warning for on-demand

---

caddyconfig/caddyfile/lexer.go
caddyconfig/caddyfile/lexer_test.go
caddytest/integration/caddyfile_adapt/heredoc.txt

I was mixing string and []rune and that broke on multi-byte runes and such. Whoops.
Followup to #5385, Closes #5400

caddyfile: Fix heredoc fuzz crasher, drop trailing newline

---

.goreleaser.yml

This adds 2 tarballs in the release:
- `caddy_{{ .Version }}_buildable-artifact.tar.gz`: this contains a `main.go`, `go.mod`, and `go.sum` along with a `vendor/` tree containing all the deps, including Caddy's own source tree as a dep. This allows the user to run `go build` against the exact files used to build our releases.
- `caddy_{{ .Version }}_src`: this packages Caddy's git tree as-is along with the `vendor/` directory of vendored deps.
To test, run:
`TAG=master goreleaser release --skip-publish --snapshot --clean`
Closes #4573

ci/cd: ship tarballs with vendored deps

---

context.go
modules/caddypki/adminapi.go

Closes https://github.com/caddyserver/caddy/issues/4893
I highly doubt anyone but ourselves used this API, so it should be safe to do this even though it's an exported function.

context: Rename func to `AppIfConfigured`

---

go.mod
listen.go
listen_unix.go
modules/caddyhttp/app.go

Fix #5393, alternate to #5405.
I haven't had a chance to thoroughly test this yet because [my `curl` installation is currently borked](https://twitter.com/mholt6/status/1631438882951806977).
I still need to clean it up a bit and add explanatory comments if this works, so don't merge it yet.
/cc @francislavoie

core: Eliminate unnecessary shutdown delay on Unix

---

modules/caddyhttp/fileserver/staticfiles.go

Minor change to fix https://github.com/caddyserver/caddy/issues/5416
Tested with `osFS` and [caddy-fs-s3](https://github.com/sagikazarmark/caddy-fs-s3), and confirmed that path canonicalization redirects still happen successfully.

remove trailing slash on fs filenames

---

listeners.go

[v0.32.0](https://github.com/quic-go/quic-go/releases/tag/v0.32.0) changed the 0-RTT API. It now has to be explicitly enabled.

quic: enable 0-RTT

---

modules/caddyhttp/reverseproxy/reverseproxy.go

…PHP-FPM requests from hanging
See: https://github.com/caddyserver/caddy/issues/5420

reverseproxy: Reset Content-Length to prevent fastcgi from hanging

---

.goreleaser.yml

The `sign-blob` command of `cosign` now prompts the user at runtime and may fail with this:
```
⨯ release failed after 1m46s               error=sign: cosign failed: exit status 1: Using payload from: dist/artifact.tar.gz
Generating ephemeral keys...
Retrieving signed certificate...
Successfully verified SCT...
Note that there may be personally identifiable information associated with this signed artifact.
This may include the email address associated with the account with which you authenticate.
This information will be used for signing this artifact and will be stored in public transparency logs and cannot be removed later.
By typing 'y', you attest that you grant (or have permission to grant) and agree to have this information stored permanently in transparency logs.
Are you sure you …
```

cicd: add `--yes` to cosign arguments

---

modules/caddytls/automation.go
modules/caddytls/tls.go

Otherwise it's a panic when setting the MaxEvents to 0 while the window is still non-zero. Should fix #5442

caddytls: Zero out throttle window first

---

caddyconfig/httpcaddyfile/httptype.go
caddyconfig/httpcaddyfile/serveroptions.go
caddytest/integration/caddyfile_adapt/global_server_options_single.txt
caddytest/integration/caddyfile_adapt/matcher_syntax.txt
modules/caddyhttp/app.go
modules/caddyhttp/ip_matchers.go
modules/caddyhttp/marshalers.go
modules/caddyhttp/matchers.go
modules/caddyhttp/server.go

Followup on #5103 and #5328.
This introduces first-class support for determining the client IP, at the HTTP server level. Also adds a placeholder and writes it to the access logs.
I'm marking this as a draft for now, because this has a certain level of risk, and needs discussion. We need to be extra careful about the implementation.
I'm taking @adam-p's guidance on this from his excellent article https://adam-p.ca/blog/2022/03/x-forwarded-for/. There's a few different valid approaches to this. This implementation takes the left-most, first valid IP. I'm _not_ excluding private IPs, because actually it happens frequently that users want their LAN IP to be used as the real client IP, in home networking contexts.
~~Currently, the header used is not configurable, I have it just set to …

caddyhttp: Determine real client IP if trusted proxies configured

---

replacer.go

This is the same as Go stdlib http.TimeFormat, but I didn't want to pull in a dependency to this file just for that.
Context: https://caddy.community/t/equivalent-to-nginx-date-gmt/19408, this would be helpful to fill some HTTP headers like `Last-Modified` that take this format.

replacer: Add HTTP time format

---

caddyconfig/httpcaddyfile/tlsapp.go
caddyconfig/httpcaddyfile/tlsapp_test.go
modules/caddyhttp/autohttps.go
modules/caddyhttp/reverseproxy/command.go
modules/caddytls/automation.go
modules/caddytls/tls.go

Also renamed the field to SubjectsRaw, which can be considered a breaking change but I don't expect this to affect much.
This has come up semi-frequently. I think it's fine to support `{env.DOMAIN}` for subjects. I'm not 100% sure if this will work in all the cases we expect it to, but it should at least be better supported than before.

caddytls: Run the replacer on automation policy subjects

---

caddyconfig/httpcaddyfile/httptype.go
logging.go
modules/caddyhttp/fileserver/command.go
modules/caddyhttp/reverseproxy/command.go
modules/caddyhttp/staticresp.go

`sink` logs have, thus far, been printed not encoded in any format. This does not play friendly with log parsers expecting a specific format from a particular source. In other words, it becomes a hassle to tell the log parser, e.g. Loki, Caddy logs are json-formated if some lines aren't.

log: make `sink` encodable

---

modules/caddyhttp/server.go

Closes #4494
I'm not super satisfied with this unfortunately... the problem is we can't really add this to the `request` log object, because it gets marshaled when we call `.With(loggableReq)` and doesn't wait until the `defer` so it logs the size as 0 because it hasn't been read yet. So we need to put it in the top-level of the log. Later on, maybe something like `.LazyWith()` might get added https://github.com/uber-go/zap/issues/1121 but for now I don't see a way to prevent it.
Because of that, I'm not sure what the best naming is. `req_size` could make sense because we already have `size` for the response size, but that's weirdly incongruent with `resp_header` using a prefix for the other half. `bytes_read` is more accurate in the sense that if the body isn't read then it would report …

caddyhttp: Log request body bytes read

---

modules/caddyhttp/reverseproxy/streaming.go

Just a possible debug aid. It's not always obvious which half the error comes from.

reverseproxy: Add mention of which half a copyBuffer err comes from

---

go.mod
go.sum
modules/caddyhttp/proxyprotocol/listenerwrapper.go
modules/caddyhttp/proxyprotocol/module.go
modules/caddyhttp/reverseproxy/caddyfile.go
modules/caddyhttp/reverseproxy/hosts.go
modules/caddyhttp/reverseproxy/httptransport.go
modules/caddyhttp/reverseproxy/reverseproxy.go
modules/caddyhttp/standard/imports.go

This is an updated (rebased to the current master and improved) version of https://github.com/caddyserver/caddy/pull/4855. 
Please let me know if any changes are needed. Would be great to have this included in the next official release :-)

proxyprotocol: Add PROXY protocol support to `reverse_proxy`, add HTTP listener wrapper

---

modules/caddyhttp/fileserver/browse.html

Use [`<meta name="color-scheme">`](https://web.dev/color-scheme/) to mark the page compatible with both light and dark themes, and let browser adapt to the themes as well.
Before:
After:

fileserver: Add color-scheme meta tag

---

cmd/commandfuncs.go
modules/caddyhttp/fileserver/browse.html
modules/caddyhttp/reverseproxy/selectionpolicies.go
modules/caddyhttp/reverseproxy/selectionpolicies_test.go

Query policy brought up in https://caddy.community/t/caddy-v2-lb-based-on-arg-name-nginx/19448/8. I'm not sure why we didn't have this, and it's super trivial to add, so why not 🤷
Closes #5469 for `client_ip_hash`

reverseproxy: Add `query` and `client_ip_hash` lb policies

---

cmd/main.go

Per the request later in #4686
@coolaj86 Could you please test this with your actual use case? I haven't had a chance yet.

cmd: Support ' quotes in envfile parsing

---

modules/caddyhttp/celmatcher.go

celmatcher: Implement `pkix.Name` conversion to string

---

caddyconfig/caddyfile/parse.go
caddyconfig/caddyfile/parse_test.go
modules/caddyhttp/reverseproxy/caddyfile.go
modules/caddyhttp/reverseproxy/fastcgi/caddyfile.go
modules/caddyhttp/reverseproxy/forwardauth/caddyfile.go

Feedback from https://caddy.community/t/caddy-as-an-authentication-proxy-to-secure-endpoint/19691 made me realize we should be a bit stricter with parsing braces.
This makes this config cause an error:
```
:8001 {
reverse_proxy https://example.com 
{
header_up Host {upstream_hostport}
}
}
```
```
Error: Caddyfile.test3:3 - Error during parsing: Unexpected '{' on a new line; did you mean to place the '{' on the previous line?
```
The other changes to `reverse_proxy`/`php_fastcgi`/`forward_auth` were to fix the error `expecting 'https://' but got '://'` from that thread; essentially, the upstreams were being parsed for each iteration of the unmarshal loop with `RemainingArgs()` but that doesn't make sense. Changing the loop means both the shortcut directives would misbehave due to the …

caddyfile: Stricter parsing, error for brace on new line

---

modules/caddyhttp/reverseproxy/metrics.go

Fixes: #5496 
We can find this `sync.Once` in `newMetricsUpstreamsHealthyUpdater` is unnecessary which is called by `reverseproxy.Provision` exactly once per `caddy run/start`. Thus it never call by `caddy reload` because it has already called in `caddy run/start` at only once.
https://github.com/caddyserver/caddy/blob/998c6e06a75030cccabcc08790bc32642791aff7/modules/caddyhttp/reverseproxy/reverseproxy.go#L419-L420
https://github.com/caddyserver/caddy/blob/998c6e06a75030cccabcc08790bc32642791aff7/modules/caddyhttp/reverseproxy/metrics.go#L38-L40
And moreover, It is necessary to reinitialize with prometheus.Unregister.
https://github.com/prometheus/client_golang/issues/475#issuecomment-428142144
Note: We can be prepared our workaround patches which seems to work fine, but it might have …

reverseproxy: Fix reinitialize upstream healthy metrics

---

metrics.go
modules/caddyhttp/encode/encode.go
modules/caddyhttp/fileserver/staticfiles.go
modules/caddyhttp/responsewriter.go
modules/caddyhttp/responsewriter_test.go

[Go 1.20 added a new `"net/http".ResponseController` type](https://tip.golang.org/doc/go1.20#http_responsecontroller) that allows, among other things, to set per-request timeouts.
This patch adds support for this new type. This will improve the stability of Mercure, and simplify its code: https://github.com/dunglas/mercure/pull/764

caddyhttp: Impl `ResponseWriter.Unwrap()`, prep for Go 1.20's `ResponseController`

---

go.mod
go.sum
modules/caddyhttp/logging.go
modules/caddyhttp/reverseproxy/fastcgi/fastcgi.go
modules/caddyhttp/server.go
modules/caddyhttp/server_test.go
modules/caddyhttp/tracing/tracer.go

Tracing is far more useful when we can correlate logs with traces. This is done by adding a `traceID` field to the access logs.
I've attempted to add this in with a minimum of performance impact, and as such have moved the request logging function out of `ServeHTTP` and into a new method that can be tested independently. I've added some basic unit tests and a couple of benchmarks to gauge the impact.
Here are benchmark results before the `traceID` field was added:
```console
$ go test -benchtime=3s -count=5 -benchmem -run=^$ -bench ^BenchmarkServer ./modules/caddyhttp | tee before.txt
goos: darwin
goarch: amd64
pkg: github.com/caddyserver/caddy/v2/modules/caddyhttp
cpu: Intel(R) Core(TM) i7-10700K CPU @ 3.80GHz
BenchmarkServer_LogRequest-16                    3927310               920.3 …
```

logging: Add traceID field to access logs when tracing is active

---

modules/caddyhttp/reverseproxy/fastcgi/fastcgi.go

Hello, first of all I love Caddy! I hope this helps.
In current 83b2697, the option "capture_stderr" is not working on the directive "php_fastcgi".
If you want to test it, just create a php file with syntax error of any type and pass it over php_fastcgi.
The problem started in the transition between the f2a7e7c commit, and the current 83b2697.
On 2022 Sept 2, it was launched the commit 83b2697 which changed some files on fastcgi.go.
These changes was titled: fastcgi: Optimize FastCGI transport (#4978).
It was changed a lot of internal functions and they were replaced with a more distributed logic into separate files (which is good).
On those changes was removed a conditional that evaluates "t.CaptureStderr" (line 164, f2a7e7c, [fastcgi.go](https://github.com/caddyserver/caddy/compare/f2a7e …

fastcgi: Fix `capture_stderr`

---

modules/caddyhttp/reverseproxy/selectionpolicies.go
modules/caddyhttp/reverseproxy/selectionpolicies_test.go

Closes #5486
This adds a new `fallback` option for some load balancing policies: `query`, `header` and `cookie`. See https://caddyserver.com/docs/caddyfile/directives/reverse_proxy#load-balancing
Previously, the default was to always choose a random upstream when using those policies when there's no value available. Now, the fallback policy is configurable.
Example usecases:
- `cookie` + `least_conn`, where the first request (with no cookie) gets the upstream with the fewest current requests, instead of a random one
- `header` + `first` where if a header isn't provided, the first available upstream is chosen instead; so essentially the `first` policy allows for primary/secondary behaviour normally, but allows for an escape hatch for testing the secondary upstream by using a header
In the …

reverseproxy: Add `fallback` for some policies, instead of always random

---

modules/caddyhttp/reverseproxy/healthchecks.go
modules/caddyhttp/reverseproxy/reverseproxy.go

reverseproxy: Fix active health check header canonicalization, refactor

---

modules/caddyhttp/reverseproxy/selectionpolicies.go

When only a single request has the least amount of requests, there's no need to compute a random number, because the modulo of 1 will always be 0 anyways.

reverseproxy: Optimize the base case for `least_conn` policy

---

cmd/commands.go
cmd/main.go

Use the LoadConfig to load the config and compare it in each interaction of watch and larger the interaction to 3 seconds.
Resolve #3517

feature: watch include directory

---

modules/caddyhttp/server.go

Closes https://github.com/caddyserver/caddy/issues/5528
Does what it says on the tin! Given there's already a getter for `Server` I just went ahead with following that pseudo-convention rather than exporting, which also has the benefit of not having developers accidentally overwrite it in their custom middlewares.

Add a getter for Server.name

---

caddytest/integration/caddyfile_adapt/reverse_proxy_port_range.txt
modules/caddyhttp/reverseproxy/addresses.go
modules/caddyhttp/reverseproxy/addresses_test.go
modules/caddyhttp/reverseproxy/caddyfile.go
modules/caddyhttp/reverseproxy/command.go

See discussion in https://caddy.community/t/reverse-proxy-to-backend-over-range-of-ports/19602
This doesn't work for JSON configs because this expanding happens at config-adapt-time. See the forum thread for an explanation.

reverseproxy: Expand port ranges to multiple upstreams in CLI + Caddyfile

---

caddytest/integration/caddyfile_adapt/header.txt
modules/caddyhttp/headers/caddyfile.go

Something that I've thought about a few times, I find the syntax awkward for setting a response header operation to be deferred since it requires opening a block to enable `defer` in simple cases.
So my solution is to add another prefix similarly to our existing ones, `>` meaning "set with defer", think an arrow meaning "later".
Before:
```
header {
Field value
defer
}
```
After:
```
header >Field value
```

headers: Add `>` Caddyfile shortcut for enabling `defer`

---

.gitignore
modules/caddyhttp/fileserver/browse.html

I looked at the new file browser template and found it to be pretty good looking. Nice job! I tried it locally and found that the footer looked something like this: 
The black space after the footer looks kinda awkward, so I decided to fix it. With this PR, it looks like this:

Fix file browser footer while in grid mode

---

modules/caddyhttp/app.go
modules/caddyhttp/server.go

Detailed discussing in slack.
If there are multiple listening ports, h3server won't close some of its quic listeners, leading to resource leak.
More explanation in comments.

Fix h3 shutdown

---

modules/caddyhttp/fileserver/browse.html

This PR aims to fix the font in the file browser's breadcrumb. It loads the Poppins font, but my system doesn't have that, so therefore I get Times New Roman, which is an alright font (if you're a teacher), but it looks very out of place here. I took the same approach as the body (load system-ui font as an alternative) which fits more.

Fix file browser breadcrumb font

---

modules/caddyhttp/fileserver/staticfiles.go

Fixes #5546
Tested with a Caddyfile with a form roughly resembling:
```
route {
header {
ETag "\"${content-hash-here}\""
-Last-Modified
}
root * /content/by-hash/${content-hash-here}
file_server
}
```
(with `${content-hash-here}` replaced with an actual hash rendered to base-16).

fileserver: Allow Etag override

---

modules/caddyhttp/fileserver/browse.html

Title explains this PR. Here's how the grid view looks like on mobile with this PR: 
Here's how it looks like without these changes: 
I don't know if the grid entry width thing is something you guys want (personally I think it looks better), but the breadcrumbs should not be black on mobile at least.

Make grid entires take up full width on mobile view and fix breadcrumb colors in dark mode mobile view (fileserver)

---

modules/caddyhttp/fileserver/staticfiles.go

Apparently useful for Nix environments
/cc @charles-dyfis-net

fileserver: Don't set Etag if mtime is 0 or 1 (close #5548)

---

caddyconfig/caddyfile/importargs.go
caddyconfig/caddyfile/parse.go
caddyconfig/httpcaddyfile/builtins_test.go
caddyconfig/httpcaddyfile/testdata/import_variadic.txt
caddyconfig/httpcaddyfile/testdata/import_variadic_snippet.txt
caddyconfig/httpcaddyfile/testdata/import_variadic_with_import.txt

~~As discussed in slack, if an imported file also has a snippet with variadic placeholders and imports this snippet, parsing will fail saying not enough arguments.~~
~~Added tests show what the problem is.~~
When importing, caddy will always replace tokens placeholders. However, when importing a file that contains snippets definition, caddy will replace **them**. For `{args[n]}` type token, they will either be replaced or dropped, which is undesirable since they are part of a snippet.
Implement a naive algorithm to skip replacing tokens if they are part of a snippet. It **does not** check for syntax error, that will be done later when caddy finished importing all the tokens.

Do not replace import tokens if they are part of a snippet

---

listen_unix.go
listen_unix_setopt.go
listen_unix_setopt_freebsd.go

This option is preferable on FreeBSD as it uses a hash to balance load between threads.

listen_unix.go: Use consts to set SO_REUSEPORT_LB on FreeBSD

---

caddyconfig/caddyfile/dispenser.go
caddyconfig/caddyfile/importargs.go
caddyconfig/caddyfile/lexer.go
caddyconfig/caddyfile/parse.go
caddyconfig/httpcaddyfile/builtins_test.go

Previously when implementing variadic placeholders, caddy config token's `File` will be modified to reflect their import chain to help debug config error. One side effect is the [extra colon](https://github.com/caddyserver/caddy/issues/5538#issuecomment-1551609453) for imported files in file_server.
This patch uses a separate field to track import chain, and still keeps the error output the same.

config: keep track of import instead of modifying file name

---

modules/caddyhttp/templates/templates.go
modules/caddyhttp/templates/tplcontext.go

This is a fix for the issue I created earlier, closes #5552. It's mostly a copy-paste of the `include` function, but skips the template parsing step to just return the body of the file unmodified.

templates: Add `readFile` function, skips parsing contents as a template

---

cmd/commands.go
cmd/storagefuncs.go

#5313 
Thanks for the fun project!
1)
> I think I'd probably want to put that in the caddycmd package though (the cmd folder), as it's purely a CLI utility, and not really anything to do with Caddy core. (Assuming nothing new needs to be exported. If so let me know.)
The two functions in `caddy.go` that is? There are caddycmd wrappers separately as is.
2)
> In the case of running as a systemd service, the command would need to be run as the caddy user to correctly access the files owned by that user, if the file_system storage module is used.
I started by shelling out `systemctl status caddy` for part of the rerun check but relying only on the `--user` flag felt a little less awkward. I'm not sure what the best option is though. Besides file permissions, it seemed necessary to re-exec …

cmd: Implement storage import/export

---

modules/caddyhttp/server.go

Allow registering a custom network mapping for HTTP/3. This is useful if the original network for HTTP/1.1 and HTTP/2 is not a standard `unix`, `tcp4`, or `tcp6` network. To keep backwards compatibility, we fall back to `udp` if the original network is not registered in the mapping.
Fixes #5555

caddyhttp: support custom network for HTTP/3

---

caddytest/integration/caddyfile_adapt/header.txt
modules/caddyhttp/headers/caddyfile.go

Tiny followup to #5535 to make `>` work as a prefix for replacements (i.e. 2 args following the header field).
For example:
```
header >Set-Cookie (.*) "$1; SameSite=None;"
```
Defer is usually necessary for replacements, so it should be as easy as possible to set up.

headers: Allow `>` defer shortcut for replacements

---

modules/caddyhttp/reverseproxy/caddyfile.go
modules/caddyhttp/reverseproxy/reverseproxy.go
modules/caddyhttp/reverseproxy/streaming.go

This PR adds two settings related to streaming connections to the reverse_proxy handler:
`stream_timeout` defines the maximum lifetime of a streaming connection in the reverse proxy; when the connection reaches this age it is closed
`stream_close_delay` defines the time for which the proxy waits before closing the streaming connections when it is cleaned up i.e. after a configuration change
#5471

reverseproxy: streaming timeouts

---

modules/caddyhttp/reverseproxy/healthchecks.go

Fix #5590
We weren't considering `tls_except_ports` for active health checks. This fixes that. I rearranged the code a bit to make it read more naturally with this in mind.

reverseproxy: Support `tls_except_ports` for active health checks

---

listeners.go
listeners_test.go

Closes #4675
Allows one to specify the wanted socket permissions like so:
- `unix//path/to/unix.sock:0666` (unix socket at `/path/to/unix.sock` with `0666` (`ugw=rw`)
The leading `0` is optional. `unix//path/to/unix.sock:666` would yield the same permissions.
Using `:u=rw,r=rw,=o=rw` will not work. This could, however, be added fairly easily later.
This commit also changes the default unix socket file permissions to `u=rw,g=rw,o=` (`0660`).
It used to default to the shell's umask.
However, the fact that caddy used to default to the umask hasn't been documented anywhere as far as I am aware.
The only mentions I know of are my two comments in https://caddy.community/t/new-user-cant-get-darkweb-site-host-working/15491/12 and #4675.
So I would argue this isn't strictly a deprecation …

core: Add optional unix socket file permissions

---

listeners.go

Because abtract unix sockets aren't real paths on the filesystem and thus can't be `chmod`ed.
Fixes the issue reported by @lxhao61 in https://github.com/caddyserver/caddy/commit/22927e278dc29c9d1804c20f483510ec569f23ed#commitcomment-119530849
I believe this applies to all platforms, including Windows.

core: Skip `chmod` for abstract unix sockets

---

.goreleaser.yml

Fixes GH Actions failure reported in https://github.com/caddyserver/caddy/actions/runs/5420166639/jobs/9866067348.
The [goreleaser deprecation notice](https://goreleaser.com/deprecations/#sourcerlcp) recommends removal.

chore: remove deprecated property `rlcp` in goreleaser config

---

listeners.go

…tic optimization by quic-go
Fix [5605](https://github.com/caddyserver/caddy/issues/5605), [3932](https://github.com/quic-go/quic-go/issues/3932).
As a side effect, less code for interface implementation.

listeners: embed `net.UDPConn` to allow automatic optimization by quic-go

---

go.mod
go.sum

We just released [v0.36.1](https://github.com/quic-go/quic-go/releases/tag/v0.36.1), which disables GSO by default due to the [problems we found](https://github.com/quic-go/quic-go/issues/3911).

update quic-go to v0.36.1

---

caddyconfig/caddyfile/dispenser.go
caddyconfig/caddyfile/lexer.go
caddyconfig/caddyfile/parse.go
caddyconfig/httpcaddyfile/builtins_test.go

Fix [5625](https://github.com/caddyserver/caddy/issues/5625).

caddyfile: Fix comparing if two tokens are on the same line

---

modules/caddyhttp/fileserver/command.go

I've seen a few requests for guidance on how to customize the default file browser template. The template file is stored in this repository. Users might find the reference to the template [here](https://caddyserver.com/docs/caddyfile/directives/file_server#browse) in the documentation of the `browse` sub-directive of the `file_server` directive, which many users seem to miss or glance over. Adding the sub-command allows the user to not leave the terminal or search through the interwebz on how to find the template. They can run `caddy file-server export-template` right from the terminal where they are. This feels more ergonomic.
If accepted, I'll update the website docs accordingly.

fileserver: add `export-template` sub-command to `file-server`

---

go.mod
go.sum

https://github.com/quic-go/quic-go/releases/tag/v0.36.2

chore: update quic-go to v0.36.2

---

admin.go
caddy.go
context.go

Separate currentCtxMu to protect currentCtx, and a new rawCfgMu to protect rawCfg and synchronize loads.
This fixed the panic for me and race detector did not find any data races.

core: Refine mutex during reloads (fix #5628)

---

.github/workflows/ci.yml
.github/workflows/cross-build.yml
.github/workflows/lint.yml
.github/workflows/release.yml
.github/workflows/release_published.yml
README.md
go.mod
go.sum
modules/caddyhttp/caddyauth/basicauth.go
modules/caddyhttp/errors.go
modules/caddyhttp/fileserver/staticfiles.go
modules/caddyhttp/reverseproxy/reverseproxy.go
modules/caddyhttp/reverseproxy/selectionpolicies.go

See https://github.com/quic-go/quic-go/releases/tag/v0.37.0 for release notes.

Update quic-go to v0.37.0, bump to Go 1.20 minimum

---

modules/caddyhttp/fileserver/browse.html

This adds lazy image loading to the grid view mode of the fileserver, to reduce traffic on large listings.

fileserver: add lazy image loading

---

modules/caddyhttp/reverseproxy/caddyfile.go
modules/caddyhttp/reverseproxy/upstreams.go

allows AUpstreams to be externally instantiable for use within plugins. otherwise the first call to `GetUpstreams` will panic in dereferencing a nil value

export reverseproxy.ipVersions type

---

modules/caddyhttp/reverseproxy/reverseproxy.go

This PR cleans up the situation with proxied connection termination after configuration reload under several circumstances.
To my best knowledge the situation before this PR is captured in the following table that summarizes when the connections are terminated on configuration reload:
<table cellspacing="0" cellpadding="0">
<thead>
<tr>
<th>flush_interval</th>
<th>Connection Type</th>
<th>stream_close_delay</th>
<th>Terminated</th>
</tr>
</thead>
<tbody>
<tr>
<td rowspan="3">-1</td>
<td rowspan="2">Streaming</td>
<td>0</td>
<td>On Reload (1)</td>
</tr>
<tr>
<td>&gt; 0</td>
<td>On Reload (1) *</td>
</tr>
<tr>
<td>Other</td>
<td></td>
<td>On Reload (1) *</td>
</tr>
<tr>
<td rowspan="3">!= -1</td>
<td rowspan="2">Streaming</td>
<td>0</td>
<td>On Reload (2)</td>
</tr>
<tr>
<td>&gt; 0</td> …

reverseproxy: Connection termination cleanup

---

admin.go
cmd/commandfuncs.go

This should actually be a non-breaking change, since previously we only allowed the empty Host for unix sockets. We still allow that, but turns out the most popular clients used with the admin API (Caddy's CLI and curl) don't allow empty hostnames anymore:
- Caddy's CLI starting with Go 1.20.6 (https://github.com/golang/go/issues/61431)
- Curl starting with 7.50 (https://superuser.com/a/925610) (but it worked starting with 7.40)
Anyway, this is mildly infuriating because we can no longer be compliant with RFC 2616 Section 14.26 as Go requires setting a host. But it's the best we can do.
We could disable the security checks completely for unix sockets -- and the [infosec community has assured me](https://infosec.exchange/@mholt/110794015397914193) that doing so would be safe -- but I am …

core: Allow loopback hosts for admin endpoint (fix #5650)

---

caddyconfig/httpcaddyfile/httptype.go

Fix `string does not match ~[]E` error

---

modules/caddyhttp/reverseproxy/streaming.go

reverseproxy: Fix hijack ordering which broke websockets

---

.github/workflows/release.yml

Apparently it's been deprecated [since January](https://goreleaser.com/deprecations/#-rm-dist).

chore: use `--clean` instead of `--rm-dist` for goreleaser

---

caddyconfig/caddyfile/importargs.go
caddyconfig/caddyfile/parse_test.go

Fix [issue reported on community](https://caddy.community/t/problem-after-upgrading-to-2-7-2/20687).
When importing arguments, regex will usually match a substring of the key, this change detects if it's a substring match.
Personally I think caddy shouldn't allow braces in the replacer as it has other implications. But this will do for now.

import: check that matched key is not a substring of the replacement key

---

caddytest/integration/caddyfile_adapt/replaceable_upstream.txt
caddytest/integration/caddyfile_adapt/replaceable_upstream_partial_port.txt
caddytest/integration/caddyfile_adapt/replaceable_upstream_port.txt
modules/caddyhttp/reverseproxy/addresses.go
modules/caddyhttp/reverseproxy/addresses_test.go
modules/caddyhttp/reverseproxy/caddyfile.go
modules/caddyhttp/reverseproxy/command.go

reverseproxy: do not parse upstream address too early if it contains replaceble parts

---

cmd/commandfuncs.go
internal/sockets.go
listeners.go
listeners_test.go

Fixes #5694, a bug where the following Caddyfile
```Caddyfile
{
admin unix/admin.sock|0660
}
```
and `caddy reload --config Caddyfile`
would throw the following error instead of reloading it:
```
INFO    using provided configuration    {"config_file": "Caddyfile", "config_adapter": ""}
Error: sending configuration to instance: performing request: Post "http://127.0.0.1/load": dial unix admin.sock|0660: connect: no such file or directory
[ERROR] exit status 1
```
---
This bug also affected `caddy start` and `caddy stop`.

cmd: fix cli when admin endpoint uses new unix socket permission format

---

.goreleaser.yml

This will add RISC-V prebuilts for Caddy.

feat: Add 64-bit RISC-V to goreleaser config

---

modules/caddyhttp/reverseproxy/reverseproxy.go
modules/caddyhttp/reverseproxy/upstreams.go

Should fix #5736.
I don't love this, because it involves allocating new `Upstream`s for every request, but there's no other elegant, safe way to do this AFAIK.
One potential solution could be to have the `GetUpstreams()` method return `[]Upstream` instead of `[]*Upstream` -- this would be a breaking change but AFAIK nobody else is implementing these modules (yet?). It would also be a correctness bugfix, since the current API returns the same upstream values but we change the Host value. (Even if synchronized, it'd logically be wrong.)
@kkroo Would you be able to give this a try and confirm whether it resolves the races for you, at least? I might still implement the fix differently and ask you to test one more time, but if we verify as we go I can be more confident of the fix. Thank you!! …

reverseproxy: Always return new upstreams (fix #5736)

---

caddyconfig/caddyfile/lexer.go
caddyconfig/caddyfile/lexer_test.go

Fix #5760
- Prevents trying to parse heredoc while already inside quotes
- A space while parsing the heredoc marker immediately ends parsing and returns the token as-is
- Now only checks for `<<<` after reaching a newline so that it doesn't eagerly error if there's three `<<<` in a row on a token in the middle of a line
- Rearranged tests to cover more cases, more clearly

caddyfile: Loosen heredoc parsing

---

caddyconfig/caddyfile/dispenser.go
caddyconfig/httpcaddyfile/builtins.go

Before:
```
Error: parsing caddyfile tokens for 'reverse_proxy': parsing upstream 'wss://foo': Caddyfile:7 - Error during parsing: the scheme wss:// is only supported in browsers; use https:// instead, import chain: ['']
```
After:
```
Error: parsing caddyfile tokens for 'reverse_proxy': parsing upstream 'wss://foo': the scheme wss:// is only supported in browsers; use https:// instead, at Caddyfile:7
```
Essentially: moving the filename to the end, hiding import chain if empty, and removing the redundant "Error during parsing".

caddyfile: Adjust error formatting

---

replacer.go

Fix [5773](https://github.com/caddyserver/caddy/issues/5773)
The comment for `http.TimeFormat` says the time being formatted must be in the UTC timezone to get the correct value and it's indeed used by stdlib.

replacer: change timezone to UTC for "time.now.http" placeholders

---

modules/caddyhttp/reverseproxy/httptransport.go
modules/caddytls/certselection.go

These happen to be harmless memory aliasing
but I guess the linter can't know that and we
can't really prove it in general.

Appease gosec linter

---

caddyconfig/caddyfile/lexer.go
caddyconfig/caddyfile/lexer_test.go

Fixes `panic: runtime error: slice bounds out of range [:3] with capacity 2`
Followup to #5761, fixes #5770

caddyfile: Fix case where heredoc marker is empty after newline

---

modules/logging/filters.go
modules/logging/filters_test.go

As discussed in this [previous PR](https://github.com/caddyserver/caddy/pull/5101), here is the improvement to make the query filter handle array of strings.
This is needed so that the query filter can be used on headers, especially useful for the `Referer`.
**Disclaimer:** my first lines of code in Go, tried my best using the same logic and style that were used already. Successfully tested locally (and unit tests passed).

logging: query filter for array of strings

---

.github/workflows/ci.yml
.github/workflows/lint.yml

Implements #5768
Run `govulncheck` to scan for vulnerable Go packages/modules in CI

chore: check vuln Go mods in CI

---

cmd/commandfuncs.go
cmd/commands.go
cmd/main.go

Fix: https://github.com/caddyserver/caddy/issues/5802
Prevent `--envfile` from overwriting existing environment variables.
For example:
```bash
$ cat .env
FOO=.env
FOO_DOT_ENV="set in .env"
$ cat .env.prod
FOO=.env.prod
FOO_DOT_ENV_TEST="set in .env.test"
$ go run cmd/caddy/main.go run --envfile .env --environ | grep FOO
FOO=.env
FOO_DOT_ENV=set in .env
$ go run cmd/caddy/main.go run --envfile .env.prod --envfile .env --environ | grep FOO
FOO=.env.prod
FOO_DOT_ENV_TEST=set in .env.test
FOO_DOT_ENV=set in .env
$ FOO=system go run cmd/caddy/main.go run --envfile .env.prod --envfile .env --environ | grep FOO
FOO=system
FOO_DOT_ENV_TEST=set in .env.test
FOO_DOT_ENV=set in .env
```

cmd: Prevent overwriting existing env vars with `--envfile`

---

.github/workflows/lint.yml
caddyconfig/httpcaddyfile/httptype.go
caddyconfig/httpcaddyfile/replace.go
caddyconfig/httpcaddyfile/shorthands.go

Fixes #5788
Add a section to replace placeholder shorthands for extracted named routes.

httpcaddyfile: fix placeholder shorthands in named routes

---

modules/caddyhttp/reverseproxy/upstreams.go

Add a nil check for AUpstreams.Versions in AUpstreams.GetUpstreams to handle the case where versions is not set in the configuration file.
This fixes #5809.
I'm not completely sure this is the correct place to fix this - nil checks are probably never a bad idea - but it might also be good to ensure AUpstreams.Versions is actually initialized to include both IPv4 and IPv6 in the first place when it is not set in the configuration.

reverseproxy: fix nil pointer dereference in AUpstreams.GetUpstreams

---

modules/caddyhttp/fileserver/browse.html

- continuation of #5806 (my bad; github closed the pr automatically after force pushing a clean branch; lesson learnt 😄 )
1. Add folder symlink icon as current master displays folder symlinks as file symlinks 
2. Make `<path>` tags self-closing in SVG.
3. Minor ui fix: in search field use `<input type="search">` instead of `text`
---
@francislavoie: in reply to https://github.com/caddyserver/caddy/pull/5806#issuecomment-1712279472 and https://github.com/caddyserver/caddy/pull/5806#issuecomment-1712104514
Keeping things simple is probably a higher priority than achieving some imaginary 'optimization' at the cost of adding extra complexity. I've updated the pr to only add the `folder-symlink` and `type=search` for the search field — it adds a tiny ⛌ button for resetting the search when it …

fileserver: browse template SVG icons and UI tweaks

---

caddytest/caddytest.go

This error message is always empty because this field isn't set on a client request. This patch fixes the issue.

fix: caddytest.AssertResponseCode error message

---

modules/caddyhttp/reverseproxy/reverseproxy.go

Fixes https://github.com/caddyserver/caddy/issues/5776
AFAICT there's no reason for this condition to exist. If there are no routes, then the compiled handler will simply invoke the `next` handler, which is the desired behavior.

reverseproxy: Allow fallthrough for response handlers without routes

---

modules/caddyhttp/templates/tplcontext.go

Issue:
This pull request addresses fixes #5835, which was created to track the progress of the discussion on the Caddy community forum: https://caddy.community/t/file-server-httpinclude-with-x-forwarded-for/21087. The issue discusses the need to allow the virtual request of `httpInclude` of a file_server to include the `X-Forwarded-For` header. Currently, the `X-Forwarded-For` header is not set in the virtual request, which poses a challenge for applications that rely on this header to determine the client's IP address and make decisions based on it.
Goal:
The goal of this enhancement is to modify the `funcHTTPInclude` function in the Caddy codebase to include the `X-Forwarded-For` header in the virtual request. This change will enable reverse proxies to set the `X-Forwarded-For` header, …

templates: Add dummy `RemoteAddr` to `httpInclude` request, proxy compatibility

---

modules/caddyhttp/fileserver/command.go

Original idea from @francislavoie: https://github.com/dunglas/frankenphp/pull/238#discussion_r1344667798
Maybe could we also add a `-a` shortcut for `--access-log`?

fileserver: Add command shortcuts `-l` and `-a`

---

caddytest/integration/caddyfile_adapt/encode_options.txt
modules/caddyhttp/encode/encode.go

After this change, WebAssembly files will be encoded (compressed). This is useful because WebAssembly files are uncompressed.
Pull request #2624 did the same thing 4 years ago but it seems that the change got lost.

encode: Add `application/wasm*` to the default content types

---

caddyconfig/httpcaddyfile/httptype.go
caddytest/integration/caddyfile_adapt/enable_tls_for_catch_all_site.txt

Enable TLS for catch-all site if `tls` directive is specified, even with non-standard port
Fixes #5747 
The input Caddyfile
```
:8443 {
tls internal {
on_demand
}
}
```
is `adapt --pretty` to
```
{
"apps": {
"http": {
"servers": {
"srv0": {
"listen": [
":8443"
],
"tls_connection_policies": [
{}
]
}
}
},
"tls": {
"automation": {
"policies": [
{
"issuers": [
{
"module": "internal"
}
],
"on_demand": true
}
]
}
}
}
}
```
Regression test
The input Caddyfile
```
:8443 {
}
```
is `adapt --pretty` to
```
{
"apps": {
"http": {
"servers": {
"srv0": {
"listen": [
":8443"
]
}
}
}
}
}
```

httpcaddyfile: Enable TLS for catch-all site if `tls` directive is specified

---

modules/caddyhttp/reverseproxy/reverseproxy.go

Closes https://github.com/caddyserver/caddy/issues/5838

reverseproxy: Fix retries on "upstreams unavailable" error

---

caddytest/integration/caddyfile_adapt/reverse_proxy_buffers.txt
modules/caddyhttp/reverseproxy/caddyfile.go

When trying to set the `requst_buffers` or `response_buffers` to `-1` for unlimited, go-humanise fails to parse the value and crashes caddy
This allows the special value of `-1` to be set in the Caddyfile, this seemed like a good simple way to do this, as no other negative values would be valid.
It was always possible to set `-1` using JSON or the API.

reverseproxy: fix parsing Caddyfile fails for unlimited request/response buffers

---

.gitignore
cmd/cobra.go
cmd/commandfuncs.go
cmd/commands.go
cmd/main.go

We document custom status codes that we exit with in https://caddyserver.com/docs/command-line#exit-codes, but I think it's been broken since our switch to Cobra 😭 
This PR:
- Fixes the exit code behaviour by wrapping the code in an error to be checked in `Main()`, was reminded by https://github.com/dunglas/frankenphp/pull/239
- Adds `--envfile` support to `caddy adapt` and `caddy environ`, noticed it was missing and it's useful to test env file things in the Caddyfile, while looking into https://caddy.community/t/errors-using-environment-variable-s-in-caddyfile/21347
- Renames variables throughout `commandfuncs.go`, I found them needlessly long and redundant, each mentioning their command they're apart of in the variable name
- Closes #5871 by adding support for `caddy -v` for showing …

cmd: Fix exiting with custom status code, add `caddy -v`

---

modules/caddyhttp/reverseproxy/selectionpolicies.go

Closes #5609
Not sure why we never got around to this, it's such a simple fix 🤦 anyway here it is.

reverseproxy: Fix `least_conn` policy regression

---

modules/caddyhttp/reverseproxy/caddyfile.go
modules/caddyhttp/reverseproxy/reverseproxy.go
modules/caddyhttp/reverseproxy/streaming.go
modules/caddyhttp/reverseproxy/streaming_test.go

This makes debug logging very noisy when reverse proxying, but I guess that's the point.
This has shown to be useful in troubleshooting vexing infrastructure problems.

reverseproxy: Add more debug logs

---

modules/caddytls/cf.go

It's not ideal to have to compile with a different toolchain, and I'd understand if you'd rather wait for upstream Go.
With this patch, we can get PQ caddy:
```
git clone https://github.com/bwesterb/caddy
git clone https://github.com/cloudflare/go
cd go/src
./make.bash
cd ../../caddy/cmd/caddy
git checkout pq
../../../go/bin/go build
```
This enables PQ for browser -> Caddy by default. For PQ Caddy -> upstream we need [this patch](https://github.com/caddyserver/caddy/pull/5851), and then we can use:
```
localhost {
reverse_proxy https://pq.cloudflareresearch.com {
header_up Host {upstream_hostport}
tls_curves X25519Kyber768Draft00 x25519 secp256r1
}
}
}
```
For Caddy -> upstream we're not enabling it by default, as not all upstreams might support it, and it would incur an …

tls: Add support for X25519Kyber768Draft00 post-quantum "curve" when compiled with cfgo.

---

modules/caddyhttp/fileserver/browse.html

When contents are equal, but maybe just a sort order is different, it is good to add `<link rel="canonical" href="{{.Path}}/" />`. This helps search engines propeely index the page.
I also added a link to the home page with the name of `{{.Host}}` just above the bread crumbs to make the page clearer.
https://paste.tnonline.net/files/28Wun5CQZiqA_Screenshot_20231007_134435_Opera.png

fileserver: Add canonical URL to browse template

---

admin.go
admin_test.go

Fixes #5836
Deleting a non-existing config key returned status `200`. Now it returns `404`.
I took the chance to also update the status codes for putting an already existing key (status `409`) and patching a non-existing key (status `404`), instead of failing with an internal error.

admin: respond with 4xx status code on non-existing config path

---

caddyconfig/caddyfile/importargs.go
caddyconfig/caddyfile/parse_test.go

fix [5716](https://github.com/caddyserver/caddy/issues/5716).

caddyfile: Fix variadic placeholder false positive when token contains `:`

---

cmd/packagesfuncs.go

It occurred to me that users of `dpkg-divert` (per our instructions [here](https://caddyserver.com/docs/build#package-support-files-for-custom-builds-for-debianubunturaspbian)) may have their symlink `/usr/local/bin/caddy` be overwritten by the `upgrade`, `add-package`, or `remove-package` commands because we're replacing the symlink source, i.e. `/usr/local/bin/caddy`, and not its target. This may cause some system inconsistency or confusion. The fix is simply to resolve the symlink.

cmd: upgrade: resolve symlink of the executable

---

caddyconfig/httpcaddyfile/tlsapp.go
caddytest/integration/caddyfile_adapt/tls_automation_policies_11.txt

Fixes an issue reported in https://caddy.community/t/21415
We need to check that the `ManagerRaw` (i.e. `get_certificate` usually) is also the same, otherwise automation policies get merged when they shouldn't.

httpcaddyfile: Fix TLS automation policy merging with get_certificate

---

modules/caddyhttp/templates/templates.go
modules/caddyhttp/templates/tplcontext.go

templates: Clarify `include` args docs, add `.ClientIP`

---

cmd/cobra.go

This pull request addresses issue https://github.com/caddyserver/caddy/issues/5893, where the version string was reported inconsistently when using the `-v` or `--version` CLI flags. The issue was due to the absence of a newline character at the end of the version string when using these flags. This inconsistency could potentially disrupt update check automation and other tooling that relies on consistent version string formatting.
To fix this issue, I have added a newline character (`\n`) to the version template in the code. With this change, the version string output is now consistent whether you use `caddy version` or `caddy -v / caddy --version`. This ensures a smoother experience for users and more reliable tooling integration.
Please review and merge this pull request to ensure …

Add newline character to version string in CLI output

---

modules/caddyhttp/server.go

Should fix #5756.
Tested allocations with this benchmark:
```
func BenchmarkServer_LengthReader(b *testing.B) {
req := httptest.NewRequest(http.MethodGet, "/", nil)
for i := 0; i < b.N; i++ {
var bodyReader *lengthReader
for j := 0; j < 10000; j++ {
if req.Body != nil {
// For testing without sync.Pool
// bodyReader = &lengthReader{Source: req.Body}
bodyReader = GetLengthReader(req.Body)
req.Body = bodyReader
}
PutLengthReader(bodyReader)
}
}
b.ReportAllocs()
}
```
Without sync.Pool:
BenchmarkServer_LengthReader-12    	    1808	    700019 ns/op	  240003 B/op	   10000 allocs/op
With sync.Pool
BenchmarkServer_LengthReader-12    	    9516	    127160 ns/op	       0 B/op	       0 allocs/op
This is my first time writing Go code, tried my best to stick to the same style. Successfully passed unit …

Use sync.Pool to reduce lengthReader allocations

---

caddyconfig/httpcaddyfile/httptype.go
caddytest/integration/caddyfile_adapt/log_except_catchall_blocks.txt
caddytest/integration/caddyfile_adapt/log_override_hostname.txt
caddytest/integration/caddyfile_adapt/log_override_name_multiaccess.txt
caddytest/integration/caddyfile_adapt/log_override_name_multiaccess_debug.txt

This took a long while to figure out. https://caddy.community/t/logging-per-subdomain-reverse-proxies/20586
When a site address has a port, the port number would be included as part of `logger_names` in the JSON output. This means that when the request is trying to match a logger, it would never match (therefore not write any access logs) because it would only use the `Host` to match it, which wouldn't have the port if some port forwarding happened.
This is safe because the Caddyfile adapter always makes separate servers even if the same domain with different ports are used in the same site block, so the hostname is unique to each server.

httpcaddyfile: Remove port from logger names

---

modules/caddyhttp/templates/tplcontext.go

templates: Delete headers on `httpError` to reset to clean slate

---

modules/caddyhttp/app.go

Discussed in https://github.com/caddyserver/website/pull/348

caddyhttp: Adjust `scheme` placeholder docs

---

go.mod
go.sum
modules/caddypki/acmeserver/acmeserver.go

This commit upgrades the router used in the acmeserver to github.com/go-chi/chi/v5. In the latest release of step-ca, the router used by certificates was upgraded to that version.
Fixes #5911

go.mod: Upgrade acmeserver to github.com/go-chi/chi/v5

---

usagepool.go

`LoadOrStore`'s comment was incomplete for a long time 😅 . It resulted in confusing godoc description of this method.

chore: Fix usage pool comment

---

modules/caddyhttp/server.go

This reverts commit c8559c448537969376623be9d352949b59907b0e to resolve the following panic:
```
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x18 pc=0x122f9b5]
goroutine 222573 [running]:
github.com/caddyserver/caddy/v2/modules/caddyhttp.(*lengthReader).Close(0x0?)
github.com/caddyserver/caddy/v2@v2.7.6-0.20231024195719-67e567b7ecec/modules/caddyhttp/server.go:931 +0x15
golang.org/x/net/http2.(*clientStream).cleanupWriteRequest(0xc000e49980, {0x0, 0x0})
golang.org/x/net@v0.17.0/http2/transport.go:1550 +0x1a2
golang.org/x/net/http2.(*clientStream).doRequest(0xc000e58f00?, 0x0?)
golang.org/x/net@v0.17.0/http2/transport.go:1327 +0x28
created by golang.org/x/net/http2.(*ClientConn).RoundTrip in goroutine 222537 …
```

Revert "caddyhttp: Use sync.Pool to reduce lengthReader allocations (#5848)"

---

modules/caddyhttp/reverseproxy/reverseproxy.go

Fix [5951](https://github.com/caddyserver/caddy/issues/5951).

reverseproxy: panic when reading from backend failed to propagate stream error

---

modules/caddyhttp/app.go

Stdlib begins to use the new round-robin scheduler in [the commit](https://go-review.googlesource.com/c/net/+/478735). neild also [said this was intended](https://github.com/golang/go/discussions/60746).
Bundled http2 is still using the old scheduler because a change was not made. We are not using the bundled http2, so this change is easy to make.

caddyhttp: http2 uses new round-robin scheduler

---

modules/caddytls/fileloader.go
modules/caddytls/folderloader.go
modules/caddytls/pemloader.go
modules/caddytls/storageloader.go

The values of the certificates loaders are processed verbatim, meaning the replaceable values aren't evaluated. This PR runs the replacer against the user-provided values.
Fixes #5962

tls: accept placeholders in string values of certificate loaders

---

go.mod
go.sum
modules/caddyhttp/proxyprotocol/listenerwrapper.go
modules/caddyhttp/proxyprotocol/module.go
modules/caddyhttp/proxyprotocol/policy.go
modules/caddyhttp/reverseproxy/httptransport.go

Further enhancements can be added later, e.g. advanced allow/denylist policies.
I'll test it out soon, unless someone beats me to the test.

proxyprotocol: use github.com/pires/go-proxyproto

---

caddyconfig/httpcaddyfile/shorthands.go
modules/caddyhttp/logging.go
modules/caddyhttp/replacer.go

Closes #5820
Whenever the `{http.request.uuid}` placeholder is processed, the UUID is also added to the access logs via `ExtraLogFields`.
Added a new Caddyfile shortcut `{uuid}` because why not.
I had to make a new `Set(field)` method for `ExtraLogFields` because otherwise when using `Add(field)`, using the placeholder multiple times in a request would add the log field each time.

caddyhttp: Add `uuid` to access logs when used

---

modules/caddyhttp/metrics.go
modules/caddyhttp/metrics_test.go

If the error returned by the wrapped handler is a `Caddy.HandlerError`, that indicates a problem that still yielded a successful HTTP transaction, so it makes sense to observe request duration and size metrics for it.
See https://github.com/mholt/caddy-ratelimit/pull/35 for some context.

metrics: Record request metrics on HTTP errors

---

logging.go
modules/caddyhttp/reverseproxy/streaming.go

Fix #5938
With this, loggers can be configured with `"with_caller": true` and `"with_stacktrace": "ERROR"` for example, which sets those options on the zap logger.

logging: Add `zap.Option` support

---

caddyconfig/httpcaddyfile/builtins.go

httpcaddyfile: Fix cert file decoding to load multiple PEM in one file

---

modules/caddyhttp/fileserver/browse.html
modules/caddyhttp/fileserver/browsetplcontext.go

Closes #6002
This PR is adding the total file size, human-readable, of all files in a directory listing.
Full-disclosure: this is my first go contribution

browse: Add total file size to directory listing

---

caddy.go
caddytest/caddytest.go
cmd/commandfuncs.go
cmd/main.go
modules/caddyhttp/fileserver/browse.go
modules/caddyhttp/fileserver/staticfiles.go
modules/caddyhttp/templates/tplcontext_test.go

Documentation of `os.ErrNotExist` [says](https://pkg.go.dev/os#IsNotExist) new code should be using `errors.Is(err, fs.ErrNotExist)`. In fact, this fixes a bug where we were checking for `os.ErrNotExist` in the file-server for an error coming from the backing virtual file-system, which might not be the OS.

chore: check against errors of `io/fs` instead of `os`

---

listen.go
listen_unix.go
listen_unix_setopt.go

Solaris 10 and Illumos are missing SO_REUSEPORT. This PR treats them more like Windows (i.e. use the listener pool).
Since https://github.com/caddyserver/caddy/pull/4705 merged, Solaris/Illumos builds of Caddy have been failing. This was reported (and closed) in https://github.com/caddyserver/caddy/issues/5213 and it looked like it was due to missing constants from `sys/unix`.
After more investigation; it's not just missing constants. I actually hardcoded those into a build of Caddy, and it builds and started, but it's not correct because even with `const unixSOREUSEPORT = 0x2004` the behavior from Linux (doubling binding to the same port) doesn't function. This is caught by the test suite as an admin server reload failure:
```
--- FAIL: TestETags (0.00s)
admin_test.go:191: expected …
```

Switch Solaris-derivatives away from listen_unix

---

modules/caddyhttp/reverseproxy/reverseproxy.go

fixes: https://github.com/caddyserver/caddy/issues/5829
currently if a request body was longer than `request_buffers` the `content-length` header sent to the upstream will be wrong, it will be the length of the buffer.
With this change, only in the case that the full request was read into the buffer, because it was set to unlimited length then the `content-length` is changed

reverseproxy: only change the content-length header when the full request was buffered

---

caddyconfig/httpcaddyfile/builtins.go
caddyconfig/httpcaddyfile/tlsapp.go
modules/caddytls/automation.go

This PR exposes certmagic's `ReusePrivateKeys` config to caddy. When certificates renew, by default, new keys are generated. But with this config, the same private keys (if available) can be reused.
Related to #5892 (maybe closes it if a new issue will be opened for TLSA updates as per https://github.com/caddyserver/caddy/issues/5892#issuecomment-1854172687)
**Note:** I'm fairly new to golang so may have missed something, but it seems to work with my naive testing below.
I have a CA that (temporarily) issues self-signed certs valid for 2 mins, making it easy to test renewals. With this sample Caddyfile:
```
https://letsdane {
respond "Body."
tls me+noemail@foo {
ca https://acme.htools.work/directory
}
}
```
run caddy, it gets cert:
```
Issued On	Sunday, 7 January 2024 at 22:15:23
Expires …
```

tls: add reuse_private_keys

---

caddyconfig/httpcaddyfile/builtins.go

This PR adds a case statement to the Caddyfile adapter that parses the TLS section to allow client auth verifiers. Closes #6018

httpcaddyfile: Support client auth verifiers

---

caddyconfig/httpcaddyfile/builtins.go

Before this commit, the response's Content-Type header was set to text/plain, which causes some browsers to treat it as plaintext instead of html, and thereby just showing the html code instead of parsing it and redirecting as expected.
This commit fixes that issue by setting Content-Type to text/html Now the browser parses the response body as HTML, which leads to the redirect working as expected.

httpcaddyfile: Fix redir <to> html

---

caddytest/integration/caddyfile_adapt/uri_replace_brace_escape.txt
caddytest/integration/caddyfile_test.go
replacer.go
replacer_test.go

Resolves #5993. Inside `func (r *Replacer) replace` we were returning the same input if it does not contain the opening brace but which meant that we were not treating the closing brace as a character that should be escaped.

replacer: Fix escaped closing braces

---

caddyconfig/httpcaddyfile/serveroptions.go
modules/caddyhttp/server.go
modules/caddyhttp/server_test.go

This is the first stab at addressing #5804 
Commits are readable in order. This review is easiest done by going through them one-by-one:
- cover existing `client_ip_headers` functionality
- cover existing `trusted_proxy` functionality with custom ranges
- write tests covering both scenarios above in combination
- introduce a failing test proving the potential security weakness of existing `trusted_proxy` + `client_ip_headers` configuration
- introduce a new configuration option (default: false) to opt-in to a safer method of parsing `client_ip_headers`
The first 3 commits provide confidence in maintaining backwards compatibility for those who rely on the existing, left-most parsing of XFF headers. The remaining commits introduce tests + config options (default off) to enable the new …

caddyhttp: Security enhancements for client IP parsing

---

modules/caddyhttp/reverseproxy/caddyfile.go
modules/caddyhttp/reverseproxy/httptransport.go

Example Caddyfile
localhost {
reverse_proxy https://example.com {
tls_curves secp521r1
}
}
}
Long term goal is to be able to configure post-quantum for Caddy -> upstream.

reverseproxy: Add `tls_curves` option to HTTP transport

---

modules/caddyhttp/fileserver/caddyfile.go

As pointed out by @dunglas, we were missing this to make it easier to embed `file_server` within other shortcut directives.

fileserver: Implement caddyfile.Unmarshaler interface

---

caddyconfig/httpcaddyfile/builtins.go
caddytest/integration/caddyfile_adapt/rewrite_directive_permutations.txt
caddytest/integration/caddyfile_adapt/root_directive_permutations.txt
modules/caddyhttp/rewrite/caddyfile.go

I had this idea from reviewing @dunglas's code recently (where he copy-pasted some code from the Caddy codebase itself). The `php_fastcgi` directive uses `RegisterDirective` to get full control of parsing, instead of the `RegisterHandlerDirective` shortcut which does automatic request matcher parsing.
That made me realize we can do the same for `root`, and that we could actually make `root /srv` work, instead of the awkward `root * /srv` with an explicit `*` matcher) that we've been stuck with since v2.0.
Nice and simple, just a small rewrite of the parsing to count the number of arguments first, and if we have only one argument then we can assume it's the actual root path and that there's no matcher, because it never makes sense to ever only pass a matcher to `root` and no root path. …

httpcaddyfile: Rewrite `root` and `rewrite` parsing to allow omitting matcher

---

caddyconfig/httpcaddyfile/builtins.go
caddyconfig/httpcaddyfile/directives.go
caddyconfig/httpcaddyfile/httptype.go
caddytest/integration/caddyfile_adapt/error_multi_site_blocks.txt
caddytest/integration/caddyfile_adapt/error_range_codes.txt
caddytest/integration/caddyfile_adapt/error_range_simple_codes.txt
caddytest/integration/caddyfile_adapt/error_simple_codes.txt
caddytest/integration/caddyfile_adapt/error_sort.txt
caddytest/integration/caddyfile_test.go

Resolves #5928 
I am pretty sure there is a lot that can be improved here since this is my first PR. I particularly don't like the way I add the expression matcher to the subroutes created inside the `parseHandleErrors` and I am pretty there is a better way of doing it.
Thank you in advance for reviewing my code!

httpcaddyfile: Add optional status code argument to `handle_errors` directive

---

caddyconfig/caddyfile/lexer.go
caddyconfig/caddyfile/lexer_test.go

Closes #6048 
@francislavoie. This seemed quick, so I thought I would take a crack at it.

caddyfile: Allow heredoc blank lines

---

caddyconfig/caddyfile/formatter.go
caddyconfig/caddyfile/formatter_test.go
caddyconfig/caddyfile/lexer.go

Fixes https://github.com/caddyserver/caddy/issues/5930
Let the formatter keep heredoc as-is.
Besides, because I missed the review window for #6051, This PR also contains a fix for #6051.
Let me know if you need me to separate them.

caddyfile: Add heredoc support to `fmt` command

---

modules/caddyhttp/matchers.go
modules/caddyhttp/matchers_test.go

Closes #6053 
@francislavoie please let me know if you would rather solve the issue some other way. Thanks!

matchers: `query` now ANDs multiple keys

---

modules/caddyhttp/marshalers.go

Reported in https://caddy.community/t/caddy-v2-health-check-with-php-fastcgi-not-working/22334
Health checks make a `Request` and try to log it with `LoggableHTTPRequest`. When trying to marshal it, we do `GetVar(r.Context(), ClientIPVarKey).(string)` which panics because we never set this var in context for health checks.
Fix is just to type assert in a guard instead of blindly using the value. Good enough.

caddyhttp: Fix panic when request missing ClientIPVarKey

---

caddytest/integration/caddyfile_adapt/log_filter_no_wrap.txt
logging.go
modules/logging/filterencoder.go

I was talking with @dunglas and he pointed out how awkward it is to have to configure `wrap` on the [`filter` encoder](https://caddyserver.com/docs/caddyfile/directives/log#filter) because it loses the nice-to-have default behaviour of checking if `stderr` is a terminal to choose a default of `console` vs `json`.
Getting this to work just right was quite messy, but I think I got it working well now. I also made some adjustments that may or may not be considered breaking changes for some people, since we're changing some default behaviour for the `filter` encoder, and I slightly changed the logic for detecting the terminal.
- we're now checking if `stderr` is a terminal instead of `stdout` because our default writer is `stderr` anyway, it was kinda incorrect to be checking `stdout` I think …

logging: Automatic `wrap` default for `filter` encoder

---

caddyconfig/caddyfile/formatter.go

Fixes #6058
Switch to strings.Builder for better performance.
Converting []rune to string seems to be inefficient.
Or we can simply use slices.Equal from "golang.org/x/exp/slices".
```
(pprof) top10
Showing nodes accounting for 17.37s, 94.30% of 18.42s total
Dropped 126 nodes (cum <= 0.09s)
Showing top 10 nodes out of 37
flat  flat%   sum%        cum   cum%
10.65s 57.82% 57.82%     15.62s 84.80%  runtime.slicerunetostring
4.87s 26.44% 84.26%      4.87s 26.44%  runtime.encoderune
0.56s  3.04% 87.30%      1.78s  9.66%  runtime.scanobject
0.28s  1.52% 88.82%      0.29s  1.57%  runtime.spanOf (inline)
0.23s  1.25% 90.07%      0.23s  1.25%  runtime.heapBits.nextFast (inline)
0.22s  1.19% 91.26%      0.51s  2.77%  runtime.findObject
0.17s  0.92% 92.18%      0.17s  0.92%  runtime.(*gcBits).bitp …
```

caddyfile: Switch to slices.Equal for better performance

---

caddyconfig/caddyfile/lexer.go
caddyconfig/caddyfile/lexer_test.go

Correctly close the heredoc when the closing marker appears immediately

caddyfile: Correctly close the heredoc when the closing marker appears immediately

---

logging.go

Added support to disable output coloring from env variables

---

modules/caddyhttp/celmatcher_test.go
modules/caddyhttp/ip_matchers.go

I think it's been deprecated long enough. Time to remove this insecure option!

matchers: Drop `forwarded` option from `remote_ip` matcher

---

.github/workflows/ci.yml
.github/workflows/cross-build.yml
.github/workflows/lint.yml

We can test on M1 mac now!
But to do so, we need to change `macos-latest` to `macos-14` for now, as per https://docs.github.com/en/actions/using-github-hosted-runners/about-github-hosted-runners/about-github-hosted-runners#standard-github-hosted-runners-for-public-repositories
So for that reason, I decided to reorganize our CI config a bit, and the result is that the job names are now simplified.
- `ubuntu-latest` -> `linux`
- `macos-latest` -> `mac`
- `windows-latest` -> `windows`
See the Actions. Looks cleaner I think.
Before merging @mholt we'll need to update the repo's required jobs config again.

chore: Rename CI jobs, run on M1 mac

---

caddytest/integration/caddyfile_adapt/log_filters.txt
modules/logging/filters.go

Just a small change to allow inlining the IP mask bits.
The config for IP masks is too verbose right now, especially because we log the IP in multiple fields: `request>remote_ip`, `request>client_ip`, and possibly in request headers depending on the clients/proxies.
Before:
```
request>remote_ip ip_mask {
ipv4 16
ipv6 32
}
request>client_ip ip_mask {
ipv4 16
ipv6 32
}
```
After:
```
request>remote_ip ip_mask 16 32
request>client_ip ip_mask 16 32
```

logging: Inline Caddyfile syntax for `ip_mask` filter

---

caddyconfig/caddyfile/parse_test.go
caddyconfig/httpcaddyfile/directives.go
modules/caddyhttp/caddyauth/caddyfile.go

This allows `basic_auth` to work as well in the Caddyfile, and emits a deprecation warning when `basicauth` is used.
This was essentially a mistake in v2.0, we made the decision to use underscores for directives that are multiple words like `file_server` etc, but we left `basicauth`. Since then, we've added `forward_auth`, so `basicauth` feels incongruent with that.
I think now's as good a time as any to realign this.

caddyauth: Rename `basicauth` to `basic_auth`

---

modules/caddyhttp/caddyauth/basicauth.go
modules/caddyhttp/caddyauth/caddyfile.go
modules/caddyhttp/caddyauth/command.go
modules/caddyhttp/caddyauth/hashes.go

It's been deprecated for over a year, time to remove it.
See https://github.com/caddyserver/caddy/pull/4720 for context.
We are changing the interfaces here, so if anyone has a plugin using those interfaces, it'll need updating. But I'm pretty sure there aren't any plugins for additional algorithms right now.

caddyauth: Drop support for `scrypt`

---

modules/caddyhttp/server.go

When trying to enable full duplex for HTTP/2, the warning log was causing a panic because `accessLogger` references an expired pointer to the request, I think.
```
2024/02/13 09:49:06.567	DEBUG	http.stdlib	http2: panic serving 127.0.0.1:48350: runtime error: invalid memory address or nil pointer dereference
goroutine 78 [running]:
golang.org/x/net/http2.(*serverConn).runHandler.func1()
/home/francis/go/pkg/mod/golang.org/x/net@v0.19.0/http2/server.go:2361 +0x145
panic({0x17c9de0?, 0x2bb1fe0?})
/usr/local/go1.22.0.linux-amd64/src/runtime/panic.go:770 +0x132
go.uber.org/zap.(*Logger).check(0x0, 0x1, {0x1a543e7, 0x1c})
/home/francis/go/pkg/mod/go.uber.org/zap@v1.26.0/logger.go:330 +0x5e
go.uber.org/zap.(*Logger).Warn(0x1ef3c20?, {0x1a543e7?, 0x1a67a88?}, {0xc0004c4080, 0x1, 0x1}) …
```

caddyhttp: Only attempt to enable full duplex for HTTP/1.x

---

modules/caddyhttp/app.go
modules/caddyhttp/server.go

Introduces the ability to register hooks to be invoked after the server has shut down. :tada:
@jjiang-stripe

caddyhttp: Register post-shutdown callbacks

---

caddyconfig/caddyfile/parse.go
caddyconfig/caddyfile/parse_test.go
caddyconfig/httpcaddyfile/addresses.go
caddyconfig/httpcaddyfile/httptype.go
caddytest/integration/acme_test.go
caddytest/integration/caddyfile_adapt/http_valid_directive_like_site_address.txt
caddytest/integration/caddyfile_test.go
caddytest/integration/pki_test.go

Resolves #6095  
@francislavoie from my understanding, that's the only change needed but I might be wrong. Also, let me know if you think we need more tests.

caddyfile: Reject directives in the place of site addresses

---

modules/caddyhttp/reverseproxy/reverseproxy.go

Now that the minimal version of go is 1.21, we can safely use `context.WithoutCancel`.

chore: use context.WithoutCancel instead of ignoreClientGoneContext

---

go.mod
go.sum

https://github.com/alecthomas/chroma/pull/932 🎉

chore: Update Chroma to get the new Caddyfile lexer

---

caddyconfig/caddyfile/formatter.go

Fixes: #6099
We assert that heredocClosingMarker is followed by a unicode.Space to simplify the check of heredoc closing
That's about a 10x speed increase in [clusterfuzz-testcase-minimized-fuzz-format-5806400649363456.txt](https://github.com/caddyserver/caddy/files/14233558/clusterfuzz-testcase-minimized-fuzz-format-5806400649363456.txt). 
**Before** 
```
$ time ./caddy fmt clusterfuzz-testcase-minimized-fuzz-format-5806400649363456.txt > /dev/null
Executed in  609.03 millis    fish           external
usr time  721.92 millis  127.15 millis  594.77 millis
sys time   64.97 millis   26.36 millis   38.60 millis
```
**After**
```
$ time ./caddy fmt clusterfuzz-testcase-minimized-fuzz-format-5806400649363456.txt > /dev/null
Executed in   51.12 millis    fish           external
usr time   40.00 …
```

caddyfile: Assert having a space after heredoc marker to simply check

---

caddytest/integration/caddyfile_adapt/tls_client_auth_cert_file-legacy-with-verifier.caddyfiletest
caddytest/integration/caddyfile_adapt_test.go
internal/testmocks/dummyverifier.go
modules/caddytls/connpolicy.go

This was inadvertently missed during #5784. Re-adding Caddyfile support with a test of a dummy verifier to ensure it isn't broken in the future. I know `LeafCertClientAuth` is there, but it doesn't have Caddyfile support. This PR is faster to fix the gap until the `LeafCertClientAuth` module supports Caddyfile.
CC/ @Gr33nbl00d

caddytls: verifier: caddyfile: re-add Caddyfile support

---

caddy.go
context.go

A sponsor found these useful; in particular, the process-global OnExit hooks.
There are also context-scoped OnExit hooks which are cleaned up automatically every config unload (and thus need to be registered every config load, which is part of the module lifecycle anyway).

OnExit hooks

---

modules/caddyhttp/fileserver/staticfiles.go

Replaces https://github.com/caddyserver/caddy/pull/5254
Context: https://caddy.community/t/caddy-stripping-querystring/22754
When a canonicalization redirect happens, it's only taking the path and adding a `/`, which loses the original query if there was one.
This preserves it safely, without making additional modifications to the URL.

fileserver: Preserve query during canonicalization redirect

---

caddytest/integration/caddyfile_test.go
modules/caddyhttp/rewrite/caddyfile.go
modules/caddyhttp/rewrite/rewrite.go

@francislavoie This is my Initial take at #6096. This is still to be improved as only add, delete and set are implemented, but I wanted to get your initial feedback on the overall architecture of the solution before implementing the remaining operations.

rewrite: Implement `uri query` operations

---

caddyconfig/httpcaddyfile/directives.go
caddyconfig/httpcaddyfile/options.go

We (@mholt @dunglas and I) were talking in Slack about the ergonomics of using the Caddyfile for end-users of custom builds of Caddy which may include many handler plugins. Forcing users to specify `order` or wrap things in `route` causes some friction that would be nice to smooth out.
The reason we never did this in the past is because we didn't want to allow plugins to depend upon eachother, because we can't guarantee the order in which plugins are loaded. We also didn't want the ordering to become unreliable when the order of directives in the standard distribution changes.
We can mitigate those factors by doing two things:
- Only allow plugins to register an order for their directive in relation to a directive in Caddy's standard distribution (we keep a `defaultDirectiveOrder` which …

httpcaddyfile: Add `RegisterDirectiveOrder` function for plugin authors

---

caddyconfig/httpcaddyfile/directives.go

This small PR will add the deprecated `skip_log` directive back to the directive order to avoid this error:
`Error: adapting config using caddyfile: directive 'skip_log' is not an ordered HTTP handler, so it cannot be used here - try placing 
See also: 
https://github.com/caddyserver/caddy/pull/6066#issuecomment-1984176170

httpcaddyfile: Keep deprecated `skip_log` in directive order

---

modules/caddyhttp/encode/encode.go

Context: https://caddy.community/t/disappear-103-early-hints-response-with-encode-enable-caddy-v2-7-6/23081
Write status immediately when status code is informational.
Also removed `Hijack` since if `101` is written beforehand, it's already written to the underlying response writer. If not, status should be written to the `net.Conn`. `reverse_proxy` write `101` to the response writer.

encode: write status immediately when status code is informational

---

modules/caddyhttp/responsewriter.go

Fix [6144](https://github.com/caddyserver/caddy/issues/6144).

http: suppress flushing if the response is being buffered

---

modules/caddyhttp/reverseproxy/caddyfile.go
modules/caddyhttp/reverseproxy/httptransport.go

Closes: #6111 
Apologies for the redo. I'm security person by trade so I often fumble through git.
This PR should incorporate corrections discussed in the last PR that I closed.
Grateful for the patience.

reverseproxy: Configurable forward proxy URL

---

caddytest/integration/reverseproxy_test.go
modules/caddyhttp/reverseproxy/caddyfile.go
modules/caddyhttp/reverseproxy/healthchecks.go
modules/caddyhttp/reverseproxy/hosts.go

To fix issue #6152 
Please let me know if this is directionally correct.

reverseproxy: active health check allows configurable health_passes and health_fails

---

modules/caddyhttp/server.go
modules/caddyhttp/server_test.go

Context: https://caddy.community/t/trusted-proxies-in-openshift/23205
As it turns out, some proxies like OpenShift (Red Hat Kubernetes platform) keep the port in the X-Forwarded-For header (or whatever configured client IP header). That's weird, but apparently not unheard of.
We weren't splitting up the value, so when we passed it to `netip.ParseAddr` it would fail, so the `client_ip` in logs didn't get populated. This fixes that, and add some clarifying comments in surrounding code.

caddyhttp: Accept XFF header values with ports, when parsing client IP

---

modules/caddyhttp/vars.go

This is a silly little bug.
I was looking into a possible config to fix an issue for Authelia, and while testing I noticed that `vars` and `vars_regexp` matchers were turning placeholders that return no value (`nil`) into literally the string `"<nil>"` because of the `default:` case doing `fmt.Sprintf("%v", vv)`.
This means that it was impossible to match against nil placeholders by checking for empty string, because the value would always be non-empty. So this fixes a matchers like this:
```
@foo not vars {rp.header.Foo} ""
@bar vars_regexp bar {rp.header.Bar} ^(.+)$
```
These matchers when inside a proxy `handle_response` _should not_ match when the response had a non-empty header value (first one because of `not` negating empty string, and the regexp requiring at least one character), …

vars: Make nil values act as empty string instead of `"<nil>"`

---

modules/logging/encoders.go

The issue caddyserver/transform-encoder#42 made the gap clear. I decided to add a few lines of docs.

logging: support `ms` duration format and add docs

---

caddytest/integration/caddyfile_adapt/uri_query_operations.caddyfiletest
caddytest/integration/caddyfile_test.go
modules/caddyhttp/rewrite/caddyfile.go
modules/caddyhttp/rewrite/rewrite.go

This PR is a followup to close #6096. It implements the replace operation for query strings.

rewrite: `uri query` replace operation

---

modules/caddyhttp/reverseproxy/selectionpolicies.go
modules/caddyhttp/reverseproxy/selectionpolicies_test.go

As per the discussion in issue https://github.com/caddyserver/caddy/issues/6201.
- All changes tested
- Dependency from a reliable source
- [Provable](https://github.com/Cyan4973/xxHash) gains in performance

Added Faster Non-cryptographic Hash Function for Load Balancing

---

modules/caddyhttp/server.go

Fix [6195](https://github.com/caddyserver/caddy/issues/6195).

close quic connections when server closes

---

admin.go

Related issue: https://github.com/caddyserver/caddy/issues/6205
Similar to the non cryptographic hash added in this PR for load balancing: https://github.com/caddyserver/caddy/pull/6203 (related issue: https://github.com/caddyserver/caddy/issues/6201)
Thanks for the helpful discussion @WeidiDeng

Added faster non-cryptographic hash for etag generation

---

README.md

This PR fixes a broken link that returns 404 Not Found in README.md (https://caddyserver.com/v2),
by replacing it with https://caddyserver.com/

chore: Fix broken links in README.md

---

.gitignore

fix main.go based builds importing caddy with that are using `go mod vendor`
Similar to https://github.com/caddyserver/caddy/issues/2237
This fixes the main.go based builds which use `go mod vendor`. The `caddyfile.go` files from every module were being ignored due to the `Caddyfile.*` rule and some git configs being case insensitive.
macOS git is case insensitive by default. Arguable that people should change this git setting but it is the default and having a project not work with the default is bad.
Also the error message you end up getting after cloning on ci servers or another computer if you don't run go mod vendor there(you don't on ci servers, that's the point) is very confusing:
```
vendor/github.com/caddyserver/caddy/v2/modules/standard/imports.go:7:2: cannot find module …
```

gitignore: Add rule for caddyfile.go

---

caddyconfig/caddyfile/importgraph.go
caddyconfig/caddyfile/parse.go

this commit fixes the issue #6224

---

caddytest/integration/caddyfile_adapt/file_server_etag_file_extensions.caddyfiletest
modules/caddyhttp/fileserver/caddyfile.go
modules/caddyhttp/fileserver/staticfiles.go

fileserver: Read Etags from precomputed files

---

modules/caddyhttp/reverseproxy/reverseproxy.go
modules/caddyhttp/reverseproxy/streaming.go

Related to [6173](https://github.com/caddyserver/caddy/pull/6173).
Websockets will show size 0 even if there are data written because the hijacked connection implements both `WriterTo` and `ReaderFrom`, and stats are only updated when the copying is done.
A log entry is like this:
```
{"level":"info","ts":1710675070.8584435,"logger":"http.log.access","msg":"handled request","request":{"remote_ip":"111.181.20.83","remote_port":"12070","client_ip":"111.181.20.83","proto":"HTTP/1.1","method":"GET","host":"example.com","uri":"/random_path","headers":{"Accept-Language":["zh-CN,zh;q=0.9,en-US;q=0.8,en;q=0.7,zh-TW;q=0.6"],"Connection":["Upgrade"],"Pragma":["no-cache"],"Cache-Control":["no-cache"],"User-Agent":["Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like …
```

reverseproxy: Wait for both ends of websocket connections to close

---

caddyconfig/httpcaddyfile/httptype.go
caddytest/integration/caddyfile_adapt/import_args_snippet.caddyfiletest
caddytest/integration/caddyfile_adapt/log_except_catchall_blocks.caddyfiletest
caddytest/integration/caddyfile_adapt/log_multi_logger_name.caddyfiletest
caddytest/integration/caddyfile_adapt/log_override_hostname.caddyfiletest
caddytest/integration/caddyfile_adapt/log_override_name_multiaccess.caddyfiletest
caddytest/integration/caddyfile_adapt/log_override_name_multiaccess_debug.caddyfiletest
caddytest/integration/caddyfile_adapt/log_skip_hosts.caddyfiletest
modules/caddyhttp/logging.go
modules/caddyhttp/server.go

Context: https://caddy.community/t/config-cleanup-for-logging-blocking-and-a-signalr-issue/22643
I realized that there's currently no good way to point a specific hostname to write to more than one logger at once, because `logger_names` is a simple `map[string]string` (so only one value per key).
To solve this, ~~I'm deprecating `logger_names` and adding a new `logger_mapping` (which Caddyfile immediately uses)~~ I'm changing `logger_names` to be a `map[string]StringArray` which is a type which accepts either a JSON string or array (where a string gets turned into a one-element string slice). Then, I reworked the logging code in the server to loop over the list of wrapped loggers.
~~I'm not 100% convinced about the `logger_mapping` name... I'd rather reuse `logger_names`, but obviously we …

caddyhttp: Support multiple logger names per host

---

caddyconfig/caddyfile/dispenser.go
caddyconfig/httpcaddyfile/httptype.go
caddyconfig/httpcaddyfile/serveroptions.go
caddyconfig/httpcaddyfile/tlsapp.go
caddytest/integration/caddyfile_adapt/expression_quotes.caddyfiletest
caddytest/integration/caddyfile_adapt/matcher_syntax.caddyfiletest
caddytest/integration/caddyfile_adapt/shorthand_parameterized_placeholders.caddyfiletest
context.go
modules/caddyhttp/celmatcher.go
modules/caddyhttp/celmatcher_test.go
modules/caddyhttp/fileserver/matcher_test.go
modules/caddyhttp/matchers.go
modules/caddyhttp/routes.go
modules/caddyhttp/vars.go

This is something I've been mulling over for months, I was trying to think of the right solution to solve this, and I think I finally just realized "duh, just add a context map to the dispenser".
The idea is that often users might define a named matcher with a regexp like this:
```
@oldposts path_regexp oldposts ^/post/(.*)$
redir @oldposts /posts/{re.oldposts.1}
```
We wrote `oldposts` a total of four times :grimacing: What if we instead we could omit having to name the regexp, when we've already named the named matcher? With this PR, now this works:
```
@oldposts path_regexp ^/post/(.*)$
redir @oldposts /posts/{re.oldposts.1}
```
Anyway, this is kinda complementary to https://github.com/caddyserver/caddy/pull/6113 but totally independent. With that one, this is possible, by not even …

caddyfile: Populate regexp matcher names by default

---

.github/workflows/ci.yml
cmd/main.go

Follow up for #6032. Only validate config is proper JSON if config slice has data.
Without this fix, running `caddy run` or `caddy start` without any config (not even Caddyfile around) results in the error:
```
Error: config is not valid JSON: unexpected end of JSON input; did you mean to use a config adapter (the --adapter flag)?
Error: caddy process exited with error: exit status 1
```

cmd: Only validate config is proper JSON if config slice has data

---

modules/caddyhttp/app.go
modules/caddyhttp/logging.go
modules/caddyhttp/server.go

Fix https://github.com/caddyserver/caddy/issues/6248
The problem is that we were skipping hosts that have `""` as their logger name (which happens when using the `log` directive with no options).
This is a regression from https://github.com/caddyserver/caddy/pull/6088, but the reporter in #6248 had a different problem on 2.7.6 which I think we've since fixed (causing `skip_hosts` to not work).
Also, I added a `SplitHostPort` in a couple spots cause I realized during testing that we were using the host with the port when we shouldn't to look up the logger names. This more thoroughly completes the idea from https://github.com/caddyserver/caddy/pull/5881

logging: Fix default access logger

---

cmd/main.go
cmd/x509rootsfallback.go
go.mod
go.sum
modules/caddyhttp/caddyhttp.go
modules/caddyhttp/caddyhttp_test.go
modules/caddyhttp/requestbody/caddyfile.go
modules/caddyhttp/requestbody/requestbody.go
modules/caddyhttp/responsewriter_test.go

caddyhttp: Address some Go 1.20 features

---

modules/caddyhttp/responsewriter.go
modules/caddyhttp/reverseproxy/streaming.go

Fix [6273](https://github.com/caddyserver/caddy/issues/6273).
The cause of the problem can be found in the [comment](https://github.com/caddyserver/caddy/issues/6273#issuecomment-2078415617).

reverse_proxy: handle buffered data during hijack

---

caddyconfig/caddyfile/lexer.go
caddyconfig/httpcaddyfile/httptype.go
caddytest/integration/caddyfile_adapt/expression_quotes.caddyfiletest

Fixes https://github.com/caddyserver/caddy/issues/6287

httpcaddyfile: Fix expression matcher shortcut in snippets

---

modules/caddyhttp/reverseproxy/httptransport.go

transport: fix proxy protocol initialization

---

modules/caddyhttp/reverseproxy/caddyfile.go
modules/caddyhttp/reverseproxy/healthchecks.go

reverseproxy: Stop following redirects in health checks by default, add `health_follow_redirects`

---

modules/caddyhttp/tracing/tracer.go

Adds the ability to use `trace_id` as a placeholder so it can be used wherever it is needed.  Such as being returned in a header to the client.

tracing: add `http.vars.trace_id` placeholder

---

caddyconfig/httpcaddyfile/builtins.go
caddyconfig/httpcaddyfile/directives.go
caddyconfig/httpcaddyfile/httptype.go
caddytest/integration/caddyfile_adapt/log_filter_with_header.txt
modules/caddyhttp/logging.go
modules/caddyhttp/server.go

closes #5978 
@francislavoie This took some time but here is my initial implementation of this. Would like to get your feedback on this and your thoughts on what other tests should go in here? Thanks.

logging: Add support for additional logger filters other than hostname

---

go.mod
go.sum
modules/caddytls/certmanagers.go

Set the requested server name in a context value for certmagic.Manager implementations to use. Pass ctx to tscert.GetCertificateWithContext.
This relies on https://github.com/tailscale/tscert/pull/9 to be merged first, which adds the new tscert.GetCertificateWithContext method.  This will enable https://github.com/tailscale/caddy-tailscale/pull/53, which enables the use of auto_https with tsnet servers running inside of caddy.
This PR only attaches the server name inside the Tailscale certmagic.Manager.  I tried to find the right place to attach it for all managers, but couldn't seem to find it.  I'd love some pointers for where to put this.
/cc @mholt

caddytls: set SNI server name in context

---

modules/caddyhttp/fileserver/browse.html
modules/caddyhttp/templates/templates.go
modules/caddyhttp/templates/tplcontext.go

See #6237
Unsure about including a function from the `url` module in `c.tpl.Funcs`, but I see little point in adding a wrapper for it.
(Also, perhaps more functions from the `url` module should be made available in templates.)

templates: Add `pathEscape` template function and use it in `browse.html`

---

caddyconfig/httpcaddyfile/serveroptions.go
modules/caddyhttp/app.go
modules/caddyhttp/logging.go
modules/caddyhttp/routes.go
modules/caddyhttp/server.go

This has been on my mind for years. Just a simple way to see which middleware handlers are being invoked during a request.
Requires DEBUG level logging to be enabled, as well as explicitly opting-in to trace logs. Here is an example global option config along with a sample server in a Caddyfile:
```
{
debug
servers {
trace
}
}
:1234 {
root /asdf
file_server browse
encode gzip zstd
templates
rewrite /foo /bar
log
}
```
Making a simple request using `curl -v http://localhost:1234` I get:
```
2024/05/10 22:32:52.613 DEBUG   http.log.trace  vars    {"module": {"root":"/asdf"}}
2024/05/10 22:32:52.613 DEBUG   http.log.trace  encode  {"module": {"prefer":["gzip","zstd"],"minimum_length":512,"match":{"headers":{"Content-Type":["application/atom+xml*","application/eot*","application/font*","applic …
```

caddyhttp: Trace individual middleware handlers

---

modules/caddytls/certmanagers.go

It turns out this is unnecessary due to certmagic setting the entire ClientHelloInfo on the context using `certmagic.ClientHelloInfoCtxKey`.

caddytls: remove ClientHelloSNICtxKey

---

modules/caddytls/automation.go

Certificate automation has permission modules that are designed to prevent inappropriate issuance of unbounded or wildcard certificates. When an explicit cert manager is used, no additional permission should be necessary. For example, this should be a valid caddyfile:
https:// {
tls {
get_certificate tailscale
}
respond OK
}
This is accomplished when provisioning an AutomationPolicy by tracking whether there were explicit managers configured directly on the policy (in the ManagersRaw field). Only when a number of potentially unsafe conditions are present AND no explicit cert managers are configured is an error returned.
The problem arises from the fact that ctx.LoadModule deletes the raw bytes after loading in order to save memory. The first time an AutomationPolicy is provisioned, the …

caddytls: fix permission requirement with AutomationPolicy

---

modules/caddyhttp/reverseproxy/httptransport.go

VERY EXPERIMENTAL. Enables HTTP/3 protocol from proxy to backend ("upstream").
I still don't fully understand why this would be needed/useful, but here is a quick stab attempt with the APIs available to us.
**Enabling HTTP/3 necessarily disables other HTTP versions. (If you specify version "3" in your config, you cannot have any other versions.) We do not support protocol downgrade or negotiation like web browsers do.** That would probably add considerable latency and complexity where you should already have control over the backends. Additionally, other HTTP transport options don't apply to the HTTP/3 round-tripper because it does not use the `http.Transport` type like the lower HTTP versions.
Example Caddyfile:
```
{
servers :1235 {
protocols h3
}
}
:1234 {
reverse_proxy localhost:1235 …
```

reverseproxy: Support HTTP/3 transport to backend

---

modules/caddyhttp/autohttps.go

We've seen some users be confused about warnings surrounding Auto HTTPS in the logs. I don't think these need to be warnings, it doesn't really add much value. It's just tracing through whether things are enabled or not, it's not really an actionable problem.

autohttps: Move log WARN to INFO, reduce confusion

---

caddyconfig/caddyfile/parse.go
caddyconfig/caddyfile/parse_test.go

Fixes https://github.com/caddyserver/caddy/issues/6332

caddyfile: Reject global request matchers earlier

---

caddy.go

appDataDir components should be searchable (u+x) when they are created, or else Caddy is unable to start with an empty HOME.

core: MkdirAll appDataDir in InstanceID with 0o700

---

caddytest/integration/caddyfile_adapt/matcher_syntax.caddyfiletest
modules/caddyhttp/ip_matchers.go

Fixes https://github.com/caddyserver/caddy/issues/6349

caddyhttp: Fix merging consecutive `client_ip` or `remote_ip` matchers

---

cmd/main.go
cmd/main_test.go

Regression caused by #6356 
Reported here:
- https://caddy.community/t/error-in-logs-with-updating-ari-after-upgrading-to-caddy-v2-8-1/24320/12
- https://github.com/caddyserver/caddy/pull/6356#issuecomment-2143713053
- fixes https://github.com/caddyserver/caddy/issues/6363

cmd: fix regression in auto-detect of Caddyfile

---

modules/caddytls/tls.go

See discussion about this setting in https://github.com/caddyserver/certmagic/issues/201
Note that this doesn't expose the setting through the caddyfile, I guess that would have to happen just-about-here: https://github.com/framer/caddy/blob/5b13f9272454ea13105689fbe24a14b00421f901/caddyconfig/httpcaddyfile/tlsapp.go#L331-L334
Not sure whether that's wanted/needed, and if it is, how to best name it?
I did consider another idea of injecting some sort of "configuration adapter" here, which would take a certmagic config, do whatever it needs to do, and then return the adapted config. This could over the long term be nicer, especially for these kind of special options -- but it would also open the world to a lot more mischief. WDYT?

Make it possible to configure the `DisableStorageCheck` setting for certmagic

---

cmd/main.go
cmd/main_test.go

Turns out, it isn't uncommon to have `Caddyfile.prod` and such (https://github.com/caddyserver/caddy/pull/6362#discussion_r1623414880). This is mentioned on the website as:
> This flag is not necessary if the --config filename starts with "Caddyfile" which assumes the caddyfile adapter
[Source](https://caddyserver.com/docs/command-line#caddy-run)
Fixes https://github.com/caddyserver/caddy/issues/6373

cmd: remove zealous check of Caddyfile auto-detection

---

.github/workflows/ci.yml
.github/workflows/release.yml
.goreleaser.yml

I ran `goreleaser check` and the version field is the only thing it complained about.

ci: upgrade to goreleaser v2

---

modules/logging/filewriter.go
modules/logging/filewriter_test.go
modules/logging/filewriter_test_windows.go

Adding a "mode" option to overwrite the default logfile permissions.
Default remains "0600" which is the one currently used by lumberjack.
Fixes #6295 
I am assuming that Mode = 0 triggers usage of default mode "0600". That implies that users cannot use a "0000" mode for their log files. This sounds reasonable to me, but your opinion here would be appreciated.
I did not test the PR in production. I only tested in local and all went fine. Beware that your umask may interfere with the mode from the config: this is why umask is unset in the tests.
This is my first PR here. I would appreciate great care in the code review, I am fully open to your comments of course.
Cheers.

logging: Allow setting log file permissions

---

caddy.go

`BuildContext` can be used to set up a caddy context from a config, but not start any listeners or active components: The returned context has the configured apps provisioned, but otherwise is inert.
This is EXPERIMENTAL: Minimally it's missing documentation and the example for how this can be used to run unit tests.
---
For context: What I'm trying to do is write unit tests, where I take a (partial) configuration for caddy and then build a context from that. The context is then used to provision modules that need testing, possibly with some weird configuration etc. The problem with the current caddy codebase is that there's no good way to do get to such a context, as on the one hand it has some important private fields (`apps`), and on the other hand all functions making a context either …

Split `run` into a public `BuildContext` and a private part

---

modules/caddyhttp/responsewriter.go

In one of our modules we had this code:
```go
buf := new(bytes.Buffer)
shouldBuffer := func(status int, header http.Header) bool {
// Returning false means headers/body will be streamed out directly to the underlying writer.
return false
}
ww := caddyhttp.NewResponseRecorder(w, buf, shouldBuffer)
// Do stuff with ww
// ...
// Write response and return error if needed
return ww.WriteResponse()
```
This worked, but when reading through the sources of caddy and the documentation of NewResponseRecorder we realized that we could also initialize it without the buffer and function:
```golang
ww := caddyhttp.NewResponseRecorder(w, nil, nil)
```
This matches how caddy initializes it, and is explicitly allowed in the docs.
However, with that change we noticed panics happening:
```
runtime.gopanic …
```

Write the header if none had been written in WriteResponse

---

modules/logging/filewriter.go
modules/logging/filewriter_test.go

Commit 101d3e7 introduced file mode setting,
but was missing a JSON Marshaller so that
CaddyFile can be converted to JSON safely.

fix file mode configuration parsing

---

go.mod
go.sum

The latest tscert [allows callers](https://github.com/tailscale/tscert/pull/11) to provide a custom http.Transport for calling Tailscale's local API.
Updates tailscale/caddy-tailscale#66

go.mod: update tscert package

---

modules/logging/filewriter.go
modules/logging/filewriter_test.go

101d3e7 introduced a configuration option to set the log file mode. This option was not taken into account if the file already exists, making users having to delete their logs to have new logs created with the right mode.
This was initially spotted in the discussion for 0bc27e5.
This will allow users to set the mode in CaddyFile and restart their server without the need to remove previous logs.
As suggested in the commit discussion I will open a separate PR to document that log files options require a server restart to be taken into account, when the log file destination does not change.

logging: set file mode when the file already exist.

---

modules/caddyhttp/reverseproxy/selectionpolicies.go

reverseproxy: add Max-Age option to sticky cookie

---

caddytest/integration/intercept_test.go
modules/caddyhttp/intercept/intercept.go

I introduced a bug in #6232: `http.intercept.header.*` placeholders contain request headers instead of original response headers.
This patch fixes the issue.
Closes https://github.com/dunglas/frankenphp/issues/884.

fix: http.intercept.header.* placeholders

---

modules/caddyhttp/reverseproxy/healthchecks.go

Fixes #6415
This changes the behavior of logging to only log the host up-state on state changes.
I manually tested it in the setup I needed it in and I noticed that if the upstream is available immediately the line is not logged. That leads me to believe that the event is also not emitted? I am again unsure if this is the intended behavior.
Thanks!

reverseproxy: Only log host is up status on change

---

listeners.go
modules/caddyhttp/ip_matchers.go
modules/caddyhttp/matchers.go
modules/caddyhttp/replacer.go
modules/caddyhttp/reverseproxy/reverseproxy.go

See RFC 8470: https://httpwg.org/specs/rfc8470.html
- We now reject matching IPs when the TLS handshake has not completed.
- This also adds a new HTTP matcher, the `tls` matcher, which can match on properties of the underlying TLS connection. For now the only property is whether the TLS handshake has completed; we can add more later if needed. This could be useful for configuring HTTP 425 responses for unwanted Early Data.
- Set the `Early-Data: 1` header in the reverse proxy if the handshake has not completed. We don't enforce the other rules regarding this header since the user would have to explicitly configure violating behavior, which they may have good reason for or may not actually be in violation, so my current answer to that would be "don't do that".
- The …

caddyhttp: Reject 0-RTT early data in IP matchers and set Early-Data header when proxying

---

modules/caddyhttp/reverseproxy/healthchecks.go

Should resolve https://caddy.community/t/can-you-pass-in-the-full-upstream-to-an-active-health-check/24718/3

reverseproxy: Add placeholder for host in active health check headers

---

modules/caddyhttp/fileserver/browse.html

This PR addresses the Content-Security-Policy warnings in Firefox: https://github.com/caddyserver/caddy/pull/6425#issuecomment-2211816751
The following changes have been made:
1. **Remove `strict-dynamic` from `style-src`**:
> Content-Security-Policy: Ignoring source “strict-dynamic” (Only supported within script-src).
2. **Remove `block-all-mixed-content`**:
> Content-Security-Policy: Ignoring ‘block-all-mixed-content’ because mixed content display upgrading makes block-all-mixed-content obsolete.
See also: https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Content-Security-Policy/block-all-mixed-content
3. **Remove `strict-dynamic`, `https:`, and `http:` from `script-src`**:
> Content-Security-Policy: Ignoring “'unsafe-inline'” within script-src: ‘strict-dynamic’ specified
> …

browse: fix Content-Security-Policy warnings in Firefox

---

.github/workflows/ci.yml
modules/caddyhttp/fileserver/browse.html
modules/caddyhttp/fileserver/browsetplcontext.go

Closes https://github.com/caddyserver/caddy/issues/6409

fileserver: Exclude symlink target size from total, show arrow on size

---

modules/caddyhttp/reverseproxy/upstreams.go
modules/caddyhttp/reverseproxy/upstreams_test.go

reverseproxy: Fix dynamic upstreams ip version

---

modules/caddyhttp/reverseproxy/healthchecks.go

Follows: https://github.com/caddyserver/caddy/pull/6440
Previously `hostAddr` would duplicate the `Host` header. This now appropriately passes the full original upstream:
```diff
5.0.0.33 - - [09/Jul/2024 15:35:04] "GET /health HTTP/1.1" 200 -
+Host: 5.0.0.33:53336
User-Agent: Go-http-client/1.1
+Full-Upstream: 5.0.0.33:8545
Accept-Encoding: gzip
```
Resolves forum post: https://caddy.community/t/can-you-pass-in-the-full-upstream-to-an-active-health-check/24718

reverseproxy: Add placeholder for networkAddr in active health check headers

---

modules/caddyhttp/reverseproxy/healthchecks.go

Added the option `Method` to the `ActiveHealthChecks` struct, which optionally sets the HTTP method used for the health check requests.
It would be good to be able to use the `HEAD` HTTP method to limit transfers on upstreams that respond with a large body, or other methods for upstreams that only respond sensibly on eg. `POST`.
I specifically have a JSON RPC upstream that I would like to test and see if it is working. It has a well defined response body to a `POST` request, that lets the active health check determine if the underlying service is actually up and ready to serve requests.

Add option to set which HTTP method to use for active health checks

---

caddytest/integration/caddyfile_adapt/reverse_proxy_health_method.caddyfiletest
modules/caddyhttp/reverseproxy/caddyfile.go

Adds Caddyfile support for setting the request method used for reverse proxy active health checks. 
Follow up to https://github.com/caddyserver/caddy/pull/6453, spurred on by https://github.com/caddyserver/caddy/pull/6453#issuecomment-2223293904
Note: There is no check on which HTTP verb is accepted as apparently some people like to make up their own.

reverseproxy: Caddyfile support for health_method

---

modules/caddyhttp/reverseproxy/caddyfile.go
modules/caddyhttp/reverseproxy/healthchecks.go
modules/caddyhttp/reverseproxy/hosts.go

Currently in draft to update the documentation with the new subdirective.
Respective docs PR: https://github.com/caddyserver/website/pull/406
Log when `health_port` and `health_upstream` is used:

reverseproxy: add health_upstream subdirective

---

.github/workflows/ci.yml

s/nobdger/nobadger
Seems like an oversight from https://github.com/caddyserver/caddy/pull/6031

ci: correct `-tags nobadger` on binary build

---

modules/caddytls/matchers.go

This PR is related to https://github.com/mholt/caddy-l4/pull/217. It implements caddyfile support for TLS handshake matchers:
- `local_ip` by caddytls.MatchLocalIP
- `remote_ip` by caddytls.MatchRemoteIP
- `sni` by caddytls.MatchServerName
P.S. I noticed, we have NotRanges in caddytls.MatchRemoteIP, but don't have them in caddytls.MatchLocalIP. Shall we fix this inconsistency as well?

Caddyfile support for TLS handshake matchers

---

modules/caddytls/certselection.go
modules/caddytls/connpolicy.go

This PR is related to https://github.com/mholt/caddy-l4/pull/217. It implements caddyfile support for TLS connection and certificate selection policies:
- `cert_selection` by caddytls.CustomCertSelectionPolicy
- `connection_policy` by caddytls.ConnectionPolicy

Caddyfile support for TLS connection and certificate selection policies

---

caddytest/integration/caddyfile_adapt/file_server_sort.caddyfiletest
modules/caddyhttp/fileserver/browse.go
modules/caddyhttp/fileserver/browsetplcontext.go
modules/caddyhttp/fileserver/caddyfile.go
modules/caddyhttp/fileserver/staticfiles.go

I have tested the config:
```
:8082 {
root * .
file_server browse {
sort size desc
}
}
```
Additionally, a `.caddyfiletest` file were wrote, but I don't know how to run it.
The related doc PR can be found [here](https://github.com/caddyserver/website/pull/407).

fileserver: add `sort` options

---

internal/ranges.go
modules/caddyhttp/ip_matchers.go
modules/caddyhttp/ip_range.go
modules/caddyhttp/reverseproxy/caddyfile.go
modules/caddytls/matchers.go

This PR follows https://github.com/mholt/caddy-l4/pull/224 and deals with the following mainline matchers only:
- caddytls.MatchLocalIP
- caddytls.MatchRemoteIP
- caddytls.MatchServerName
- caddyhttp.MatchClientIP
- caddyhttp.MatchRemoteIP
These changes allow to use runtime placeholders with TLS and HTTP IP matchers, e.g. `remote_ip {env.VAR}`. Such placeholders, if present, are evaluated **once at provision** due to the existing optimisations.
In addition, this PR adds runtime placeholders support for TLS SNI matcher, e.g. `sni {env.VAR}`. Contrary to the above, such placeholders are evaluated **each time at match**.

Runtime placeholders for selected TLS and HTTP matchers

---

modules/caddyhttp/reverseproxy/httptransport.go

Fix [6342](https://github.com/caddyserver/caddy/issues/6342).

reverse_proxy: apply keep-alive setting for h2c requests

---

modules/caddyhttp/ip_range.go

As discussed in https://github.com/mholt/caddy-l4/pull/224, let's move PrivateRangesCIDR() back to caddyhttp and caddytls after #6480.

caddyhttp: Export PrivateRangesCIDR() for plugins after #6480

---

cmd/commandfuncs.go

Fix [6508](https://github.com/caddyserver/caddy/issues/6508).

ignore exec.ErrDot when starting caddy in background

---

.github/workflows/ci.yml

GitHub Actions shell scripts are loaded with `set -e`, which tells the shell to exit at any error. The impact on our flow is missing the deletion step of the code for every failed CI run on the remote machine. This PR fixes it so No Files Left Behind.

ci: don't exit early on error in remote CI machine

---

caddytest/integration/caddyfile_adapt/reverse_proxy_health_reqbody.caddyfiletest
modules/caddyhttp/reverseproxy/caddyfile.go
modules/caddyhttp/reverseproxy/healthchecks.go

Added the field `Body` to the `ActiveHealthChecks` struct, which optionally sets the body of the request used for the health check requests.
Also added `Caddyfile` support for the same option under the name `health_request_body`. 
After adding the option to setting the HTTP method used for active health checks it turns out it's also helpful to set the body. Eg when using the POST method on a JSON RPC service with an empty body may return a `400 Bad Request`, instead of a `200 OK`. Being able to set the body to a valid NOOP RPC call enables a "deeper" health check, than just accepting the 400 status.

reverseproxy: Active health checks request body option

---

modules/caddyhttp/reverseproxy/reverseproxy.go

Most of the errors that can be seen here are write errors due to clients aborting the request from their side. Often seen ones include:
* writing: ... write: broken pipe
* writing: ... connection timed out
* writing: http2: stream closed
* writing: timeout...
* writing: h3 error...
Most of these errors are beyond of the control of caddy on the client side, probably nothing can be done on the server side. It still warrants researching when these errors occur very often, so a change in level from error to warn is better here to not polute the logs with errors in the normal case.

reverseproxy: Change logs for write errors to warn level

---

cmd/cobra.go
cmd/commandfactory.go
cmd/commands.go
cmd/main.go

since only one instance of the cobra root command exists in production branch, this means that only one copy of the caddy app can be running within a process at a time. along with that, a run of the command leaves command state dirty, which could have unintended consequences.
this is a major problem in being able to properly test caddy through the command wrapper. 
in general - having such global state is a code smell, and we should strive to remove them from the codebase when possible

cmd: Use a factory to create the caddy root command

---

caddytest/caddytest_test.go
modules/caddyhttp/staticerror.go

error: run `error` (msg) through replacer

---

caddytest/integration/caddyfile_adapt/reverse_proxy_localaddr.caddyfiletest
modules/caddyhttp/reverseproxy/caddyfile.go
modules/caddyhttp/reverseproxy/httptransport.go

reverseproxy: allow user to define source address

---

.github/workflows/ci.yml
.github/workflows/cross-build.yml
.github/workflows/lint.yml
.github/workflows/release.yml
README.md
caddyconfig/caddyfile/dispenser.go
go.mod
modules/caddyhttp/celmatcher.go

Adds [Go 1.23](https://go.dev/doc/go1.23) to the CI/CD pipeline.
Removes support for Go 1.21, which isn't maintained anymore.
Bumps golangci-lint to v1.60 (needed for Go 1.23) and fixes newly discovered errors.

chore: build and test with Go 1.23

---

modules/caddyhttp/reverseproxy/reverseproxy.go

The `reverse_proxy` directive in Caddy already supports a variety of useful placeholders, as documented [here](https://caddyserver.com/docs/json/apps/http/servers/routes/handle/reverse_proxy/#docs)
This pull request proposes the addition of a new placeholder: `{http.reverse_proxy.lb.retries}`. This placeholder tracks the number of retries actually performed by the load balancer to communicate with an upstream. I believe this would be a valuable enhancement, providing more detailed insights into load balancing behavior.
For example, in a Caddyfile, this placeholder might be used with `log_append` like this:
```Caddyfile
:8080 {
log {
output file /var/log/access.json
}
reverse_proxy {
to localhost:7070
to localhost:7071
to localhost:7072
health_uri /ping
health_body pong
health_interval 15s …
```

reverse_proxy: add placeholder http.reverse_proxy.retries

---

modules/caddyhttp/routes.go

ref: https://github.com/caddyserver/caddy/issues/6551

fix(#6551): Unexpected behaviour if caddyhttp.Route is provisioned twice   

---

modules/caddytls/matchers.go
modules/caddytls/matchers_test.go

This is an implementation of `sni_regexp` matcher requested in https://github.com/mholt/caddy-l4/issues/241.
Example syntax:
```
{
layer4 {
:8443 {
@test tls sni_regexp ^(one|two)\\.example\\.com$
route @test {
proxy {tls.regexp.1}.internal:443
}
}
}
}
```
Disclaimer: I haven't tested it extensively, so it's subject to feedback of the requestors.

caddytls: Add sni_regexp matcher

---

modules/caddyhttp/rewrite/caddyfile.go

All cases for args[0] require additional arguments present in the slice so doing the bounds check here covers all cases. Cases requiring additional parameters already include additional checks on the len(args)

rewrite: Avoid panic on bad arg count for `uri`

---

.github/workflows/lint.yml
.golangci.yml
modules/caddyhttp/server.go

ci: update the linter action version

---

go.mod
go.sum

Main feature (for Caddy): HTTP Trailer support.
For more details see [release notes](https://github.com/quic-go/quic-go/releases/tag/v0.47.0).

update quic-go to v0.47.0

---

admin.go
caddyconfig/caddyfile/importgraph.go
caddyconfig/httpcaddyfile/directives.go
caddyconfig/httpcaddyfile/httptype.go
caddyconfig/httpcaddyfile/options.go
caddyconfig/httpcaddyfile/serveroptions.go
caddyconfig/httpcaddyfile/tlsapp.go
modules/caddyevents/app.go
modules/caddyhttp/autohttps.go
modules/caddyhttp/encode/encode.go
modules/caddyhttp/fileserver/browsetplcontext.go
modules/caddyhttp/headers/headers.go
modules/caddyhttp/map/map.go
modules/caddyhttp/matchers.go
modules/caddyhttp/reverseproxy/healthchecks.go
modules/caddyhttp/reverseproxy/httptransport.go
modules/caddyhttp/server.go
modules/caddyhttp/templates/frontmatter.go
modules/caddytls/automation.go
modules/caddytls/certselection.go
modules/caddytls/matchers.go

Just a simple cleanup, we can use `slices.Contains()` in a bunch of spots now instead of helper functions to do the simple loop.

chore: Use slices package where possible

---

listeners.go
modules/caddyhttp/app.go

feat. a right side in TLS listener wrapper and more descriptive error handling in `listen`

caddyhttp: Fix listener wrapper regression from #6573

---

modules/caddyhttp/reverseproxy/caddyfile.go

Pretty self explanatory, these were outdated.

chore: Adjust incorrect `reverse_proxy` Caddyfile comment

---

.github/workflows/ci.yml
.golangci.yml
go.mod
go.sum
modules/caddyhttp/celmatcher.go
modules/caddyhttp/celmatcher_test.go
modules/caddyhttp/fileserver/matcher.go
modules/caddyhttp/matchers.go
modules/caddyhttp/templates/templates.go
modules/caddyhttp/templates/tplcontext.go
modules/caddyhttp/vars.go

Related to https://github.com/caddyserver/caddy/issues/6584, prior work in https://github.com/caddyserver/caddy/pull/4715#issuecomment-1163585563
Our current CEL placeholder regexp is too naive. It replaces everything that looks like a placeholder, and offers no good option to opt out if a literal placeholder-looking input is given to some CEL functions as input.
To solve this, we can do the placeholder replacement in two steps.
- First, we match whether the placeholder _is not_ preceded by a `\` (or start of a line) and replace it and preserving the preceding character which is matched (we now have two capture groups so `${1}` has to go to the start)
- Second, we match for a placeholder which _does_ have a preceding `\`, and drop the `\`.
That gives a way to escape through the …

caddyhttp: Escaping placeholders in CEL, add `vars` and `vars_regexp`

---

caddyconfig/httpcaddyfile/httptype.go
caddyconfig/httpcaddyfile/options.go
caddyconfig/httpcaddyfile/tlsapp.go
caddytest/integration/caddyfile_adapt/auto_https_prefer_wildcard.caddyfiletest
caddytest/integration/caddyfile_adapt/wildcard_pattern.caddyfiletest
caddytest/integration/mockdns_test.go
modules/caddyhttp/autohttps.go

Closes https://github.com/caddyserver/caddy/issues/5447
This implements a new `auto_https prefer_wildcard` option, which drops automation policies for non-wildcard domains when there's already a wildcard in another policy.
This allows users to flatten their config, and instead of using a pattern like https://caddyserver.com/docs/caddyfile/patterns#wildcard-certificates they can instead do something like:
```
{
auto_https prefer_wildcard
}
*.example.com {
tls {
dns <provider>
}
respond "fallback"
}
foo.example.com {
respond "foo"
}
```
This would only produce a single wildcard certificate, and no individual certificate for `foo.example.com` since it's already covered by the wildcard.
This also allows specifying multiple arguments to `auto_https`, so you can do the following to set multiple …

autohttps: Implement `auto_https prefer_wildcard` option

---

caddyconfig/httpcaddyfile/options.go
caddytest/integration/caddyfile_adapt/global_options.caddyfiletest
caddytest/integration/caddyfile_adapt/global_options_acme.caddyfiletest
caddytest/integration/caddyfile_adapt/global_options_admin.caddyfiletest
modules/caddytls/automation.go
modules/caddytls/ondemand.go
modules/caddytls/tls.go

It's time to get rid of these, they're not working correctly and introduce more problems than they solve, when used.

caddytls: Drop `rate_limit` and `burst`, has been deprecated

---

caddytest/integration/caddyfile_adapt/acme_server_sign_with_root.caddyfiletest
caddytest/integration/caddyfile_adapt/heredoc.caddyfiletest
caddytest/integration/caddyfile_adapt/map_and_vars_with_raw_types.caddyfiletest

They've been bothering me for too long

tests: Fix adapt test warning

---

caddyconfig/caddyfile/parse.go
caddyconfig/caddyfile/parse_test.go

When the site address line looks like `foo  ,  bar` (i.e. spaces around the `,` and not simply a comma trailing an address), then it would cause the site address to include an empty space which messes up parsing in subtle ways. This fixes that case.
Closes https://github.com/caddyserver/website/issues/395
Given this Caddyfile:
```
foo.example.com , example.com , www.example.com {
respond "foo"
}
```
Before (for some reason, no host matchers are produced, but it does automate the names):
```
{"apps":{"http":{"servers":{"srv0":{"listen":[":443"],"routes":[{"handle":[{"body":"foo","handler":"static_response"}]}]}}},"tls":{"certificates":{"automate":["foo.example.com","example.com","www.example.com"]}}}}
```
After (properly matching the hosts, later resulting in Auto HTTPS automating):
``` …
```

caddyfile: Fix comma edgecase in address parsing

---

go.mod
go.sum
modules/caddyhttp/reverseproxy/httptransport.go

Release notes: https://github.com/quic-go/quic-go/releases/tag/v0.48.0
Most relevant for Caddy: We now have support for server-side graceful shutdown.

chore: update quic-go to v0.48.0

---

caddyconfig/httpcaddyfile/httptype.go
caddyconfig/httpcaddyfile/options.go
caddyconfig/httpcaddyfile/serveroptions.go
caddytest/integration/caddyfile_adapt/metrics_merge_options.caddyfiletest
modules/caddyhttp/app.go
modules/caddyhttp/metrics.go
modules/caddyhttp/server.go

This change moves the metrics configuration from per-server level to a single config knob within the `http` app. Enabling `metrics` in any of the configured servers inside `http` enables metrics for all servers.
Fix #6604

metrics: move `metrics`  up, outside `servers`

---

sigtrap_posix.go

Backport of https://github.com/dunglas/frankenphp/pull/1101 to Caddy itself.
Sometimes (especially when using systemd), `SIGPIPE` signals can crash the server. This patch always ignore SIGPIPE, for all file descriptors.

fix: always ignore SIGPIPE

---

modules/caddyhttp/fileserver/matcher.go
modules/caddyhttp/fileserver/matcher_test.go
modules/caddyhttp/fileserver/testdata/large.txt

I found a minor bug in #6623 for the `file` matcher when written as a CEL expression.
This PR corrects the current reassignment of `root`, and adds a test to ensure the correct property is set.

fileserver: fix try_policy when instantiating file matcher from CEL

---

modules/caddyhttp/server_test.go
modules/caddyhttp/tracing/tracer.go

In [PR #5507](https://github.com/caddyserver/caddy/pull/5507), the `traceid` was added to the logs. To further align with the [OpenTelemetry Log Correlation specification](https://opentelemetry.io/docs/specs/otel/logs/#log-correlation) and achieve complete log correlation using trace context, we have now included the `spanid` alongside the `traceid`.
I conducted benchmarks to assess the performance impact of adding the `spanid`. Since `traceid` and `spanid` are always used together, I modified the existing benchmarks for `traceid` to include `spanid`. Below is the performance comparison before and after adding the `spanid`:
<details> <summary>Before:</summary>
<pre><code>
$ go test -benchtime=3s -count=10 -benchmem -run=^$ -bench ^BenchmarkServer ./modules/caddyhttp | tee before.txt
goos: …

tracing: Add `spanID` field to access logs and `http.vars.span_id` placeholder

---

modules/caddyhttp/headers/headers.go
modules/caddyhttp/reverseproxy/reverseproxy.go

Sourced from https://github.com/golang/go/commit/960654be0c4ad7918376e2e1d47491c9bc7520e0
Also usage of `clear(h)` from https://github.com/golang/go/commit/3bc28402fae2a1646e4d2756344b5eb34994d25f

reverseproxy: Sync changes from stdlib for 1xx handling

---

.github/workflows/cross-build.yml
.goreleaser.yml
README.md

I had issues with nosql that only supports old versions of Badger while upgrading [Mercure](https://mercure.rocks) dependencies: https://github.com/dunglas/mercure/pull/960. While working on this, I figured out that we could disable compilation of Badger support for nosql (already done by Caddy), but also of MySQL and Postgres.
This reduce the build time and the binary size.
This also has the nice side effect of fixing https://github.com/caddyserver/caddy/issues/6613 because this dependency will not be included in the binary at all anymore.
When https://github.com/caddyserver/caddy/pull/6097 will be finished, we may need to add back support for MySQL and Postgres, but that's not sure because the new version of nosql may provide adapters in separate modules, that users will cherry-pick …

chore: compile without nosql's support for Postgres and MySQL

---

cmd/commands.go
cmd/packagesfuncs.go

cmd: Allow `add-package` to select version of package

---

caddyconfig/httpcaddyfile/httptype.go
caddyconfig/httpcaddyfile/tlsapp.go
caddytest/integration/caddyfile_adapt/auto_https_prefer_wildcard.caddyfiletest
caddytest/integration/caddyfile_adapt/auto_https_prefer_wildcard_multi.caddyfiletest

Followup to #6146
Two fixes:
- When assembling the HTTP app, the wildcard hosts need to be collected first, then considered after, because there's no guarantee that all non-wildcards will appear after all wildcards when looping. Also we should not add a domain to Skip if it doesn't qualify for TLS anyway. But I realized we should actually add it to SkipCerts, not Skip because we do want them to still get HTTP->HTTPS redirects, just not have certs issued.
- The automation policy consolidation misbehaved if there was more than one wildcard configured, because it was comparing wildcards against eachother. This would cause all APs to disappear in some cases. Instead of handling wildcard coverage in consolidation, I reworked it to avoid adding the AP altogether if it would be covered by a …

httpcaddyfile: Fixes for `prefer_wildcard` mode

---

modules/caddyevents/app.go

Found while load testing: Even with the "events" app not logging out on "DEBUG" it would still go through the pain of serializing the event data. Especially for `tls_get_certificate` that is painful.
Comparison before/after:

Use `WithLazy` to prevent eager serialization of the event data

---

caddytest/integration/caddyfile_adapt/forward_auth_authelia.caddyfiletest
caddytest/integration/caddyfile_adapt/forward_auth_rename_headers.caddyfiletest
modules/caddyhttp/reverseproxy/forwardauth/caddyfile.go

Reported here: https://caddy.community/t/copy-header-copying-empty-headers-with-authelia/25885, but I think it has been mentioned elsewhere before as well. Fixes #6610
Basically, because we use `ReplaceKnown` in the `request_header` handler for placeholders, the `copy_header` shortcut for `forward_auth` would cause the request headers to be set to the placeholder string itself instead of skipping, when the response was missing that header.
The fix is to use a `not vars` matcher to check that the response header placeholder has a non-empty value first.
Unfortunately this produces some super verbose JSON config, but the behaviour will be more correct.

forwardauth: Skip copying missing response headers

---

caddyconfig/httpcaddyfile/httptype.go
modules/caddyhttp/caddyhttp.go
modules/caddyhttp/celmatcher.go
modules/caddyhttp/celmatcher_test.go
modules/caddyhttp/fileserver/matcher.go
modules/caddyhttp/fileserver/matcher_test.go
modules/caddyhttp/ip_matchers.go
modules/caddyhttp/matchers.go
modules/caddyhttp/matchers_test.go
modules/caddyhttp/reverseproxy/healthchecks.go
modules/caddyhttp/reverseproxy/httptransport.go
modules/caddyhttp/reverseproxy/reverseproxy.go
modules/caddyhttp/routes.go
modules/caddyhttp/vars.go
modules/caddytls/connpolicy.go
modules/caddytls/ondemand.go

As recently discussed on Slack, our `RequestMatcher` interface is sometimes insufficient in situations where matchers cannot safely operate because it can only return a boolean. Since matchers make a decision whether or not handlers can run, returning false isn't a secure decision because it may cause handlers that _must_ run (e.g. authentication) to not get run, causing possible bypass of security-critical functionality in the config.
We already had a mechanism for this, which I added in https://github.com/caddyserver/caddy/pull/4346 via putting a variable in Context and reading it back after the matcher ran. That was absolutely a hack and not the best solution. I couldn't think of a better way at the time (lack of Go skills :sweat_smile:)
To solve this, the better solution is to …

caddyhttp: Add `MatchWithError` to replace SetVar hack

---

caddytest/integration/caddyfile_adapt/file_server_file_limit.caddyfiletest
modules/caddyhttp/fileserver/browse.go
modules/caddyhttp/fileserver/caddyfile.go
modules/caddyhttp/fileserver/command.go

This PR fixes the issue #6644 . I'm not sure about the config name `file_limit`, I prefer `max_dir_limit` etc.The default is still 10000.
As mentioned in the issue, this PR gave me some background on file serve, so I will try to look at paging as well. Please feel free to edit any documentation as you see fit.

fileserver: Add `file_limit` option for browse

---

modules/caddyhttp/rewrite/caddyfile.go
modules/caddyhttp/rewrite/rewrite.go
modules/caddyhttp/rewrite/rewrite_test.go

Context: https://caddy.community/t/unable-to-use-map-variables-with-url-strip-prefix/26093/2
The problem is if the input to the Caddyfile is a placeholder whose value will start with a `/` (e.g. `{foo} = /foo`), then it would cause `{foo}` to become `/{foo}` after the adapter, then later `//foo` once replaced.
We should add the `/` if missing at runtime after running the replacer, if necessary.

rewrite: Don't add `/` in Caddyfile, do it after replacer

---

caddyconfig/httpcaddyfile/options.go
caddyconfig/httpcaddyfile/tlsapp.go
caddytest/integration/caddyfile_adapt/global_options.caddyfiletest
modules/caddytls/tls.go

Some users want to run Caddy in a totally read-only mode, but currently storage cleaning implicitly creates two files `instance.uuid` and `last_clean.json` which are undesirable in that situation. We can simply skip starting the storage cleaning goroutine via a config option.
I noticed `storage_check off` wasn't configurable in the Caddyfile, so I added that too, while I was at it.

caddytls: Allow disabling storage cleaning, avoids writing two files

---

modules/caddyhttp/reverseproxy/selectionpolicies.go
modules/caddyhttp/reverseproxy/selectionpolicies_test.go

This pull request resumes the work from https://github.com/caddyserver/caddy/pull/6388

reverseproxy: Allow `0` as weights for `weighted_round_robin`

---

caddyconfig/httpcaddyfile/builtins.go
caddyconfig/httpcaddyfile/builtins_test.go
caddytest/integration/caddyfile_adapt/global_options_log_sampling.caddyfiletest
caddytest/integration/caddyfile_adapt/log_sampling.caddyfiletest

Closes https://github.com/caddyserver/caddy/issues/6680
Support log samplig in Caddyfile
```caddyfile
{
auto_https off
log {
sampling {
interval 100
first 100
thereafter 100
}
}
}
```

httpcaddyfile: Implement log `sampling` config

---

.goreleaser.yml

Fixes https://github.com/caddyserver/dist/issues/91

chore: Add `provides` to `.deb` releases

---

context.go

They're automatically registered in the Default Registry, which we were using but not anymore. Adding them to match old behavior.
Noted in: https://github.com/caddyserver/caddy/pull/6531#issuecomment-2494938615
Thanks @ueffel

metrics: add `go` and `process` collectors

---

.github/workflows/ci.yml

I tried to have the jobs of s390x and goreleaser check work in both PRs and direct pushes to the repo, but failed. So now I replicated the condition we have for s390x to goreleaser check so they'll run only on branches from this repo.

ci: prevent jobs running on PRs from forks

---

caddytest/integration/caddyfile_adapt/php_fastcgi_handle_response.caddyfiletest
caddytest/integration/caddyfile_adapt/php_fastcgi_matcher.caddyfiletest
caddytest/integration/caddyfile_adapt/php_fastcgi_subdirectives.caddyfiletest
caddytest/integration/caddyfile_adapt/php_fastcgi_try_files_override_no_dir_index.caddyfiletest
modules/caddyhttp/fileserver/caddyfile.go
modules/caddyhttp/fileserver/matcher.go
modules/caddyhttp/reverseproxy/fastcgi/caddyfile.go

When using modern frameworks such as Symfony and Laravel, by convention, all requests are handled by a front controller named `index.php` in the document root.
Currently, Caddy does a call to `fs.Stat()` at each request to check that this file exists, but in case we use such a framework, this call is useless because we know that the file exists.
This PR adds a new `first_exist_fallback` policy that assumes that the last file in the list always exists.

fileserver: Add `first_exist_fallback` strategy for `try_files`

---

cmd/commandfuncs.go
cmd/commands.go

Addresses #6702 by explicitely preventing more than one config file passed to the fmt command. 
Also Enables the (--config/-c) flags support for the fmt command. 
@francislavoie I am not quite sure on what would be the best way to approach formatting imports as well. would we get all the import statements from the root config file and check if they refer to a file that we can resolve the path to, and then recursively do the same for the files we extracted?

cmd: `fmt` prevents multiple files passed as args, add support for `--config`

---

modules/caddyhttp/fileserver/matcher.go

Fix https://github.com/caddyserver/caddy/issues/6726, oversight from #6699 (FYI @dunglas)

fileserver: Fix policy `Validate()` oversight

---

modules/caddyhttp/fileserver/caddyfile.go

Currently, the following snippet doesn't enable precompression:
```
file_server {
precompressed
}
```
Supported formats must be passed explicitly.
This patch allows to omit the formats for simplicity. By default, Brotli, Zstandard, and gzip are enabled (in this order).
Brotli is preferred to Zstandard, because according to [Paul Calvano's article](https://paulcalvano.com/2024-03-19-choosing-between-gzip-brotli-and-zstandard-compression/), Brotli is better (smaller files) for static assets.

feat: good default for file_server.precompressed

---

caddytest/integration/caddyfile_adapt/encode_options.caddyfiletest
modules/caddyhttp/encode/caddyfile.go

Similar to https://github.com/caddyserver/caddy/pull/6736, but for `encode`.

feat: good default for encode

---

modules/caddyhttp/encode/encode.go
modules/caddyhttp/encode/encode_test.go

fix [6733](https://github.com/caddyserver/caddy/issues/6733).

encode: write status immediate for success response for CONNECT requests

---

modules/caddyhttp/reverseproxy/reverseproxy.go

RFC 8441 specifies that:
> The :protocol pseudo-header field MUST be included in the CONNECT request, and it MUST have a value of "websocket" to initiate a WebSocket connection on an HTTP/2 stream
Otherwise we might end up modifying other use cases of the extended CONNECT method later on.

reverseproxy: Only handle extended connect for websockets

---

caddyconfig/httpcaddyfile/builtins.go
caddyconfig/httpcaddyfile/httptype.go
caddyconfig/httpcaddyfile/tlsapp.go
caddytest/integration/caddyfile_adapt/tls_automation_wildcard_force_automate.caddyfiletest
caddytest/integration/caddyfile_adapt/tls_automation_wildcard_shadowing.caddyfiletest

Closes https://github.com/caddyserver/caddy/issues/5933
I think this should work according to the JSON config output, but I didn't actually test it at runtime to verify that it yields the expected behaviour. @mholt you had a repro set up locally if you want to give it a spin while reviewing.

httpcaddyfile: Implement `force_automate`

---

modules/caddyhttp/app.go

Related Issue: #6760 
Disable HTTP/3 for unix domain socket
**Caddyfile**
```Caddyfile
example.com {
bind unix/@test
respond 200
}
```
**Preview**
```txt
2025/01/05 05:28:28.361	INFO	using adjacent Caddyfile
2025/01/05 05:28:28.361	INFO	adapted config to JSON	{"adapter": "caddyfile"}
2025/01/05 05:28:28.361	WARN	Caddyfile input is not formatted; run 'caddy fmt --overwrite' to fix inconsistencies	{"adapter": "caddyfile", "file": "Caddyfile", "line": 2}
2025/01/05 05:28:28.363	INFO	admin	admin endpoint started	{"address": "localhost:2019", "enforce_origin": false, "origins": ["//localhost:2019", "//[::1]:2019", "//127.0.0.1:2019"]}
2025/01/05 05:28:28.363	INFO	http.auto_https	enabling automatic HTTP->HTTPS redirects	{"server_name": "srv0"}
2025/01/05 05:28:28.363	WARN	http	HTTP/3 disabled …
```

fix: disable h3 for unix domain socket

---

modules/logging/filewriter.go
modules/logging/filewriter_test.go

Follow-up to #6314 and https://caddy.community/t/caddy-2-9-0-breaking-change/27576/11
Maybe someone with more sysadmin experience could double-check my logic here. We want to chmod only if the permission bits differ. Did I get this right? (I would just write a test for this, but I'm not sure I have enough skills to write the test for this correctly.)

log: Only chmod if permission bits differ

---

modules/caddytls/matchers.go

This PR is the mainline part of the fix described [here](https://github.com/mholt/caddy-l4/issues/241#issuecomment-2610292874) for the issue with missing `{tls.regexp.*}` placeholders reported [here](https://github.com/mholt/caddy-l4/issues/241#issuecomment-2609215818).

caddytls: Fix sni_regexp matcher to obtain layer4 contexts

---

cmd/main.go
go.mod
go.sum

Setting the [Go runtime memory limit](https://pkg.go.dev/runtime/debug#SetMemoryLimit) can improve significantly the performance of Caddy (and FrankenPHP and Mercure, according to our tests), especially on low-resources machines and containers.
This patch uses [github.com/KimMachineGun/automemlimit](https://github.com/KimMachineGun/automemlimit) to automatically find a good limit using the currently configured groups. This is especially useful when setting limits to containers using Docker, Kubernetes, LXC, and the like.
This PR is similar to #6047, which does the same things go the max number of processors.
Thanks to @flovntp for the idea and for finding this library!

feat: automatically set GOMEMLIMIT

---

modules/caddyhttp/reverseproxy/metrics.go
modules/caddyhttp/reverseproxy/reverseproxy.go

I'm not a fan of storing the state in the active context, but it seems to be the only way to catch if this is a reload of Caddy or a fresh start.
Fixes #6773

reverse_proxy: re-add healthy upstreams metric

---

modules/caddyhttp/reverseproxy/metrics.go

I'm not very happy with the approach, but I cannot think of another one. Others who can see a better solution are welcome to suggest.
Fixes #6813

reverseproxy: ignore duplicate collector registration error

---

admin.go

fix: fix index validation for PUT requests

---

modules/caddyhttp/fileserver/browse.go
modules/caddyhttp/fileserver/browsetplcontext.go

fix [6828](https://github.com/caddyserver/caddy/issues/6828)
Also should fix `If-Modified-Since` handling, but no one reported that yet.

file_server: use the UTC timezone for modified time

---

admin_test.go

- TestAdminHandlerErrorHandling - Tests the handler.handleError()
functionality by directly verifying error response formatting
- TestAdminHandlerBuiltinRouteErrors - Tests the error
handling pathway by using real admin server routes and verifying
both error responses and prometheus metrics increments
- provisionAdminRouters: add unit tests for admin handler registration and routing for admin.api
- TestAllowedOriginsUnixSocket: checks unix socket with default origins are added
- TestReplaceRemoteAdminServer: test for replaceRemoteAdminServer with certificate validation, custom origins and cleanup
- TestManageIdentity: tests the manageIdentity function to test identifiers with configs.
this increases the test coverage of admin.go from 31% to 59%.
Increases total coverage from 37.9% to 47%. …

feat/tests: tests for error handling & metrics in admin endpoints

---

go.mod
go.sum

Updated hypermodeinc/ristretto to v0.2.0 to remove glog and avoid possible flag redefinition when using caddy sdk.

remove glog dependency

---

caddyconfig/caddyfile/formatter.go
caddyconfig/caddyfile/formatter_test.go

This addresses issue #6859 by writing the opening and closing braces and ignoring indentation when it detects that we the cursor is currently within a backquote section. 
I have added 2 new tests for the two cases where the braces are wrapped with regular quotes and backquotes. I have confirmed that it works at  least with the following example:
```
block {
header Content-Type text/plain
templates
respond "Home page date: {{now | date `2006`}}"
handle /path {
header Content-Type text/plain
templates
respond `Path page date: {{now | date "2006"}}`
}
}
```

Fix caddy fmt breaks backquote wrapped braces in template

---

go.mod
go.sum

v0.50.1 contains a fix for CVE-2025-29785.

update quic-go to v0.50.1

---

caddy.go
context.go
internal/filesystems/map.go
modules/caddyevents/app.go
modules/caddyfs/filesystem.go
modules/caddyhttp/fileserver/matcher.go
modules/caddyhttp/fileserver/matcher_test.go
modules/caddyhttp/fileserver/staticfiles.go

**Breaking change for modules that use events. I suspect this will affect very few code bases.** Events are also documented as still experimental, and for good reason! This allows us to do much more with events and make them more useful.
Requires some slight trickery to invert dependencies. We can't have the caddy package import the caddyevents package, because caddyevents imports caddy. Interface to the rescue!
Also add two new events, experimentally: started, and stopping. At the request of a sponsor.
Also rename "Filesystems" to "FileSystems" to match Go convention (unrelated to events, was just bugging me when I noticed it).
/cc @ankon

events: Refactor; move Event into core, so core can emit events

---

listeners.go

According to the documentation for  [strings.HasPrefix](https://pkg.go.dev/strings#HasPrefix), the order of the parameters here should be incorrect.

bug: Fix the incorrect parameter order

---

modules/caddyhttp/reverseproxy/healthchecks.go
modules/caddyhttp/reverseproxy/hosts.go
modules/caddyhttp/reverseproxy/reverseproxy.go

Currently if we extract the `DialInfo` from a `Request` `Context` in a custom `Transport` during an active health check, then the `Upstream` in the `DialInfo` will be nil.
This PR attempts to set the `Upstream` to a sensible value, based on wether or not the `Upstream` has been overridden in the active health check's config.
This is useful when using a custom Transport for the `reverse_proxy` module, as it makes `GetDialInfo` behave similarly in active health check requests and client requests.

Add a valid Upstream to the DialInfo when doing active health checks

---

modules/caddyhttp/reverseproxy/httptransport.go
modules/caddytls/acmeissuer.go

forwardproxy: reference correct field name in LoadModule

---

context.go

`opts` argument in the `zapslog.NewHandler` function should not be passed as `nil`
https://github.com/uber-go/zap/blob/7db06bc9b095571d3dc3d4eebdfbe4dd9bd20405/exp/zapslog/handler.go#L53

fix: Remove `nil` arg from `zapslog.NewHandler` call

---

modules/caddyhttp/fileserver/browse.html

This pull request adds support for `.avif` image files in the file browser. The `.avif` extension has been included in the list of recognized image formats.
See also https://caddy.community/t/caddy-fails-to-img-avif-in-file-server-grid-layout/30680/2

fileserver: Add support for .avif image format

---

logging.go
logging_test.go

I found that any direct use of `Log()` function to get the default `*zap.Logger` results in bypass of any configured include/exclude rules. Using the `filteringCore` ensures the default loggers respects the user configuration.

log: default logger should respect `{in,ex}clude`

---

admin_test.go
caddyconfig/httpcaddyfile/directives.go
cmd/commandfuncs.go

Optimize code using a more modern writing style.

refactor: use maps.Copy for cleaner map handling

---

modules/caddyhttp/reverseproxy/fastcgi/caddyfile.go
modules/caddyhttp/reverseproxy/httptransport.go
modules/caddyhttp/staticresp.go
modules/caddytls/certselection.go
modules/caddytls/connpolicy.go

There is a [new function](https://pkg.go.dev/slices@go1.21.0#Contains) added in the go1.21 standard library, which can make the code more concise and easy to read.

refactor: use slices.Contains to simplify code

---

caddyconfig/httpcaddyfile/builtins.go

Fixes #7050
The log_skip directive was designed not to accept arguments.
Blocks should not be passed through, but there was a bug that allowed them to be passed through, so I fixed the code to detect blocks and return an error.
Thank you.

caddyfile: reject blocks in log_skip directive

---

cmd/commands.go
cmd/commands_test.go

cmd: fix `Commands` function not returning all registered commands

---

.github/workflows/lint.yml

Some things don't fail on PRs 🤷🏼

ci: add `{base,head}-ref` to  dep review check

---

modules/caddyhttp/caddyauth/basicauth.go
modules/caddyhttp/reverseproxy/selectionpolicies.go

In Go 1.21, the standard library includes built-in [max/min](https://pkg.go.dev/builtin@go1.21.0#max) function, which can greatly simplify the code.

refactor: use the built-in max/min to simplify the code

---

modules/caddyhttp/reverseproxy/httptransport.go

Fix [7111](https://github.com/caddyserver/caddy/issues/7111)

reverse proxy: validate versions in http transport

---

modules/caddyhttp/fileserver/browse.html

This commit adds support for [LibreJS](https://en.wikipedia.org/wiki/GNU_LibreJS).
LibreJS would block this embedded JavaScript because its license is not stated in a machine-readable format.
More info: https://www.gnu.org/software/librejs/free-your-javascript.html#magnet-link-license

fileserver: specify license for embedded JavaScript

---

modules/caddyhttp/encode/encode_test.go

In the Go 1.21 standard library, a new function has been introduced that enhances code conciseness and readability. It can be find  [here](https://pkg.go.dev/slices@go1.21.1#Equal).

refactor: use slices.Equal to simplify code

---

.github/dependabot.yml

This should address the noise reported in https://github.com/caddyserver/caddy/pull/7077?notification_referrer_id=NT_kwDOACg5l7MxNzAzMjQ1MjQ3NzoyNjM2MTgz#issuecomment-2978338062

ci: reduce dependabot spam

---

cmd/commandfuncs.go
cmd/commands.go

Read input from stdin if `--config -` is passed.
Fix small typo for similar stdin usage message in `caddy fmt`.
Return same error as 'validate' when there are no args.
Resolves https://github.com/caddyserver/caddy/issues/7162

cmd: Allow `caddy adapt` to read from stdin

---

modules/caddyhttp/headers/headers.go

fix inconsistent function name in comment

chore: fix inconsistent function name in comment

---

modules/caddytls/automation.go

The fix for #6901 ( e276994174983dbb190d4bb9acaab157ef14373b ) appears to have broken support for modules that provide ondemand TLS, such as https://github.com/tailscale/caddy-tailscale
This issue was previously fixed in #6328 but the commit linked above reverts that change. I have tested starting Caddy with the following config after reverting the changes to `automation.go`, and it appears to still work fine, so I don't think any changes to that file were required to fix #6901 
> ```Caddyfile
> {
> 	on_demand_tls {
> 		ask http://localhost:9123/ask
> 	}
> }
> 
> https:// {
> 	tls {
> 		on_demand
> 	}
> }
> ```
_Originally posted by @jonaharagon in [#6901](https://github.com/caddyserver/caddy/issues/6901#issuecomment-2730246096)_
in summary - tracking `hadExplicitManagers` within an …

caddytls: fix regression in external certificate manager support

---

modules/caddyhttp/app.go

Fix [7175](https://github.com/caddyserver/caddy/issues/7175).

http: clean up listeners if some of the listeners fail to bind

---

modules/caddyhttp/fileserver/staticfiles.go

Adds a bit more details to the [etag_file_extensions](https://caddyserver.com/docs/json/apps/http/servers/routes/handle/file_server/etag_file_extensions/) field, specifically how the content of the Etag files should look like.
This comes mainly from my frustration with getting it right, as can be seen in #7096.

doc: Add a few lines about Etag file content

---

caddyconfig/caddyfile/formatter.go
caddyconfig/caddyfile/formatter_test.go

A space was being added on the previous non-empty line before the opening curly brace of an env variable.
Issue reference - #6881 
- Do not add space if there are pending newLines (`formatter.go` line 244)
- Add space if the last character was not a space (`formatter.go` line 227)
No AI was used.

caddyfile: Prevent trailing space on line before env variable - Fixes #6881

---

modules/caddyhttp/encode/encode.go

Fixes response corruption when encode and handle_errors directives are used together - Adds disabled flag to responseWriter to prevent encoding during error processing - Resolves issue where gzip headers were mixed with plain text error responses.
Fixes #6617
**Test Results**
Before Fix (Corrupted Response)
```
curl -k -H "Accept-Encoding: gzip" https://localhost:8080/  
```
After Fix (Clean Error Response)
```
curl -k -H "Accept-Encoding: gzip" https://localhost:8080/  
```
Normal Responses Still Work
```
curl -k -H "Accept-Encoding: gzip" https://localhost:8080/valid.html  
```  
Test Configuration Used
```
localhost:8080 {
encode zstd gzip
handle_errors {
respond "Error: Status {http.error.status_code}"
}
root * .
templates
file_server
}
```
Template file with error: {{ poop }} …

 encode: fix response corruption when handle_errors is used

---

modules.go

If `GOEXPERIMENT=jsonv2` is used to compile caddy, caddy will panic if tls is used:
```
panic: expected ModuleMap because inline_key is empty; but we do not recognize this type: caddy.ModuleMap
goroutine 1 [running]:
github.com/caddyserver/caddy/v2.Context.loadModulesFromSomeMap({{0x2362c30, 0xc000748be0}, 0xc0000c9c80, 0xc00042b680, {0xc000420280, 0x2, 0x2}, {0x0, 0x0, 0x0}, ...}, ...)
github.com/caddyserver/caddy/v2@v2.10.2/context.go:296 +0x1c5
github.com/caddyserver/caddy/v2.Context.LoadModule({{0x2362c30, 0xc000748be0}, 0xc0000c9c80, 0xc00042b680, {0xc000420280, 0x2, 0x2}, {0x0, 0x0, 0x0}, ...}, ...)
github.com/caddyserver/caddy/v2@v2.10.2/context.go:265 +0x585
github.com/caddyserver/caddy/v2/modules/caddytls.(*TLS).Provision(0xc0005fa280, {{0x2362c30, 0xc000748be0}, 0xc0000c9c80, …
```

core: use reflect.TypeFor to check for encoding/json.RawMessage

---

caddyconfig/httpcaddyfile/builtins.go
caddyconfig/httpcaddyfile/tlsapp.go
caddytest/integration/caddyfile_adapt/acme_dns_configured.caddyfiletest
caddytest/integration/caddyfile_adapt/tls_dns_override_acme_dns.caddyfiletest
caddytest/integration/caddyfile_adapt/tls_dns_override_global_dns.caddyfiletest
caddytest/integration/caddyfile_adapt/tls_dns_resolvers_with_global_provider.caddyfiletest
caddytest/integration/mockdns_test.go

I was getting the following spurious error:
```console
{
acme_ca https://acme-staging-v02.api.letsencrypt.org/directory
acme_dns cloudflare REDACTED_API_KEY
}
*.mydomain.com {
tls {
resolvers 1.1.1.1 1.0.0.1
}
}
<snip>
Error: adapting config using caddyfile: parsing caddyfile tokens for 'tls': setting DNS challenge options [resolvers] requires a DNS provider (set with the 'dns' subdirective or 'acme_dns' global option), at Caddyfile:9
```
This brings the logic in line with the intended behaviour implied by the error message. (If the current behaviour is correct, then the error message should be changed accordingly.)
No AI was used.

httpcaddyfile: Add missing DNS challenge check for `acme_dns`
