caddyserver/caddy

server/server.go

adding crypto/tls sessioncache

---

middleware/headers/headers.go

Make sure you can not only add/overwrite headers but also **remove** them.
```
header / -Server
```
```
header / {
-Server
X-Header1 Value1
X-Header2 Value2
}
```

Close #64 (Make it possible to remove headers)

---

config/setup/tls.go
config/setup/tls_test.go
server/config.go
server/server.go

Added tls option block including: ciphers, protocols and cache options

---

main.go

Also moved the minimum ulimit value into a constant and the whole ulimit check into its own function.

Updated ulimit warning message to include the recommended min value.

---

middleware/fastcgi/fastcgi.go

FastCGI middleware now supports unix sockets. Usage is same as before but specifying unix socket file instead of server address.
Example using unix socket.
```
fastcgi / /var/run/php5-fpm.sock php
```
Example using server address, same as before.
```
fastcgi / 127.0.0.1:9000 php
```

FastCGI: support for unix sockets.

---

middleware/proxy/policy.go
middleware/proxy/policy_test.go
middleware/proxy/upstream.go
middleware/proxy/upstream_test.go

Closes #93. Also added some tests.

added custom policy support

---

README.md

@jumanjiman We're adding a link to your Docker container. I will merge this in shortly unless you'd rather not have it mentioned here.

Add link to Docker container jumanjiman/caddy

---

middleware/errors/errors_test.go

Add unit test for errors middleware

---

middleware/recorder.go

let middleware.responseRecorder be a http.Hijacker

---

config/setup/ext_test.go

Please review and let me know the changes

Preliminary test case for setup/config/ext.go

---

config/setup/ext_test.go

Please review and let me know the more test case that has to go into the test struct

test for function extParse written for config/setup/ext_go

---

config/setup/log_test.go

Tests for config/setup/log.go

---

config/setup/internal_test.go

Tests for config/setup/internal.go

Tests for config/setup/internal.go

---

config/directives.go
config/setup/basicauth_test.go
config/setup/controllertest.go
config/setup/ext_test.go
config/setup/git_test.go
config/setup/gzip_test.go
config/setup/headers_test.go
config/setup/internal_test.go
config/setup/log_test.go
config/setup/rewrite_test.go
config/setup/tls_test.go

While working on custom build, I realised the need for this.

setup: export functions and variables for external packages.

---

config/setup/browse.go
middleware/browse/browse.go
middleware/browse/browse_test.go

now you can click on `Name`, `Size` or `Modified` to sort the listing

Implement sorting for "browse"

---

config/setup/websocket.go
config/setup/websocket_test.go

Completed test for config/setup/websocket.go

Test for webSocketParse function in config/setup

---

config/setup/templates.go
config/setup/templates_test.go

Initial Test case for config/setup/templates.go , also i modified the variables to so that they are more readable and made them global so that they can be used in tests , that'll help improve the readability of the test case and also the purpose of those assertions too

Initial Test case for config/setup/templates.go

---

config/setup/templates_test.go

Test coverage for  config/setup/templates.go complete

Complete test coverage for config/setup/templates.go

---

README.md

The grammar felt off on the sentence I changed. You can take or leave this PR, I won't be offended if you dislike my suggestion.

Massage some verbiage

---

config/setup/markdown_test.go

Im not sure whether i have to assert only for the Pathscope or there is something more too , let me know

preliminary test case for config/setup/markdown.go

---

middleware/extensions/ext_test.go

Test cases that verify expected changes to `req.URL`

Initial tests for the extensions middleware

---

config/setup/markdown_test.go

Complete test coverage for config/setup/markdown.go , more test cases have to be added

Complete test coverage for config/setup/markdown.go

---

middleware/redirect/redirect.go
middleware/redirect/redirect_test.go

The get parameters are now forwarded when redirected.
Added some tests to validate this behavior.

Changes regarding issue 180

---

middleware/browse/browse.go

Save sorting preferences as cookies

---

middleware/markdown/metadata.go
middleware/markdown/metadata_test.go
middleware/markdown/process.go

from map[string]interface{} to map[string]string

Change metadata variables type in markdown directive

---

middleware/recorder_test.go

Checking the approach , want review

Complete test coverage for recorder.go of middleware package

---

middleware/replacer_test.go

Initial tests for replacer to get the reviewing on the testing methodology

Initial test for replacer

---

middleware/browse/browse_test.go

@pyed , here is the initial test for Json browse response code :)

 Initial test for  Json response in browse.go

---

config/parse/dispenser.go
config/setup/errors.go
config/setup/errors_test.go
config/setup/log.go
config/setup/log_test.go
config/setup/roller.go
middleware/errors/errors.go
middleware/log/log.go
middleware/roller.go

Hi!
I added the lumberjack library for logs rolling. I did some testing locally, it works like a charme.
I put some default values in it that seemed right, let me know what you think about it.

Added lumberjack library for log rolling

---

main.go

Started working on passing configuration as command arguments.

Configuration as command line arg #222

---

middleware/browse/browse.go

I think it would be interesting to have the possibility to include user defined variables into browse template.

User defined variables in Browse

---

config/setup/browse.go

https://github.com/mholt/caddy/issues/261

allow consecutive spaces for browse

---

middleware/browse/browse.go
middleware/browse/browse_test.go
middleware/browse/testdata/photos/test3.html

Exhaustive test coverage to test the usage of sort,order and limit parameter for the browse middleware and fix for https://github.com/mholt/caddy/issues/264

Better test coverage  and browse middleware bug fix 

---

app/app_test.go
config/config_test.go

Improves coverage for functions
* app.SetCPU
* config.validDirective
* config.makeStorages
* config.makeOnces

Improve coverage for config and app

---

middleware/fileserver.go
middleware/fileserver_test.go

+ change the returned error from serveFile in case f.Stat fails

Fileserver tests

---

middleware/commands.go
middleware/commands_test.go

Hopefully this will help with #276 - @Makpoc and @PatelNDipen could you please check this out and see if this works?

Parse Windows commands differently than Unix commands

---

caddy/caddy.go
caddy/caddyfile/json.go
caddy/config.go
caddy/helpers.go
caddy/letsencrypt/letsencrypt.go
caddy/letsencrypt/storage.go
caddy/parse/parse.go
caddy/restart.go
caddy/setup/bindhost.go
caddy/setup/root.go
caddy/setup/startupshutdown.go
caddy/setup/tls.go
middleware/basicauth/basicauth.go
middleware/browse/browse_test.go
middleware/fastcgi/fastcgi.go
middleware/fastcgi/fcgiclient.go
middleware/fastcgi/fcgiclient_test.go
middleware/fileserver_test.go
middleware/gzip/filter.go
middleware/log/log.go
middleware/markdown/process.go
middleware/markdown/renderer.go
server/server.go

Hope this helps, ran the code through ```golint``` and made the appropriate adjustments, some notes:
1. Couldn't pass the whole linter as some of the ```blackfriday``` interface functions also need attention.
2. Adjusted some methods returninh unexported types at the linter called that annoying :).
3. Adjusted all tests after the fact, all passing.

Refactor- lint pacification

---

main.go

As per https://github.com/mholt/caddy/issues/331 in succession to #330 (#317)

Alphabetize command line options, vars, and checks

---

main.go

As per https://github.com/mholt/caddy/issues/317

add --pidfile string option

---

caddy/setup/browse.go

https://github.com/mholt/caddy/issues/261#issuecomment-158415762

allow consecutive spaces in the header

---

README.md

not all lines wrap at 80 characters but now most do.

copy edit to wrap around 80 chars

---

README.md

add links to inspired by projects and updated language with golang.

more copy edits

---

CONTRIBUTING.md

also linked to bug reporting article.

wrap lines to 80 characters

---

caddy/setup/gzip.go
caddy/setup/gzip_test.go
middleware/gzip/gzip.go
middleware/gzip/gzip_test.go
middleware/gzip/request_filter.go
middleware/gzip/request_filter_test.go
middleware/gzip/response_filter.go
middleware/gzip/response_filter_test.go

Feature requested in https://github.com/mholt/caddy/issues/398

Gzip: support for min_length.

---

CONTRIBUTING.md

Feek --> Feel

---

caddy/setup/tls.go
caddy/setup/tls_test.go

Remove ECDHE-RSA-3DES-EDE-CBC-SHA and RSA-3DES-EDE-CBC-SHA from the default TLS config

---

middleware/gzip/gzip.go
middleware/gzip/gzip_test.go
middleware/gzip/response_filter.go
middleware/gzip/response_filter_test.go

Fix for https://github.com/mholt/caddy/issues/448

Gzip: Fix missing gzip encoding headers.

---

middleware/markdown/generator.go

Markdown: Fix panic on sitegen for request dependent template values.

---

caddy/letsencrypt/crypto.go
caddy/letsencrypt/crypto_test.go

The permission of user key file is 0666 which doesn't seem right.

letsencrypt: Fix perm of user key

---

dist/README.txt

wrap lines to 80

---

caddy/translate/de-DE.go

Just copied the bootstrap from the Spanish Translation file and replaced the Spanish strings with the German.
Created this in order of #574.

Create DE translation

---

main.go

Use rotating log files

---

middleware/recorder.go
middleware/replacer.go

Making this new PR as a preliminary work on #614 
What do you think @mholt ?

Recorder: Exporting ResponseRecorder #614

---

middleware/fastcgi/fastcgi.go

I've tested it against #567  and #614, and it will help me solve it too.

FastCGI: Explicitly set Content-Length #626

---

caddy/https/client.go
caddy/https/crypto_test.go
caddy/https/user.go

Fixes #640 
Code review / follow-up PRs would be appreciated: I just verified that the build works after these changes (and that I don't see any obvious reason tests should fail).

Fix build after https://github.com/xenolf/lego/commit/0e26b

---

caddy/https/client.go
caddy/https/crypto.go
caddy/https/crypto_test.go
caddy/https/https.go
caddy/https/user.go
caddy/https/user_test.go

- Create ECC certificates by default
- Supporting RSA and ECC

Support ECC certificates

---

dist/init/linux-systemd/README.md
dist/init/linux-systemd/caddy@.service

This pull requests adds a systemd unit file for caddy and a bit of documentation on how to install and use caddy as a systemd service. Refers to #388

systemd unit file

---

.gitattributes
build.bash
dist/automate.sh

Converts all bash scripts to bash-programming best practices, standardizes formats where possible, and completes the multi-threaded creation of distributables.

Reflow all bash scripts

---

caddy/caddy.go
caddy/restart.go
main.go

Add -restart=inproc flag for in process restart

---

caddy/https/https_test.go
caddy/setup/errors_test.go
caddy/setup/websocket.go
middleware/browse/browse_test.go
middleware/commands.go
middleware/context.go
middleware/fastcgi/fcgiclient.go
middleware/fastcgi/fcgiclient_test.go
middleware/inner/internal_test.go
middleware/markdown/metadata_test.go

https://github.com/mholt/caddy/issues/697

Correct unused assignments

---

middleware/proxy/proxy_test.go
middleware/proxy/reverseproxy.go

Please review my change like last time; I haven't been able to achieve master skills of Go yet.
Given a Caddyfile like this:
```text
127.0.0.1:2015
tls off
proxy / unix:/var/run/www.socket
```
And running an application similar to this one:
```js
/* Using built-in modules only here, since extra dependencies
* would compromise testing too much.
*/
var http = require('http');
var responder = function (request, response) {
response.writeHead(200, {'Content-Type': 'text/plain'});
response.end('socket response for ' + request.url);
};
var server = http.createServer(responder);
/* Since this folder most likely is owned by root,
* use `sudo` to run this script.
*/
server.listen('/var/run/www.socket');
```
When calling `http://127.0.0.1:2015/test` now, server replies with `socket response for …

fixes req.URL.Path for unix: sockets

---

caddy/https/https.go
caddy/https/setup.go
caddy/https/setup_test.go

- cleaner code :heart: 
- fixes #721 :hear_no_evil: 
P.S.: @mholt sorry, again :cry:

Fix for #721

---

caddy/restart.go
caddy/restart_windows.go

Related to https://github.com/mholt/caddy/issues/717

revert to old Caddyfile on failed in-process restart

---

caddy/https/crypto_test.go

Fix PrivateKeyBytes to error out and fail tests on error.

---

caddy/setup/browse.go

browse: Serve a datetime format the IE11 and Firefox understand

---

middleware/fastcgi/fastcgi.go
middleware/fastcgi/fastcgi_test.go

Strip [] from IPv6 addresses for FastCGI.

---

middleware/proxy/proxy.go

The bug was introduced in e2234497b79603388b58ba226abb157aa4aaf065

Fix for #854

---

middleware/proxy/proxy.go
middleware/proxy/proxy_test.go

Fix for cleaned URL.Path

---

dist/init/linux-upstart/README.md
dist/init/linux-upstart/caddy.conf

Fixes a number of smaller issues:
* Ensures that /etc/caddy exists
* Ensures correct HOME folder
* Adds logging capabilities

Make upstart script more fault tolerant and easier to debug

---

caddyhttp/httpserver/replacer.go
caddyhttp/httpserver/replacer_test.go

Add a {request} placeholder to the replacer.
Closes #858.

Log Requests

---

caddyhttp/httpserver/plugin.go

[See this also.](https://github.com/caddyserver/caddyserver.com/pull/52)

Add minify directive

---

caddyhttp/proxy/policy.go

This commit shouldn't change any behavior. It is simply a cleanup of
the different proxy policies. It also adds some comments explaining the
sampling method used, since on first inspection it might not appear to
be a uniformly random selection.
My hope is to make the code easier to understand

Refactor and clean up policy code

---

README.md

Fix go get url

---

caddyhttp/httpserver/plugin.go

Add filemanager directive

---

caddyhttp/httpserver/replacer.go
caddyhttp/httpserver/replacer_test.go
caddyhttp/proxy/proxy_test.go
caddyhttp/proxy/reverseproxy.go

Proxy performance

---

caddyhttp/header/header.go
caddyhttp/header/header_test.go

Rebase of #947 after I incorrectly rebased that PR :/
Thank goodness for `git reflog`.
Fixes #818

HTTP Headers

---

caddyhttp/proxy/setup_test.go
caddyhttp/proxy/upstream.go

proxy: fix hyphen issue when parsing target

---

caddyhttp/httpserver/plugin.go

Not sure it's the right place ...

Register ratelimit

---

dist/init/linux-upstart/caddy.conf

Specify the reload signal in the upstart script

---

caddyhttp/redirect/setup.go
caddyhttp/redirect/setup_test.go

redir: loading block arguments before parsing matcher

---

caddytls/crypto_test.go

```
==================
WARNING: DATA RACE
Write at 0x00c42049d300 by goroutine 26:
github.com/mholt/caddy/caddytls.standaloneTLSTicketKeyRotation()
/home/tw/golib/src/github.com/mholt/caddy/caddytls/crypto.go:230 +0x698
Previous read at 0x00c42049d300 by goroutine 25:
github.com/mholt/caddy/caddytls.TestStandaloneTLSTicketKeyRotation()
/home/tw/golib/src/github.com/mholt/caddy/caddytls/crypto_test.go:113 +0x413
testing.tRunner()
/home/tw/goroot/src/testing/testing.go:610 +0xc9
Goroutine 26 (running) created at:
github.com/mholt/caddy/caddytls.TestStandaloneTLSTicketKeyRotation()
/home/tw/golib/src/github.com/mholt/caddy/caddytls/crypto_test.go:101 +0x2a4
testing.tRunner()
/home/tw/goroot/src/testing/testing.go:610 +0xc9
Goroutine 25 (running) created at:
testing.(*T).Run() …
```

tls: fix TestStandaloneTLSTicketKeyRotation data race

---

caddy.go
rlimit_posix.go
rlimit_windows.go

improve rlimit usage

---

caddyhttp/proxy/proxy_test.go

proxy: add Host header checking

---

.gitignore
caddyhttp/internalsrv/internal.go
caddyhttp/internalsrv/internal_test.go

Enable downloading of protected content. See issue #979

---

caddyhttp/httpserver/replacer.go
caddyhttp/httpserver/replacer_test.go

Rounding the latency based on the suggestions from @mholt.  This addresses #995.

Rounding the latency in certain scenarios

---

dist/init/linux-sysvinit/README.md
dist/init/linux-sysvinit/caddy

As he provided in: https://github.com/mholt/caddy/pull/983
I think these changes are correct, but would love a double-check from @weingart before we merge this?

dist/init/linux-sysvinit: process @weingart's feedback

---

caddyhttp/httpserver/replacer.go
caddyhttp/httpserver/replacer_test.go

Logging the request body if the Content-Type is application/json or
application/xml.  This addresses #1015.

Now logging the request body

---

caddyhttp/log/log.go
caddyhttp/log/log_test.go
caddyhttp/log/setup.go
caddyhttp/log/setup_test.go

log: support multiple log entries under one path scope

---

caddyhttp/log/log_test.go

log: add multiple log entry test

---

caddyhttp/caddyhttp.go
caddyhttp/caddyhttp_test.go
caddyhttp/httpserver/plugin.go
caddyhttp/rewrite/rewrite.go
caddyhttp/rewrite/rewrite_test.go
caddyhttp/rewrite/setup.go
caddyhttp/rewrite/setup_test.go
caddyhttp/status/setup.go
caddyhttp/status/setup_test.go
caddyhttp/status/status.go
caddyhttp/status/status_test.go

Simple implementation of middleware for responding with specified status as discussed in #1012

Add 'status' middleware instead of 'status' directive for 'rewrite' middleware

---

caddyhttp/httpserver/plugin.go

It looks like this is the only file that needed to be updated.  Please let me know if that's not the case.

awslambda external plugin

---

caddyfile/parse.go
caddyfile/parse_test.go

parser: fix broken absolute path imports

---

caddyhttp/httpserver/plugin.go

See https://github.com/caddyserver/caddyserver.com/pull/78

Add expires directive

---

caddyhttp/header/header.go
caddyhttp/header/header_test.go

header: defer header operations

---

caddyhttp/httpserver/replacer.go
caddyhttp/httpserver/replacer_test.go

replacer: evaluate header placeholder when replacing

---

caddyhttp/proxy/proxy_test.go
caddyhttp/proxy/reverseproxy.go

proxy: handle 'without' option in encoded form of URL path

---

caddytls/setup_test.go

We need consistency/(unity) in code style!!!

CurvePreferences (Test) -- Code Style

---

README.md

Not sure if this is useful, but Caddy is (currently) an A+, seems nice to show it off 😉

Adding Go Report Card badge

---

dist/automate.go

Changes after [this PR](https://github.com/mholt/archiver/pull/12).

dist: adapt to archiver's refactor

---

caddyhttp/proxy/proxy_test.go
caddyhttp/proxy/reverseproxy.go

proxy: preserve path trailing slash if it was there

---

caddyhttp/gzip/gzip.go
caddyhttp/header/header.go
caddyhttp/httpserver/error.go
caddyhttp/httpserver/recorder.go
caddyhttp/proxy/proxy_test.go
caddyhttp/proxy/reverseproxy.go

header: implement http.Hijacker for responseWriterWrapper

---

caddyhttp/errors/setup.go
caddyhttp/errors/setup_test.go

errors: don't join the absolute file path

---

.travis.yml
appveyor.yml

Update Travis and Appveyor to Go 1.7.3

Update to Go 1.7.3

---

caddyhttp/httpserver/plugin.go

See hacdias/caddy-filemanager#35.

Moving File Manager higher in the directive list

---

startupshutdown/startupshutdown.go

Logging that a startup or shutdown command has been executed and what it was seems to me to be useful.

Log Startup and Shutdown Commands

---

caddyhttp/proxy/proxy.go

proxy: set request's body to nil explicitly

---

caddyfile/dispenser_test.go
caddyfile/parse.go
caddyhttp/browse/browse.go
caddyhttp/fastcgi/fcgiclient.go
caddyhttp/fastcgi/fcgiclient_test.go
caddyhttp/markdown/markdown.go
caddyhttp/proxy/proxy.go
caddyhttp/proxy/upstream.go
caddyhttp/rewrite/rewrite.go
caddytls/config.go
caddytls/crypto_test.go
caddytls/handshake.go
caddytls/user.go

I've passed code through gometaliner and made some changes: aligned structs, removed dead/unused code, simplified some statements.

Remove dead code, do struct alignment, simplify code

---

caddyhttp/proxy/setup_test.go
caddyhttp/proxy/upstream.go

proxy: make value is optional when removing a header

---

caddyhttp/header/header.go
caddyhttp/header/header_test.go
caddyhttp/header/setup.go
caddyhttp/header/setup_test.go

Get rid of TODO and custom Header type.

Use http.Header instead of custom type

---

caddyhttp/caddyhttp.go
caddyhttp/caddyhttp_test.go
caddyhttp/httpserver/plugin.go
caddyhttp/httpserver/replacer.go
caddyhttp/httpserver/server.go
caddyhttp/httpserver/siteconfig.go
caddyhttp/maxrequestbody/maxrequestbody.go
caddyhttp/maxrequestbody/maxrequestbody_test.go
caddyhttp/proxy/proxy.go

@mholt I'm looking for opinions on this implementation before I proceed further
[Issue](https://github.com/mholt/caddy/issues/1027)

(WIP) Add maxrequestbody directive

---

caddyhttp/proxy/proxy_test.go

Just a little unit test for Issue #1283

test: add unit test for #1283

---

caddyhttp/browse/browse.go
caddyhttp/browse/browse_test.go
caddyhttp/browse/setup.go
caddyhttp/browse/testdata/photos/hidden.html
caddyhttp/staticfiles/fileserver.go

Hide hidden files in ```browse``` plugin, fixes #1287

Fix for issue #1287 - don't list hidden files in directory listing

---

caddy/caddymain/run.go
caddyhttp/proxy/upstream.go

Remove pre 0.9 code

---

caddyhttp/fastcgi/fastcgi.go
caddyhttp/fastcgi/setup.go
caddyhttp/fastcgi/setup_test.go

Here is an awkward attempt at an implementation of feature request #1336. It appears to function correctly, but I'm guessing that the code quality and tests require more work, and/or I'm lacking some understanding that could lead to this breaking in some cases. Please let me know your feedback!

Add root option to fastcgi directive

---

caddyhttp/proxy/proxy_test.go
caddyhttp/proxy/reverseproxy.go

proxy: use a new context for the outgoing request

---

caddyhttp/httpserver/server.go

httpserver: support QUIC reload

---

caddyhttp/httpserver/plugin.go

CGI middleware for Caddy. Directive syntax has been flattened and problems raised in issues forum have been addressed.

Register cgi plugin

---

caddyhttp/httpserver/server.go
caddytls/config.go

Fixes https://github.com/mholt/caddy/issues/1455 (hope so)

Disable TLS completely if there is no listener with tls enabled

---

caddyfile/dispenser.go

Revert removed method

---

caddyfile/dispenser.go

Revert "Revert removed IncrNest method"

---

caddyhttp/httpserver/context.go
caddyhttp/httpserver/context_test.go

This PR is adding support for `ServerIP` context which can be used to get the local server IP. This is useful for example to print out the server IP in a template (e.g. `Server IP: {{.ServerIP}}`) when testing several instances of Caddy behind a load balancer.

Adding support for ServerIP context

---

caddyhttp/templates/templates.go

The issue is caddy will return wrong "Content-Type" (application/x-gzip) if "gzip" and "templates" are used at the same time.
To reproduce, run these code
```
cat << EOF > Caddyfile
localhost:2015 {
gzip
templates
}
EOF
echo test > index.html
caddy &
curl http://localhost:2015 -H 'accept-encoding: gzip' -v
```
and got
```
< HTTP/1.1 200 OK
< Content-Encoding: gzip
< Last-Modified: Tue, 28 Feb 2017 10:42:03 GMT
< Server: Caddy
< Vary: Accept-Encoding
< Date: Tue, 28 Feb 2017 10:43:11 GMT
< Content-Length: 29
< Content-Type: application/x-gzip
```
And the pull request fixed this.

Set right MIME type in middleware templates

---

caddy.go
caddyhttp/basicauth/basicauth.go
caddyhttp/basicauth/basicauth_test.go
caddyhttp/fastcgi/fastcgi.go
caddyhttp/httpserver/context.go
caddyhttp/httpserver/middleware.go
caddyhttp/httpserver/mitm.go
caddyhttp/httpserver/mitm_test.go
caddyhttp/httpserver/replacer.go
caddyhttp/httpserver/replacer_test.go
caddyhttp/httpserver/server.go
caddyhttp/rewrite/to.go
caddyhttp/staticfiles/fileserver.go
caddyhttp/staticfiles/fileserver_test.go

Replaced use of 
caddy.CtxKey("remote_user")
and 
caddy.CtxKey("mitm")
with constants

Added Const for use of CtxKeys

---

caddy/caddymain/run.go
caddy/main.go
plugins.go
sigtrap.go

The goal of this is to create plugins that can register Event Hooks and process information according to the type of event that is fired.

Introducing Event Hooks Plugins

---

dist/init/linux-sysvinit/README.md
dist/init/linux-sysvinit/caddy
dist/init/linux-upstart/caddy.conf
dist/init/linux-upstart/caddy.conf.centos-6
dist/init/linux-upstart/caddy.conf.ubuntu-12.04

See also https://github.com/mholt/caddy/pull/1272#issue-191256343

Make CADDYPATH equal across init scripts

---

caddyhttp/log/setup.go
caddyhttp/log/setup_test.go

log: only allow new roller related options in a block

---

caddyhttp/proxy/proxy_test.go
caddyhttp/proxy/reverseproxy.go

proxy: use untouched URL for concatenating

---

caddyhttp/httpserver/context.go
caddyhttp/templates/templates.go

template: support custom functions

---

caddyhttp/httpserver/context.go
caddyhttp/httpserver/context_test.go
caddyhttp/templates/templates_test.go
caddyhttp/templates/testdata/root.html

template: add test for custom function

---

caddyhttp/httpserver/context.go
caddyhttp/httpserver/context_test.go

This adds the ability to display the remote hostname of the visitors IP with template actions.

Add hostname template action

---

caddyhttp/proxy/proxy_test.go
caddyhttp/proxy/reverseproxy.go

proxy: take original URL path into account when remove prefix

---

caddyhttp/gzip/gzip.go
caddyhttp/gzip/gzip_test.go
caddyhttp/gzip/setup.go

```
benchmark           old ns/op     new ns/op     delta
BenchmarkGzip-4     2219756       2123427       -4.34%
benchmark           old allocs     new allocs     delta
BenchmarkGzip-4     25             8              -68.00%
benchmark           old bytes     new bytes     delta
BenchmarkGzip-4     959566        146507        -84.73%
```

gzip: pool gzip.Writer to reduce allocation

---

dist/init/mac-launchd/README.md
dist/init/mac-launchd/com.caddyserver.web.plist

update macOS launchd example

---

caddyhttp/gzip/gzip.go
caddyhttp/header/header.go
caddyhttp/httpserver/error.go
caddyhttp/httpserver/recorder.go
caddyhttp/proxy/proxy.go
caddyhttp/proxy/proxy_test.go
caddyhttp/proxy/reverseproxy.go

proxy: recognize client's cancellation

---

caddyhttp/gzip/gzip.go
caddyhttp/gzip/responsefilter_test.go
caddyhttp/header/header.go
caddyhttp/httpserver/recorder.go
caddyhttp/httpserver/responsewriterwrapper.go
caddyhttp/internalsrv/internal.go
caddyhttp/proxy/proxy_test.go

Per discussion in #1642 
Introduce responseWriterWrapper and SupportedInterfaces for code reuse.
N/A.
Maybe we should inform the middleware author how to use them.

introduce responseWriterWrapper and SupportedInterfaces

---

caddyhttp/httpserver/plugin.go

The directive _datadog_ has been added to allow configuration of the plugin [caddy-datadog](https://github.com/payintech/caddy-datadog).
This pull request is not related with an existing issue.
Add documentation for new directive `datadog`

Add datadog directive

---

caddyhttp/proxy/proxy_test.go

fix issue #1652
Fix `TestWebSocketReverseProxyServeHTTPHandler` failure.
#1652 
N/A.

proxy: synchronize websocket test

---

caddyhttp/proxy/proxy_test.go
caddyhttp/proxy/reverseproxy.go

As per #1512 this PR only contains the necessary changes to fix #1502 and nothing more.
Sorry for closing the other PR and sorry for the delays - I'm having a kinda hard time in life right now and things like that are the result I guess. 😕
P.S.: I have no idea why one of the commit tests failed... Maybe a race condition? Because I haven't seen such a failure personally yet. <sup>With Rust that wouldn't have happened.</sup>

Fixed #1502: Proxying of unannounced trailers

---

caddyhttp/proxy/upstream.go

Keeps variable usage consistency throughout that code block.
related to #1666 
none

proxy: one liner wrt variable reuse

---

caddyhttp/proxy/policy.go

Corrects a few comment issues in proxy policy.
N/A
N/A

Correct proxy policy documentation

---

caddy/caddymain/run.go
plugins.go
sigtrap.go

[Breaking Change] Add ExtraInfo to EventHook

---

caddyhttp/proxy/upstream.go
caddyhttp/proxy/upstream_test.go

Checks for a given string in the content response from a backend.
https://github.com/mholt/caddy/issues/324
In http.proxy:
http_check_contentstring a string to search for in the content response from the backend.

Custom proxy upstream health check #324

---

caddyhttp/gzip/gzip_test.go
caddyhttp/mime/mime_test.go

Simply correct the message showed when tests fail.
Not yet.
No documentation need to be changed.

gzip,mime: show response header instead of the request one in test message

---

caddyhttp/httpserver/plugin.go

Add `webdav` directive for webdav plugin! 😄

Add webdav directive

---

caddyhttp/basicauth/setup.go

remove magic number by method call. :)
/cc @mholt 
No.
No.

remove magic number

---

caddyhttp/httpserver/plugin.go

It adds nobots directive used in nobots plugin
There is no issue
There is no changes

Adding nobots directive

---

caddyhttp/httpserver/server.go

Encapsulates writing of error response when no served vhosts match the requested host.
If HTTP version is 2.0 or above, 421 status code is written, otherwise - 404. Error now is a bit more descriptive.
N/A
N/A

Encapsulate WriteSiteNotFound error

---

caddyhttp/httpserver/vhosttrie.go

Adds global FallbackHosts for vhost matching instead of hardcoded values.
Makes it possible for plugins and directives to change the list of FallbackHosts.
None
None

Add global FallbackHosts for vhost matching

---

sigtrap.go
sigtrap_posix.go

Makes exit codes different for different exit reasons.
https://github.com/abiosoft/caddy-docker/issues/65
Probably none at this point?
New code explanations:
0: normal or expected exit
1: error before server finished starting
2: double SIGINT (force quit)
3: error stopping with SIGQUIT
4: shutdown callback(s) returned error(s)

Distinguishable exit codes

---

caddyhttp/httpserver/plugin.go

Add 'jekyll' plugin, which will be released soon 😄

Add 'jekyll' plugin.

---

caddyhttp/httpserver/plugin.go

Add the `awses` plugin (wrapping up the README and documentation first).

Add 'awses' plugin directive

---

caddyhttp/browse/browse.go
caddyhttp/browse/browse_test.go

Support absolute symlink to directory.
Support recursive symlink to directory.
Could there be some security issue with absolute symlinks? make sure they are inside root or path spec?

browse: Support absolute and recursive directory symlinks

---

caddyhttp/httpserver/plugin.go

Adds forwardproxy to directives' list
N/A
ASAIK, the documentation for plugins is handled at registration.

Add forwardproxy to directives' list

---

caddyhttp/browse/setup.go

Make filename column fill out extra space

Make filename column fill out space

---

caddyhttp/push/handler.go
caddyhttp/push/handler_test.go

Do not push index file when not in a rule

---

README.md

Fixed build instruction : https://github.com/mholt/caddy/issues/1843#issuecomment-329259661
https://github.com/mholt/caddy/issues/1843
Build Instruction

fixed build instruction

---

caddyhttp/proxy/proxy_test.go
caddyhttp/proxy/reverseproxy.go

We exit proxying immediately when websocket backend shutdowns, 
#1840 
N/A

proxy: websocket proxy exits immediately if backend is shutdown

---

caddytls/client.go
plugins.go

1. Register a new Event Hook `CertRenewEvent`
#1864 
/

Implement CertRenewEvent

---

assets_test.go
caddy.go
upgrade.go

all: improve error checking

---

README.md

This changes add proper an easy instruction for building.
N/A
Install/Build instructions.

Update build instruction

---

caddyhttp/markdown/markdown.go
caddyhttp/markdown/setup.go
caddyhttp/markdown/setup_test.go
caddyhttp/markdown/template.go

Only update template when file changed
#1908 
N/A

markdown: only update template when file changed

---

caddytls/client.go
caddytls/filestorage.go
caddytls/storage.go
caddytls/sync_locker.go
caddytls/tls_test.go
caddytls/user_test.go

Abstracts the mutual exclusion mechanism behind an interface
First installment in https://github.com/mholt/caddy/issues/1918 series
None
(as for point 1, I have refactored the code and made sure that all existing tests are still passing)

Extract locker into an interface

---

caddyhttp/browse/setup.go

Correct Browse "modified date" alignment that may be a bit misaligned depending on time and date.
I'm unsure if it is the best way to correct the issue.
#1952
None.

Correct browse modified date alignment

---

caddyhttp/templates/templates_test.go
caddyhttp/templates/testdata/as_it_is.txt

Add extension filter test case and simplify test code
N/A
N/A

template: add extension filter test and simplify test code

---

caddyhttp/httpserver/recorder.go

As a implement of `ResponseWriter`, `ResponseBuffer` could be consistent with the definition, following is quoted from doc of the `ResponseWriter.Write`
> // If WriteHeader has not yet been called, Write calls
// WriteHeader(http.StatusOK) before writing the data. 
N/A
N/A

ResponseBuffer: add missing header writing

---

plugins.go

Use `sync.Map` to make `eventHooks` concurrent r/w safe
#1974 
N/A

make eventHooks thread safe

---

caddyhttp/httpserver/plugin.go

Add geoip directive to Caddyfile for [caddy-geoip](https://github.com/kodnaplakal/caddy-geoip)
https://github.com/mholt/caddy/issues/1819
No

httpserver: Add geoip directive (closes #1819)

---

caddytls/filestorage_test.go

Making a PR just to run these tests on Windows 😛

tls: Fix tests on Windows

---

caddyhttp/httpserver/plugin.go

Adds "run" directive that will be used by plugin https://github.com/lucaslorentz/caddy-run
N/A
N/A
I created this plugin because I find it useful to run .NET Core applications and also php cgi.
It is different from the **on** plugin, because it is not event driven and also ensures the application keeps running in background with several extra options and restart policy.
Let me know if you already have plans for directive name **run**, I can easily rename the plugin.
I've been testing it mainly on windows, tests, suggestions and feedback are welcome.
After this PR get's merged I will add it to caddy plugins list.

Add "supervisor" directive

---

caddytls/config.go

Fix typo: "incompabile"

---

caddyhttp/markdown/markdown.go

Fix 500 error for nonexisting files
https://github.com/mholt/caddy/issues/2256
---

Fix 500 error in markdown plugin

---

caddytls/handshake.go

gofmt `caddytls/handshake.go`
n/a
n/a

caddytls: gofmt

---

appveyor.yml

Attempts to fix mysteriously broken AppVeyor tests.
https://github.com/appveyor/ci/issues/2613
None

Attempting to fix AppVeyor builds

---

caddy.go

it's a stupid mistake
- fix a bug of deadlock
None
None

fix a bug of deadlock

---

caddyhttp/httpserver/tplcontext.go
caddyhttp/httpserver/tplcontext_test.go

Introduces new template action to get TLS protocol version
None
Template action should be documented here: https://caddyserver.com/docs/template-actions

new template action: TLS protocol version

---

caddyhttp/browse/setup.go

This applies the filter when using the browser history to go the
previous directory.

browse: filter on document load

---

caddy/caddymain/run.go

Fix linter warning

---

caddyhttp/httpserver/plugin.go

Fixes https://github.com/techknowlogick/caddy-s3browser/issues/2
Add s3browser directive
https://github.com/techknowlogick/caddy-s3browser/issues/2
None

Add s3browser directive

---

caddyhttp/httpserver/plugin.go

Thanks to @webprofusion-chrisc for spotting this typo
https://github.com/mholt/caddy/pull/2383#issuecomment-445432256
N/A

Fix `s3browser` plugin name

---

caddy.go
caddy/caddymain/run.go
caddyhttp/httpserver/server.go

Following discussion in issue #2458 I have implemented a change to how sites are output to this
Each port has been grouped.
````
Activating privacy features... done.
Serving HTTP on port:444
http://localhost:444
Serving HTTP on port:80
http://curlyparsley.kinchik.ie
http://
http://salmon.kinchik.ie
http://pepper.kinchik.ie
http://courgette.kinchik.ie
http://splitpeas.kinchik.ie/path
http://ripefig.kinchik.ie
http://192.168.15.184
Serving HTTPS on port:443
https://pie.kinchik.toflidium.com
Serving HTTP on port:2015
http://fig.kinchik.ie:2015
Serving HTTP on port:4467
http://localhost:4467
Serving HTTP on port:1667
http://127.0.0.1:1667
http://localhost:1667
````
When caddy is set to log to stdout you also still get the log entries.  I need some help to fix thils.
````
Activating privacy …
```

Modify Startup Output

---

caddy.go
caddy/caddymain/run.go
caddyhttp/httpserver/server.go

Reverts mholt/caddy#2469
Until additional changes have been made.

Revert "Modify Startup Output"

---

caddyhttp/httpserver/plugin.go

Added "dyndns" directive for support caddy-dyndns plugin

Added dyndns directive to httpserver

---

onevent/on.go

`OncePerServerBlock` should return err.

onevent: add missing return error

---

caddytls/setup_test.go

sort import package which is unsorted.

caddy/caddytls: sort import package.

---

README.md

Add link to Good First Issue

---

caddytls/config.go

Each time the Caddyfile reloads and Caddy is restarted, `caddytls.NewConfig` starts a goroutine for cleaning the certificate storage. This goroutine ranges over a `time.Ticker` channel; although `Stop` is called on this ticker, `Stop` does not close the underlying channel so the goroutine never exits.
This change adds an additional channel that is listened to in the certificate cleaning goroutine so it can exit on restarts.
Fixes #2642 
None
1. I did not write any new tests for this code because it is contained within a function `caddytls.NewConfig` which is currently untested. I can carve out some time to test the entire function, though it feels out of scope for this PR. 
2. I observed that calling `certmagic.CleanStorage` is delayed by 12 hours. If a restart always occurs before 12 …

Fix goroutine leak when restarting Caddy

---

caddytls/config.go
caddytls/config_test.go
caddytls/setup_test.go

Fix #2641.
#2641.
Nothing I believe.

Verify client cert filenames

---

caddy/caddymain/run.go
caddyhttp/basicauth/basicauth.go
caddyhttp/browse/browse.go
caddyhttp/httpserver/logger.go
caddyhttp/httpserver/server.go
caddyhttp/proxy/reverseproxy.go
caddyhttp/requestid/requestid.go
caddyhttp/websocket/websocket.go
caddytls/config.go
caddytls/setup_test.go
caddytls/tls.go
onevent/hook/hook_test.go
onevent/on.go

Keeps the list sorted and prevents future merge conflicts.

Used goimports to fix import order

---

cmd/proc_posix.go

Add some missing import to fix build on my macOS
None
None

Fix: unix build in v2

---

caddy.go

title: 'Fixing a compilation error'
labels: ''
assignees: ''
---
Small bug fix during compilation.
./caddy.go:230:12: cannot use *dep (type debug.Module) as type *debug.Module in return argument
./caddy.go:233:12: cannot use bi.Main (type debug.Module) as type *debug.Module in return argument

Fixing a compilation error

---

caddy/caddymain/run.go

This is simply log caddy version before caddy starts.
https://github.com/caddyserver/caddy/issues/2635
I don't know if there is any documentation to change

Log caddy version on start

---

admin.go

Fix caddyconfig import in admin.go

---

README.md

Issue #2716 was caused by a misunderstanding regarding the filename to use when creating a custom build from source. These changes aim to make the instructions more explicit.
---
title: ''
labels: ''
assignees: ''
---
Adds clarification to the build steps when building from source using custom or altered modules.
#2716 
None; this is a documentation change.

Update build docs to clarify usage of `.go` extension

---

cmd/commands.go
go.mod
go.sum

The github.com/mitchellh/go-ps truncates the process name to only 16 characters. The fork by keybase fixes that. Switch to using Keybase fork of go-ps.
mitchellh/go-ps#15
N/A
- [N/A] I have written tests and verified that they fail without my change

Fix stop command

---

.github/CONTRIBUTING.md

Change mholt/caddy import path references to caddyserver/caddy in the contributing document

Change mholt/caddy references to caddyserver/caddy

---

README.md
azure-pipelines.yml

Introduces CI for the v2 branch
None.
N/A
- [N/A] I have written tests and verified that they fail without my change
Let's see if this works.

v2: introduce CI for v2 branch

---

cmd/commandfuncs.go
cmd/commands.go

---
title: ''
labels: 'v2'
assignees: ''
---
sort cmd && use RegisterCommand function to register cmd.
in v2 barnch, cmd registered by variable definition, init function and RegisterCommand, the behavior is inconsistent and confusing.
only manual testing:
none
none

cmd register use RegisterCommand

---

caddyconfig/caddyfile/lexer.go
caddyconfig/caddyfile/lexer_test.go
modules/caddyhttp/fileserver/staticfiles_test.go

This is a PR to track the porting of tests to complete successfully on Windows.

Make tests work on Windows

---

azure-pipelines.yml

The func to parse the network address was `ParseListenerAddress`. It was changed at some point to `ParseNetworkAddress`. This PR updates the name on the fuzz target so it's more descriptive and easily tracked.
N/A
N/A

update the fuzzer target name for the address parser

---

.gitignore
README.md
azure-pipelines.yml
caddyconfig/caddyfile/parse_fuzz.go

One of the fuzzers was missing due to an entry in `.gitignore` that didn't interact well with Apple's case-insensitive filesystem. This PR adds a negation condition for the directory to include the fuzzer.
Also print the fuzzing type when running CI to better trace the jobs.
N/A
N/A

Add missing fuzzer

---

azure-pipelines.yml

Fixing a git-oopsie on my behalf. Oddly enough, Github didn't report the line being re-added in the previous PR.
N/A
N/A

Re-remove admin fuzz target from azure-pipelines.yml

---

README.md

---
title: 'update readme to remove GO111MODULE env'
labels: ''
assignees: ''
---
Remove GO111MODULE  env variable, because the Go 1.13 do not require it.
#2885

update readme to remove GO111MODULE env variable

---

caddyconfig/httpcaddyfile/builtins.go
caddyconfig/httpcaddyfile/directives.go
caddyconfig/httpcaddyfile/httptype.go
caddyconfig/httpcaddyfile/parser_test.go
cmd/main.go
modules/caddyhttp/matchers.go
modules/caddyhttp/matchers_test.go

These are mostly breaking changes as described by #2959. We need to do these now before we reach a stable tag. We'll clearly document all breaking changes right in the release notes.
Once these are done, I will write new Caddyfile documentation for our new [documentation site](https://caddyserver.com/docs/).

v2: Implement Caddyfile enhancements (breaking changes)

---

caddyhttp/httpserver/logger.go

Partial fix/rollback of #2781, which was inadvertently a breaking change.
Attempting fix for #2973.
/cc @corny @danlsgiga

Don't use default log settings on custom logs

---

caddyconfig/httpcaddyfile/builtins.go
caddyconfig/httpcaddyfile/httptype.go
caddyconfig/httpcaddyfile/parser_test.go

Rebased and addresses feedback in https://github.com/caddyserver/caddy/pull/2937

add support for root ca certificate in the caddyfile

---

go.mod
go.sum

update quic-go to v0.14.4

---

caddy.go

Can I make PR like this without opening an issue first ?

Fix spelling error

---

modules/caddyhttp/caddyhttp.go

This might be a small typo which need to fix.

It might be HTTP->HTTPS in the comment

---

README.md

just a small correction to fix the Features link in the `README.md`
**PS:** Thank you so much for your work! :pray:

fix features link in README.md

---

caddyconfig/httpcaddyfile/httptype_test.go
caddyconfig/httpcaddyfile/options.go

~~Still WIP~~ - doing this the lazy way and using CI to run the tests instead of running it locally 😅 
Fixes #3126

Improve global options parsing, plus tests (#3126)

---

README.md

v2: update CI badge on README

---

modules/caddyhttp/reverseproxy/fastcgi/fastcgi.go

This should resolve #3178.
@AlexMax Could you try this as well if you have a chance?

fastcgi: Ensure root is always absolute

---

caddytest/caddytest.go

Minor fix to integration tests

report error on failed location response

---

.github/workflows/fuzzing.yml
caddyconfig/caddyfile/parse_fuzz.go
caddyconfig/httpcaddyfile/addresses_fuzz.go
listeners_fuzz.go
replacer_fuzz.go

Fewer deps & use only native Go fuzzing engine. Should make our life a bit easier.

ci: fuzz: switch engine from libfuzzer to native go-fuzz

---

modules/caddyhttp/caddyauth/basicauth.go

This should cause the browser to show a credentials prompt after submitting wrong credentials.
/cc @Eadinator

basicauth: Re-prompt after invalid credentials (fix #3239)

---

.github/CONTRIBUTING.md

Relevant edits compared to the v1 branch:
- `Writing a plugin` -> `Writing a Caddy module`, and section updated to use "module" nomenclature instead
- `Improving documentation` section points to https://github.com/caddyserver/website, no longer says third-party plugins docs are on the website
- `Don't accept new dependencies lightly.` section mentions go modules instead of vendoring
- `Be extra careful in some areas of the code.` section mentions `caddyhttp` package instead of `caddy`
Full diff between this and what's on v1:
```diff
diff --git a/.github/CONTRIBUTING.md b/.github/CONTRIBUTING.md
index d5478adf5..6dbba068a 100644
--- a/.github/CONTRIBUTING.md
+++ b/.github/CONTRIBUTING.md
@@ -8,7 +8,7 @@ For starters, we invite you to join [the Caddy forum](https://caddy.community) w
- …
```

docs: Pull contributing document from v1 branch

---

README.md

Credit to @kanagawa41 for spotting these!
Fixes #3282

doc: Fix broken links in README.md

---

modules/caddytls/acmeissuer.go

Discovered this today when playing around with `on_demand_tls` 🤗

Fix misspelling in onDemandAskRequest error

---

caddytest/caddytest.go

Expose some handy timeouts just in case testing code needs to extended them.

expose caddytest timeouts

---

.github/workflows/ci.yml
.travis.yml

ci: add tests on s390x and ppc64le

---

.goreleaser.yml

Add linux-armv5 builds

---

cmd/commands.go

docs: Fix command.Func documentation

---

modules/caddyhttp/server.go

This should fix #3375. Please let me know if you would like any other changes, or how I can add some tests to this. I didn't see a way to run any tests, but based on my own server it looks like this enables the functionality I was looking for.

adding wildcard matching of logger names

---

modules/caddyhttp/celmatcher.go

docs: link to CEL standard definitions

---

caddyfile/lexer.go
caddyfile/parse_test.go

* add tests for an empty file
* return nil from `lexer.load` when the file is empty
This is #3414 for v1, too.

v1: Allow empty files to be imported

---

caddyconfig/caddyfile/dispenser.go

Thanks to @nchagrass-bud for pointing it out https://github.com/caddyserver/caddy/pull/3439#discussion_r430962674

chore: Fix typo in dispenser.go

---

.goreleaser.yml

This is partial revert of #3436. I've added a semi-lengthy comment to never forget again why the build script is written the way it is.

ci: fix an oopsie in the release script

---

.github/workflows/release.yml
.github/workflows/release_published.yml

@mholt no need to retag for this one, but it should fix things for next time.

ci: Fix gemfury upload condition, move triggers to publish event

---

.github/workflows/release_published.yml

ci: Fix another oops with publish workflow

---

modules/caddyhttp/templates/tplcontext.go

Disable hard wraps in Markdown rendering

---

modules/caddyhttp/reverseproxy/fastcgi/fastcgi.go

fastcgi: Fill REMOTE_USER with http.auth.user.id placeholder

---

modules/caddyhttp/celmatcher.go
modules/caddyhttp/celmatcher_test.go

The goal is to be able to create a matcher for client certificate DN using CEL expressions, for instance:
```
@client_cert {
expression {http.request.tls.client.subject} == 'CN=bla,OU=blabla,O=bla,L=bla,ST=bleh,C=buh'
}
```

Add support to  resolve CN in CEL expression

---

modules/caddyhttp/fileserver/staticfiles_test.go

I don't have Windows so using this PR to test...

fileserver: Fix new file hide tests on Windows

---

cmd/commandfuncs.go
cmd/commands.go

Resolves https://github.com/caddyserver/caddy/issues/3679

cmd: Allow `caddy fmt` to read from stdin

---

modules/metrics/metrics.go

metrics: fix handler to not run the next route

---

caddytest/integration/caddyfile_adapt/php_fastcgi_index_off.txt
modules/caddyhttp/reverseproxy/fastcgi/caddyfile.go

Discussed in #3841
Nothing fancy here, just wiring up some timeouts.

fastcgi: Add timeouts support to Caddyfile adapter

---

modules/caddytls/connpolicy.go

Closes #3563
@danlsgiga would you be able to give this a shot? I just whipped this up real quick and it's a pretty straightforward change. Let me know if this is helpful for you.
(I don't yet have Caddyfile support implemented. Do you need that?)

caddytls: Configure trusted CAs from PEM files

---

cmd/main.go

Close https://github.com/caddyserver/caddy/issues/3897

cmd: add ability to read config from stdin

---

cmd/commandfuncs.go
cmd/notify.go
cmd/notify_linux.go
cmd/notify_other.go

Issue: #3786
Based on Gaurav Dhameeja's work in #3908.

cmd: Implement sd_notify() to notify systemd about finished initialization

---

.github/CONTRIBUTING.md

Minor spelling fixes to make this document even better

CONTRIBUTING: fix spelling

---

modules/caddyhttp/fileserver/browsetpl.go

Adds a dark color scheme if the user's browser prefers one.
Tried to keep to the original's design as well as I could, any propositions are welcome.

Add dark color scheme media query

---

modules/caddyhttp/fileserver/staticfiles.go

I noticed file server had debug lines for most everything else but the most common problem people have are file permissions or files not being found. Showing those cases when attempting to open the file would make debugging much easier.

fileserver: Add a few more debug lines for fileserver problems

---

cmd/main.go

Fixed typos in the documentation

cmd: main: fix minor doc typos

---

caddyconfig/caddyfile/formatter_fuzz.go

Brainfart + linter not playing well with build tag = fail

fuzz: fix the FuzzFormat comparison

---

caddyconfig/httpcaddyfile/options.go
caddyconfig/httpcaddyfile/tlsapp.go
caddytest/integration/caddyfile_adapt/global_options_acme.txt

Followup to https://github.com/caddyserver/caddy/commit/42b7134ffa3bf3e9e86514c82407979c2627a5ab

httpcaddyfile: Add global option for `storage_clean_interval`

---

modules/caddytls/tls.go

caddytls: Run replacer on ask URL, for env vars

---

cmd/commandfuncs.go

upgrade: inherit the permissions of the original executable

---

cmd/commandfuncs.go

cmd: use net.ErrClosed for matching returned error

---

modules/caddyhttp/matchers.go

A very simple PR to update the documentation for MatchQuery. See https://caddy.community/t/query-matcher-issue/13366

caddyhttp: Improved documentation for MatchQuery

---

modules/caddyhttp/server.go

Might also be worth adding method binning to the metrics middleware in this PR.

caddyhttp: Reject absurd methods

---

modules/caddyhttp/templates/templates.go

Fix https://github.com/caddyserver/caddy/issues/4563

templates: Elaborate on what's supported by the markdown function

---

caddy.go

Currently the config returned by `caddy.config_loaders` is applied even though there is no change in the config. This results in a lot of wasted cpu cycles to restart all the apps and modules.
I've added a basic optimization step to prevent unnecessary reloads.
It would be great if you could add this to the next release.

Prevent unnecessary loading of config

---

modules/caddyhttp/server.go

Hoping this fixes #4256.
@ledlamp I just whipped this up real quick. Can you test to confirm this fixes the issue for you?

caddyhttp: Honor wildcard hosts in log SkipHosts

---

modules/caddyhttp/templates/templates.go

Otherwise, it might be confusing for beginners (like me!)

templates: Documentation consistency

---

modules/caddyhttp/reverseproxy/reverseproxy.go

reverseproxy: HTTP 504 for upstream timeouts

---

modules/caddyhttp/headers/headers.go
modules/caddyhttp/headers/headers_test.go

headers: Support wildcards for delete ops

---

modules/caddyhttp/reverseproxy/forwardauth/caddyfile.go

See https://caddy.community/t/using-forward-auth-and-writing-my-own-authenticator-in-php/16410, apparently it didn't work when `copy_headers` wasn't used.
This is because we were skipping adding a handler to the routes in the "good response handler", but this causes the logic in `reverseproxy.go` to ignore the response handler since it's empty. Instead, we can just always put in the `header` handler, even with an empty `Set` operation, it's just a no-op, but it fixes that condition in the proxy code:
https://github.com/caddyserver/caddy/blob/10f85558ead15e119f8e9abd81c8ad55eb865f8b/modules/caddyhttp/reverseproxy/reverseproxy.go#L806-L810

forwardauth: Fix case when `copy_headers` is omitted

---

modules/caddyhttp/reverseproxy/caddyfile.go
modules/caddyhttp/reverseproxy/httptransport.go

Should close #3841. /cc @RussellLuo

reverseproxy: Implement read & write timeouts for HTTP transport

---

.gitattributes
.github/workflows/lint.yml

https://github.com/golangci/golangci-lint/issues/580#issuecomment-704913317 🤷‍♂️

chore: Add .gitattributes to force *.go to LF

---

caddyconfig/httpcaddyfile/addresses.go
listeners.go
modules/caddyhttp/matchers.go
modules/caddyhttp/reverseproxy/reverseproxy.go
modules/caddytls/matchers.go

core: Change net.IP to netip.Addr; use netip.Prefix

---

modules/caddyhttp/templates/templates.go

templates: cap of slice should not be smaller than length

---

.github/workflows/lint.yml

Windows linter keeps timing out

ci: Increase linter timeout

---

admin.go

Fixes [4954](https://github.com/caddyserver/caddy/issues/4954)
Don't stop admin server when error occurs.

admin: Don't stop old server if new one fails

---

caddyconfig/httpcaddyfile/httptype.go

httpcaddyfile: Add `{cookie.*}` placeholder shortcut

---

.github/workflows/release.yml
.goreleaser.yml

I followed this guide by @shibumi: https://shibumi.dev/posts/keyless-signatures-with-github-actions/. To test and validate it works, I may need to create a release in a dummy repo. Thoughts?
@shibumi, can you please take a look? 🙂

ci: generate SBOM and sign artifacts using cosign

---

caddyconfig/httpcaddyfile/addresses.go
listeners.go

Commit 1e18afb5c862d62be130d563785de5c58f08ae8e broke my caddy setup.
This commit fixes it.

httpcaddyfile: Fix bind when IPv6 is specified with network

---

modules/caddyhttp/autohttps.go

Fix #4829 /cc @whitestrake
After thinking about it a bit, the fix seemed like it would probably be pretty easy.
I flipped an `if` to reduce indentation (`continue` early) and wrapped the insert with a simple condition that checks if we have any actual domains with certs in the config, and if not then we can probably assume we have a catch-all HTTPS site if we got that far.
Confirmed with some `fmt.Printf` that the routes still have the route added at the start if there is any domain configured, and it doesn't if there are no domains. The catch-all redirect at the end is always added, which would only run when the user doesn't define their own catch-all HTTP route.

caddyhttp: Skip inserting HTTP->HTTPS redir if catch-all for both exist

---

modules/caddyhttp/encode/encode.go

Fix [5059](https://github.com/caddyserver/caddy/issues/5059).

encode: don't WriteHeader unless called

---

modules/caddyhttp/headers/caddyfile.go
modules/caddyhttp/reverseproxy/reverseproxy.go

Fixes #5074
/cc @dunglas for optional sanity check :sweat_smile:

reverseproxy: On 103 don't delete own headers

---

caddyconfig/httpcaddyfile/tlsapp.go
caddytest/integration/caddyfile_adapt/tls_automation_policies_10.txt

httpcaddyfile: Fix edgecase with `auto_https off` with provided certs

---

modules/caddyhttp/replacer.go

Add placeholder `{http.request.orig_uri.path.*}` just like `{http.request.uri.path.*}`.

caddyhttp: add placeholder {http.request.orig_uri.path.*}

---

modules/caddyhttp/reverseproxy/healthchecks.go

Fix #5281 - hopefully :)
Can you test this out, @maidmaid? There are CI artifacts you can download to make it easier.

reverseproxy: Set origreq in active health check

---

cmd/cobra.go
cmd/commands.go

* Coral -> Cobra
* https://github.com/caddyserver/caddy/issues/5294#issuecomment-1378233390

chore: Fix typo, coral -> cobra

---

cmd/commandfuncs.go
cmd/commands.go

cmd: Add `--envfile` flag to `validate` command

---

caddy.go
cmd/commandfuncs.go
context.go
modules.go

cmd: Fix validating JSON with unknown fields

---

modules/caddyhttp/reverseproxy/command.go

reverseproxy: Header up/down support for CLI command

---

modules/caddyhttp/templates/tplcontext.go

May be useful in a loop handling listFiles entries to adopt different behavior is a file is a directory.

templates: Add `fileStat` function

---

modules/caddyhttp/fileserver/browse.go
modules/caddyhttp/fileserver/browse.html
modules/caddyhttp/fileserver/browsetplcontext_test.go

fileserver: Use EscapedPath for browse

---

go.mod
go.sum
listeners.go

update quic-go to v0.35.0

---

modules/caddyhttp/encode/encode.go

encode: Fix infinite recursion

---

modules/logging/filters.go

Fixes https://caddy.community/t/is-caddy-mutating-header-content-from-logging-settings/20947

logging: Clone array on log filters, prevent side-effects

---

caddyconfig/httpcaddyfile/httptype.go

httpcaddyfile: Sort TLS SNI matcher, for deterministic adapt output

---

modules/caddyhttp/reverseproxy/upstreams.go

Just an oversight, A is missing the same debug logging that SRV had

reverseproxy: Add debug logging for dynamic A upstreams

---

caddy.go

Ensure AppDataDir exists inside caddy.InstanceID()

---

modules/caddyhttp/staticresp.go

Previously the `caddy respond` command would treat the argument passed to --listen as a TCP socket address, iterating over a possible port range.
This pull request factors the server creation out into a separate function, allowing this to be reused in case the listen address is a unix network address.
For example `caddy respond hi --listen "unix//tmp/test|0200"`

caddyhttp: support unix sockets in `caddy respond` command

---

cmd/caddy/main.go
cmd/main.go

Closes https://github.com/caddyserver/xcaddy/pull/168.

refactor: move automaxprocs init in caddycmd.Main()

---

modules/caddyhttp/reverseproxy/command.go

I noticed those print lines the other day and thought they looked like the an odd duck.

cmd: reverseproxy: log: use caddy logger

---

caddytest/caddytest.go

This would allow us to run the test server for benchmarks too.

tests: uses testing.TB interface

---

caddytest/integration/leafcertloaders_test.go

Reported in:
https://github.com/caddyserver/caddy/pull/6108#issuecomment-1979773494

ci: fix the integration test `TestLeafCertLoaders`

---

modules/caddyhttp/rewrite/rewrite.go

Fixes the segfault issue mentioned in the comments of #6165

Added a null check to avoid segfault in rewrite module provision

---

modules/caddytls/connpolicy.go

doc: add `verifier` in `ClientAuthentication` caddyfile marshaler doc

---

caddyconfig/httpcaddyfile/builtins.go
modules/caddyhttp/reverseproxy/caddyfile.go
modules/caddytls/connpolicy.go

I don't think I missed any other chore, have I?

chore: add warn logs when using deprecated fields

---

caddytest/caddytest.go
caddytest/caddytest_test.go

See: https://caddy.community/t/posted-configuration-isnt-active/23794/8

caddytest: normalize the JSON config

---

modules/caddyfs/filesystem.go

ive been meaning to fix this for a while... lol

chore: Fix a typo in filesystem.go

---

caddytest/integration/caddyfile_adapt/acme_server_sign_with_root.caddyfiletest
modules/caddypki/acmeserver/caddyfile.go

Closes #6338 
@mholt @francislavoie

acmeserver: Add `sign_with_root` for Caddyfile

---

.golangci.yml

I noticed complaints about deprecated config, so decided to fix them.

chore: update golangci config

---

go.mod
go.sum
modules/caddyhttp/proxyprotocol/listenerwrapper.go

Issue #6484
made necessary changes to maintain forward compatibility with github.com/pires/go-proxyproto

proxyprotocol: Update WrapListener to use ConnPolicyFunc for PROXY protocol

---

modules/caddyhttp/proxyprotocol/listenerwrapper.go

chore: Fix a typo

---

caddytest/integration/caddyfile_adapt/file_server_precompressed.caddyfiletest

Adds a test for https://github.com/caddyserver/caddy/pull/6737.

test: add a test for precompressed defaults

---

modules/caddyhttp/reverseproxy/fastcgi/caddyfile.go

Docs for https://github.com/caddyserver/caddy/pull/6698 and https://github.com/caddyserver/caddy/pull/6699.

docs: improve parsePHPFastCGI docs

---

go.mod
go.sum

Cobra had a few optimizations and fixes

chore: upgrade cobra

---

modules/caddyhttp/requestbody/requestbody.go

Fixes https://github.com/caddyserver/caddy/pull/5795#issuecomment-2719244183

requestbody: Fix ContentLength calculation after body replacement

---

listeners.go

chore: fix comment

---

caddytest/integration/caddyfile_adapt/acme_server_policy-allow.caddyfiletest
caddytest/integration/caddyfile_adapt/acme_server_policy-both.caddyfiletest
caddytest/integration/caddyfile_adapt/acme_server_policy-deny.caddyfiletest
modules/caddypki/acmeserver/caddyfile.go

Not sure where my mind was when I wrote those lines and why I didn't add tests. Anyways, fixed.
Reported here: https://caddy.community/t/acme-server-allow-domains/30973

acme_server: fix policy parsing in caddyfile

---

modules/caddyhttp/reverseproxy/httptransport.go

Similar to [7151](https://github.com/caddyserver/caddy/pull/7151), but for reverse proxy.

reverse_proxy: use the new KeepAliveConfig to set probe interval
